anyio::_core::_synchronization::Lock
None anyio._core._synchronization.Lock.acquire(self)
Acquire the lock.
Referenced by anyio._core._synchronization.Condition.wait.
None anyio._core._synchronization.Lock.acquire_nowait(self)
Acquire the lock, without blocking. :raises ~anyio.WouldBlock: if the operation would block
None anyio._core._synchronization.Lock.release(self)
Release the lock.
Referenced by anyio._core._synchronization.Condition.wait.
bool anyio._core._synchronization.Lock.locked(self)
Return True if the lock is currently held.
LockStatistics anyio._core._synchronization.Lock.statistics(self)
Return statistics about the current state of this lock. .. versionadded:: 3.0
Referenced by pip._vendor.tenacity.BaseRetrying.begin, pip._vendor.tenacity.BaseRetrying.iter.