setuptools::_vendor::importlib_metadata::Sectioned
setuptools._vendor.importlib_metadata.Sectioned::_sample
setuptools._vendor.importlib_metadata.Sectioned.section_pairs(cls, text)
References anyio._core._fileio.AsyncFile.read, anyio._core._tempfile.SpooledTemporaryFile.read, click.testing.EchoingStdin.read, fastapi.datastructures.UploadFile.read, lib.microdot.microdot.AsyncBytesIO.read, paho.mqtt.client._WebsocketWrapper.read, pip._internal.network.lazy_wheel.LazyZipOverHTTP.read, pip._vendor.cachecontrol.filewrapper.CallbackFileWrapper.read, pip._vendor.distlib.metadata.LegacyMetadata.read, pip._vendor.distlib.util.PyPIRCFile.read, pip._vendor.packaging._tokenizer.Tokenizer.read, pip._vendor.rich._null_file.NullFile.read, pip._vendor.rich.progress._Reader.read, pip._vendor.rich.theme.Theme.read, pip._vendor.urllib3.response.HTTPResponse.read, pip._vendor.urllib3.util.retry.Retry.read, pip._vendor.urllib3.util.ssltransport.SSLTransport.read, setuptools._vendor.importlib_metadata.Sectioned.read, starlette.datastructures.UploadFile.read, typing_extensions.Reader.read, urllib3.contrib.emscripten.response.EmscriptenHttpResponseWrapper.read, urllib3.response.BaseHTTPResponse.read, urllib3.response.HTTPResponse.read, urllib3.util.retry.Retry.read, urllib3.util.ssltransport.SSLTransport.read, setuptools._vendor.importlib_metadata.Sectioned.valid.
setuptools._vendor.importlib_metadata.Sectioned.read(text, filter_=None)
Referenced by pip._vendor.urllib3.util.retry._RetryMeta.BACKOFF_MAX, pip._vendor.urllib3.response.MultiDecoder.decompress, setuptools._vendor.importlib_metadata.Sectioned.section_pairs.
setuptools._vendor.importlib_metadata.Sectioned.valid(line)
Referenced by setuptools._vendor.importlib_metadata.Sectioned.section_pairs.