fastapi::openapi::models::EmailStr
fastapi.openapi.models.EmailStr::_validate
str fastapi.openapi.models.EmailStr.validate(cls, Any v)
Referenced by pydantic.v1.networks.AnyUrl.build, pydantic.v1.main.BaseModel.schema_json, pip._vendor.distlib.metadata.Metadata.write.
str fastapi.openapi.models.EmailStr._validate(cls, Any __input_value, Any _)