anyio::_backends::_asyncio::AsyncIOBackend
T_Retval anyio._backends._asyncio.AsyncIOBackend.run(cls, Callable[[Unpack[PosArgsT]], Awaitable[T_Retval]] func, tuple[Unpack[PosArgsT]] args, dict[str, Any] kwargs, dict[str, Any] options)
Run the given coroutine function in an asynchronous event loop. The current thread must not be already running an event loop. :param func: a coroutine function :param args: positional arguments to ``func`` :param kwargs: positional arguments to ``func`` :param options: keyword arguments to call the backend ``run()`` implementation with :return: the return value of the coroutine function
References anyio._backends._asyncio.get_callable_name.
Referenced by pip._internal.cli.base_command.Command._main, pip._internal.cli.base_command.Command._run_wrapper.
object anyio._backends._asyncio.AsyncIOBackend.current_token(cls)
Return an object that allows other threads to run code inside the event loop. :return: a token object, specific to the event loop running in the current thread
float anyio._backends._asyncio.AsyncIOBackend.current_time(cls)
Return the current value of the event loop's internal clock. :return: the clock value (seconds)
Referenced by anyio._backends._asyncio.AsyncIOBackend.run_sync_in_worker_thread.
type[BaseException] anyio._backends._asyncio.AsyncIOBackend.cancelled_exception_class(cls)
Return the exception class that is raised in a task if it's cancelled.
None anyio._backends._asyncio.AsyncIOBackend.checkpoint(cls)
Check if the task has been cancelled, and allow rescheduling of other tasks. This is effectively the same as running :meth:`checkpoint_if_cancelled` and then :meth:`cancel_shielded_checkpoint`.
References anyio._backends._asyncio.AsyncIOBackend.sleep.
Referenced by anyio.abc._eventloop.AsyncBackend.checkpoint_if_cancelled, anyio._backends._asyncio.AsyncIOBackend.connect_unix, anyio._backends._asyncio.AsyncIOBackend.create_unix_datagram_socket, anyio._backends._asyncio.AsyncIOBackend.open_process, anyio._backends._asyncio.AsyncIOBackend.run_sync_in_worker_thread, anyio._backends._asyncio.AsyncIOBackend.wait_all_tasks_blocked.
None anyio._backends._asyncio.AsyncIOBackend.checkpoint_if_cancelled(cls)
Check if the current task group has been cancelled. This will check if the task has been cancelled, but will not allow other tasks to be scheduled if not.
References anyio._backends._asyncio.AsyncIOBackend.sleep.
None anyio._backends._asyncio.AsyncIOBackend.cancel_shielded_checkpoint(cls)
Allow the rescheduling of other tasks. This will give other tasks the opportunity to run, but without checking if the current task group has been cancelled, unlike with :meth:`checkpoint`.
References anyio._backends._asyncio.AsyncIOBackend.sleep.
None anyio._backends._asyncio.AsyncIOBackend.sleep(cls, float delay)
Pause the current task for the specified duration. :param delay: the duration, in seconds
References anyio._backends._asyncio.AsyncIOBackend.sleep.
Referenced by anyio._backends._asyncio.AsyncIOBackend.cancel_shielded_checkpoint, anyio.abc._eventloop.AsyncBackend.cancel_shielded_checkpoint, anyio._backends._asyncio.AsyncIOBackend.checkpoint, anyio._backends._asyncio.AsyncIOBackend.checkpoint_if_cancelled, anyio._backends._asyncio.AsyncIOBackend.sleep, anyio._backends._asyncio.AsyncIOBackend.wait_all_tasks_blocked.
CancelScope anyio._backends._asyncio.AsyncIOBackend.create_cancel_scope(cls, *, float deadline=math.inf, bool shield=False)
Referenced by anyio.abc._eventloop.AsyncBackend.cancel_shielded_checkpoint.
float anyio._backends._asyncio.AsyncIOBackend.current_effective_deadline(cls)
Return the nearest deadline among all the cancel scopes effective for the current task. :return: - a clock value from the event loop's internal clock - ``inf`` if there is no deadline in effect - ``-inf`` if the current scope has been cancelled :rtype: float
Referenced by anyio.abc._eventloop.AsyncBackend.checkpoint_if_cancelled.
abc.TaskGroup anyio._backends._asyncio.AsyncIOBackend.create_task_group(cls)
abc.Event anyio._backends._asyncio.AsyncIOBackend.create_event(cls)
abc.Lock anyio._backends._asyncio.AsyncIOBackend.create_lock(cls, *, bool fast_acquire)
abc.Semaphore anyio._backends._asyncio.AsyncIOBackend.create_semaphore(cls, int initial_value, *, int|None max_value=None, bool fast_acquire=False)
abc.CapacityLimiter anyio._backends._asyncio.AsyncIOBackend.create_capacity_limiter(cls, float total_tokens)
T_Retval anyio._backends._asyncio.AsyncIOBackend.run_sync_in_worker_thread(cls, Callable[[Unpack[PosArgsT]], T_Retval] func, tuple[Unpack[PosArgsT]] args, bool abandon_on_cancel=False, abc.CapacityLimiter|None limiter=None)
References anyio._backends._asyncio.AsyncIOBackend.checkpoint, anyio._backends._asyncio.AsyncIOBackend.current_default_thread_limiter, anyio._backends._asyncio.AsyncIOBackend.current_time, anyio._backends._asyncio.find_root_task.
None anyio._backends._asyncio.AsyncIOBackend.check_cancelled(cls)
T_Retval anyio._backends._asyncio.AsyncIOBackend.run_async_from_thread(cls, Callable[[Unpack[PosArgsT]], Awaitable[T_Retval]] func, tuple[Unpack[PosArgsT]] args, object token)
T_Retval anyio._backends._asyncio.AsyncIOBackend.run_sync_from_thread(cls, Callable[[Unpack[PosArgsT]], T_Retval] func, tuple[Unpack[PosArgsT]] args, object token)
abc.BlockingPortal anyio._backends._asyncio.AsyncIOBackend.create_blocking_portal(cls)
Process anyio._backends._asyncio.AsyncIOBackend.open_process(cls, StrOrBytesPath|Sequence[StrOrBytesPath] command, *, int|IO[Any]|None stdin, int|IO[Any]|None stdout, int|IO[Any]|None stderr, **Any kwargs)
References anyio._backends._asyncio.AsyncIOBackend.checkpoint.
None anyio._backends._asyncio.AsyncIOBackend.setup_process_pool_exit_at_shutdown(cls, set[abc.Process] workers)
References anyio._backends._asyncio._shutdown_process_pool_on_exit, anyio._backends._asyncio.find_root_task.
abc.SocketStream anyio._backends._asyncio.AsyncIOBackend.connect_tcp(cls, str host, int port, IPSockAddrType|None local_address=None)
abc.UNIXSocketStream anyio._backends._asyncio.AsyncIOBackend.connect_unix(cls, str|bytes path)
References anyio._backends._asyncio.AsyncIOBackend.checkpoint.
SocketListener anyio._backends._asyncio.AsyncIOBackend.create_tcp_listener(cls, socket.socket sock)
SocketListener anyio._backends._asyncio.AsyncIOBackend.create_unix_listener(cls, socket.socket sock)
UDPSocket | ConnectedUDPSocket anyio._backends._asyncio.AsyncIOBackend.create_udp_socket(cls, AddressFamily family, IPSockAddrType|None local_address, IPSockAddrType|None remote_address, bool reuse_port)
abc.UNIXDatagramSocket | abc.ConnectedUNIXDatagramSocket anyio._backends._asyncio.AsyncIOBackend.create_unix_datagram_socket(cls, socket.socket raw_socket, str|bytes|None remote_path)
References anyio._backends._asyncio.AsyncIOBackend.checkpoint.
Sequence[ tuple[ AddressFamily, SocketKind, int, str, tuple[str, int] | tuple[str, int, int, int] | tuple[int, bytes], ] ] anyio._backends._asyncio.AsyncIOBackend.getaddrinfo(cls, bytes|str|None host, str|int|None port, *, int|AddressFamily family=0, int|SocketKind type=0, int proto=0, int flags=0)
References anyio._backends._asyncio.AsyncIOBackend.getaddrinfo.
Referenced by anyio._backends._asyncio.AsyncIOBackend.getaddrinfo.
tuple[str, str] anyio._backends._asyncio.AsyncIOBackend.getnameinfo(cls, IPSockAddrType sockaddr, int flags=0)
References anyio._backends._asyncio.AsyncIOBackend.getnameinfo.
Referenced by anyio._backends._asyncio.AsyncIOBackend.getnameinfo.
None anyio._backends._asyncio.AsyncIOBackend.wait_readable(cls, FileDescriptorLike obj)
None anyio._backends._asyncio.AsyncIOBackend.wait_writable(cls, FileDescriptorLike obj)
None anyio._backends._asyncio.AsyncIOBackend.notify_closing(cls, FileDescriptorLike obj)
SocketListener anyio._backends._asyncio.AsyncIOBackend.wrap_listener_socket(cls, socket.socket sock)
SocketStream anyio._backends._asyncio.AsyncIOBackend.wrap_stream_socket(cls, socket.socket sock)
UNIXSocketStream anyio._backends._asyncio.AsyncIOBackend.wrap_unix_stream_socket(cls, socket.socket sock)
UDPSocket anyio._backends._asyncio.AsyncIOBackend.wrap_udp_socket(cls, socket.socket sock)
ConnectedUDPSocket anyio._backends._asyncio.AsyncIOBackend.wrap_connected_udp_socket(cls, socket.socket sock)
UNIXDatagramSocket anyio._backends._asyncio.AsyncIOBackend.wrap_unix_datagram_socket(cls, socket.socket sock)
ConnectedUNIXDatagramSocket anyio._backends._asyncio.AsyncIOBackend.wrap_connected_unix_datagram_socket(cls, socket.socket sock)
CapacityLimiter anyio._backends._asyncio.AsyncIOBackend.current_default_thread_limiter(cls)
Referenced by anyio._backends._asyncio.AsyncIOBackend.run_sync_in_worker_thread.
AbstractContextManager[AsyncIterator[Signals]] anyio._backends._asyncio.AsyncIOBackend.open_signal_receiver(cls, *Signals signals)
TaskInfo anyio._backends._asyncio.AsyncIOBackend.get_current_task(cls)
Sequence[TaskInfo] anyio._backends._asyncio.AsyncIOBackend.get_running_tasks(cls)
None anyio._backends._asyncio.AsyncIOBackend.wait_all_tasks_blocked(cls)
References anyio._backends._asyncio.AsyncIOBackend.checkpoint, anyio._backends._asyncio.AsyncIOBackend.sleep.
TestRunner anyio._backends._asyncio.AsyncIOBackend.create_test_runner(cls, dict[str, Any] options)