pip::_vendor::pkg_resources::WorkingSet
list pip._vendor.pkg_resources.WorkingSet::entries
dict pip._vendor.pkg_resources.WorkingSet::entry_keys
dict pip._vendor.pkg_resources.WorkingSet::by_key
dict pip._vendor.pkg_resources.WorkingSet::normalized_to_canonical_keys
list pip._vendor.pkg_resources.WorkingSet::callbacks
pip._vendor.pkg_resources.WorkingSet._build_master(cls)
Prepare the master working set.
pip._vendor.pkg_resources.WorkingSet._build_from_requirements(cls, req_spec)
Build a working set from a requirement spec. Rewrites sys.path.
Distribution pip._vendor.pkg_resources.WorkingSet._resolve_dist(self, req, best, replace_conflicting, env, installer, required_by, to_activate)
pip._vendor.pkg_resources.WorkingSet._added_new(self, dist)
pip._vendor.pkg_resources.WorkingSet._build_master(cls)
Prepare the master working set.
pip._vendor.pkg_resources.WorkingSet._build_from_requirements(cls, req_spec)
Build a working set from a requirement spec. Rewrites sys.path.
pip._vendor.pkg_resources.WorkingSet._resolve_dist(self, req, best, replace_conflicting, env, installer, required_by, to_activate)
pip._vendor.pkg_resources.WorkingSet._added_new(self, dist)
pip._vendor.pkg_resources.WorkingSet.add_entry(self, str entry)
Add a path item to ``.entries``, finding any distributions on it ``find_distributions(entry, True)`` is used to find distributions corresponding to the path entry, and they are added. `entry` is always appended to ``.entries``, even if it is already present. (This is because ``sys.path`` can contain the same value more than once, and the ``.entries`` of the ``sys.path`` WorkingSet should always equal ``sys.path``.)
Distribution | None pip._vendor.pkg_resources.WorkingSet.find(self, Requirement req)
Find a distribution matching requirement `req` If there is an active distribution for the requested project, this returns it as long as it meets the version requirement specified by `req`. But, if there is an active distribution for the project and it does *not* meet the `req` requirement, ``VersionConflict`` is raised. If there is no active distribution for the requested project, ``None`` is returned.
pip._vendor.pkg_resources.WorkingSet.iter_entry_points(self, str group, str|None name=None)
Yield entry point objects from `group` matching `name` If `name` is None, yields all entry points in `group` from all distributions in the working set, otherwise only ones matching both `group` and `name` are yielded (in distribution order).
pip._vendor.pkg_resources.WorkingSet.run_script(self, str requires, str script_name)
Locate distribution for `requires` and run `script_name` script
pip._vendor.pkg_resources.WorkingSet.add(self, Distribution dist, str|None entry=None, bool insert=True, bool replace=False)
Add `dist` to working set, associated with `entry` If `entry` is unspecified, it defaults to the ``.location`` of `dist`. On exit from this routine, `entry` is added to the end of the working set's ``.entries`` (if it wasn't already present). `dist` is only added to the working set if it's for a project that doesn't already have a distribution in the set, unless `replace=True`. If it's added, any callbacks registered with the ``subscribe()`` method will be called.
Referenced by pip._vendor.distlib.manifest.Manifest.add_many, pip._vendor.urllib3._collections.HTTPHeaderDict.extend, urllib3._collections.HTTPHeaderDict.extend, setuptools._vendor.ordered_set.OrderedSet.update.
list[_DistributionT] pip._vendor.pkg_resources.WorkingSet.resolve(self, Iterable[Requirement] requirements, Environment|None env, _InstallerTypeT[_DistributionT] installer, bool replace_conflicting=False, tuple[str,...]|None extras=None)
list[_DistributionT] pip._vendor.pkg_resources.WorkingSet.resolve(self, Iterable[Requirement] requirements, Environment|None env=None, *, _InstallerTypeT[_DistributionT] installer, bool replace_conflicting=False, tuple[str,...]|None extras=None)
list[Distribution] pip._vendor.pkg_resources.WorkingSet.resolve(self, Iterable[Requirement] requirements, Environment|None env=None, _InstallerType|None installer=None, bool replace_conflicting=False, tuple[str,...]|None extras=None)
list[Distribution] | list[_DistributionT] pip._vendor.pkg_resources.WorkingSet.resolve(self, Iterable[Requirement] requirements, Environment|None env=None, _InstallerType|None|_InstallerTypeT[_DistributionT] installer=None, bool replace_conflicting=False, tuple[str,...]|None extras=None)
List all distributions needed to (recursively) meet `requirements` `requirements` must be a sequence of ``Requirement`` objects. `env`, if supplied, should be an ``Environment`` instance. If not supplied, it defaults to all distributions available within any entry or distribution in the working set. `installer`, if supplied, will be invoked with each requirement that cannot be met by an already-installed distribution; it should return a ``Distribution`` or ``None``. Unless `replace_conflicting=True`, raises a VersionConflict exception if any requirements are found on the path that have the correct name but the wrong version. Otherwise, if an `installer` is supplied it will be invoked to obtain the correct version of the requirement and activate it. `extras` is a list of the extras to be used with these requirements. This is important because extra requirements may look like `my_req; extra = "my_extra"`, which would otherwise be interpreted as a purely optional requirement. Instead, we want to be able to assert that these requirements are truly required.
tuple[list[_DistributionT], dict[Distribution, Exception]] pip._vendor.pkg_resources.WorkingSet.find_plugins(self, Environment plugin_env, Environment|None full_env, _InstallerTypeT[_DistributionT] installer, bool fallback=True)
tuple[list[_DistributionT], dict[Distribution, Exception]] pip._vendor.pkg_resources.WorkingSet.find_plugins(self, Environment plugin_env, Environment|None full_env=None, *, _InstallerTypeT[_DistributionT] installer, bool fallback=True)
tuple[list[Distribution], dict[Distribution, Exception]] pip._vendor.pkg_resources.WorkingSet.find_plugins(self, Environment plugin_env, Environment|None full_env=None, _InstallerType|None installer=None, bool fallback=True)
tuple[ list[Distribution] | list[_DistributionT], dict[Distribution, Exception], ] pip._vendor.pkg_resources.WorkingSet.find_plugins(self, Environment plugin_env, Environment|None full_env=None, _InstallerType|None|_InstallerTypeT[_DistributionT] installer=None, bool fallback=True)
Find all activatable distributions in `plugin_env` Example usage:: distributions, errors = working_set.find_plugins( Environment(plugin_dirlist) ) # add plugins+libs to sys.path map(working_set.add, distributions) # display errors print('Could not load', errors) The `plugin_env` should be an ``Environment`` instance that contains only distributions that are in the project's "plugin directory" or directories. The `full_env`, if supplied, should be an ``Environment`` contains all currently-available distributions. If `full_env` is not supplied, one is created automatically from the ``WorkingSet`` this method is called on, which will typically mean that every directory on ``sys.path`` will be scanned for distributions. `installer` is a standard installer callback as used by the ``resolve()`` method. The `fallback` flag indicates whether we should attempt to resolve older versions of a plugin if the newest version cannot be resolved. This method returns a 2-tuple: (`distributions`, `error_info`), where `distributions` is a list of the distributions found in `plugin_env` that were loadable, along with any other distributions that are needed to resolve their dependencies. `error_info` is a dictionary mapping unloadable plugin distributions to an exception instance describing the error that occurred. Usually this will be a ``DistributionNotFound`` or ``VersionConflict`` instance.
pip._vendor.pkg_resources.WorkingSet.require(self, *_NestedStr requirements)
Ensure that distributions matching `requirements` are activated `requirements` must be a string or a (possibly-nested) sequence thereof, specifying the distributions and versions required. The return value is a sequence of the distributions that needed to be activated to fulfill the requirements; all relevant distributions are included, even if they were already activated in this working set.
pip._vendor.pkg_resources.WorkingSet.subscribe(self, Callable[[Distribution], object] callback, bool existing=True)
Invoke `callback` for all distributions If `existing=True` (default), call on all existing ones, as well.
pip._vendor.pkg_resources.WorkingSet.add_entry(self, entry)
Add a path item to ``.entries``, finding any distributions on it ``find_distributions(entry, True)`` is used to find distributions corresponding to the path entry, and they are added. `entry` is always appended to ``.entries``, even if it is already present. (This is because ``sys.path`` can contain the same value more than once, and the ``.entries`` of the ``sys.path`` WorkingSet should always equal ``sys.path``.)
pip._vendor.pkg_resources.WorkingSet.find(self, req)
Find a distribution matching requirement `req` If there is an active distribution for the requested project, this returns it as long as it meets the version requirement specified by `req`. But, if there is an active distribution for the project and it does *not* meet the `req` requirement, ``VersionConflict`` is raised. If there is no active distribution for the requested project, ``None`` is returned.
pip._vendor.pkg_resources.WorkingSet.iter_entry_points(self, group, name=None)
Yield entry point objects from `group` matching `name` If `name` is None, yields all entry points in `group` from all distributions in the working set, otherwise only ones matching both `group` and `name` are yielded (in distribution order).
pip._vendor.pkg_resources.WorkingSet.run_script(self, requires, script_name)
Locate distribution for `requires` and run `script_name` script
pip._vendor.pkg_resources.WorkingSet.add(self, dist, entry=None, insert=True, replace=False)
Add `dist` to working set, associated with `entry` If `entry` is unspecified, it defaults to the ``.location`` of `dist`. On exit from this routine, `entry` is added to the end of the working set's ``.entries`` (if it wasn't already present). `dist` is only added to the working set if it's for a project that doesn't already have a distribution in the set, unless `replace=True`. If it's added, any callbacks registered with the ``subscribe()`` method will be called.
Referenced by setuptools._vendor.ordered_set.OrderedSet.update.
pip._vendor.pkg_resources.WorkingSet.resolve(self, requirements, env=None, installer=None, replace_conflicting=False, extras=None)
List all distributions needed to (recursively) meet `requirements` `requirements` must be a sequence of ``Requirement`` objects. `env`, if supplied, should be an ``Environment`` instance. If not supplied, it defaults to all distributions available within any entry or distribution in the working set. `installer`, if supplied, will be invoked with each requirement that cannot be met by an already-installed distribution; it should return a ``Distribution`` or ``None``. Unless `replace_conflicting=True`, raises a VersionConflict exception if any requirements are found on the path that have the correct name but the wrong version. Otherwise, if an `installer` is supplied it will be invoked to obtain the correct version of the requirement and activate it. `extras` is a list of the extras to be used with these requirements. This is important because extra requirements may look like `my_req; extra = "my_extra"`, which would otherwise be interpreted as a purely optional requirement. Instead, we want to be able to assert that these requirements are truly required.
pip._vendor.pkg_resources.WorkingSet.find_plugins(self, plugin_env, full_env=None, installer=None, fallback=True)
Find all activatable distributions in `plugin_env` Example usage:: distributions, errors = working_set.find_plugins( Environment(plugin_dirlist) ) # add plugins+libs to sys.path map(working_set.add, distributions) # display errors print('Could not load', errors) The `plugin_env` should be an ``Environment`` instance that contains only distributions that are in the project's "plugin directory" or directories. The `full_env`, if supplied, should be an ``Environment`` contains all currently-available distributions. If `full_env` is not supplied, one is created automatically from the ``WorkingSet`` this method is called on, which will typically mean that every directory on ``sys.path`` will be scanned for distributions. `installer` is a standard installer callback as used by the ``resolve()`` method. The `fallback` flag indicates whether we should attempt to resolve older versions of a plugin if the newest version cannot be resolved. This method returns a 2-tuple: (`distributions`, `error_info`), where `distributions` is a list of the distributions found in `plugin_env` that were loadable, along with any other distributions that are needed to resolve their dependencies. `error_info` is a dictionary mapping unloadable plugin distributions to an exception instance describing the error that occurred. Usually this will be a ``DistributionNotFound`` or ``VersionConflict`` instance.
pip._vendor.pkg_resources.WorkingSet.require(self, *requirements)
Ensure that distributions matching `requirements` are activated `requirements` must be a string or a (possibly-nested) sequence thereof, specifying the distributions and versions required. The return value is a sequence of the distributions that needed to be activated to fulfill the requirements; all relevant distributions are included, even if they were already activated in this working set.
pip._vendor.pkg_resources.WorkingSet.subscribe(self, callback, existing=True)
Invoke `callback` for all distributions If `existing=True` (default), call on all existing ones, as well.