setuptools::dist::Distribution
dict setuptools.dist.Distribution::_DISTUTILS_UNSUPPORTED_METADATA
setuptools.dist.Distribution::_patched_dist
dict setuptools.dist.Distribution::package_data
list setuptools.dist.Distribution::dist_files
setuptools.dist.Distribution::src_root
setuptools.dist.Distribution::dependency_links
setuptools.dist.Distribution::setup_requires
setuptools.dist.Distribution::set_defaults
setuptools.dist.Distribution::metadata
Referenced by setuptools._vendor.importlib_metadata.Distribution._read_dist_info_reqs, pip._internal.req.req_install.InstallRequirement._set_requirement, pip._internal.req.req_install.InstallRequirement.archive, pip._internal.req.req_install.InstallRequirement.archive, pip._internal.req.req_install.InstallRequirement.assert_source_matches_version, setuptools._vendor.importlib_metadata.Distribution.name, setuptools._vendor.importlib_metadata.Distribution.version, pip._internal.req.req_install.InstallRequirement.warn_on_mismatching_name.
setuptools.dist.Distribution::install_requires
setuptools.dist.Distribution::extras_require
setuptools.dist.Distribution::command_options
setuptools.dist.Distribution::cmdclass
list setuptools.dist.Distribution::packages
list setuptools.dist.Distribution::py_modules
list setuptools.dist.Distribution::ext_modules
setuptools.dist.Distribution::exclude_package
setuptools.dist.Distribution::global_options
setuptools.dist.Distribution::negative_opt
setuptools.dist.Distribution::help_commands
dict setuptools.dist.Distribution::_orig_extras_require
list setuptools.dist.Distribution::_orig_install_requires
setuptools.dist.Distribution::_tmp_extras_require
setuptools.dist.Distribution.patch_missing_pkg_info(self, attrs)
setuptools.dist.Distribution.warn_dash_deprecation(self, opt, section)
setuptools.dist.Distribution.make_option_lowercase(self, opt, section)
setuptools.dist.Distribution.parse_config_files(self, filenames=None, ignore_option_errors=False)
Parses configuration files from various levels and loads configuration.
setuptools.dist.Distribution.fetch_build_eggs(self, requires)
Resolve pre-setup requirements
setuptools.dist.Distribution.finalize_options(self)
Allow plugins to apply arbitrary operations to the distribution. Each hook may optionally define a 'order' to influence the order of execution. Smaller numbers go first and the default is 0.
setuptools.dist.Distribution.get_egg_cache_dir(self)
setuptools.dist.Distribution.fetch_build_egg(self, req)
Fetch an egg needed for building
setuptools.dist.Distribution.get_command_class(self, command)
Pluggable version of get_command_class()
setuptools.dist.Distribution.print_commands(self)
setuptools.dist.Distribution.get_command_list(self)
setuptools.dist.Distribution.include(self, **attrs)
Add items to distribution that are named in keyword arguments For example, 'dist.include(py_modules=["x"])' would add 'x' to the distribution's 'py_modules' attribute, if it was not already there. Currently, this method only supports inclusion for attributes that are lists or tuples. If you need to add support for adding to other attributes in this or a subclass, you can add an '_include_X' method, where 'X' is the name of the attribute. The method will be called with the value passed to 'include()'. So, 'dist.include(foo={"bar":"baz"})' will try to call 'dist._include_foo({"bar":"baz"})', which can then handle whatever special inclusion logic is needed.
setuptools.dist.Distribution.exclude_package(self, package)
Remove packages, modules, and extensions in named package
setuptools.dist.Distribution.has_contents_for(self, package)
Return true if 'exclude_package(package)' would do something
setuptools.dist.Distribution.exclude(self, **attrs)
Remove items from distribution that are named in keyword arguments For example, 'dist.exclude(py_modules=["x"])' would remove 'x' from the distribution's 'py_modules' attribute. Excluding packages uses the 'exclude_package()' method, so all of the package's contained packages, modules, and extensions are also excluded. Currently, this method only supports exclusion from attributes that are lists or tuples. If you need to add support for excluding from other attributes in this or a subclass, you can add an '_exclude_X' method, where 'X' is the name of the attribute. The method will be called with the value passed to 'exclude()'. So, 'dist.exclude(foo={"bar":"baz"})' will try to call 'dist._exclude_foo({"bar":"baz"})', which can then handle whatever special exclusion logic is needed.
setuptools.dist.Distribution.get_cmdline_options(self)
Return a '{cmd: {opt:val}}' map of all command-line options Option names are all long, but do not include the leading '--', and contain dashes rather than underscores. If the option doesn't take an argument (e.g. '--quiet'), the 'val' is 'None'. Note that options provided by config files are intentionally excluded.
setuptools.dist.Distribution.iter_distribution_names(self)
Yield all packages, modules, and extension names in distribution
setuptools.dist.Distribution.handle_display_options(self, option_order)
If there were any non-global "display-only" options (--help-commands or the metadata display options) on the command line, display the requested info and return true; else return false.
setuptools.dist.Distribution.run_command(self, command)
Referenced by setuptools.command.editable_wheel.editable_wheel._run_build_subcommands, setuptools.command.editable_wheel.editable_wheel._run_install, setuptools.command.editable_wheel.editable_wheel._safely_run, setuptools._distutils.command.install_lib.install_lib.build, setuptools.command.install.install.do_egg_install, setuptools.command.develop.develop.install_for_development, setuptools.command.test.test.project_on_sys_path, setuptools._distutils.command.bdist.bdist.run, setuptools._distutils.command.bdist_dumb.bdist_dumb.run, setuptools._distutils.command.bdist_rpm.bdist_rpm.run, setuptools._distutils.command.build.build.run, setuptools._distutils.command.install.install.run, setuptools._distutils.command.install_scripts.install_scripts.run, setuptools._distutils.command.register.register.run, setuptools.command.bdist_egg.bdist_egg.run, setuptools.command.bdist_rpm.bdist_rpm.run, setuptools.command.install_egg_info.install_egg_info.run, setuptools.command.install_scripts.install_scripts.run, setuptools.command.rotate.rotate.run, setuptools.command.sdist.sdist.run, setuptools.command.upload_docs.upload_docs.run.
setuptools.dist.Distribution._validate_metadata(self)
setuptools.dist.Distribution._set_metadata_defaults(self, attrs)
Fill-in missing metadata fields not supported by distutils. Some fields may have been set by other tools (e.g. pbr). Those fields (vars(self.metadata)) take precedence to supplied attrs.
setuptools.dist.Distribution._finalize_requires(self)
Set `metadata.python_requires` and fix environment markers in `install_requires` and `extras_require`.
setuptools.dist.Distribution._convert_extras_requirements(self)
Convert requirements in `extras_require` of the form `"extra": ["barbazquux; {marker}"]` to `"extra:{marker}": ["barbazquux"]`.
setuptools.dist.Distribution._move_install_requirements_markers(self)
Move requirements in `install_requires` that are using environment markers `extras_require`.
setuptools.dist.Distribution._clean_req(self, req)
Given a Requirement, remove environment markers and return it.
setuptools.dist.Distribution._finalize_license_files(self)
Compute names of all license files which should be included.
setuptools.dist.Distribution._parse_config_files(self, filenames=None)
Adapted from distutils.dist.Distribution.parse_config_files, this method provides the same functionality in subtly-improved ways.
setuptools.dist.Distribution._setuptools_commands(self)
setuptools.dist.Distribution._set_command_options(self, command_obj, option_dict=None)
Set the options for 'command_obj' from 'option_dict'. Basically this means copying elements of a dictionary ('option_dict') to attributes of an instance ('command'). 'command_obj' must be a Command instance. If 'option_dict' is not supplied, uses the standard option dictionary for this command (from 'self.command_options'). (Adopted from distutils.dist.Distribution._set_command_options)
setuptools.dist.Distribution._get_project_config_files(self, filenames)
Add default file and split between INI and TOML
setuptools.dist.Distribution._finalize_setup_keywords(self)
setuptools.dist.Distribution._exclude_misc(self, name, value)
Handle 'exclude()' for list/tuple attrs without a special handler
setuptools.dist.Distribution._include_misc(self, name, value)
Handle 'include()' for list/tuple attrs without a special handler
setuptools.dist.Distribution._exclude_packages(self, packages)
setuptools.dist.Distribution._parse_command_opts(self, parser, args)
setuptools.dist.Distribution._normalize_version(version)
setuptools.dist.Distribution._validate_version(version)
setuptools.dist.Distribution._suffix_for(req)
For a requirement, return the 'extras_require' suffix for that requirement.
setuptools.dist.Distribution._expand_patterns(patterns)
>>> list(Distribution._expand_patterns(['LICENSE'])) ['LICENSE'] >>> list(Distribution._expand_patterns(['setup.cfg', 'LIC*'])) ['setup.cfg', 'LICENSE']
setuptools.dist.Distribution._removed(ep)
When removing an entry point, if metadata is loaded from an older version of Setuptools, that removed entry point will attempt to be loaded and will fail. See #2765 for more details.