pip::_vendor::pkg_resources::ZipManifests
pip._vendor.pkg_resources.ZipManifests::load
pip._vendor.pkg_resources.ZipManifests.build(cls, str path)
Build a dictionary similar to the zipimport directory caches, except instead of tuples, store ZipInfo objects. Use a platform-specific path separator (os.sep) for the path keys for compatibility with pypy on Windows.
Referenced by pydantic._internal._decorators.Decorator.bind_to_cls, setuptools._distutils.command.install_lib.install_lib.run, setuptools.command.install_lib.install_lib.run.
pip._vendor.pkg_resources.ZipManifests.build(cls, path)
Build a dictionary similar to the zipimport directory caches, except instead of tuples, store ZipInfo objects. Use a platform-specific path separator (os.sep) for the path keys for compatibility with pypy on Windows.
Referenced by setuptools._distutils.command.install_lib.install_lib.run, setuptools.command.install_lib.install_lib.run.