anyio::_core::_synchronization::Semaphore
anyio._core._synchronization.Semaphore::_fast_acquire
None anyio._core._synchronization.Semaphore.acquire(self)
Decrement the semaphore value, blocking if necessary.
None anyio._core._synchronization.Semaphore.acquire_nowait(self)
Acquire the underlying lock, without blocking. :raises ~anyio.WouldBlock: if the operation would block
None anyio._core._synchronization.Semaphore.release(self)
Increment the semaphore value.
int anyio._core._synchronization.Semaphore.value(self)
The current value of the semaphore.
Referenced by pip._internal.models.link.LinkHash.as_dict, pip._internal.models.link.LinkHash.as_hashes, pip._internal.models.link.LinkHash.is_hash_allowed, pip._internal.models.link.LinkHash.is_hash_allowed, pydantic._internal._utils.LazyClassAttribute.value.
int | None anyio._core._synchronization.Semaphore.max_value(self)
The maximum value of the semaphore.
SemaphoreStatistics anyio._core._synchronization.Semaphore.statistics(self)
Return statistics about the current state of this semaphore. .. versionadded:: 3.0
Referenced by pip._vendor.tenacity.BaseRetrying.begin, pip._vendor.tenacity.BaseRetrying.iter.