anyio::abc::_tasks::TaskGroup
None anyio.abc._tasks.TaskGroup.start_soon(self, Callable[[Unpack[PosArgsT]], Awaitable[Any]] func, *Unpack[PosArgsT] args, object name=None)
Start a new task in this task group. :param func: a coroutine function :param args: positional arguments to call the function with :param name: name of the task, for the purposes of introspection and debugging .. versionadded:: 3.0
Any anyio.abc._tasks.TaskGroup.start(self, Callable[..., Awaitable[Any]] func, *object args, object name=None)
Start a new task and wait until it signals for readiness. The target callable must accept a keyword argument ``task_status`` (of type :class:`TaskStatus`). Awaiting on this method will return whatever was passed to ``task_status.started()`` (``None`` by default). .. note:: The :class:`TaskStatus` class is generic, and the type argument should indicate the type of the value that will be passed to ``task_status.started()``. :param func: a coroutine function that accepts the ``task_status`` keyword argument :param args: positional arguments to call the function with :param name: an optional name for the task, for introspection and debugging :return: the value passed to ``task_status.started()`` :raises RuntimeError: if the task finishes without calling ``task_status.started()`` .. seealso:: :ref:`start_initialize` .. versionadded:: 3.0
Referenced by pip._vendor.rich.progress._TrackThread.run, pip._vendor.rich.live.Live.stop, pip._vendor.rich.progress.Progress.stop, pip._vendor.rich.status.Status.stop.