ILogPanelMQTT::ILogPanelMQTT
ILogPanelMQTT.ILogPanelMQTT.Publicar(self, str topic, message)
Referenced by LogPanelMQTT.LogPanelMQTT.PubLog, LogPanelMQTT.LogPanelMQTT.PubRawLog, LogPanelMQTT.LogPanelMQTT.PubUserLog.
ILogPanelMQTT.ILogPanelMQTT.PubLog(self, str key, int id_emisor, str nombre_emisor, int id_receptor, str nombre_receptor, str elemento, str estado)
ILogPanelMQTT.ILogPanelMQTT.PubUserLog(self, str entidad_interes, str objeto, str recurso, str estado)
ILogPanelMQTT.ILogPanelMQTT.PubRawLog(self, str objeto, str recurso, str value)
ILogPanelMQTT.ILogPanelMQTT.Publicar(self, str topic, message)
ILogPanelMQTT.ILogPanelMQTT.suscribir(self, str topic, callback)
ILogPanelMQTT.ILogPanelMQTT.PubLog(self, str key, int id_emisor, str nombre_emisor, int id_receptor, str nombre_receptor, str elemento, str estado)
ILogPanelMQTT.ILogPanelMQTT.PubUserLog(self, str entidad_interes, str objeto, str recurso, str estado)
ILogPanelMQTT.ILogPanelMQTT.PubRawLog(self, str objeto, str recurso, str value)
ILogPanelMQTT.ILogPanelMQTT.Publicar(self, str topic, message)
ILogPanelMQTT.ILogPanelMQTT.PubLog(self, str key, int id_emisor, str nombre_emisor, int id_receptor, str nombre_receptor, str elemento, str estado)
ILogPanelMQTT.ILogPanelMQTT.PubUserLog(self, str entidad_interes, str objeto, str recurso, str estado)
ILogPanelMQTT.ILogPanelMQTT.PubRawLog(self, str objeto, str recurso, str value)