pydantic::v1::networks::AnyUrl
bool pydantic.v1.networks.AnyUrl::strip_whitespace
Referenced by pydantic.v1.networks.AnyUrl.validate.
int pydantic.v1.networks.AnyUrl::min_length
Referenced by pydantic.v1.networks.AnyUrl.build.
int pydantic.v1.networks.AnyUrl::max_length
Referenced by pydantic.v1.networks.AnyUrl.build.
pydantic.v1.networks.AnyUrl::allowed_schemes
Referenced by pydantic.v1.networks.AnyUrl.validate_parts.
bool pydantic.v1.networks.AnyUrl::tld_required
Referenced by pydantic.v1.networks.AnyUrl.validate_host.
bool pydantic.v1.networks.AnyUrl::user_required
Referenced by pydantic.v1.networks.AnyUrl.validate_parts.
bool pydantic.v1.networks.AnyUrl::host_required
Referenced by pydantic.v1.networks.AnyUrl.validate_host.
Set pydantic.v1.networks.AnyUrl::hidden_parts
Referenced by pydantic.v1.networks.AnyUrl.build.
pydantic.v1.networks.AnyUrl::scheme
Referenced by pip._vendor.distlib.locators.JSONLocator._get_project, pip._vendor.distlib.locators.PyPIJSONLocator._get_project, pip._vendor.distlib.locators.PyPIRPCLocator._get_project, urllib3.connectionpool.HTTPConnectionPool._make_request, pip._vendor.distlib.locators.Locator._update_version_data, pip._vendor.distlib.metadata.Metadata._validate_value, pip._vendor.distlib.metadata.LegacyMetadata.check, uvicorn.protocols.http.h11_impl.H11Protocol.connection_made, uvicorn.protocols.http.httptools_impl.HttpToolsProtocol.connection_made, uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol.connection_made, uvicorn.protocols.websockets.websockets_sansio_impl.WebSocketsSansIOProtocol.connection_made, uvicorn.protocols.websockets.wsproto_impl.WSProtocol.connection_made, pip._vendor.distlib.locators.AggregatingLocator.get_distribution_names, uvicorn.protocols.http.h11_impl.H11Protocol.handle_events, urllib3.connectionpool.HTTPConnectionPool.is_same_host, starlette.datastructures.URL.is_secure, pip._vendor.distlib.locators.Locator.locate, uvicorn.protocols.websockets.websockets_impl.WebSocketProtocol.process_request, pip._vendor.distlib.metadata.LegacyMetadata.set, pip._vendor.distlib.metadata.Metadata.validate.
pydantic.v1.networks.AnyUrl::user
Referenced by setuptools.command.easy_install.easy_install._fix_install_dir_for_user_site, simple.MQTTClient.connect, setuptools._distutils.command.install.install.create_home_path, setuptools._distutils.command.build_ext.build_ext.finalize_options, setuptools._distutils.command.install.install.finalize_options, setuptools._distutils.command.install.install.finalize_other, setuptools._distutils.command.install.install.finalize_unix.
pydantic.v1.networks.AnyUrl::password
Referenced by pip._vendor.distlib.index.PackageIndex.check_credentials, setuptools._distutils.command.upload.upload.finalize_options, starlette.datastructures.URL.replace, setuptools._distutils.command.register.register.send_metadata, setuptools._distutils.command.upload.upload.upload_file, setuptools.command.upload_docs.upload_docs.upload_file.
pydantic.v1.networks.AnyUrl::host
Referenced by urllib3.connectionpool.HTTPConnectionPool._get_conn, urllib3.connectionpool.HTTPConnectionPool._make_request, urllib3.connectionpool.HTTPConnectionPool._put_conn, uvicorn.config.Config.bind_socket, urllib3.connection.HTTPSConnection.connect, starlette.routing.Host.handle, urllib3.util.url.Url.hostname, urllib3.connectionpool.HTTPConnectionPool.is_same_host, starlette.datastructures.URLPath.make_absolute_url, urllib3.util.url.Url.netloc.
pydantic.v1.networks.AnyUrl::tld
pydantic.v1.networks.AnyUrl::host_type
pydantic.v1.networks.AnyUrl::port
Referenced by pip._vendor.urllib3.connection.HTTPConnection._new_conn, pip._vendor.urllib3.contrib.socks.SOCKSConnection._new_conn, urllib3.connection.HTTPConnection._new_conn, urllib3.connectionpool.HTTPSConnectionPool._prepare_proxy, uvicorn.config.Config.bind_socket, simple.MQTTClient.connect, urllib3.connection.HTTPSConnection.connect, urllib3.connectionpool.HTTPConnectionPool.is_same_host, starlette.datastructures.URL.replace.
pydantic.v1.networks.AnyUrl::path
Referenced by starlette.responses.FileResponse._handle_multiple_ranges, starlette.responses.FileResponse._handle_simple, starlette.responses.FileResponse._handle_single_range, pip._vendor.distlib.database.DistributionPath._yield_distributions, pip._vendor.distlib.database._Cache.add, pip._vendor.distlib.database.EggInfoDistribution.check_installed_files, pip._vendor.distlib.database.InstalledDistribution.check_installed_files, pip._vendor.distlib.database._Cache.clear, OntologiaPU.OntologiaPU.crearNuevaOntologia, pip._internal.models.link.Link.filename, pkg_resources._vendor.importlib_resources.readers.FileReader.files, pkg_resources._vendor.importlib_resources.readers.NamespaceReader.files, setuptools._vendor.importlib_resources.readers.FileReader.files, setuptools._vendor.importlib_resources.readers.NamespaceReader.files, pip._vendor.distlib.database.InstalledDistribution.get_distinfo_file, pip._vendor.distlib.database.InstalledDistribution.get_distinfo_resource, pkg_resources._vendor.importlib_resources._compat.TraversableResourcesLoader.get_resource_reader, setuptools._vendor.importlib_resources._compat.TraversableResourcesLoader.get_resource_reader, OntologiaPU.OntologiaPU.guardarGrafoOntologia, starlette.routing.Mount.handle, starlette.routing.Route.handle, starlette.routing.WebSocketRoute.handle, pip._vendor.distlib.database.EggInfoDistribution.list_distinfo_files, pip._vendor.distlib.database.InstalledDistribution.list_distinfo_files, pip._vendor.distlib.database.EggInfoDistribution.list_installed_files, pip._vendor.urllib3.util.url.Url.request_uri, urllib3.util.url.Url.request_uri, pkg_resources._vendor.importlib_resources.readers.FileReader.resource_path, pkg_resources._vendor.importlib_resources.readers.NamespaceReader.resource_path, setuptools._vendor.importlib_resources.readers.FileReader.resource_path, setuptools._vendor.importlib_resources.readers.NamespaceReader.resource_path, starlette.responses.FileResponse.set_stat_headers, pip._vendor.distlib.database.InstalledDistribution.shared_locations, pip._internal.models.link.Link.splitext, pip._vendor.distlib.database.InstalledDistribution.write_installed_files, pip._vendor.distlib.database.InstalledDistribution.write_shared_locations.
pydantic.v1.networks.AnyUrl::query
Referenced by starlette.datastructures.URL.include_query_params, starlette.datastructures.URL.remove_query_params, pip._vendor.urllib3.util.url.Url.request_uri, urllib3.util.url.Url.request_uri.
pydantic.v1.networks.AnyUrl::fragment
str pydantic.v1.networks.AnyUrl.build(cls, *, str scheme, Optional[str] user=None, Optional[str] password=None, str host, Optional[str] port=None, Optional[str] path=None, Optional[str] query=None, Optional[str] fragment=None, **str _kwargs)
References pydantic.v1.networks.AnyUrl.get_default_parts, pydantic.v1.networks.AnyUrl.hidden_parts, annotated_types.Len.max_length, annotated_types.MaxLen.max_length, pip._vendor.rich.pretty.Pretty.max_length, pydantic.fields._FromFieldInfoInputs.max_length, pydantic.networks.UrlConstraints.max_length, pydantic.types.PaymentCardNumber.max_length, pydantic.types.StringConstraints.max_length, pydantic.v1.fields.FieldInfo.max_length, pydantic.v1.networks.AnyUrl.max_length, annotated_types.Len.min_length, annotated_types.MinLen.min_length, pydantic.fields._FromFieldInfoInputs.min_length, pydantic.types.PaymentCardNumber.min_length, pydantic.types.StringConstraints.min_length, pydantic.v1.fields.FieldInfo.min_length, pydantic.v1.networks.AnyUrl.min_length, fastapi._compat.model_field.ModelField.validate, fastapi._compat.v2.ModelField.validate, fastapi.datastructures.UploadFile.validate, fastapi.openapi.models.EmailStr.validate, pip._internal.models.direct_url.DirectUrl.validate, pydantic.main.BaseModel.validate, pydantic.types.PaymentCardNumber.validate, pydantic.types.PaymentCardNumber.validate, pydantic.v1.fields.ModelField.validate, pydantic.v1.main.BaseModel.validate, pydantic.v1.networks.AnyUrl.validate.
Referenced by setuptools._distutils.command.install_lib.install_lib.run, setuptools.command.install_lib.install_lib.run.
'AnyUrl' pydantic.v1.networks.AnyUrl.validate(cls, Any value, 'ModelField' field, 'BaseConfig' config)
References pydantic.v1.networks.AnyUrl._build_url, pydantic.v1.networks.AnyUrl._match_url, pydantic.v1.networks.AnyUrl.apply_default_parts, pydantic.types.PaymentCardNumber.strip_whitespace, pydantic.types.StringConstraints.strip_whitespace, pydantic.v1.networks.AnyUrl.strip_whitespace, pydantic.v1.networks.AnyUrl.validate_parts.
Referenced by pydantic.v1.networks.AnyUrl.build, pip._vendor.distlib.metadata.Metadata.write.
'Parts' pydantic.v1.networks.AnyUrl.validate_parts(cls, 'Parts' parts, bool validate_port=True)
A method used to validate parts of a URL. Could be overridden to set default values for parts if missing
References pydantic.v1.networks.AnyUrl._validate_port, pydantic.networks.UrlConstraints.allowed_schemes, pydantic.v1.networks.AnyUrl.allowed_schemes, pydantic.v1.networks.AnyUrl.user_required.
Referenced by pydantic.v1.networks.AnyUrl.validate.
Tuple[str, Optional[str], str, bool] pydantic.v1.networks.AnyUrl.validate_host(cls, 'Parts' parts)
References pydantic.v1.networks.ascii_domain_regex, pydantic.networks.UrlConstraints.host_required, pydantic.v1.networks.AnyUrl.host_required, pydantic.v1.networks.int_domain_regex, pydantic.v1.networks.AnyUrl.tld_required.
Referenced by pydantic.v1.networks.AnyUrl._build_url, pydantic.v1.networks.MultiHostDsn._build_url.
'Parts' pydantic.v1.networks.AnyUrl.apply_default_parts(cls, 'Parts' parts)
References annotated_types.BaseMetadata.__slots__, annotated_types.GroupedMetadata.__slots__, anyio._backends._asyncio.TaskState.__slots__, anyio._core._fileio.Path.__slots__, anyio._core._synchronization.ResourceGuard.__slots__, anyio._core._testing.TaskInfo.__slots__, anyio.abc._resources.AsyncResource.__slots__, anyio.lowlevel.RunVar.__slots__, anyio.lowlevel.RunvarToken.__slots__, click.exceptions.Exit.__slots__, click.shell_completion.CompletionItem.__slots__, h11._events._ResponseBase.__slots__, h11._events.Data.__slots__, h11._events.EndOfMessage.__slots__, h11._events.Event.__slots__, h11._events.Request.__slots__, h11._headers.Headers.__slots__, paho.mqtt.client.MQTTMessage.__slots__, paho.mqtt.client.MQTTMessageInfo.__slots__, paho.mqtt.matcher.MQTTMatcher.Node.__slots__, pip._internal.models.candidate.InstallationCandidate.__slots__, pip._internal.models.format_control.FormatControl.__slots__, pip._internal.models.index.PackageIndex.__slots__, pip._internal.models.link.Link.__slots__, pip._internal.models.scheme.Scheme.__slots__, pip._internal.models.search_scope.SearchScope.__slots__, pip._internal.models.selection_prefs.SelectionPreferences.__slots__, pip._internal.models.target_python.TargetPython.__slots__, pip._internal.req.req_file.ParsedLine.__slots__, pip._internal.req.req_file.ParsedRequirement.__slots__, pip._vendor.msgpack.ext.Timestamp.__slots__, pip._vendor.packaging.tags.Tag.__slots__, pip._vendor.rich.control.Control.__slots__, pip._vendor.rich.emoji.Emoji.__slots__, pip._vendor.rich.jupyter.JupyterMixin.__slots__, pip._vendor.rich.style._Bit.__slots__, pip._vendor.rich.style.Style.__slots__, pip._vendor.rich.style.StyleStack.__slots__, pip._vendor.rich.text.Text.__slots__, pip._vendor.urllib3.packages.backports.weakref_finalize.weakref_finalize.__slots__, pip._vendor.urllib3.packages.backports.weakref_finalize.weakref_finalize._Info.__slots__, pip._vendor.urllib3.util.url.Url.__slots__, pydantic._internal._config.ConfigWrapper.__slots__, pydantic._internal._fields.PydanticMetadata.__slots__, pydantic._internal._generate_schema._FieldNameStack.__slots__, pydantic._internal._generate_schema._ModelTypeStack.__slots__, pydantic._internal._generate_schema.GenerateSchema.__slots__, pydantic._internal._mock_val_ser.MockCoreSchema.__slots__, pydantic._internal._mock_val_ser.MockValSer.__slots__, pydantic._internal._repr.Representation.__slots__, pydantic._internal._utils.SafeGetItemProxy.__slots__, pydantic._internal._utils.ValueItems.__slots__, pydantic._internal._validate_call.ValidateCallWrapper.__slots__, pydantic.color.Color.__slots__, pydantic.color.RGBA.__slots__, pydantic.fields.FieldInfo.__slots__, pydantic.fields.ModelPrivateAttr.__slots__, pydantic.main.BaseModel.__slots__, pydantic.mypy.PydanticPluginConfig.__slots__, pydantic.networks.IPvAnyAddress.__slots__, pydantic.networks.IPvAnyInterface.__slots__, pydantic.networks.IPvAnyNetwork.__slots__, pydantic.networks.NameEmail.__slots__, pydantic.plugin._schema_validator.PluggableSchemaValidator.__slots__, pydantic.v1.class_validators.Validator.__slots__, pydantic.v1.color.Color.__slots__, pydantic.v1.color.RGBA.__slots__, pydantic.v1.dataclasses.DataclassProxy.__slots__, pydantic.v1.env_settings.EnvSettingsSource.__slots__, pydantic.v1.env_settings.InitSettingsSource.__slots__, pydantic.v1.env_settings.SecretsSettingsSource.__slots__, pydantic.v1.error_wrappers.ErrorWrapper.__slots__, pydantic.v1.error_wrappers.ValidationError.__slots__, pydantic.v1.fields.FieldInfo.__slots__, pydantic.v1.fields.ModelField.__slots__, pydantic.v1.fields.ModelPrivateAttr.__slots__, pydantic.v1.generics.GenericModel.__slots__, pydantic.v1.main.BaseModel.__slots__, pydantic.v1.mypy.PydanticPluginConfig.__slots__, pydantic.v1.networks.AnyUrl.__slots__, pydantic.v1.networks.AnyUrl.get_default_parts.
Referenced by pydantic.v1.networks.AnyUrl.validate.
'AnyUrl' pydantic.v1.networks.AnyUrl._build_url(cls, Match[str] m, str url, 'Parts' parts)
Validate hosts and build the AnyUrl object. Split from `validate` so this method can be altered in `MultiHostDsn`.
References pydantic.v1.networks.AnyUrl.validate_host.
Referenced by pydantic.v1.networks.AnyUrl.validate.
Optional[Match[str]] pydantic.v1.networks.AnyUrl._match_url(str url)
References pydantic.v1.networks.url_regex.
Referenced by pydantic.v1.networks.AnyUrl.validate.
None pydantic.v1.networks.AnyUrl._validate_port(Optional[str] port)
Referenced by pydantic.v1.networks.MultiHostDsn._build_url, pydantic.v1.networks.AnyUrl.validate_parts.
'Parts' pydantic.v1.networks.AnyUrl.get_default_parts('Parts' parts)
Referenced by pydantic.v1.networks.AnyUrl.apply_default_parts, pydantic.v1.networks.AnyUrl.build.