lib::microdot::microdot::MultiDict
lib.microdot.microdot.MultiDict.get(self, key, default=None, type=None)
Return the value for a given key. :param key: The key to retrieve. :param default: A default value to use if the key does not exist. :param type: A type conversion callable to apply to the value. If the multidict contains more than one value for the requested key, this method returns the first value only. Example:: >>> d = MultiDict() >>> d['age'] = '42' >>> d.get('age') '42' >>> d.get('age', type=int) 42 >>> d.get('name', default='noname') 'noname'
Referenced by setuptools.package_index.PyPIConfig._get_repo_cred, pip._vendor.distlib.metadata.LegacyMetadata._write_field, starlette.datastructures.MutableHeaders.add_vary_header, pip._vendor.distlib.metadata.LegacyMetadata.check, setuptools.package_index.PyPIConfig.creds_by_repository, pip._vendor.distlib.metadata.LegacyMetadata.write_file.
lib.microdot.microdot.MultiDict.getlist(self, key, type=None)
Return all the values for a given key. :param key: The key to retrieve. :param type: A type conversion callable to apply to the values. If the requested key does not exist in the dictionary, this method returns an empty list. Example:: >>> d = MultiDict() >>> d.getlist('items') [] >>> d['items'] = '3' >>> d.getlist('items') ['3'] >>> d['items'] = '56' >>> d.getlist('items') ['3', '56'] >>> d.getlist('items', type=int) [3, 56]