IConsultas::IConsultasOOS
bool IConsultas.IConsultasOOS.consultarOntoActiva(self)
Verifica si la ontología instanciada está activa/disponible.
Optional[str] IConsultas.IConsultasOOS.consultarId(self)
Retorna el identificador del objeto (id_object).
Optional[str] IConsultas.IConsultasOOS.consultarDescription(self)
Retorna la descripción del estado (State).
Any IConsultas.IConsultasOOS.consultarPrivate(self)
Retorna si el feed es privado (private).
Optional[str] IConsultas.IConsultasOOS.consultarTitle(self)
Retorna el título (title) del feed.
Optional[str] IConsultas.IConsultasOOS.consultarFeed(self)
Retorna la URL del feed (feed).
Any IConsultas.IConsultasOOS.consultarStatus(self)
Retorna el estado live/frozen (status).
Any IConsultas.IConsultasOOS.consultarUpdated(self)
Retorna la fecha/tiempo de última actualización (updated).
Any IConsultas.IConsultasOOS.consultarCreated(self)
Retorna la fecha de creación (created).
Any IConsultas.IConsultasOOS.consultarCreator(self)
Retorna el creator del feed.
Any IConsultas.IConsultasOOS.consultarVersion(self)
Retorna la versión (version).
Any IConsultas.IConsultasOOS.consultarWebsite(self)
Retorna la URL del website relacionado.
Any IConsultas.IConsultasOOS.consultarServiceState(self)
Retorna el estado del servicio inteligente (service_state).
List[Any] IConsultas.IConsultasOOS.consultarTagsDatastream(self, str idDatastream)
Retorna tags para un datastream dado.
Dict[str, Any] IConsultas.IConsultasOOS.consultarUnitDatastream(self, str idDatastream)
Retorna diccionario {label, symbol} de la unidad de un datastream.
Dict[str, Any] IConsultas.IConsultasOOS.consultarDatastreams(self, str idDatastream)
Retorna metadatos del datastream (min/max, format, type, tags, unit).
List[Any] IConsultas.IConsultasOOS.consultarTagsTodosDatastreams(self)
Retorna tags para todos los datastreams.
List[Dict[str, Any]] IConsultas.IConsultasOOS.consultarUnitTodosDatastreams(self)
Retorna lista de unidades (datastream_id, label, symbol).
List[Dict[str, Any]] IConsultas.IConsultasOOS.consultarTodosDatastreams(self)
Retorna lista completa de datastreams con metadatos y tags.
List[str] IConsultas.IConsultasOOS.consultarListaIdDatastreams(self)
Retorna lista de ids de datastreams.
Dict[str, Any] IConsultas.IConsultasOOS.consultarLocation(self)
Retorna localización del objeto {lon, lat, name, domain, ele}.
Dict[str, Any] IConsultas.IConsultasOOS.consultarState(self)
Retorna el estado completo del objeto (diccionario de propiedades).
List[Any] IConsultas.IConsultasOOS.consultarTagsObjeto(self)
Retorna lista de tags del objeto.
List[Dict[str, Any]] IConsultas.IConsultasOOS.consultarDataStreamFormat(self)
Retorna formatos y tipos de datastreams.
List[Any] IConsultas.IConsultasOOS.consultarDataStreamFormatPorId(self, str datastream_id)
Retorna formato de datastream por id.
Dict[str, Any] IConsultas.IConsultasOOS.consultarServiceIntelligent(self)
Retorna estado y datastreams relacionados con el servicio inteligente.
List[Any] IConsultas.IConsultasOOS.consultarMetodosSend(self)
Retorna instancias de métodos Send (consultar instancias).
List[Any] IConsultas.IConsultasOOS.consultarMetodosReceive(self)
Retorna instancias de métodos Receive.
List[Any] IConsultas.IConsultasOOS.consultarMetodosExternal(self)
Retorna instancias de métodos External.
Dict[str, Any] IConsultas.IConsultasOOS.diccionarioMetaDatosObjeto(self)
Retorna diccionario con metadatos del objeto y su ubicación.
List[Dict[str, Any]] IConsultas.IConsultasOOS.listaMetaDatosDataStreams(self)
Retorna lista de metadatos de los datastreams.
List[Dict[str, Any]] IConsultas.IConsultasOOS.tieneContrato(self, str osidDestino)
Consulta si existe contrato (ECA) para un destino dado.
List[Dict[str, Any]] IConsultas.IConsultasOOS.verificarContrato(self, str osid, str osidDestino)
Verifica contrato entre dos objetos.
List[Dict[str, Any]] IConsultas.IConsultasOOS.listarDinamicEstado(self, str eca_state)
Lista ECAs dinámicas por estado.
List[Dict[str, Any]] IConsultas.IConsultasOOS.estadoEca(self, str eca_name)
Consulta estado de una ECA por nombre.
List[Dict[str, Any]] IConsultas.IConsultasOOS.usuarioEca(self, str eca_name)
Consulta usuario asociado a una ECA.
List[Dict[str, Any]] IConsultas.IConsultasOOS.listarEcasEvento(self, str osid, str eca_state)
Lista ECAs que inician por evento para un objeto y estado.
List[Dict[str, Any]] IConsultas.IConsultasOOS.listarEcasEventoSegunUsuario(self, str osid, str state_eca, str usuario_eca)
Lista ECAs por usuario y estado.
List[Dict[str, Any]] IConsultas.IConsultasOOS.listarEcas(self)
Lista todas las ECAs.
List[Dict[str, Any]] IConsultas.IConsultasOOS.listarEcasUsuario(self, str user_eca)
Lista ECAs asociadas a un usuario.
List[Any] IConsultas.IConsultasOOS.listarNombresEcasUsuario(self, str user_eca)
Lista nombres y estados de ECAs de un usuario.
Dict[str, Any] IConsultas.IConsultasOOS.getEca(self, str nombreEca)
Obtiene una ECA completa por nombre.
None IConsultas.IConsultasOOS.setServiceIntelligent(self, Any valorNuevo)
Actualiza la propiedad service_state del objeto.
None IConsultas.IConsultasOOS.setEcaState(self, str valorNuevo, str nombreECA)
Actualiza el estado de una ECA.
None IConsultas.IConsultasOOS.setEcaListState(self, List[List[Any]] listaEcas)
Actualiza el estado de varias ECAs (lista de [nombre, valor]).
None IConsultas.IConsultasOOS.eliminarEca(self, str nombreECA)
Elimina los individuos asociados a una ECA.
Dict[str, Any] IConsultas.IConsultasOOS.pasarListaDiccionario(self, List[Any] lista, List[str] keys)
Convierte una lista (resultado SPARQL) a diccionario con claves provistas.
Dict[str, Any] IConsultas.IConsultasOOS.decodificar(self, Dict[str, Any] diccionario)
Decodifica valores binarios/bytes a UTF-8 cuando sea necesario.
Referenced by ConsultasOOS.ConsultasOOS.consultarDataStreamFormat, ConsultasOOS.ConsultasOOS.consultarState, ConsultasOOS.ConsultasOOS.diccionarioMetaDatosObjeto, ConsultasOOS.ConsultasOOS.pasarListaDiccionario.