pip::_vendor::pygments::lexer::RegexLexerMeta
dict pip._vendor.pygments.lexer.RegexLexerMeta::_all_tokens
Referenced by pip._vendor.pygments.lexer.RegexLexerMeta.get_tokendefs, pip._vendor.pygments.lexer.RegexLexerMeta.process_tokendef.
int pip._vendor.pygments.lexer.RegexLexerMeta::_tmpname
Referenced by pip._vendor.pygments.lexer.RegexLexerMeta._process_new_state, pip._vendor.pygments.lexer.RegexLexerMeta.get_tokendefs.
pip._vendor.pygments.lexer.RegexLexerMeta::_tokens
Referenced by pip._vendor.pygments.lexer.RegexLexerMeta.get_tokendefs, pip._vendor.pygments.lexer.ExtendedRegexLexer.get_tokens_unprocessed, pip._vendor.pygments.lexer.RegexLexer.get_tokens_unprocessed.
pip._vendor.pygments.lexer.RegexLexerMeta::token_variants
Referenced by pip._vendor.pygments.lexer.RegexLexerMeta.get_tokendefs.
pip._vendor.pygments.lexer.RegexLexerMeta._process_regex(cls, regex, rflags, state)
Preprocess the regular expression component of a token definition.
Referenced by pip._vendor.pygments.lexer.RegexLexerMeta._process_state.
pip._vendor.pygments.lexer.RegexLexerMeta._process_token(cls, token)
Preprocess the token component of a token definition.
Referenced by pip._vendor.pygments.lexer.RegexLexerMeta._process_state.
pip._vendor.pygments.lexer.RegexLexerMeta._process_new_state(cls, new_state, unprocessed, processed)
Preprocess the state transition action of a token definition.
References pip._vendor.pygments.lexer.RegexLexerMeta._process_state, pip._vendor.pygments.lexer.RegexLexerMeta._tmpname.
Referenced by pip._vendor.pygments.lexer.RegexLexerMeta._process_state.
pip._vendor.pygments.lexer.RegexLexerMeta._process_state(cls, unprocessed, processed, state)
Preprocess a single state definition.
References pip._vendor.pygments.lexer.RegexLexerMeta._process_new_state, pip._vendor.pygments.lexer.RegexLexerMeta._process_regex, pip._vendor.pygments.lexer.RegexLexerMeta._process_state, pip._vendor.pygments.lexer.RegexLexerMeta._process_token, pip._vendor.distlib.util.ExportEntry.flags, pip._vendor.packaging._elffile.ELFFile.flags, pip._vendor.pygments.lexer.RegexLexer.flags, pip._vendor.pygments.scanner.Scanner.flags, pip._vendor.pyparsing.core.QuotedString.flags, pip._vendor.pyparsing.core.Regex.flags, pkg_resources._vendor.pyparsing.core.QuotedString.flags, pkg_resources._vendor.pyparsing.core.Regex.flags, setuptools._vendor.pyparsing.core.QuotedString.flags, setuptools._vendor.pyparsing.core.Regex.flags.
Referenced by pip._vendor.pygments.lexer.RegexLexerMeta._process_new_state, pip._vendor.pygments.lexer.RegexLexerMeta._process_state, pip._vendor.pygments.lexer.RegexLexerMeta.process_tokendef.
pip._vendor.pygments.lexer.RegexLexerMeta._process_regex(cls, regex, rflags, state)
Preprocess the regular expression component of a token definition.
pip._vendor.pygments.lexer.RegexLexerMeta._process_token(cls, token)
Preprocess the token component of a token definition.
pip._vendor.pygments.lexer.RegexLexerMeta._process_new_state(cls, new_state, unprocessed, processed)
Preprocess the state transition action of a token definition.
References pip._vendor.pygments.lexer.RegexLexerMeta._process_state, pip._vendor.pygments.lexer.RegexLexerMeta._tmpname.
pip._vendor.pygments.lexer.RegexLexerMeta._process_state(cls, unprocessed, processed, state)
Preprocess a single state definition.
References pip._vendor.pygments.lexer.RegexLexerMeta._process_new_state, pip._vendor.pygments.lexer.RegexLexerMeta._process_regex, pip._vendor.pygments.lexer.RegexLexerMeta._process_state, pip._vendor.pygments.lexer.RegexLexerMeta._process_token, pip._vendor.distlib.util.ExportEntry.flags, pip._vendor.packaging._elffile.ELFFile.flags, pip._vendor.pygments.lexer.RegexLexer.flags, pip._vendor.pygments.scanner.Scanner.flags, pip._vendor.pyparsing.core.QuotedString.flags, pip._vendor.pyparsing.core.Regex.flags, pkg_resources._vendor.pyparsing.core.QuotedString.flags, pkg_resources._vendor.pyparsing.core.Regex.flags, setuptools._vendor.pyparsing.core.QuotedString.flags, setuptools._vendor.pyparsing.core.Regex.flags.
pip._vendor.pygments.lexer.RegexLexerMeta.process_tokendef(cls, name, tokendefs=None)
Preprocess a dictionary of token definitions.
References pip._vendor.pygments.lexer.RegexLexerMeta._all_tokens, pip._vendor.pygments.lexer.RegexLexerMeta._process_state, pip._vendor.pygments.lexer.RegexLexer.tokens, pip._vendor.pygments.lexers.python._PythonConsoleLexerBase.tokens, pip._vendor.pygments.lexers.python.CythonLexer.tokens, pip._vendor.pygments.lexers.python.DgLexer.tokens, pip._vendor.pygments.lexers.python.Python2TracebackLexer.tokens, pip._vendor.pygments.lexers.python.PythonLexer.tokens, pip._vendor.pygments.lexers.python.PythonTracebackLexer.tokens.
Referenced by pip._vendor.pygments.lexer.RegexLexerMeta.get_tokendefs.
pip._vendor.pygments.lexer.RegexLexerMeta.get_tokendefs(cls)
Merge tokens from superclasses in MRO order, returning a single tokendef dictionary. Any state that is not defined by a subclass will be inherited automatically. States that *are* defined by subclasses will, by default, override that state in the superclass. If a subclass wishes to inherit definitions from a superclass, it can use the special value "inherit", which will cause the superclass' state definition to be included at that point in the state.
References charset_normalizer.models.CliDetectionResult.__dict__, colorama.ansitowin32.StreamWrapper.__dict__, pip._vendor.pygments.lexer.RegexLexerMeta.__dict__, pip._vendor.pygments.lexer.RegexLexerMeta.__mro__.
Referenced by pip._vendor.pygments.lexer.RegexLexerMeta.get_tokendefs.
pip._vendor.pygments.lexer.RegexLexerMeta.process_tokendef(cls, name, tokendefs=None)
Preprocess a dictionary of token definitions.
References pip._vendor.pygments.lexer.RegexLexerMeta._all_tokens, pip._vendor.pygments.lexer.RegexLexerMeta._process_state, pip._vendor.pygments.lexer.RegexLexer.tokens, pip._vendor.pygments.lexers.python._PythonConsoleLexerBase.tokens, pip._vendor.pygments.lexers.python.CythonLexer.tokens, pip._vendor.pygments.lexers.python.DgLexer.tokens, pip._vendor.pygments.lexers.python.Python2TracebackLexer.tokens, pip._vendor.pygments.lexers.python.PythonLexer.tokens, pip._vendor.pygments.lexers.python.PythonTracebackLexer.tokens.
pip._vendor.pygments.lexer.RegexLexerMeta.get_tokendefs(cls)
Merge tokens from superclasses in MRO order, returning a single tokendef dictionary. Any state that is not defined by a subclass will be inherited automatically. States that *are* defined by subclasses will, by default, override that state in the superclass. If a subclass wishes to inherit definitions from a superclass, it can use the special value "inherit", which will cause the superclass' state definition to be included at that point in the state.
References charset_normalizer.models.CliDetectionResult.__dict__, colorama.ansitowin32.StreamWrapper.__dict__, pip._vendor.pygments.lexer.RegexLexerMeta.__dict__, pip._vendor.pygments.lexer.RegexLexerMeta.__mro__, pip._vendor.pygments.lexer.RegexLexerMeta._all_tokens, pip._vendor.pygments.lexer.RegexLexerMeta._tmpname, pip._vendor.pygments.lexer.RegexLexerMeta._tokens, pip._vendor.pygments.lexer.RegexLexerMeta.get_tokendefs, pip._vendor.pygments.lexer.RegexLexerMeta.process_tokendef, pip._vendor.pygments.lexer.RegexLexerMeta.token_variants.