anyio::abc::_eventloop::AsyncBackend
T_Retval anyio.abc._eventloop.AsyncBackend.run(cls, Callable[[Unpack[PosArgsT]], Awaitable[T_Retval]] func, tuple[Unpack[PosArgsT]] args, dict[str, Any] kwargs, dict[str, Any] options)
Run the given coroutine function in an asynchronous event loop. The current thread must not be already running an event loop. :param func: a coroutine function :param args: positional arguments to ``func`` :param kwargs: positional arguments to ``func`` :param options: keyword arguments to call the backend ``run()`` implementation with :return: the return value of the coroutine function
Referenced by pip._internal.cli.base_command.Command._main, pip._internal.cli.base_command.Command._run_wrapper.
object anyio.abc._eventloop.AsyncBackend.current_token(cls)
Return an object that allows other threads to run code inside the event loop. :return: a token object, specific to the event loop running in the current thread
float anyio.abc._eventloop.AsyncBackend.current_time(cls)
Return the current value of the event loop's internal clock. :return: the clock value (seconds)
type[BaseException] anyio.abc._eventloop.AsyncBackend.cancelled_exception_class(cls)
Return the exception class that is raised in a task if it's cancelled.
None anyio.abc._eventloop.AsyncBackend.checkpoint(cls)
Check if the task has been cancelled, and allow rescheduling of other tasks. This is effectively the same as running :meth:`checkpoint_if_cancelled` and then :meth:`cancel_shielded_checkpoint`.
Referenced by anyio.abc._eventloop.AsyncBackend.checkpoint_if_cancelled.
None anyio.abc._eventloop.AsyncBackend.checkpoint_if_cancelled(cls)
Check if the current task group has been cancelled. This will check if the task has been cancelled, but will not allow other tasks to be scheduled if not.
References anyio._backends._asyncio.AsyncIOBackend.checkpoint, anyio._backends._trio.TrioBackend.checkpoint, anyio.abc._eventloop.AsyncBackend.checkpoint, anyio._backends._asyncio.AsyncIOBackend.current_effective_deadline, anyio._backends._trio.TrioBackend.current_effective_deadline, anyio.abc._eventloop.AsyncBackend.current_effective_deadline.
None anyio.abc._eventloop.AsyncBackend.cancel_shielded_checkpoint(cls)
Allow the rescheduling of other tasks. This will give other tasks the opportunity to run, but without checking if the current task group has been cancelled, unlike with :meth:`checkpoint`.
References anyio._backends._asyncio.AsyncIOBackend.create_cancel_scope, anyio._backends._trio.TrioBackend.create_cancel_scope, anyio.abc._eventloop.AsyncBackend.create_cancel_scope, anyio._backends._asyncio.AsyncIOBackend.sleep, anyio._backends._trio.TrioBackend.sleep, anyio.abc._eventloop.AsyncBackend.sleep, pip._vendor.tenacity._asyncio.AsyncRetrying.sleep, pip._vendor.tenacity.BaseRetrying.sleep, pip._vendor.tenacity.RetryAction.sleep, pip._vendor.tenacity.tornadoweb.TornadoRetrying.sleep.
None anyio.abc._eventloop.AsyncBackend.sleep(cls, float delay)
Pause the current task for the specified duration. :param delay: the duration, in seconds
Referenced by anyio.abc._eventloop.AsyncBackend.cancel_shielded_checkpoint.
CancelScope anyio.abc._eventloop.AsyncBackend.create_cancel_scope(cls, *, float deadline=math.inf, bool shield=False)
Referenced by anyio.abc._eventloop.AsyncBackend.cancel_shielded_checkpoint.
float anyio.abc._eventloop.AsyncBackend.current_effective_deadline(cls)
Return the nearest deadline among all the cancel scopes effective for the current task. :return: - a clock value from the event loop's internal clock - ``inf`` if there is no deadline in effect - ``-inf`` if the current scope has been cancelled :rtype: float
Referenced by anyio.abc._eventloop.AsyncBackend.checkpoint_if_cancelled.
TaskGroup anyio.abc._eventloop.AsyncBackend.create_task_group(cls)
Event anyio.abc._eventloop.AsyncBackend.create_event(cls)
Lock anyio.abc._eventloop.AsyncBackend.create_lock(cls, *, bool fast_acquire)
Semaphore anyio.abc._eventloop.AsyncBackend.create_semaphore(cls, int initial_value, *, int|None max_value=None, bool fast_acquire=False)
CapacityLimiter anyio.abc._eventloop.AsyncBackend.create_capacity_limiter(cls, float total_tokens)
T_Retval anyio.abc._eventloop.AsyncBackend.run_sync_in_worker_thread(cls, Callable[[Unpack[PosArgsT]], T_Retval] func, tuple[Unpack[PosArgsT]] args, bool abandon_on_cancel=False, CapacityLimiter|None limiter=None)
None anyio.abc._eventloop.AsyncBackend.check_cancelled(cls)
T_Retval anyio.abc._eventloop.AsyncBackend.run_async_from_thread(cls, Callable[[Unpack[PosArgsT]], Awaitable[T_Retval]] func, tuple[Unpack[PosArgsT]] args, object token)
T_Retval anyio.abc._eventloop.AsyncBackend.run_sync_from_thread(cls, Callable[[Unpack[PosArgsT]], T_Retval] func, tuple[Unpack[PosArgsT]] args, object token)
BlockingPortal anyio.abc._eventloop.AsyncBackend.create_blocking_portal(cls)
Process anyio.abc._eventloop.AsyncBackend.open_process(cls, StrOrBytesPath|Sequence[StrOrBytesPath] command, *, int|IO[Any]|None stdin, int|IO[Any]|None stdout, int|IO[Any]|None stderr, **Any kwargs)
None anyio.abc._eventloop.AsyncBackend.setup_process_pool_exit_at_shutdown(cls, set[Process] workers)
SocketStream anyio.abc._eventloop.AsyncBackend.connect_tcp(cls, str host, int port, IPSockAddrType|None local_address=None)
UNIXSocketStream anyio.abc._eventloop.AsyncBackend.connect_unix(cls, str|bytes path)
SocketListener anyio.abc._eventloop.AsyncBackend.create_tcp_listener(cls, socket sock)
SocketListener anyio.abc._eventloop.AsyncBackend.create_unix_listener(cls, socket sock)
UDPSocket | ConnectedUDPSocket anyio.abc._eventloop.AsyncBackend.create_udp_socket(cls, AddressFamily family, IPSockAddrType|None local_address, IPSockAddrType|None remote_address, bool reuse_port)
UNIXDatagramSocket anyio.abc._eventloop.AsyncBackend.create_unix_datagram_socket(cls, socket raw_socket, None remote_path)
ConnectedUNIXDatagramSocket anyio.abc._eventloop.AsyncBackend.create_unix_datagram_socket(cls, socket raw_socket, str|bytes remote_path)
UNIXDatagramSocket | ConnectedUNIXDatagramSocket anyio.abc._eventloop.AsyncBackend.create_unix_datagram_socket(cls, socket raw_socket, str|bytes|None remote_path)
Sequence[ tuple[ AddressFamily, SocketKind, int, str, tuple[str, int] | tuple[str, int, int, int] | tuple[int, bytes], ] ] anyio.abc._eventloop.AsyncBackend.getaddrinfo(cls, bytes|str|None host, str|int|None port, *, int|AddressFamily family=0, int|SocketKind type=0, int proto=0, int flags=0)
tuple[str, str] anyio.abc._eventloop.AsyncBackend.getnameinfo(cls, IPSockAddrType sockaddr, int flags=0)
None anyio.abc._eventloop.AsyncBackend.wait_readable(cls, FileDescriptorLike obj)
None anyio.abc._eventloop.AsyncBackend.wait_writable(cls, FileDescriptorLike obj)
None anyio.abc._eventloop.AsyncBackend.notify_closing(cls, FileDescriptorLike obj)
SocketListener anyio.abc._eventloop.AsyncBackend.wrap_listener_socket(cls, socket sock)
SocketStream anyio.abc._eventloop.AsyncBackend.wrap_stream_socket(cls, socket sock)
UNIXSocketStream anyio.abc._eventloop.AsyncBackend.wrap_unix_stream_socket(cls, socket sock)
UDPSocket anyio.abc._eventloop.AsyncBackend.wrap_udp_socket(cls, socket sock)
ConnectedUDPSocket anyio.abc._eventloop.AsyncBackend.wrap_connected_udp_socket(cls, socket sock)
UNIXDatagramSocket anyio.abc._eventloop.AsyncBackend.wrap_unix_datagram_socket(cls, socket sock)
ConnectedUNIXDatagramSocket anyio.abc._eventloop.AsyncBackend.wrap_connected_unix_datagram_socket(cls, socket sock)
CapacityLimiter anyio.abc._eventloop.AsyncBackend.current_default_thread_limiter(cls)
AbstractContextManager[AsyncIterator[Signals]] anyio.abc._eventloop.AsyncBackend.open_signal_receiver(cls, *Signals signals)
TaskInfo anyio.abc._eventloop.AsyncBackend.get_current_task(cls)
Sequence[TaskInfo] anyio.abc._eventloop.AsyncBackend.get_running_tasks(cls)
None anyio.abc._eventloop.AsyncBackend.wait_all_tasks_blocked(cls)
TestRunner anyio.abc._eventloop.AsyncBackend.create_test_runner(cls, dict[str, Any] options)