starlette::schemas::BaseSchemaGenerator
dict[str, Any] starlette.schemas.BaseSchemaGenerator.get_schema(self, list[BaseRoute] routes)
Referenced by starlette.schemas.BaseSchemaGenerator.OpenAPIResponse.
list[EndpointInfo] starlette.schemas.BaseSchemaGenerator.get_endpoints(self, list[BaseRoute] routes)
Given the routes, yields the following information: - path eg: /users/ - http_method one of 'get', 'post', 'put', 'patch', 'delete', 'options' - func method ready to extract the docstring
References starlette.schemas.BaseSchemaGenerator._remove_converter, starlette.schemas.BaseSchemaGenerator.get_endpoints.
Referenced by starlette.schemas.BaseSchemaGenerator.get_endpoints, starlette.schemas.SchemaGenerator.get_schema.
dict[str, Any] starlette.schemas.BaseSchemaGenerator.parse_docstring(self, Callable[..., Any] func_or_method)
Given a function, parse the docstring as YAML and return a dictionary of info.
Referenced by starlette.schemas.SchemaGenerator.get_schema.
Response starlette.schemas.BaseSchemaGenerator.OpenAPIResponse(self, Request request)
References starlette.schemas.BaseSchemaGenerator.get_schema.
str starlette.schemas.BaseSchemaGenerator._remove_converter(self, str path)
Remove the converter from the path. For example, a route like this: Route("/users/{id:int}", endpoint=get_user, methods=["GET"]) Should be represented as `/users/{id}` in the OpenAPI schema.
Referenced by starlette.schemas.BaseSchemaGenerator.get_endpoints.