IConsultasPerfilUsuario::IConsultasPerfilUsuario
bool IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarActive(self)
Consulta si la ontologia de usuario está activa Returns: bool: True si lo está, False en caso contrario
str IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarEmailUsuario(self)
Consulta el email del usuario desde la ontología. Returns: str: Email del usuario o cadena vacía si no se encuentra.
List[List[Any]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarListaIpObjectos(self)
Consulta la lista de IPs de objetos relacionados al usuario. Returns: List[List[Any]]: Lista de IPs de objetos.
List[Dict[str, str]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarListaIpIdObjectosUsuario(self)
Consulta la lista de IPs e IDs de objetos del usuario. Returns: List[Dict[str, str]]: Lista de diccionarios con claves 'ipobjeto' e 'idobjeto'.
List[Dict[str, str]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarListaObjetosRelacionadosEdificio(self, str nombreEdificio)
Consulta los objetos relacionados a un edificio específico. Args: nombreEdificio: Nombre del edificio a consultar. Returns: List[Dict[str, str]]: Lista de diccionarios con claves 'name_object', 'ipobjeto', 'idobjeto'.
List[Dict[str, str]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarPartesEdificioConObjetosRelacionados(self, str nombreEdificio)
Consulta las partes de un edificio con sus objetos relacionados. Args: nombreEdificio: Nombre del edificio a consultar. Returns: List[Dict[str, str]]: Lista de diccionarios con claves 'nombreparte', 'name_object', 'ipobjeto', 'idobjeto'.
List[Dict[str, str]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarObjetosRelacionadosACosasDeEdificio(self, str nombreEdificio)
Consulta los objetos relacionados a cosas de un edificio. Args: nombreEdificio: Nombre del edificio a consultar. Returns: List[Dict[str, str]]: Lista de diccionarios con claves 'name_thing', 'name_object', 'ipobjeto', 'idobjeto'.
List[Dict[str, str]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarListaIpIdObjectosEdificio(self, str nombreEdificio)
Consulta la lista completa de IPs e IDs de objetos de un edificio. Incluye objetos relacionados directamente, en partes del edificio y en cosas. Args: nombreEdificio: Nombre del edificio a consultar. Returns: List[Dict[str, str]]: Lista combinada de objetos del edificio.
List[List[Any]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarEdificioRelacionadoObjeto(self, str idObjeto)
Consulta el edificio relacionado a un objeto específico. Args: idObjeto: ID del objeto a consultar. Returns: List[List[Any]]: Lista con el nombre del edificio relacionado.
List[Dict[str, str]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarListaPreferenciasObjetoEventoporOSID(self, str idObjeto)
Consulta las preferencias donde el objeto es el evento (origen). Args: idObjeto: OSID del objeto evento. Returns: List[Dict[str, str]]: Lista de diccionarios con información completa del ECA. Claves: 'name_eca', 'state_eca', 'id_event_object', 'ip_event_object', 'name_event_object', 'id_event_resource', 'name_event_resource', 'comparator_condition', 'variable_condition', 'type_variable_condition', 'unit_condition', 'meaning_condition', 'id_action_object', 'ip_action_object', 'name_action_object', 'id_action_resource', 'name_action_resource', 'comparator_action', 'variable_action', 'type_variable_action', 'unit_action', 'meaning_action', 'name_activity', 'start_date_activity', 'end_date_activity'.
List[Dict[str, str]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarListaPreferenciasObjetoAccionporOSID(self, str idObjeto)
Consulta las preferencias donde el objeto es la acción (destino). Args: idObjeto: OSID del objeto acción. Returns: List[Dict[str, str]]: Lista de diccionarios con información completa del ECA. Claves: igual que consultarListaPreferenciasObjetoEventoporOSID.
List[Dict[str, str]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarListaPreferenciasporOSID(self, str idObjeto)
Consulta todas las preferencias relacionadas a un objeto (evento o acción). Args: idObjeto: OSID del objeto. Returns: List[Dict[str, str]]: Lista combinada de preferencias donde el objeto es evento o acción.
List[Dict[str, str]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarObjetivoUsuario(self)
Consulta los objetivos del usuario. Returns: List[Dict[str, str]]: Lista de diccionarios con claves 'name_objective', 'specific', 'start_date', 'Measurable', 'suitable_for'.
List[Dict[str, str]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarActosObjetivosUsuario(self)
Consulta los actos asociados a los objetivos del usuario. Returns: List[Dict[str, str]]: Lista de diccionarios con claves 'name_objective', 'name_acts', 'number', 'start_date_acts', 'final_date', 'description_act', 'state_acts', 'specific', 'start_date', 'Measurable', 'suitable_for'.
List[Dict[str, str]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarRecursosObjetivosUsuario(self)
Consulta los recursos asociados a los objetivos del usuario. Returns: List[Dict[str, str]]: Lista de diccionarios con claves 'name_objective', 'name_resource', 'number_resource', 'specific', 'start_date', 'Measurable', 'suitable_for'.
List[List[Dict[str, str]]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarActosGroupObjetivos(self)
Consulta los actos agrupados por objetivo. Returns: List[List[Dict[str, str]]]: Lista de listas, donde cada sublista contiene los actos de un objetivo específico.
List[List[Dict[str, str]]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarRecGroupObjetivos(self)
Consulta los recursos agrupados por objetivo. Returns: List[List[Dict[str, str]]]: Lista de listas, donde cada sublista contiene los recursos de un objetivo específico.
List[Dict[str, str]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarActosUsuario(self)
Consulta todos los actos del usuario sin información completa del objetivo. Returns: List[Dict[str, str]]: Lista de diccionarios con claves 'name_objective', 'name_acts', 'number', 'start_date_acts', 'final_date', 'description_act', 'state_acts'.
List[Dict[str, str]] IConsultasPerfilUsuario.IConsultasPerfilUsuario.consultarRecursosUsuario(self)
Consulta todos los recursos del usuario sin información completa del objetivo. Returns: List[Dict[str, str]]: Lista de diccionarios con claves 'name_objective', 'name_resource', 'number_resource'.
Dict[str, str] IConsultasPerfilUsuario.IConsultasPerfilUsuario.pasarListaDiccionario(self, List[Any] lista, List[str] keys)
Convierte una lista de valores a un diccionario usando las claves proporcionadas. Args: lista: Lista de valores a convertir. keys: Lista de claves para el diccionario. Returns: Dict[str, str]: Diccionario con los valores mapeados a las claves.
Dict[str, str] IConsultasPerfilUsuario.IConsultasPerfilUsuario.decodificar(self, Dict[str, Any] diccionario)
Decodifica los valores de un diccionario de bytes a string UTF-8. Args: diccionario: Diccionario con valores posiblemente en bytes. Returns: Dict[str, str]: Diccionario con valores decodificados.
Referenced by ConsultasOOS.ConsultasOOS.consultarDataStreamFormat, ConsultasOOS.ConsultasOOS.consultarState, ConsultasOOS.ConsultasOOS.diccionarioMetaDatosObjeto, ConsultasOOS.ConsultasOOS.pasarListaDiccionario.