pip::_internal::metadata::pkg_resources::Environment
pip._internal.metadata.pkg_resources.Environment::_ws
Referenced by pip._internal.metadata.pkg_resources.Environment._iter_distributions, pip._internal.metadata.pkg_resources.Environment.get_distribution, pip._internal.metadata.pkg_resources.Distribution.is_extra_provided.
BaseEnvironment pip._internal.metadata.pkg_resources.Environment.default(cls)
BaseEnvironment pip._internal.metadata.pkg_resources.Environment.from_paths(cls, list[str]|None paths)
BaseDistribution | None pip._internal.metadata.pkg_resources.Environment.get_distribution(self, str name)
Given a requirement name, return the installed distributions. The name may not be normalized. The implementation must canonicalize it for lookup.
References pip._internal.metadata.pkg_resources.Environment._search_distribution, pip._internal.metadata.pkg_resources.Environment._ws.
Referenced by pip._vendor.distlib.database.DistributionPath.get_file_path.
BaseEnvironment pip._internal.metadata.pkg_resources.Environment.default(cls)
BaseEnvironment pip._internal.metadata.pkg_resources.Environment.from_paths(cls, Optional[List[str]] paths)
Optional[BaseDistribution] pip._internal.metadata.pkg_resources.Environment.get_distribution(self, str name)
Given a requirement name, return the installed distributions. The name may not be normalized. The implementation must canonicalize it for lookup.
References pip._internal.metadata.pkg_resources.Environment._search_distribution, pip._internal.metadata.pkg_resources.Environment._ws.
Referenced by pip._vendor.distlib.database.DistributionPath.get_file_path.
Iterator[BaseDistribution] pip._internal.metadata.pkg_resources.Environment._iter_distributions(self)
Iterate through installed distributions. This function should be implemented by subclass, but never called directly. Use the public ``iter_distribution()`` instead, which implements additional logic to make sure the distributions are valid.
References pip._internal.metadata.pkg_resources.Environment._ws.
BaseDistribution | None pip._internal.metadata.pkg_resources.Environment._search_distribution(self, str name)
Find a distribution matching the ``name`` in the environment. This searches from *all* distributions available in the environment, to match the behavior of ``pkg_resources.get_distribution()``.
References pip._internal.metadata.base.BaseEnvironment.iter_all_distributions.
Referenced by pip._internal.metadata.pkg_resources.Environment.get_distribution.
Iterator[BaseDistribution] pip._internal.metadata.pkg_resources.Environment._iter_distributions(self)
Iterate through installed distributions. This function should be implemented by subclass, but never called directly. Use the public ``iter_distribution()`` instead, which implements additional logic to make sure the distributions are valid.
References pip._internal.metadata.pkg_resources.Environment._ws.
Optional[BaseDistribution] pip._internal.metadata.pkg_resources.Environment._search_distribution(self, str name)
Find a distribution matching the ``name`` in the environment. This searches from *all* distributions available in the environment, to match the behavior of ``pkg_resources.get_distribution()``.
References pip._internal.metadata.base.BaseEnvironment.iter_all_distributions.