pip::_vendor::rich::layout::RowSplitter
str pip._vendor.rich.layout.RowSplitter.get_tree_icon(self)
Get the icon (emoji) used in layout.tree
Iterable[Tuple["Layout", Region]] pip._vendor.rich.layout.RowSplitter.divide(self, Sequence["Layout"] children, Region region)
Divide a region amongst several child layouts. Args: children (Sequence(Layout)): A number of child layouts. region (Region): A rectangular region to divide.
Referenced by pip._vendor.rich.text.Span.right_crop, pip._vendor.rich.text.Text.split.
str pip._vendor.rich.layout.RowSplitter.get_tree_icon(self)
Get the icon (emoji) used in layout.tree
Iterable[Tuple["Layout", Region]] pip._vendor.rich.layout.RowSplitter.divide(self, Sequence["Layout"] children, Region region)
Divide a region amongst several child layouts. Args: children (Sequence(Layout)): A number of child layouts. region (Region): A rectangular region to divide.
Referenced by pip._vendor.rich.text.Span.right_crop.