pip::_internal::metadata::base::BaseEnvironment
BaseEnvironment pip._internal.metadata.base.BaseEnvironment.default(cls)
BaseEnvironment pip._internal.metadata.base.BaseEnvironment.from_paths(cls, list[str]|None paths)
BaseDistribution | None pip._internal.metadata.base.BaseEnvironment.get_distribution(self, str name)
Given a requirement name, return the installed distributions. The name may not be normalized. The implementation must canonicalize it for lookup.
Referenced by pip._vendor.distlib.database.DistributionPath.get_file_path.
Iterator[BaseDistribution] pip._internal.metadata.base.BaseEnvironment.iter_all_distributions(self)
Iterate through all installed distributions without any filtering.
References pip._internal.metadata.base.BaseEnvironment._iter_distributions.
Referenced by pip._internal.metadata.pkg_resources.Environment._search_distribution, pip._internal.metadata.importlib._envs.Environment.get_distribution, pip._internal.metadata.base.BaseEnvironment.iter_installed_distributions.
Iterator[BaseDistribution] pip._internal.metadata.base.BaseEnvironment.iter_installed_distributions(self, bool local_only=True, Container[str] skip=stdlib_pkgs, bool include_editables=True, bool editables_only=False, bool user_only=False)
Return a list of installed distributions. This is based on ``iter_all_distributions()`` with additional filtering options. Note that ``iter_installed_distributions()`` without arguments is *not* equal to ``iter_all_distributions()``, since some of the configurations exclude packages by default. :param local_only: If True (default), only return installations local to the current virtualenv, if in a virtualenv. :param skip: An iterable of canonicalized project names to ignore; defaults to ``stdlib_pkgs``. :param include_editables: If False, don't report editables. :param editables_only: If True, only report editables. :param user_only: If True, only report installations in the user site directory.
References pip._internal.metadata.base.BaseEnvironment.iter_all_distributions.
"BaseEnvironment" pip._internal.metadata.base.BaseEnvironment.default(cls)
"BaseEnvironment" pip._internal.metadata.base.BaseEnvironment.from_paths(cls, Optional[List[str]] paths)
Optional["BaseDistribution"] pip._internal.metadata.base.BaseEnvironment.get_distribution(self, str name)
Given a requirement name, return the installed distributions. The name may not be normalized. The implementation must canonicalize it for lookup.
Referenced by pip._vendor.distlib.database.DistributionPath.get_file_path.
Iterator[BaseDistribution] pip._internal.metadata.base.BaseEnvironment.iter_all_distributions(self)
Iterate through all installed distributions without any filtering.
References pip._internal.metadata.base.BaseEnvironment._iter_distributions.
Iterator[BaseDistribution] pip._internal.metadata.base.BaseEnvironment.iter_installed_distributions(self, bool local_only=True, Container[str] skip=stdlib_pkgs, bool include_editables=True, bool editables_only=False, bool user_only=False)
Return a list of installed distributions. This is based on ``iter_all_distributions()`` with additional filtering options. Note that ``iter_installed_distributions()`` without arguments is *not* equal to ``iter_all_distributions()``, since some of the configurations exclude packages by default. :param local_only: If True (default), only return installations local to the current virtualenv, if in a virtualenv. :param skip: An iterable of canonicalized project names to ignore; defaults to ``stdlib_pkgs``. :param include_editables: If False, don't report editables. :param editables_only: If True, only report editables. :param user_only: If True, only report installations in the user site directory.
References pip._internal.metadata.base.BaseEnvironment.iter_all_distributions.
Iterator[BaseDistribution] pip._internal.metadata.base.BaseEnvironment._iter_distributions(self)
Iterate through installed distributions. This function should be implemented by subclass, but never called directly. Use the public ``iter_distribution()`` instead, which implements additional logic to make sure the distributions are valid.
Referenced by pip._internal.metadata.base.BaseEnvironment.iter_all_distributions.
Iterator["BaseDistribution"] pip._internal.metadata.base.BaseEnvironment._iter_distributions(self)
Iterate through installed distributions. This function should be implemented by subclass, but never called directly. Use the public ``iter_distribution()`` instead, which implements additional logic to make sure the distributions are valid.