pydantic_core::core_schema::ValidationInfo
ContextT pydantic_core.core_schema.ValidationInfo.context(self)
The current validation context.
CoreConfig | None pydantic_core.core_schema.ValidationInfo.config(self)
The CoreConfig that applies to this validation.
Referenced by pip._internal.cli.parser.CustomOptionParser.option_list_all, pip._vendor.distlib.compat.ConvertingList.pop.
Literal['python', 'json'] pydantic_core.core_schema.ValidationInfo.mode(self)
The type of input data we are currently validating.
dict[str, Any] pydantic_core.core_schema.ValidationInfo.data(self)
The data being validated for this model.
Referenced by pip._vendor.requests.models.RequestHooksMixin.deregister_hook, urllib3.contrib.emscripten.response.EmscriptenHttpResponseWrapper.json, urllib3.response.BaseHTTPResponse.json.
str | None pydantic_core.core_schema.ValidationInfo.field_name(self)
The name of the current field being validated if this validator is attached to a model field.