pydantic::mypy
str pydantic::mypy.CONFIGFILE_KEY
str pydantic::mypy.METADATA_KEY
str pydantic::mypy.BASEMODEL_FULLNAME
str pydantic::mypy.BASESETTINGS_FULLNAME
str pydantic::mypy.ROOT_MODEL_FULLNAME
str pydantic::mypy.MODEL_METACLASS_FULLNAME
str pydantic::mypy.FIELD_FULLNAME
str pydantic::mypy.DATACLASS_FULLNAME
str pydantic::mypy.MODEL_VALIDATOR_FULLNAME
dict pydantic::mypy.DECORATOR_FULLNAMES
dict pydantic::mypy.IMPLICIT_CLASSMETHOD_DECORATOR_FULLNAMES
pydantic::mypy.MYPY_VERSION_TUPLE
str pydantic::mypy.BUILTINS_NAME
pydantic::mypy.ERROR_ORM
pydantic::mypy.ERROR_CONFIG
pydantic::mypy.ERROR_ALIAS
pydantic::mypy.ERROR_UNEXPECTED
pydantic::mypy.ERROR_UNTYPED
pydantic::mypy.ERROR_FIELD_DEFAULTS
pydantic::mypy.ERROR_EXTRA_FIELD_ROOT_MODEL
type[Plugin] pydantic.mypy.plugin(str version)
`version` is the mypy version string. We might want to use this to print a warning if the mypy version being used is newer, or especially older, than we expect (or need). Args: version: The mypy version string. Return: The Pydantic mypy plugin type.
Type pydantic.mypy.from_attributes_callback(MethodContext ctx)
Raise an error if from_attributes is not enabled.
References pydantic.mypy.error_from_attributes, pydantic.mypy.error_unexpected_behavior.
bool pydantic.mypy.is_root_model(TypeInfo info)
Return whether the type info is a root model subclass (or the `RootModel` class itself).
Referenced by pydantic.mypy.PydanticModelField.expand_type, pydantic.mypy.PydanticModelTransformer.transform.
None pydantic.mypy.error_from_attributes(str model_name, CheckerPluginInterface api, Context context)
Emits an error when the model does not have `from_attributes=True`.
Referenced by pydantic.mypy.from_attributes_callback.
None pydantic.mypy.error_invalid_config_value(str name, SemanticAnalyzerPluginInterface api, Context context)
Emits an error when the config value is invalid.
Referenced by pydantic.mypy.PydanticModelTransformer.get_config_update.
None pydantic.mypy.error_required_dynamic_aliases(SemanticAnalyzerPluginInterface api, Context context)
Emits required dynamic aliases error. This will be called when `warn_required_dynamic_aliases=True`.
Referenced by pydantic.mypy.PydanticModelTransformer.collect_config, pydantic.mypy.PydanticModelTransformer.collect_field_or_class_var_from_stmt.
None pydantic.mypy.error_unexpected_behavior(str detail, CheckerPluginInterface|SemanticAnalyzerPluginInterface api, Context context)
Emits unexpected behavior error.
Referenced by pydantic.mypy.from_attributes_callback.
None pydantic.mypy.error_untyped_fields(SemanticAnalyzerPluginInterface api, Context context)
Emits an error when there is an untyped field in the model.
Referenced by pydantic.mypy.PydanticModelTransformer.collect_field_or_class_var_from_stmt.
None pydantic.mypy.error_extra_fields_on_root_model(CheckerPluginInterface api, Context context)
Emits an error when there is more than just a root field defined for a subclass of RootModel.
None pydantic.mypy.add_method(SemanticAnalyzerPluginInterface|CheckerPluginInterface api, ClassDef cls, str name, list[Argument] args, Type return_type, Type|None self_type=None, TypeVarType|None tvar_def=None, bool is_classmethod=False)
Very closely related to `mypy.plugins.common.add_method_to_class`, with a few pydantic-specific changes.
Referenced by pydantic.mypy.PydanticModelTransformer.add_initializer, pydantic.mypy.PydanticModelTransformer.add_model_construct_method.
dict[str, Any] | None pydantic.mypy.parse_toml(str config_file)
Returns a dict of config keys to values. It reads configs from toml file and returns `None` if the file is not a toml file.