pydantic::_internal::_generate_schema
tuple pydantic::_internal::_generate_schema._SUPPORTS_TYPEDDICT
pydantic::_internal::_generate_schema.FieldDecoratorInfo
pydantic::_internal::_generate_schema.FieldDecoratorInfoType
pydantic::_internal::_generate_schema.AnyFieldDecorator
TypeAlias pydantic::_internal::_generate_schema.ModifyCoreSchemaWrapHandler
TypeAlias pydantic::_internal::_generate_schema.GetCoreSchemaFunction
TypeAlias pydantic::_internal::_generate_schema.ParametersCallback
list pydantic::_internal::_generate_schema.TUPLE_TYPES
list pydantic::_internal::_generate_schema.LIST_TYPES
list pydantic::_internal::_generate_schema.SET_TYPES
list pydantic::_internal::_generate_schema.FROZEN_SET_TYPES
list pydantic::_internal::_generate_schema.DICT_TYPES
list pydantic::_internal::_generate_schema.IP_TYPES
list pydantic::_internal::_generate_schema.SEQUENCE_TYPES
list pydantic::_internal::_generate_schema.ITERABLE_TYPES
list pydantic::_internal::_generate_schema.TYPE_TYPES
list pydantic::_internal::_generate_schema.PATTERN_TYPES
list pydantic::_internal::_generate_schema.PATH_TYPES
list pydantic::_internal::_generate_schema.MAPPING_TYPES
list pydantic::_internal::_generate_schema.COUNTER_TYPES
list pydantic::_internal::_generate_schema.DEQUE_TYPES
pydantic::_internal::_generate_schema.ValidateCallSupportedTypes
pydantic::_internal::_generate_schema.VALIDATE_CALL_SUPPORTED_TYPES
list pydantic::_internal::_generate_schema.UNSUPPORTED_STANDALONE_FIELDINFO_ATTRIBUTES
dict pydantic::_internal::_generate_schema._mode_to_validator
pydantic::_internal::_generate_schema.JsonEncoders
bool pydantic._internal._generate_schema.check_validator_fields_against_field_name(FieldDecoratorInfo info, str field)
Check if field name is in validator fields. Args: info: The field info. field: The field name to check. Returns: `True` if field name is in validator fields, `False` otherwise.
Referenced by pydantic._internal._generate_schema.filter_field_decorator_info_by_field.
None pydantic._internal._generate_schema.check_decorator_fields_exist(Iterable[AnyFieldDecorator] decorators, Iterable[str] fields)
Check if the defined fields in decorators exist in `fields` param. It ignores the check for a decorator if the decorator has `*` as field or `check_fields=False`. Args: decorators: An iterable of decorators. fields: An iterable of fields name. Raises: PydanticUserError: If one of the field names does not exist in `fields` param.
Referenced by pydantic._internal._generate_schema.GenerateSchema._model_schema.
list[Decorator[FieldDecoratorInfoType]] pydantic._internal._generate_schema.filter_field_decorator_info_by_field(Iterable[Decorator[FieldDecoratorInfoType]] validator_functions, str field)
References pydantic._internal._generate_schema.check_validator_fields_against_field_name.
Referenced by pydantic._internal._generate_schema.GenerateSchema._common_field_schema, pydantic._internal._generate_schema.GenerateSchema._computed_field_schema.
core_schema.CoreSchema pydantic._internal._generate_schema.apply_each_item_validators(core_schema.CoreSchema schema, list[Decorator[ValidatorDecoratorInfo]] each_item_validators)
References pydantic._internal._generate_schema.apply_each_item_validators, pydantic._internal._generate_schema.apply_validators.
Referenced by pydantic._internal._generate_schema.GenerateSchema._common_field_schema, pydantic._internal._generate_schema.apply_each_item_validators.
tuple[JsonDict | None, JsonDict | JsonSchemaExtraCallable | None] pydantic._internal._generate_schema._extract_json_schema_info_from_field_info(FieldInfo|ComputedFieldInfo info)
Referenced by pydantic._internal._generate_schema.GenerateSchema._apply_single_annotation_json_schema, pydantic._internal._generate_schema.GenerateSchema._common_field_schema, pydantic._internal._generate_schema.GenerateSchema._computed_field_schema.
CoreSchema pydantic._internal._generate_schema._add_custom_serialization_from_json_encoders(JsonEncoders|None json_encoders, Any tp, CoreSchema schema)
Iterate over the json_encoders and add the first matching encoder to the schema. Args: json_encoders: A dictionary of types and their encoder functions. tp: The type to check for a matching encoder. schema: The schema to add the encoder to.
Referenced by pydantic._internal._generate_schema.GenerateSchema._apply_annotations, pydantic._internal._generate_schema.GenerateSchema.generate_schema.
core_schema.CoreSchema pydantic._internal._generate_schema.apply_validators(core_schema.CoreSchema schema, Iterable[Decorator[RootValidatorDecoratorInfo]]|Iterable[Decorator[ValidatorDecoratorInfo]]|Iterable[Decorator[FieldValidatorDecoratorInfo]] validators)
Apply validators to a schema. Args: schema: The schema to apply validators on. validators: An iterable of validators. field_name: The name of the field if validators are being applied to a model field. Returns: The updated schema.
Referenced by pydantic._internal._generate_schema.GenerateSchema._common_field_schema, pydantic._internal._generate_schema.GenerateSchema._model_schema, pydantic._internal._generate_schema.apply_each_item_validators.
bool pydantic._internal._generate_schema._validators_require_validate_default(Iterable[Decorator[ValidatorDecoratorInfo]] validators)
In v1, if any of the validators for a field had `always=True`, the default value would be validated. This serves as an auxiliary function for re-implementing that logic, by looping over a provided collection of (v1-style) ValidatorDecoratorInfo's and checking if any of them have `always=True`. We should be able to drop this function and the associated logic calling it once we drop support for v1-style validator decorators. (Or we can extend it and keep it if we add something equivalent to the v1-validator `always` kwarg to `field_validator`.)
Referenced by pydantic._internal._generate_schema.GenerateSchema._common_field_schema.
str | list[str | int] | list[list[str | int]] | None pydantic._internal._generate_schema._convert_to_aliases(str|AliasChoices|AliasPath|None alias)
Referenced by pydantic._internal._generate_schema.GenerateSchema._generate_dc_field_schema, pydantic._internal._generate_schema.GenerateSchema._generate_md_field_schema, pydantic._internal._generate_schema.GenerateSchema._generate_parameter_schema, pydantic._internal._generate_schema.GenerateSchema._generate_parameter_v3_schema, pydantic._internal._generate_schema.GenerateSchema._generate_td_field_schema.
core_schema.CoreSchema pydantic._internal._generate_schema.apply_model_validators(core_schema.CoreSchema schema, Iterable[Decorator[ModelValidatorDecoratorInfo]] validators, Literal['inner', 'outer', 'all'] mode)
Apply model validators to a schema. If mode == 'inner', only "before" validators are applied If mode == 'outer', validators other than "before" are applied If mode == 'all', all validators are applied Args: schema: The schema to apply validators on. validators: An iterable of validators. mode: The validator mode. Returns: The updated schema.
Referenced by pydantic._internal._generate_schema.GenerateSchema._model_schema.
core_schema.CoreSchema pydantic._internal._generate_schema.wrap_default(FieldInfo field_info, core_schema.CoreSchema schema)
Wrap schema with default schema if default value or `default_factory` are available. Args: field_info: The field info object. schema: The schema to apply default on. Returns: Updated schema by default value or `default_factory`.
Referenced by pydantic._internal._generate_schema.GenerateSchema._annotated_schema, pydantic._internal._generate_schema.GenerateSchema._common_field_schema, pydantic._internal._generate_schema.GenerateSchema._generate_parameter_schema, pydantic._internal._generate_schema.GenerateSchema._generate_parameter_v3_schema.
GetJsonSchemaFunction | None pydantic._internal._generate_schema._extract_get_pydantic_json_schema(Any tp)
Extract `__get_pydantic_json_schema__` from a type, handling the deprecated `__modify_schema__`.
References pydantic._internal._generate_schema._extract_get_pydantic_json_schema.
Referenced by pydantic._internal._generate_schema.GenerateSchema._apply_annotations, pydantic._internal._generate_schema._extract_get_pydantic_json_schema, pydantic._internal._generate_schema.GenerateSchema._get_wrapped_inner_schema, pydantic._internal._generate_schema.GenerateSchema.generate_schema.
CoreSchema | None pydantic._internal._generate_schema.resolve_original_schema(CoreSchema schema, _Definitions definitions)
Referenced by pydantic._internal._generate_schema.GenerateSchema._apply_annotations, pydantic._internal._generate_schema.GenerateSchema.generate_schema.
Literal['inline', 'keep', 'preserve_metadata'] pydantic._internal._generate_schema._inlining_behavior(core_schema.DefinitionReferenceSchema def_ref)
Determine the inlining behavior of the `'definition-ref'` schema. - If no `'serialization'` schema and no metadata is attached, the schema can safely be inlined. - If it has metadata but only related to the deferred discriminator application, it can be inlined provided that such metadata is kept. - Otherwise, the schema should not be inlined. Doing so would remove the `'serialization'` schema or metadata.
Referenced by pydantic._internal._generate_schema._Definitions._resolve_definition, pydantic._internal._generate_schema._Definitions.finalize_schema.