pip::_internal::req::constructors
pip::_internal::req::constructors.logger
pip::_internal::req::constructors.operators
tuple[str, str | None] pip._internal.req.constructors._strip_extras(str path)
Referenced by pip._internal.req.constructors._set_requirement_extras, pip._internal.req.constructors.parse_editable, pip._internal.req.constructors.parse_req_from_line, pip._internal.req.constructors.parse_req_from_line.
set[str] pip._internal.req.constructors.convert_extras(str|None extras)
Referenced by pip._internal.req.constructors.parse_req_from_line, pip._internal.req.constructors.parse_req_from_line.
Requirement pip._internal.req.constructors._set_requirement_extras(Requirement req, set[str] new_extras)
Returns a new requirement based on the given one, with the supplied extras. If the given requirement already has extras those are replaced (or dropped if no new extras are given).
Referenced by pip._internal.req.constructors.install_req_drop_extras, pip._internal.req.constructors.install_req_extend_extras, pip._internal.req.constructors.install_req_from_parsed_requirement.
tuple[str | None, str, set[str]] pip._internal.req.constructors.parse_editable(str editable_req)
Parses an editable requirement into: - a requirement name - an URL - extras - editable options Accepted requirements: svn+http://blahblah@rev#egg=Foobar[baz]&subdirectory=version_subdir .[some_extra]
References pip._internal.req.constructors._strip_extras.
Referenced by pip._internal.req.constructors._set_requirement_extras, pip._internal.req.constructors.parse_req_from_editable.
None pip::_internal::req::constructors::check_first_requirement_in_file(str filename)
Check if file is parsable as a requirements file. This is heavily based on ``pkg_resources.parse_requirements``, but simplified to just check the first meaningful line. :raises InvalidRequirement: If the first meaningful line cannot be parsed as an requirement.
Referenced by pip._internal.req.constructors._set_requirement_extras, pip._internal.req.constructors.deduce_helpful_msg.
str pip::_internal::req::constructors::deduce_helpful_msg(str req)
Returns helpful msg in case requirements file does not exist, or cannot be parsed. :params req: Requirements file path
References pip._internal.req.constructors.check_first_requirement_in_file.
Referenced by pip._internal.req.constructors.parse_req_from_line, pip._internal.req.constructors.parse_req_from_line.
RequirementParts pip::_internal::req::constructors::parse_req_from_editable(str editable_req)
References pip._internal.req.constructors.parse_editable.
Referenced by pip._internal.req.constructors.install_req_from_editable, pip._internal.req.constructors.install_req_from_editable.
InstallRequirement pip._internal.req.constructors.install_req_from_editable(str editable_req, InstallRequirement|str|None comes_from=None, *, bool|None use_pep517=None, bool isolated=False, list[str]|None global_options=None, dict[str, list[str]]|None hash_options=None, bool constraint=False, bool user_supplied=False, bool permit_editable_wheels=False, dict[str, str|list[str]]|None config_settings=None)
References pip._internal.req.constructors.parse_req_from_editable.
Referenced by pip._internal.req.constructors.install_req_from_parsed_requirement, pip._internal.req.constructors.install_req_from_parsed_requirement.
bool pip::_internal::req::constructors::_looks_like_path(str name)
Checks whether the string "looks like" a path on the filesystem. This does not check whether the target actually exists, only judge from the appearance. Returns true if any of the following conditions is true: * a path separator is found (either os.path.sep or os.path.altsep); * a dot is found (which represents the current directory).
Referenced by pip._internal.req.constructors._get_url_from_path, pip._internal.req.constructors.install_req_from_editable.
str | None pip._internal.req.constructors._get_url_from_path(str path, str name)
First, it checks whether a provided path is an installable directory. If it is, returns the path. If false, check if the path is an archive file (such as a .whl). The function checks if the path is a file. If false, if the path has an @, it will treat it as a PEP 440 URL requirement and return the path.
References pip._internal.req.constructors._looks_like_path.
Referenced by pip._internal.req.constructors.parse_req_from_line, pip._internal.req.constructors.parse_req_from_line.
RequirementParts pip._internal.req.constructors.parse_req_from_line(str name, str|None line_source)
References pip._internal.req.constructors._get_url_from_path, pip._internal.req.constructors._strip_extras, pip._internal.req.constructors.convert_extras, pip._internal.req.constructors.deduce_helpful_msg.
Referenced by pip._internal.req.constructors.install_req_from_line, pip._internal.req.constructors.install_req_from_line.
InstallRequirement pip._internal.req.constructors.install_req_from_line(str name, str|InstallRequirement|None comes_from=None, *, bool|None use_pep517=None, bool isolated=False, list[str]|None global_options=None, dict[str, list[str]]|None hash_options=None, bool constraint=False, str|None line_source=None, bool user_supplied=False, dict[str, str|list[str]]|None config_settings=None)
Creates an InstallRequirement from a name, which might be a requirement, directory containing 'setup.py', filename, or URL. :param line_source: An optional string describing where the line is from, for logging purposes in case of an error.
References pip._internal.req.constructors.parse_req_from_line.
Referenced by pip._internal.req.constructors.install_req_from_parsed_requirement, pip._internal.req.constructors.install_req_from_parsed_requirement.
InstallRequirement pip._internal.req.constructors.install_req_from_req_string(str req_string, InstallRequirement|None comes_from=None, bool isolated=False, bool|None use_pep517=None, bool user_supplied=False)
InstallRequirement pip._internal.req.constructors.install_req_from_parsed_requirement(ParsedRequirement parsed_req, bool isolated=False, bool|None use_pep517=None, bool user_supplied=False, dict[str, str|list[str]]|None config_settings=None)
References pip._internal.req.constructors.install_req_from_editable, pip._internal.req.constructors.install_req_from_line.
InstallRequirement pip::_internal::req::constructors::install_req_from_link_and_ireq(Link link, InstallRequirement ireq)
InstallRequirement pip::_internal::req::constructors::install_req_drop_extras(InstallRequirement ireq)
Creates a new InstallationRequirement using the given template but without any extras. Sets the original requirement as the new one's parent (comes_from).
References pip._internal.req.constructors._set_requirement_extras.
InstallRequirement pip::_internal::req::constructors::install_req_extend_extras(InstallRequirement ireq, Collection[str] extras)
Returns a copy of an installation requirement with some additional extras. Makes a shallow copy of the ireq object.
References pip._internal.req.constructors._set_requirement_extras.
Set[str] pip._internal.req.constructors.convert_extras(Optional[str] extras)
Requirement pip._internal.req.constructors._set_requirement_extras(Requirement req, Set[str] new_extras)
Returns a new requirement based on the given one, with the supplied extras. If the given requirement already has extras those are replaced (or dropped if no new extras are given).
References pip._internal.req.constructors._strip_extras, pip._internal.req.constructors.check_first_requirement_in_file, pip._internal.req.constructors.parse_editable.
InstallRequirement pip._internal.req.constructors.install_req_from_editable(str editable_req, Optional[Union[InstallRequirement, str]] comes_from=None, *, Optional[bool] use_pep517=None, bool isolated=False, Optional[List[str]] global_options=None, Optional[Dict[str, List[str]]] hash_options=None, bool constraint=False, bool user_supplied=False, bool permit_editable_wheels=False, Optional[Dict[str, Union[str, List[str]]]] config_settings=None)
References pip._internal.req.constructors._looks_like_path, pip._internal.req.constructors.parse_req_from_editable.
RequirementParts pip._internal.req.constructors.parse_req_from_line(str name, Optional[str] line_source)
References pip._internal.req.constructors._get_url_from_path, pip._internal.req.constructors._strip_extras, pip._internal.req.constructors.convert_extras, pip._internal.req.constructors.deduce_helpful_msg.
InstallRequirement pip._internal.req.constructors.install_req_from_line(str name, Optional[Union[str, InstallRequirement]] comes_from=None, *, Optional[bool] use_pep517=None, bool isolated=False, Optional[List[str]] global_options=None, Optional[Dict[str, List[str]]] hash_options=None, bool constraint=False, Optional[str] line_source=None, bool user_supplied=False, Optional[Dict[str, Union[str, List[str]]]] config_settings=None)
Creates an InstallRequirement from a name, which might be a requirement, directory containing 'setup.py', filename, or URL. :param line_source: An optional string describing where the line is from, for logging purposes in case of an error.
References pip._internal.req.constructors.parse_req_from_line.
InstallRequirement pip._internal.req.constructors.install_req_from_req_string(str req_string, Optional[InstallRequirement] comes_from=None, bool isolated=False, Optional[bool] use_pep517=None, bool user_supplied=False)
InstallRequirement pip._internal.req.constructors.install_req_from_parsed_requirement(ParsedRequirement parsed_req, bool isolated=False, Optional[bool] use_pep517=None, bool user_supplied=False, Optional[Dict[str, Union[str, List[str]]]] config_settings=None)
References pip._internal.req.constructors._set_requirement_extras, pip._internal.req.constructors.install_req_from_editable, pip._internal.req.constructors.install_req_from_line.