setuptools::config::_validate_pyproject::formats
setuptools::config::_validate_pyproject::formats._logger
str setuptools::config::_validate_pyproject::formats.VERSION_PATTERN
setuptools::config::_validate_pyproject::formats.VERSION_REGEX
str setuptools::config::_validate_pyproject::formats.PEP508_IDENTIFIER_PATTERN
setuptools::config::_validate_pyproject::formats.PEP508_IDENTIFIER_REGEX
setuptools::config::_validate_pyproject::formats.trove_classifier
str setuptools::config::_validate_pyproject::formats.ENTRYPOINT_PATTERN
setuptools::config::_validate_pyproject::formats.ENTRYPOINT_REGEX
str setuptools::config::_validate_pyproject::formats.RECOMMEDED_ENTRYPOINT_PATTERN
setuptools::config::_validate_pyproject::formats.RECOMMEDED_ENTRYPOINT_REGEX
str setuptools::config::_validate_pyproject::formats.ENTRYPOINT_GROUP_PATTERN
setuptools::config::_validate_pyproject::formats.ENTRYPOINT_GROUP_REGEX
bool setuptools.config._validate_pyproject.formats.pep440(str version)
bool setuptools.config._validate_pyproject.formats.pep508_identifier(str name)
Referenced by setuptools.config._validate_pyproject.formats.python_entrypoint_reference.
bool setuptools::config::_validate_pyproject::formats::pep508(str value)
Referenced by setuptools.config._validate_pyproject.formats.pep508_versionspec.
bool setuptools.config._validate_pyproject.formats.pep508_versionspec(str value)
Expression that can be used to specify/lock versions (including ranges)
References setuptools.config._validate_pyproject.formats.pep508.
bool setuptools.config._validate_pyproject.formats.pep517_backend_reference(str value)
References setuptools.config._validate_pyproject.formats.python_identifier.
str setuptools.config._validate_pyproject.formats._download_classifiers()
Referenced by setuptools.config._validate_pyproject.formats._TroveClassifier._disable_download.
bool setuptools.config._validate_pyproject.formats.url(str value)
bool setuptools.config._validate_pyproject.formats.python_identifier(str value)
Referenced by setuptools.config._validate_pyproject.formats.pep517_backend_reference, setuptools.config._validate_pyproject.formats.python_entrypoint_reference, setuptools.config._validate_pyproject.formats.python_qualified_identifier.
bool setuptools.config._validate_pyproject.formats.python_qualified_identifier(str value)
References setuptools.config._validate_pyproject.formats.python_identifier.
Referenced by setuptools.config._validate_pyproject.formats.python_module_name.
bool setuptools.config._validate_pyproject.formats.python_module_name(str value)
References setuptools.config._validate_pyproject.formats.python_qualified_identifier.
bool setuptools.config._validate_pyproject.formats.python_entrypoint_group(str value)
bool setuptools.config._validate_pyproject.formats.python_entrypoint_name(str value)
bool setuptools.config._validate_pyproject.formats.python_entrypoint_reference(str value)
References setuptools.config._validate_pyproject.formats.pep508_identifier, setuptools.config._validate_pyproject.formats.python_identifier.