pip::_vendor::packaging::tags
pip::_vendor::packaging::tags.logger
pip::_vendor::packaging::tags.PythonVersion
pip::_vendor::packaging::tags.AppleVersion
dict pip::_vendor::packaging::tags::INTERPRETER_SHORT_NAMES
int pip::_vendor::packaging::tags::_32_BIT_INTERPRETER
pip::_vendor::packaging::tags.MacVersion
frozenset[Tag] pip._vendor.packaging.tags.parse_tag(str tag)
Parses the provided tag (e.g. `py3-none-any`) into a frozenset of Tag instances. Returning a set is required due to the possibility that the tag is a compressed tag set.
int | str | None pip._vendor.packaging.tags._get_config_var(str name, bool warn=False)
Referenced by pip._vendor.packaging.tags._abi3_applies, pip._vendor.packaging.tags._cpython_abis, pip._vendor.packaging.tags._generic_abi, pip._vendor.packaging.tags.interpreter_version, pip._vendor.packaging.tags.mac_platforms.
str pip::_vendor::packaging::tags::_normalize_string(str string)
Referenced by pip._vendor.packaging.tags._generic_abi, pip._vendor.packaging.tags._generic_platforms, pip._vendor.packaging.tags._linux_platforms, pip._vendor.packaging.tags.android_platforms, pip._vendor.packaging.tags.cpython_tags, pip._vendor.packaging.tags.mac_platforms.
bool pip._vendor.packaging.tags._is_threaded_cpython(list[str] abis)
Determine if the ABI corresponds to a threaded (`--disable-gil`) build. The threaded builds are indicated by a "t" in the abiflags.
Referenced by pip._vendor.packaging.tags.cpython_tags.
bool pip._vendor.packaging.tags._abi3_applies(PythonVersion python_version, bool threading)
Determine if the Python version supports abi3. PEP 384 was first implemented in Python 3.2. The threaded (`--disable-gil`) builds do not support abi3.
Referenced by pip._vendor.packaging.tags.cpython_tags, pip._vendor.packaging.tags.cpython_tags.
list[str] pip._vendor.packaging.tags._cpython_abis(PythonVersion py_version, bool warn=False)
References pip._vendor.packaging.tags._get_config_var, pip._vendor.packaging.tags._version_nodot.
Referenced by pip._vendor.packaging.tags._generic_abi, pip._vendor.packaging.tags.cpython_tags, pip._vendor.packaging.tags.cpython_tags.
Iterator[Tag] pip._vendor.packaging.tags.cpython_tags(PythonVersion|None python_version=None, Iterable[str]|None abis=None, Iterable[str]|None platforms=None, *, bool warn=False)
Yields the tags for a CPython interpreter. The tags consist of: - cp<python_version>-<abi>-<platform> - cp<python_version>-abi3-<platform> - cp<python_version>-none-<platform> - cp<less than python_version>-abi3-<platform> # Older Python versions down to 3.2. If python_version only specifies a major version then user-provided ABIs and the 'none' ABItag will be used. If 'abi3' or 'none' are specified in 'abis' then they will be yielded at their normal position and not at the beginning.
References pip._vendor.packaging.tags._abi3_applies, pip._vendor.packaging.tags._cpython_abis, pip._vendor.packaging.tags._is_threaded_cpython, pip._vendor.packaging.tags._version_nodot, pip._vendor.packaging.tags.platform_tags.
Referenced by pip._vendor.packaging.tags.mac_platforms, pip._vendor.packaging.tags.sys_tags.
list[str] pip._vendor.packaging.tags._generic_abi()
Return the ABI tag based on EXT_SUFFIX.
References pip._vendor.packaging.tags._cpython_abis, pip._vendor.packaging.tags._get_config_var, pip._vendor.packaging.tags._normalize_string.
Referenced by pip._vendor.packaging.tags.generic_tags, pip._vendor.packaging.tags.generic_tags.
Iterator[Tag] pip._vendor.packaging.tags.generic_tags(str|None interpreter=None, Iterable[str]|None abis=None, Iterable[str]|None platforms=None, *, bool warn=False)
Yields the tags for a generic interpreter. The tags consist of: - <interpreter>-<abi>-<platform> The "none" ABI will be added if it was not explicitly provided.
References pip._vendor.packaging.tags._generic_abi, pip._vendor.packaging.tags.interpreter_name, pip._vendor.packaging.tags.interpreter_version, pip._vendor.packaging.tags.platform_tags.
Referenced by pip._vendor.packaging.tags.mac_platforms, pip._vendor.packaging.tags.sys_tags.
Iterator[str] pip._vendor.packaging.tags._py_interpreter_range(PythonVersion py_version)
Yields Python versions in descending order. After the latest version, the major-only version will be yielded, and then all previous versions of that major version.
Referenced by pip._vendor.packaging.tags.compatible_tags, pip._vendor.packaging.tags.compatible_tags.
Iterator[Tag] pip._vendor.packaging.tags.compatible_tags(PythonVersion|None python_version=None, str|None interpreter=None, Iterable[str]|None platforms=None)
Yields the sequence of tags that are compatible with a specific version of Python. The tags consist of: - py*-none-<platform> - <interpreter>-none-any # ... if `interpreter` is provided. - py*-none-any
References pip._vendor.packaging.tags._py_interpreter_range, pip._vendor.packaging.tags.platform_tags.
Referenced by pip._vendor.packaging.tags.mac_platforms, pip._vendor.packaging.tags.sys_tags.
str pip::_vendor::packaging::tags::_mac_arch(str arch, bool is_32bit=_32_BIT_INTERPRETER)
Referenced by pip._vendor.packaging.tags.mac_platforms, pip._vendor.packaging.tags.mac_platforms.
list[str] pip._vendor.packaging.tags._mac_binary_formats(AppleVersion version, str cpu_arch)
Referenced by pip._vendor.packaging.tags.mac_platforms, pip._vendor.packaging.tags.mac_platforms.
Iterator[str] pip._vendor.packaging.tags.mac_platforms(AppleVersion|None version=None, str|None arch=None)
Yields the platform tags for a macOS system. The `version` parameter is a two-item tuple specifying the macOS version to generate platform tags for. The `arch` parameter is the CPU architecture to generate platform tags for. Both parameters default to the appropriate value for the current system.
References pip._vendor.packaging.tags._mac_arch, pip._vendor.packaging.tags._mac_binary_formats.
Referenced by pip._vendor.packaging.tags.mac_platforms, pip._vendor.packaging.tags.platform_tags.
Iterator[str] pip._vendor.packaging.tags.ios_platforms(AppleVersion|None version=None, str|None multiarch=None)
Yields the platform tags for an iOS system. :param version: A two-item tuple specifying the iOS version to generate platform tags for. Defaults to the current iOS version. :param multiarch: The CPU architecture+ABI to generate platform tags for - (the value used by `sys.implementation._multiarch` e.g., `arm64_iphoneos` or `x84_64_iphonesimulator`). Defaults to the current multiarch value.
Referenced by pip._vendor.packaging.tags.platform_tags.
Iterator[str] pip._vendor.packaging.tags.android_platforms(int|None api_level=None, str|None abi=None)
Yields the :attr:`~Tag.platform` tags for Android. If this function is invoked on non-Android platforms, the ``api_level`` and ``abi`` arguments are required. :param int api_level: The maximum `API level <https://developer.android.com/tools/releases/platforms>`__ to return. Defaults to the current system's version, as returned by ``platform.android_ver``. :param str abi: The `Android ABI <https://developer.android.com/ndk/guides/abis>`__, e.g. ``arm64_v8a``. Defaults to the current system's ABI , as returned by ``sysconfig.get_platform``. Hyphens and periods will be replaced with underscores.
References pip._vendor.packaging.tags._normalize_string.
Referenced by pip._vendor.packaging.tags.platform_tags.
Iterator[str] pip._vendor.packaging.tags._linux_platforms(bool is_32bit=_32_BIT_INTERPRETER)
References pip._vendor.packaging.tags._normalize_string.
Referenced by pip._vendor.packaging.tags.mac_platforms, pip._vendor.packaging.tags.platform_tags.
Iterator[str] pip._vendor.packaging.tags._generic_platforms()
References pip._vendor.packaging.tags._normalize_string.
Referenced by pip._vendor.packaging.tags.mac_platforms, pip._vendor.packaging.tags.platform_tags.
Iterator[str] pip._vendor.packaging.tags.platform_tags()
Provides the platform tags for this installation.
References pip._vendor.packaging.tags._generic_platforms, pip._vendor.packaging.tags._linux_platforms, pip._vendor.packaging.tags.android_platforms, pip._vendor.packaging.tags.ios_platforms, pip._vendor.packaging.tags.mac_platforms.
Referenced by pip._vendor.packaging.tags.compatible_tags, pip._vendor.packaging.tags.compatible_tags, pip._vendor.packaging.tags.cpython_tags, pip._vendor.packaging.tags.cpython_tags, pip._vendor.packaging.tags.generic_tags, pip._vendor.packaging.tags.generic_tags.
str pip::_vendor::packaging::tags::interpreter_name()
Returns the name of the running interpreter. Some implementations have a reserved, two-letter abbreviation which will be returned when appropriate. Returns the name of the running interpreter.
Referenced by pip._vendor.packaging.tags.generic_tags, pip._vendor.packaging.tags.generic_tags, pip._vendor.packaging.tags.mac_platforms, pip._vendor.packaging.tags.sys_tags.
str pip::_vendor::packaging::tags::interpreter_version(*, bool warn=False)
Returns the version of the running interpreter.
References pip._vendor.packaging.tags._get_config_var, pip._vendor.packaging.tags._version_nodot.
Referenced by pip._vendor.packaging.tags.generic_tags, pip._vendor.packaging.tags.generic_tags, pip._vendor.packaging.tags.sys_tags.
str pip::_vendor::packaging::tags::_version_nodot(PythonVersion version)
Referenced by pip._vendor.packaging.tags._abi3_applies, pip._vendor.packaging.tags._cpython_abis, pip._vendor.packaging.tags.cpython_tags, pip._vendor.packaging.tags.cpython_tags, pip._vendor.packaging.tags.interpreter_version, pip._vendor.packaging.tags.mac_platforms.
Iterator[Tag] pip._vendor.packaging.tags.sys_tags(*, bool warn=False)
Returns the sequence of tag triples for the running interpreter. The order of the sequence corresponds to priority order for the interpreter, from most to least important.
References pip._vendor.packaging.tags.compatible_tags, pip._vendor.packaging.tags.cpython_tags, pip._vendor.packaging.tags.generic_tags, pip._vendor.packaging.tags.interpreter_name, pip._vendor.packaging.tags.interpreter_version.
bool pip._vendor.packaging.tags._abi3_applies(PythonVersion python_version)
Determine if the Python version supports abi3. PEP 384 was first implemented in Python 3.2.
References pip._vendor.packaging.tags._get_config_var, pip._vendor.packaging.tags._version_nodot.
Iterator[Tag] pip._vendor.packaging.tags.cpython_tags(Optional[PythonVersion] python_version=None, Optional[Iterable[str]] abis=None, Optional[Iterable[str]] platforms=None, *, bool warn=False)
Yields the tags for a CPython interpreter. The tags consist of: - cp<python_version>-<abi>-<platform> - cp<python_version>-abi3-<platform> - cp<python_version>-none-<platform> - cp<less than python_version>-abi3-<platform> # Older Python versions down to 3.2. If python_version only specifies a major version then user-provided ABIs and the 'none' ABItag will be used. If 'abi3' or 'none' are specified in 'abis' then they will be yielded at their normal position and not at the beginning.
References pip._vendor.packaging.tags._abi3_applies, pip._vendor.packaging.tags._cpython_abis, pip._vendor.packaging.tags._normalize_string, pip._vendor.packaging.tags._version_nodot, pip._vendor.packaging.tags.platform_tags.
Iterator[Tag] pip._vendor.packaging.tags.generic_tags(Optional[str] interpreter=None, Optional[Iterable[str]] abis=None, Optional[Iterable[str]] platforms=None, *, bool warn=False)
Yields the tags for a generic interpreter. The tags consist of: - <interpreter>-<abi>-<platform> The "none" ABI will be added if it was not explicitly provided.
References pip._vendor.packaging.tags._generic_abi, pip._vendor.packaging.tags.interpreter_name, pip._vendor.packaging.tags.interpreter_version, pip._vendor.packaging.tags.platform_tags.
Iterator[Tag] pip._vendor.packaging.tags.compatible_tags(Optional[PythonVersion] python_version=None, Optional[str] interpreter=None, Optional[Iterable[str]] platforms=None)
Yields the sequence of tags that are compatible with a specific version of Python. The tags consist of: - py*-none-<platform> - <interpreter>-none-any # ... if `interpreter` is provided. - py*-none-any
References pip._vendor.packaging.tags._py_interpreter_range, pip._vendor.packaging.tags.platform_tags.
List[str] pip._vendor.packaging.tags._mac_binary_formats(MacVersion version, str cpu_arch)
Iterator[str] pip._vendor.packaging.tags.mac_platforms(Optional[MacVersion] version=None, Optional[str] arch=None)
Yields the platform tags for a macOS system. The `version` parameter is a two-item tuple specifying the macOS version to generate platform tags for. The `arch` parameter is the CPU architecture to generate platform tags for. Both parameters default to the appropriate value for the current system.
References pip._vendor.packaging.tags._generic_platforms, pip._vendor.packaging.tags._get_config_var, pip._vendor.packaging.tags._linux_platforms, pip._vendor.packaging.tags._mac_arch, pip._vendor.packaging.tags._mac_binary_formats, pip._vendor.packaging.tags._normalize_string, pip._vendor.packaging.tags._version_nodot, pip._vendor.packaging.tags.compatible_tags, pip._vendor.packaging.tags.cpython_tags, pip._vendor.packaging.tags.generic_tags, pip._vendor.packaging.tags.interpreter_name, pip._vendor.packaging.tags.mac_platforms.