pip::_vendor::rich::_win32_console
Any pip::_vendor::rich::_win32_console::windll
int pip::_vendor::rich::_win32_console::STDOUT
int pip::_vendor::rich::_win32_console::ENABLE_VIRTUAL_TERMINAL_PROCESSING
pip::_vendor::rich::_win32_console.COORD
Referenced by pip._vendor.rich._win32_console.WindowsCoordinates.from_param.
Any pip::_vendor::rich::_win32_console::_GetStdHandle
Referenced by pip._vendor.rich._win32_console.WindowsCoordinates.from_param, pip._vendor.rich._win32_console.GetStdHandle.
pip::_vendor::rich::_win32_console.argtypes
pip::_vendor::rich::_win32_console.restype
Any pip::_vendor::rich::_win32_console::_GetConsoleMode
Referenced by pip._vendor.rich._win32_console.WindowsCoordinates.from_param, pip._vendor.rich._win32_console.GetConsoleMode.
Any pip::_vendor::rich::_win32_console::_FillConsoleOutputCharacterW
Referenced by pip._vendor.rich._win32_console.FillConsoleOutputCharacter, pip._vendor.rich._win32_console.WindowsCoordinates.from_param.
Any pip::_vendor::rich::_win32_console::_FillConsoleOutputAttribute
Referenced by pip._vendor.rich._win32_console.FillConsoleOutputAttribute, pip._vendor.rich._win32_console.WindowsCoordinates.from_param.
Any pip::_vendor::rich::_win32_console::_SetConsoleTextAttribute
Referenced by pip._vendor.rich._win32_console.WindowsCoordinates.from_param, pip._vendor.rich._win32_console.SetConsoleTextAttribute.
Any pip::_vendor::rich::_win32_console::_GetConsoleScreenBufferInfo
Referenced by pip._vendor.rich._win32_console.WindowsCoordinates.from_param, pip._vendor.rich._win32_console.GetConsoleScreenBufferInfo.
Any pip::_vendor::rich::_win32_console::_SetConsoleCursorPosition
Referenced by pip._vendor.rich._win32_console.WindowsCoordinates.from_param, pip._vendor.rich._win32_console.SetConsoleCursorPosition.
Any pip::_vendor::rich::_win32_console::_GetConsoleCursorInfo
Referenced by pip._vendor.rich._win32_console.WindowsCoordinates.from_param, pip._vendor.rich._win32_console.GetConsoleCursorInfo.
Any pip::_vendor::rich::_win32_console::_SetConsoleCursorInfo
Referenced by pip._vendor.rich._win32_console.WindowsCoordinates.from_param, pip._vendor.rich._win32_console.SetConsoleCursorInfo.
Any pip::_vendor::rich::_win32_console::_SetConsoleTitle
Referenced by pip._vendor.rich._win32_console.WindowsCoordinates.from_param, pip._vendor.rich._win32_console.SetConsoleTitle.
wintypes HANDLE pip::_vendor::rich::_win32_console::handle
pip::_vendor::rich::_win32_console.console
pip::_vendor::rich::_win32_console.term
pip::_vendor::rich::_win32_console.style
pip::_vendor::rich::_win32_console.heading
wintypes HANDLE pip::_vendor::rich::_win32_console::GetStdHandle(int handle=STDOUT)
Retrieves a handle to the specified standard device (standard input, standard output, or standard error). Args: handle (int): Integer identifier for the handle. Defaults to -11 (stdout). Returns: wintypes.HANDLE: The handle
References pip._vendor.rich._win32_console._GetStdHandle.
Referenced by pip._vendor.rich._win32_console.WindowsCoordinates.from_param.
int pip::_vendor::rich::_win32_console::GetConsoleMode(wintypes.HANDLE std_handle)
Retrieves the current input mode of a console's input buffer or the current output mode of a console screen buffer. Args: std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer. Raises: LegacyWindowsError: If any error occurs while calling the Windows console API. Returns: int: Value representing the current console mode as documented at https://docs.microsoft.com/en-us/windows/console/getconsolemode#parameters
References pip._vendor.rich._win32_console._GetConsoleMode.
int pip::_vendor::rich::_win32_console::FillConsoleOutputCharacter(wintypes.HANDLE std_handle, str char, int length, WindowsCoordinates start)
Writes a character to the console screen buffer a specified number of times, beginning at the specified coordinates. Args: std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer. char (str): The character to write. Must be a string of length 1. length (int): The number of times to write the character. start (WindowsCoordinates): The coordinates to start writing at. Returns: int: The number of characters written.
References pip._vendor.rich._win32_console._FillConsoleOutputCharacterW.
Referenced by pip._vendor.rich._win32_console.LegacyWindowsTerm.erase_end_of_line, pip._vendor.rich._win32_console.LegacyWindowsTerm.erase_line, pip._vendor.rich._win32_console.LegacyWindowsTerm.erase_start_of_line.
int pip::_vendor::rich::_win32_console::FillConsoleOutputAttribute(wintypes.HANDLE std_handle, int attributes, int length, WindowsCoordinates start)
Sets the character attributes for a specified number of character cells, beginning at the specified coordinates in a screen buffer. Args: std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer. attributes (int): Integer value representing the foreground and background colours of the cells. length (int): The number of cells to set the output attribute of. start (WindowsCoordinates): The coordinates of the first cell whose attributes are to be set. Returns: int: The number of cells whose attributes were actually set.
References pip._vendor.rich._win32_console._FillConsoleOutputAttribute.
Referenced by pip._vendor.rich._win32_console.LegacyWindowsTerm.erase_end_of_line, pip._vendor.rich._win32_console.LegacyWindowsTerm.erase_line, pip._vendor.rich._win32_console.LegacyWindowsTerm.erase_start_of_line.
bool pip::_vendor::rich::_win32_console::SetConsoleTextAttribute(wintypes.HANDLE std_handle, wintypes.WORD attributes)
Set the colour attributes for all text written after this function is called. Args: std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer. attributes (int): Integer value representing the foreground and background colours. Returns: bool: True if the attribute was set successfully, otherwise False.
References pip._vendor.rich._win32_console._SetConsoleTextAttribute.
Referenced by pip._vendor.rich._win32_console.LegacyWindowsTerm.write_styled.
CONSOLE_SCREEN_BUFFER_INFO pip::_vendor::rich::_win32_console::GetConsoleScreenBufferInfo(wintypes.HANDLE std_handle)
Retrieves information about the specified console screen buffer. Args: std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer. Returns: CONSOLE_SCREEN_BUFFER_INFO: A CONSOLE_SCREEN_BUFFER_INFO ctype struct contain information about screen size, cursor position, colour attributes, and more.
References pip._vendor.rich._win32_console._GetConsoleScreenBufferInfo.
Referenced by pip._vendor.rich._win32_console.LegacyWindowsTerm.cursor_position, pip._vendor.rich._win32_console.WindowsCoordinates.from_param, pip._vendor.rich._win32_console.LegacyWindowsTerm.screen_size.
bool pip::_vendor::rich::_win32_console::SetConsoleCursorPosition(wintypes.HANDLE std_handle, WindowsCoordinates coords)
Set the position of the cursor in the console screen Args: std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer. coords (WindowsCoordinates): The coordinates to move the cursor to. Returns: bool: True if the function succeeds, otherwise False.
References pip._vendor.rich._win32_console._SetConsoleCursorPosition.
Referenced by pip._vendor.rich._win32_console.LegacyWindowsTerm.move_cursor_backward, pip._vendor.rich._win32_console.LegacyWindowsTerm.move_cursor_down, pip._vendor.rich._win32_console.LegacyWindowsTerm.move_cursor_forward, pip._vendor.rich._win32_console.LegacyWindowsTerm.move_cursor_to, pip._vendor.rich._win32_console.LegacyWindowsTerm.move_cursor_to_column, pip._vendor.rich._win32_console.LegacyWindowsTerm.move_cursor_up.
bool pip::_vendor::rich::_win32_console::GetConsoleCursorInfo(wintypes.HANDLE std_handle, CONSOLE_CURSOR_INFO cursor_info)
Get the cursor info - used to get cursor visibility and width Args: std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer. cursor_info (CONSOLE_CURSOR_INFO): CONSOLE_CURSOR_INFO ctype struct that receives information about the console's cursor. Returns: bool: True if the function succeeds, otherwise False.
References pip._vendor.rich._win32_console._GetConsoleCursorInfo.
bool pip::_vendor::rich::_win32_console::SetConsoleCursorInfo(wintypes.HANDLE std_handle, CONSOLE_CURSOR_INFO cursor_info)
Set the cursor info - used for adjusting cursor visibility and width Args: std_handle (wintypes.HANDLE): A handle to the console input buffer or the console screen buffer. cursor_info (CONSOLE_CURSOR_INFO): CONSOLE_CURSOR_INFO ctype struct containing the new cursor info. Returns: bool: True if the function succeeds, otherwise False.
References pip._vendor.rich._win32_console._SetConsoleCursorInfo.
bool pip::_vendor::rich::_win32_console::SetConsoleTitle(str title)
Sets the title of the current console window Args: title (str): The new title of the console window. Returns: bool: True if the function succeeds, otherwise False.
References pip._vendor.rich._win32_console._SetConsoleTitle.