pip::_vendor::packaging::markers
pip::_vendor::packaging::markers.Operator
pip::_vendor::packaging::markers.EvaluateContext
dict pip::_vendor::packaging::markers.MARKERS_ALLOWING_SET
dict pip::_vendor::packaging::markers::_operators
tuple pip::_vendor::packaging::markers.VARIABLE
dict pip::_vendor::packaging::markers.ALIASES
tuple pip::_vendor::packaging::markers.VERSION_CMP
tuple pip::_vendor::packaging::markers.MARKER_OP
pip::_vendor::packaging::markers.MARKER_VALUE
pip::_vendor::packaging::markers.BOOLOP
tuple pip::_vendor::packaging::markers.MARKER_VAR
pip::_vendor::packaging::markers.MARKER_ITEM
pip::_vendor::packaging::markers.LPAREN
pip::_vendor::packaging::markers.RPAREN
pip::_vendor::packaging::markers.MARKER_EXPR
pip::_vendor::packaging::markers.MARKER_ATOM
pip::_vendor::packaging::markers.MARKER
pip::_vendor::packaging::markers._undefined
Any pip._vendor.packaging.markers._normalize_extra_values(Any results)
Normalize extra values.
str pip._vendor.packaging.markers._format_marker(list[str]|MarkerAtom|str marker, bool|None first=True)
References pip._vendor.packaging.markers._format_marker.
Referenced by pip._vendor.packaging.markers._format_marker, pip._vendor.packaging.markers._format_marker, pip._vendor.packaging.markers.format_full_version.
bool pip._vendor.packaging.markers._eval_op(str lhs, Op op, str|AbstractSet[str] rhs)
Referenced by pip._vendor.packaging.markers._evaluate_markers, pip._vendor.packaging.markers._evaluate_markers.
tuple[str, str | AbstractSet[str]] pip._vendor.packaging.markers._normalize(str lhs, str|AbstractSet[str] rhs, str key)
Referenced by pip._vendor.packaging.markers._evaluate_markers.
bool pip._vendor.packaging.markers._evaluate_markers(MarkerList markers, dict[str, str|AbstractSet[str]] environment)
References pip._vendor.packaging.markers._eval_op, pip._vendor.packaging.markers._evaluate_markers, pip._vendor.packaging.markers._normalize.
Referenced by pip._vendor.packaging.markers._evaluate_markers, pip._vendor.packaging.markers._evaluate_markers, pip._vendor.packaging.markers.Marker.evaluate, pip._vendor.packaging.markers.Marker.evaluate.
str pip._vendor.packaging.markers.format_full_version(sys._version_info info)
Referenced by pip._vendor.packaging.markers.default_environment, pip._vendor.packaging.markers.format_full_version.
Environment pip._vendor.packaging.markers.default_environment()
References pip._vendor.packaging.markers.format_full_version.
Referenced by pip._vendor.packaging.markers.Marker.evaluate, pip._vendor.packaging.markers.Marker.evaluate.
dict[str, str | AbstractSet[str]] pip._vendor.packaging.markers._repair_python_full_version(dict[str, str|AbstractSet[str]] env)
Work around platform.python_version() returning something that is not PEP 440 compliant for non-tagged Python builds.
Referenced by pip._vendor.packaging.markers.Marker.evaluate.
List[Any] pip._vendor.packaging.markers._coerce_parse_result(Union[ParseResults, List[Any]] results)
References pip._vendor.packaging.markers._coerce_parse_result.
Referenced by pip._vendor.packaging.markers._coerce_parse_result, pip._vendor.packaging.markers.format_full_version.
str pip._vendor.packaging.markers._format_marker(Union[List[str], Tuple[Node,...], str] marker, Optional[bool] first=True)
References pip._vendor.packaging.markers._format_marker.
bool pip._vendor.packaging.markers._eval_op(str lhs, Op op, str rhs)
str pip._vendor.packaging.markers._get_env(Dict[str, str] environment, str name)
Referenced by pip._vendor.packaging.markers._evaluate_markers.
bool pip._vendor.packaging.markers._evaluate_markers(List[Any] markers, Dict[str, str] environment)
References pip._vendor.packaging.markers._eval_op, pip._vendor.packaging.markers._evaluate_markers, pip._vendor.packaging.markers._get_env.
str pip._vendor.packaging.markers.format_full_version("sys._version_info" info)
References pip._vendor.packaging.markers._coerce_parse_result, pip._vendor.packaging.markers._format_marker, pip._vendor.packaging.markers.format_full_version.