h11::_readers
h11::_readers.header_field_re
h11::_readers.obs_fold_re
h11::_readers.request_line_re
h11::_readers.status_line_re
h11::_readers.chunk_header_re
h11::_readers.ReadersType
dict h11::_readers.READERS
Iterable[bytes] h11._readers._obsolete_line_fold(Iterable[bytes] lines)
Referenced by h11._readers._decode_header_lines.
Iterable[Tuple[bytes, bytes]] h11._readers._decode_header_lines(Iterable[bytes] lines)
References h11._readers._obsolete_line_fold.
Referenced by h11._readers.maybe_read_from_IDLE_client, h11._readers.maybe_read_from_SEND_RESPONSE_server.
Optional[Request] h11._readers.maybe_read_from_IDLE_client(ReceiveBuffer buf)
References h11._readers._decode_header_lines.
Union[InformationalResponse, Response, None] h11._readers.maybe_read_from_SEND_RESPONSE_server(ReceiveBuffer buf)
References h11._readers._decode_header_lines.
None h11._readers.expect_nothing(ReceiveBuffer buf)