pip::_vendor::pygments::formatters
dict pip::_vendor::pygments::formatters::_formatter_cache
dict pip::_vendor::pygments::formatters::_pattern_cache
pip::_vendor::pygments::formatters.oldmod
pip::_vendor::pygments::formatters.newmod
pip::_vendor::pygments::formatters.aliases
pip::_vendor::pygments::formatters.filenames
pip::_vendor::pygments::formatters::_fn_matches(fn, glob)
Return whether the supplied file name fn matches pattern filename.
Referenced by pip._vendor.pygments.formatters.get_formatter_for_filename.
pip::_vendor::pygments::formatters::_load_formatters(module_name)
Load a formatter (and all others in the module too).
Referenced by pip._vendor.pygments.formatters.find_formatter_class, pip._vendor.pygments.formatters.get_all_formatters, pip._vendor.pygments.formatters.get_formatter_for_filename.
pip::_vendor::pygments::formatters::get_all_formatters()
Return a generator for all formatter classes.
References pip._vendor.pygments.formatters._load_formatters.
pip::_vendor::pygments::formatters::find_formatter_class(alias)
Lookup a formatter by alias. Returns None if not found.
References pip._vendor.pygments.formatters._load_formatters.
Referenced by pip._vendor.pygments.formatters.get_formatter_by_name.
pip::_vendor::pygments::formatters::get_formatter_by_name(_alias, **options)
Return an instance of a :class:`.Formatter` subclass that has `alias` in its aliases list. The formatter is given the `options` at its instantiation. Will raise :exc:`pygments.util.ClassNotFound` if no formatter with that alias is found.
References pip._vendor.pygments.formatters.find_formatter_class.
pip::_vendor::pygments::formatters::load_formatter_from_file(filename, formattername="CustomFormatter", **options)
Return a `Formatter` subclass instance loaded from the provided file, relative to the current directory. The file is expected to contain a Formatter class named ``formattername`` (by default, CustomFormatter). Users should be very careful with the input, because this method is equivalent to running ``eval()`` on the input file. The formatter is given the `options` at its instantiation. :exc:`pygments.util.ClassNotFound` is raised if there are any errors loading the formatter. .. versionadded:: 2.2
pip::_vendor::pygments::formatters::get_formatter_for_filename(fn, **options)
Return a :class:`.Formatter` subclass instance that has a filename pattern matching `fn`. The formatter is given the `options` at its instantiation. Will raise :exc:`pygments.util.ClassNotFound` if no formatter for that filename is found.
References pip._vendor.pygments.formatters._fn_matches, pip._vendor.pygments.formatters._load_formatters.