setuptools::_vendor::tomli::_parser
setuptools::_vendor::tomli::_parser.ASCII_CTRL
setuptools::_vendor::tomli::_parser.ILLEGAL_BASIC_STR_CHARS
setuptools::_vendor::tomli::_parser.ILLEGAL_MULTILINE_BASIC_STR_CHARS
setuptools::_vendor::tomli::_parser.ILLEGAL_LITERAL_STR_CHARS
setuptools::_vendor::tomli::_parser.ILLEGAL_MULTILINE_LITERAL_STR_CHARS
setuptools::_vendor::tomli::_parser.ILLEGAL_COMMENT_CHARS
setuptools::_vendor::tomli::_parser.TOML_WS
setuptools::_vendor::tomli::_parser.TOML_WS_AND_NEWLINE
setuptools::_vendor::tomli::_parser.BARE_KEY_CHARS
setuptools::_vendor::tomli::_parser.KEY_INITIAL_CHARS
setuptools::_vendor::tomli::_parser.HEXDIGIT_CHARS
setuptools::_vendor::tomli::_parser.BASIC_STR_ESCAPE_REPLACEMENTS
dict[str, Any] setuptools._vendor.tomli._parser.load(BinaryIO __fp, *, ParseFloat parse_float=float)
Parse TOML from a binary file object.
dict[str, Any] setuptools._vendor.tomli._parser.loads(str __s, *, ParseFloat parse_float=float)
Parse TOML from a string.
References setuptools._vendor.tomli._parser.create_dict_rule, setuptools._vendor.tomli._parser.create_list_rule, setuptools._vendor.tomli._parser.key_value_rule, setuptools._vendor.tomli._parser.make_safe_parse_float, setuptools._vendor.tomli._parser.skip_chars, setuptools._vendor.tomli._parser.skip_comment, setuptools._vendor.tomli._parser.suffixed_err.
Pos setuptools._vendor.tomli._parser.skip_chars(str src, Pos pos, Iterable[str] chars)
Referenced by setuptools._vendor.tomli._parser.create_dict_rule, setuptools._vendor.tomli._parser.create_list_rule, setuptools._vendor.tomli._parser.loads, setuptools._vendor.tomli._parser.parse_basic_str_escape, setuptools._vendor.tomli._parser.parse_inline_table, setuptools._vendor.tomli._parser.parse_key, setuptools._vendor.tomli._parser.parse_key_part, setuptools._vendor.tomli._parser.parse_key_value_pair, setuptools._vendor.tomli._parser.skip_comments_and_array_ws.
Pos setuptools._vendor.tomli._parser.skip_until(str src, Pos pos, str expect, *, frozenset[str] error_on, bool error_on_eof)
References setuptools._vendor.tomli._parser.suffixed_err.
Referenced by setuptools._vendor.tomli._parser.parse_literal_str, setuptools._vendor.tomli._parser.parse_multiline_str, setuptools._vendor.tomli._parser.skip_comment.
Pos setuptools._vendor.tomli._parser.skip_comment(str src, Pos pos)
References setuptools._vendor.tomli._parser.skip_until.
Referenced by setuptools._vendor.tomli._parser.loads, setuptools._vendor.tomli._parser.skip_comments_and_array_ws.
Pos setuptools._vendor.tomli._parser.skip_comments_and_array_ws(str src, Pos pos)
References setuptools._vendor.tomli._parser.skip_chars, setuptools._vendor.tomli._parser.skip_comment.
Referenced by setuptools._vendor.tomli._parser.parse_array.
tuple[Pos, Key] setuptools._vendor.tomli._parser.create_dict_rule(str src, Pos pos, Output out)
References setuptools._vendor.tomli._parser.parse_key, setuptools._vendor.tomli._parser.skip_chars, setuptools._vendor.tomli._parser.suffixed_err.
Referenced by setuptools._vendor.tomli._parser.loads.
tuple[Pos, Key] setuptools._vendor.tomli._parser.create_list_rule(str src, Pos pos, Output out)
References setuptools._vendor.tomli._parser.parse_key, setuptools._vendor.tomli._parser.skip_chars, setuptools._vendor.tomli._parser.suffixed_err.
Referenced by setuptools._vendor.tomli._parser.loads.
Pos setuptools._vendor.tomli._parser.key_value_rule(str src, Pos pos, Output out, Key header, ParseFloat parse_float)
References setuptools._vendor.tomli._parser.parse_key_value_pair, setuptools._vendor.tomli._parser.suffixed_err.
Referenced by setuptools._vendor.tomli._parser.loads.
tuple[Pos, Key, Any] setuptools._vendor.tomli._parser.parse_key_value_pair(str src, Pos pos, ParseFloat parse_float)
References setuptools._vendor.tomli._parser.parse_key, setuptools._vendor.tomli._parser.parse_value, setuptools._vendor.tomli._parser.skip_chars, setuptools._vendor.tomli._parser.suffixed_err.
Referenced by setuptools._vendor.tomli._parser.key_value_rule, setuptools._vendor.tomli._parser.parse_inline_table.
tuple[Pos, Key] setuptools._vendor.tomli._parser.parse_key(str src, Pos pos)
References setuptools._vendor.tomli._parser.parse_key_part, setuptools._vendor.tomli._parser.skip_chars.
Referenced by setuptools._vendor.tomli._parser.create_dict_rule, setuptools._vendor.tomli._parser.create_list_rule, setuptools._vendor.tomli._parser.parse_key_value_pair.
tuple[Pos, str] setuptools._vendor.tomli._parser.parse_key_part(str src, Pos pos)
References setuptools._vendor.tomli._parser.parse_literal_str, setuptools._vendor.tomli._parser.parse_one_line_basic_str, setuptools._vendor.tomli._parser.skip_chars, setuptools._vendor.tomli._parser.suffixed_err.
Referenced by setuptools._vendor.tomli._parser.parse_key.
tuple[Pos, str] setuptools._vendor.tomli._parser.parse_one_line_basic_str(str src, Pos pos)
References setuptools._vendor.tomli._parser.parse_basic_str.
Referenced by setuptools._vendor.tomli._parser.parse_key_part, setuptools._vendor.tomli._parser.parse_value.
tuple[Pos, list] setuptools._vendor.tomli._parser.parse_array(str src, Pos pos, ParseFloat parse_float)
References setuptools._vendor.tomli._parser.parse_value, setuptools._vendor.tomli._parser.skip_comments_and_array_ws, setuptools._vendor.tomli._parser.suffixed_err.
Referenced by setuptools._vendor.tomli._parser.parse_value.
tuple[Pos, dict] setuptools._vendor.tomli._parser.parse_inline_table(str src, Pos pos, ParseFloat parse_float)
References setuptools._vendor.tomli._parser.parse_key_value_pair, setuptools._vendor.tomli._parser.skip_chars, setuptools._vendor.tomli._parser.suffixed_err.
Referenced by setuptools._vendor.tomli._parser.parse_value.
tuple[Pos, str] setuptools._vendor.tomli._parser.parse_basic_str_escape(str src, Pos pos, *, bool multiline=False)
References setuptools._vendor.tomli._parser.parse_hex_char, setuptools._vendor.tomli._parser.skip_chars, setuptools._vendor.tomli._parser.suffixed_err.
Referenced by setuptools._vendor.tomli._parser.parse_basic_str_escape_multiline.
tuple[Pos, str] setuptools._vendor.tomli._parser.parse_basic_str_escape_multiline(str src, Pos pos)
References setuptools._vendor.tomli._parser.parse_basic_str_escape.
tuple[Pos, str] setuptools._vendor.tomli._parser.parse_hex_char(str src, Pos pos, int hex_len)
References setuptools._vendor.tomli._parser.is_unicode_scalar_value, setuptools._vendor.tomli._parser.suffixed_err.
Referenced by setuptools._vendor.tomli._parser.parse_basic_str_escape.
tuple[Pos, str] setuptools._vendor.tomli._parser.parse_literal_str(str src, Pos pos)
References setuptools._vendor.tomli._parser.skip_until.
Referenced by setuptools._vendor.tomli._parser.parse_key_part, setuptools._vendor.tomli._parser.parse_value.
tuple[Pos, str] setuptools._vendor.tomli._parser.parse_multiline_str(str src, Pos pos, *, bool literal)
References setuptools._vendor.tomli._parser.parse_basic_str, setuptools._vendor.tomli._parser.skip_until.
Referenced by setuptools._vendor.tomli._parser.parse_value.
tuple[Pos, str] setuptools._vendor.tomli._parser.parse_basic_str(str src, Pos pos, *, bool multiline)
References setuptools._vendor.tomli._parser.suffixed_err.
Referenced by setuptools._vendor.tomli._parser.parse_multiline_str, setuptools._vendor.tomli._parser.parse_one_line_basic_str.
tuple[Pos, Any] setuptools._vendor.tomli._parser.parse_value(str src, Pos pos, ParseFloat parse_float)
References setuptools._vendor.tomli._parser.parse_array, setuptools._vendor.tomli._parser.parse_inline_table, setuptools._vendor.tomli._parser.parse_literal_str, setuptools._vendor.tomli._parser.parse_multiline_str, setuptools._vendor.tomli._parser.parse_one_line_basic_str, setuptools._vendor.tomli._parser.suffixed_err.
Referenced by setuptools._vendor.tomli._parser.parse_array, setuptools._vendor.tomli._parser.parse_key_value_pair.
TOMLDecodeError setuptools._vendor.tomli._parser.suffixed_err(str src, Pos pos, str msg)
Return a `TOMLDecodeError` where error message is suffixed with coordinates in source.
Referenced by setuptools._vendor.tomli._parser.create_dict_rule, setuptools._vendor.tomli._parser.create_list_rule, setuptools._vendor.tomli._parser.key_value_rule, setuptools._vendor.tomli._parser.loads, setuptools._vendor.tomli._parser.parse_array, setuptools._vendor.tomli._parser.parse_basic_str, setuptools._vendor.tomli._parser.parse_basic_str_escape, setuptools._vendor.tomli._parser.parse_hex_char, setuptools._vendor.tomli._parser.parse_inline_table, setuptools._vendor.tomli._parser.parse_key_part, setuptools._vendor.tomli._parser.parse_key_value_pair, setuptools._vendor.tomli._parser.parse_value, setuptools._vendor.tomli._parser.skip_until.
bool setuptools._vendor.tomli._parser.is_unicode_scalar_value(int codepoint)
Referenced by setuptools._vendor.tomli._parser.parse_hex_char.
ParseFloat setuptools._vendor.tomli._parser.make_safe_parse_float(ParseFloat parse_float)
A decorator to make `parse_float` safe. `parse_float` must not return dicts or lists, because these types would be mixed with parsed TOML tables and arrays, thus confusing the parser. The returned decorated callable raises `ValueError` instead of returning illegal types.
Referenced by setuptools._vendor.tomli._parser.loads.