pydantic::_internal::_signature
pydantic::_internal::_signature._HAS_DEFAULT_FACTORY
str pydantic._internal._signature._field_name_for_signature(str field_name, FieldInfo field_info)
Extract the correct name to use for the field when generating a signature. Assuming the field has a valid alias, this will return the alias. Otherwise, it will return the field name. First priority is given to the alias, then the validation_alias, then the field name. Args: field_name: The name of the field field_info: The corresponding FieldInfo object. Returns: The correct name to use when generating a signature.
Referenced by pydantic._internal._signature._generate_signature_parameters, pydantic._internal._signature._process_param_defaults.
Parameter pydantic._internal._signature._process_param_defaults(Parameter param)
Modify the signature for a parameter in a dataclass where the default value is a FieldInfo instance. Args: param (Parameter): The parameter Returns: Parameter: The custom processed parameter
References pydantic._internal._signature._field_name_for_signature.
Referenced by pydantic._internal._signature.generate_pydantic_signature.
dict[str, Parameter] pydantic._internal._signature._generate_signature_parameters(Callable[..., None] init, dict[str, FieldInfo] fields, bool validate_by_name, ExtraValues|None extra)
Generate a mapping of parameter names to Parameter objects for a pydantic BaseModel or dataclass.
References pydantic._internal._signature._field_name_for_signature.
Referenced by pydantic._internal._signature.generate_pydantic_signature.
Signature pydantic._internal._signature.generate_pydantic_signature(Callable[..., None] init, dict[str, FieldInfo] fields, bool validate_by_name, ExtraValues|None extra, bool is_dataclass=False)
Generate signature for a pydantic BaseModel or dataclass. Args: init: The class init. fields: The model fields. validate_by_name: The `validate_by_name` value of the config. extra: The `extra` value of the config. is_dataclass: Whether the model is a dataclass. Returns: The dataclass/BaseModel subclass signature.
References pydantic._internal._signature._generate_signature_parameters, pydantic._internal._signature._process_param_defaults.