pip::_vendor::pyproject_hooks::_impl
None pip._vendor.pyproject_hooks._impl.write_json(Mapping[str, Any] obj, str path, **kwargs)
Referenced by pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller._call_hook, pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller._call_hook.
Mapping[str, Any] pip._vendor.pyproject_hooks._impl.read_json(str path)
Referenced by pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller._call_hook, pip._vendor.pyproject_hooks._impl.BuildBackendHookCaller._call_hook.
None pip._vendor.pyproject_hooks._impl.default_subprocess_runner(Sequence[str] cmd, Optional[str] cwd=None, Optional[Mapping[str, str]] extra_environ=None)
The default method of calling the wrapper subprocess. This uses :func:`subprocess.check_call` under the hood.
None pip._vendor.pyproject_hooks._impl.quiet_subprocess_runner(Sequence[str] cmd, Optional[str] cwd=None, Optional[Mapping[str, str]] extra_environ=None)
Call the subprocess while suppressing output. This uses :func:`subprocess.check_output` under the hood.
str pip._vendor.pyproject_hooks._impl.norm_and_check(str source_tree, str requested)
Normalise and check a backend path. Ensure that the requested backend path is specified as a relative path, and resolves to a location under the given source tree. Return an absolute version of the requested path.
Referenced by pip._vendor.pyproject_hooks._impl.norm_and_check.
pip._vendor.pyproject_hooks._impl.write_json(obj, path, **kwargs)
pip._vendor.pyproject_hooks._impl.read_json(path)
pip._vendor.pyproject_hooks._impl.default_subprocess_runner(cmd, cwd=None, extra_environ=None)
The default method of calling the wrapper subprocess. This uses :func:`subprocess.check_call` under the hood.
pip._vendor.pyproject_hooks._impl.quiet_subprocess_runner(cmd, cwd=None, extra_environ=None)
Call the subprocess while suppressing output. This uses :func:`subprocess.check_output` under the hood.
pip._vendor.pyproject_hooks._impl.norm_and_check(source_tree, requested)
Normalise and check a backend path. Ensure that the requested backend path is specified as a relative path, and resolves to a location under the given source tree. Return an absolute version of the requested path.
References pip._vendor.pyproject_hooks._impl.norm_and_check.