pip::_vendor::urllib3::contrib::_appengine_environ
pip::_vendor::urllib3::contrib::_appengine_environ::is_appengine()
References pip._vendor.urllib3.contrib._appengine_environ.is_local_appengine, pip._vendor.urllib3.contrib._appengine_environ.is_prod_appengine.
Referenced by pip._vendor.urllib3.contrib._appengine_environ.is_appengine_sandbox.
pip::_vendor::urllib3::contrib::_appengine_environ::is_appengine_sandbox()
Reports if the app is running in the first generation sandbox. The second generation runtimes are technically still in a sandbox, but it is much less restrictive, so generally you shouldn't need to check for it. see https://cloud.google.com/appengine/docs/standard/runtimes
References pip._vendor.urllib3.contrib._appengine_environ.is_appengine.
pip::_vendor::urllib3::contrib::_appengine_environ::is_local_appengine()
Referenced by pip._vendor.urllib3.contrib._appengine_environ.is_appengine.
pip::_vendor::urllib3::contrib::_appengine_environ::is_prod_appengine()
Referenced by pip._vendor.urllib3.contrib._appengine_environ.is_appengine.
pip::_vendor::urllib3::contrib::_appengine_environ::is_prod_appengine_mvms()
Deprecated.