anyio::_core::_eventloop
str anyio::_core::_eventloop.BACKENDS
anyio::_core::_eventloop.T_Retval
anyio::_core::_eventloop.PosArgsT
anyio::_core::_eventloop.threadlocals
dict anyio::_core::_eventloop.loaded_backends
T_Retval anyio._core._eventloop.run(Callable[[Unpack[PosArgsT]], Awaitable[T_Retval]] func, *Unpack[PosArgsT] args, str backend="asyncio", dict[str, Any]|None backend_options=None)
Run the given coroutine function in an asynchronous event loop. The current thread must not be already running an event loop. :param func: a coroutine function :param args: positional arguments to ``func`` :param backend: name of the asynchronous event loop implementation – currently either ``asyncio`` or ``trio`` :param backend_options: keyword arguments to call the backend ``run()`` implementation with (documented :ref:`here <backend options>`) :return: the return value of the coroutine function :raises RuntimeError: if an asynchronous event loop is already running in this thread :raises LookupError: if the named backend is not found
References anyio._core._eventloop.get_async_backend.
None anyio._core._eventloop.sleep(float delay)
Pause the current task for the specified duration. :param delay: the duration, in seconds
References anyio._core._eventloop.get_async_backend, anyio._core._eventloop.sleep.
Referenced by anyio._core._eventloop.sleep, anyio._core._eventloop.sleep_forever, anyio._core._eventloop.sleep_until.
None anyio._core._eventloop.sleep_forever()
Pause the current task until it's cancelled. This is a shortcut for ``sleep(math.inf)``. .. versionadded:: 3.1
References anyio._core._eventloop.sleep.
None anyio._core._eventloop.sleep_until(float deadline)
Pause the current task until the given time. :param deadline: the absolute time to wake up at (according to the internal monotonic clock of the event loop) .. versionadded:: 3.1
References anyio._core._eventloop.current_time, anyio._core._eventloop.sleep.
float anyio._core._eventloop.current_time()
Return the current value of the event loop's internal clock. :return: the clock value (seconds)
References anyio._core._eventloop.current_time, anyio._core._eventloop.get_async_backend.
Referenced by anyio._core._eventloop.current_time, anyio._core._eventloop.sleep_until.
tuple[str, ...] anyio._core._eventloop.get_all_backends()
Return a tuple of the names of all built-in backends.
type[BaseException] anyio._core._eventloop.get_cancelled_exc_class()
Return the current async library's cancellation exception class.
References anyio._core._eventloop.get_async_backend.
Generator[Any, None, None] anyio._core._eventloop.claim_worker_thread(type[AsyncBackend] backend_class, object token)
type[AsyncBackend] anyio._core._eventloop.get_async_backend(str|None asynclib_name=None)
Referenced by anyio._core._eventloop.current_time, anyio._core._eventloop.get_cancelled_exc_class, anyio._core._eventloop.run, anyio._core._eventloop.sleep.