pip::_internal::utils::virtualenv
pip::_internal::utils::virtualenv.logger
pip::_internal::utils::virtualenv._INCLUDE_SYSTEM_SITE_PACKAGES_REGEX
bool pip::_internal::utils::virtualenv::_running_under_venv()
Checks if sys.base_prefix and sys.prefix match. This handles PEP 405 compliant virtual environments.
Referenced by pip._internal.utils.virtualenv.running_under_virtualenv, pip._internal.utils.virtualenv.virtualenv_no_global.
bool pip::_internal::utils::virtualenv::_running_under_legacy_virtualenv()
Checks if sys.real_prefix is set. This handles virtual environments created with pypa's virtualenv.
Referenced by pip._internal.utils.virtualenv.running_under_virtualenv, pip._internal.utils.virtualenv.virtualenv_no_global.
bool pip::_internal::utils::virtualenv::running_under_virtualenv()
True if we're running inside a virtual environment, False otherwise.
References pip._internal.utils.virtualenv._running_under_legacy_virtualenv, pip._internal.utils.virtualenv._running_under_venv.
list[str] | None pip._internal.utils.virtualenv._get_pyvenv_cfg_lines()
Reads {sys.prefix}/pyvenv.cfg and returns its contents as list of lines Returns None, if it could not read/access the file.
Referenced by pip._internal.utils.virtualenv._no_global_under_venv.
bool pip::_internal::utils::virtualenv::_no_global_under_venv()
Check `{sys.prefix}/pyvenv.cfg` for system site-packages inclusion PEP 405 specifies that when system site-packages are not supposed to be visible from a virtual environment, `pyvenv.cfg` must contain the following line: include-system-site-packages = false Additionally, log a warning if accessing the file fails.
References pip._internal.utils.virtualenv._get_pyvenv_cfg_lines.
Referenced by pip._internal.utils.virtualenv.virtualenv_no_global.
bool pip::_internal::utils::virtualenv::_no_global_under_legacy_virtualenv()
Check if "no-global-site-packages.txt" exists beside site.py This mirrors logic in pypa/virtualenv for determining whether system site-packages are visible in the virtual environment.
Referenced by pip._internal.utils.virtualenv.virtualenv_no_global.
bool pip::_internal::utils::virtualenv::virtualenv_no_global()
Returns a boolean, whether running in venv with no system site-packages.
References pip._internal.utils.virtualenv._no_global_under_legacy_virtualenv, pip._internal.utils.virtualenv._no_global_under_venv, pip._internal.utils.virtualenv._running_under_legacy_virtualenv, pip._internal.utils.virtualenv._running_under_venv.