pip::_vendor::packaging::specifiers
pip::_vendor::packaging::specifiers.UnparsedVersion
pip::_vendor::packaging::specifiers.UnparsedVersionVar
pip::_vendor::packaging::specifiers.CallableOperator
pip::_vendor::packaging::specifiers._prefix_regex
pip::_vendor::packaging::specifiers.ParsedVersion
pip::_vendor::packaging::specifiers.VersionTypeVar
Version pip._vendor.packaging.specifiers._coerce_version(UnparsedVersion version)
Referenced by pip._vendor.packaging.specifiers.SpecifierSet.filter.
list[str] pip._vendor.packaging.specifiers._version_split(str version)
Split version into components. The split components are intended for version comparison. The logic does not attempt to retain the original version string, so joining the components back with :func:`_version_join` may not produce the original version string.
Referenced by pip._vendor.packaging.specifiers.Specifier._compare_compatible, pip._vendor.packaging.specifiers.Specifier._compare_compatible, pip._vendor.packaging.specifiers.Specifier._compare_equal, pip._vendor.packaging.specifiers.Specifier._compare_equal.
str pip._vendor.packaging.specifiers._version_join(list[str] components)
Join split version components into a version string. This function assumes the input came from :func:`_version_split`, where the first component must be the epoch (either empty or numeric), and all other components numeric.
Referenced by pip._vendor.packaging.specifiers.Specifier._compare_compatible.
bool pip::_vendor::packaging::specifiers::_is_not_suffix(str segment)
tuple[list[str], list[str]] pip._vendor.packaging.specifiers._pad_version(list[str] left, list[str] right)
Referenced by pip._vendor.packaging.specifiers.Specifier._compare_equal, pip._vendor.packaging.specifiers.Specifier._compare_equal.
Callable[["Specifier", ParsedVersion, str], bool] pip._vendor.packaging.specifiers._require_version_compare(Callable[["Specifier", ParsedVersion, str], bool] fn)
Tuple[List[str], List[str]] pip._vendor.packaging.specifiers._pad_version(List[str] left, List[str] right)