pydantic::json_schema
pydantic::json_schema.CoreSchemaOrFieldType
pydantic::json_schema.JsonSchemaValue
pydantic::json_schema.JsonSchemaMode
dict pydantic::json_schema._MODE_TITLE_MAPPING
pydantic::json_schema.JsonSchemaWarningKind
pydantic::json_schema.NoDefault
str pydantic::json_schema.DEFAULT_REF_TEMPLATE
A sentinel value used to indicate that no default value should be used when generating a JSON Schema for a core schema with a default value.
pydantic::json_schema.CoreRef
The default format string used to generate reference names.
Referenced by pydantic.json_schema.GenerateJsonSchema.definition_ref_schema, pydantic.json_schema.GenerateJsonSchema.definitions_schema, pydantic.json_schema.GenerateJsonSchema.generate_inner.
pydantic::json_schema.DefsRef
Referenced by pydantic.json_schema.GenerateJsonSchema.get_defs_ref, pydantic.json_schema._DefinitionsRemapping.remap_json_schema.
pydantic::json_schema.JsonRef
Referenced by pydantic.json_schema.GenerateJsonSchema._build_definitions_remapping, pydantic.json_schema._get_all_json_refs, pydantic.json_schema.GenerateJsonSchema.generate_inner, pydantic.json_schema.GenerateJsonSchema.get_cache_defs_ref_schema, pydantic.json_schema.GenerateJsonSchema.get_json_ref_counts, pydantic.json_schema.GenerateJsonSchema.handle_ref_overrides, pydantic.json_schema._DefinitionsRemapping.remap_json_schema, pydantic.json_schema.GenerateJsonSchema.resolve_ref_schema.
pydantic::json_schema.CoreModeRef
pydantic::json_schema.JsonSchemaKeyT
tuple pydantic::json_schema._PRIMITIVE_JSON_SCHEMA_TYPES
TypeAlias pydantic::json_schema._HashableJsonValue
pydantic::json_schema.AnyType
pydantic::json_schema.SkipJsonSchema
dict[str, Any] pydantic.json_schema.model_json_schema(type[BaseModel]|type[PydanticDataclass] cls, bool by_alias=True, str ref_template=DEFAULT_REF_TEMPLATE, Literal['any_of', 'primitive_type_array'] union_format='any_of', type[GenerateJsonSchema] schema_generator=GenerateJsonSchema, JsonSchemaMode mode='validation')
Utility function to generate a JSON Schema for a model. Args: cls: The model class to generate a JSON Schema for. by_alias: If `True` (the default), fields will be serialized according to their alias. If `False`, fields will be serialized according to their attribute name. ref_template: The template to use for generating JSON Schema references. union_format: The format to use when combining schemas from unions together. Can be one of: - `'any_of'`: Use the [`anyOf`](https://json-schema.org/understanding-json-schema/reference/combining#anyOf) keyword to combine schemas (the default). - `'primitive_type_array'`: Use the [`type`](https://json-schema.org/understanding-json-schema/reference/type) keyword as an array of strings, containing each type of the combination. If any of the schemas is not a primitive type (`string`, `boolean`, `null`, `integer` or `number`) or contains constraints/metadata, falls back to `any_of`. schema_generator: The class to use for generating the JSON Schema. mode: The mode to use for generating the JSON Schema. It can be one of the following: - 'validation': Generate a JSON Schema for validating data. - 'serialization': Generate a JSON Schema for serializing data. Returns: The generated JSON Schema.
tuple[dict[tuple[type[BaseModel] | type[PydanticDataclass], JsonSchemaMode], JsonSchemaValue], JsonSchemaValue] pydantic.json_schema.models_json_schema(Sequence[tuple[type[BaseModel]|type[PydanticDataclass], JsonSchemaMode]] models, *, bool by_alias=True, str|None title=None, str|None description=None, str ref_template=DEFAULT_REF_TEMPLATE, Literal['any_of', 'primitive_type_array'] union_format='any_of', type[GenerateJsonSchema] schema_generator=GenerateJsonSchema)
Utility function to generate a JSON Schema for multiple models. Args: models: A sequence of tuples of the form (model, mode). by_alias: Whether field aliases should be used as keys in the generated JSON Schema. title: The title of the generated JSON Schema. description: The description of the generated JSON Schema. ref_template: The reference template to use for generating JSON Schema references. union_format: The format to use when combining schemas from unions together. Can be one of: - `'any_of'`: Use the [`anyOf`](https://json-schema.org/understanding-json-schema/reference/combining#anyOf) keyword to combine schemas (the default). - `'primitive_type_array'`: Use the [`type`](https://json-schema.org/understanding-json-schema/reference/type) keyword as an array of strings, containing each type of the combination. If any of the schemas is not a primitive type (`string`, `boolean`, `null`, `integer` or `number`) or contains constraints/metadata, falls back to `any_of`. schema_generator: The schema generator to use for generating the JSON Schema. Returns: A tuple where: - The first element is a dictionary whose keys are tuples of JSON schema key type and JSON mode, and whose values are the JSON schema corresponding to that pair of inputs. (These schemas may have JsonRef references to definitions that are defined in the second returned element.) - The second element is a JSON schema containing all definitions referenced in the first returned element, along with the optional title and description keys.
list[JsonDict] pydantic.json_schema._deduplicate_schemas(Iterable[JsonDict] schemas)
References pydantic.json_schema._make_json_hashable.
Referenced by pydantic.json_schema._DefinitionsRemapping.from_prioritized_choices, pydantic.json_schema.GenerateJsonSchema.get_flattened_anyof, pydantic.json_schema.GenerateJsonSchema.tagged_union_schema.
_HashableJsonValue pydantic.json_schema._make_json_hashable(JsonValue value)
References pydantic.json_schema._make_json_hashable.
Referenced by pydantic.json_schema._deduplicate_schemas, pydantic.json_schema._make_json_hashable.
set[JsonRef] pydantic.json_schema._get_all_json_refs(Any item)
Get all the definitions references from a JSON schema.
References pydantic.json_schema.JsonRef.
Referenced by pydantic.json_schema.GenerateJsonSchema._garbage_collect_definitions.
ConfigDict pydantic.json_schema._get_typed_dict_config(type[Any]|None cls)
Referenced by pydantic.json_schema.GenerateJsonSchema.typed_dict_schema.
core_schema.PlainSerializerFunctionSerSchema | None pydantic.json_schema._get_ser_schema_for_default_value(CoreSchema schema)
Get a `'function-plain'` serialization schema that can be used to serialize a default value. This takes into account having the serialization schema nested under validation schema(s).
References pydantic.json_schema._get_ser_schema_for_default_value.
Referenced by pydantic.json_schema._get_ser_schema_for_default_value, pydantic.json_schema.GenerateJsonSchema.default_schema.