fastapi::utils
tuple fastapi::utils._CLONED_TYPES_CACHE
tuple fastapi::utils._invalid_args_message
bool fastapi.utils.is_body_allowed_for_status_code(Union[int, str, None] status_code)
Set[str] fastapi.utils.get_path_param_names(str path)
ModelField fastapi.utils.create_model_field(str name, Any type_, Optional[Dict[str, Validator]] class_validators=None, Optional[Any] default=Undefined, Union[bool, UndefinedType] required=Undefined, Union[Type[BaseConfig], None] model_config=None, Optional[FieldInfo] field_info=None, Optional[str] alias=None, Literal["validation", "serialization"] mode="validation", Literal["1", "auto"] version="auto")
Referenced by fastapi.utils.create_cloned_field.
ModelField fastapi.utils.create_cloned_field(ModelField field, *, Optional[MutableMapping[Type[BaseModel], Type[BaseModel]]] cloned_types=None)
References fastapi.utils.create_cloned_field, fastapi.utils.create_model_field.
Referenced by fastapi.utils.create_cloned_field.
str fastapi.utils.generate_operation_id_for_path(*, str name, str path, str method)
str fastapi.utils.generate_unique_id("APIRoute" route)
None fastapi.utils.deep_dict_update(Dict[Any, Any] main_dict, Dict[Any, Any] update_dict)
References fastapi.utils.deep_dict_update.
Referenced by fastapi.utils.deep_dict_update.
Union[DefaultPlaceholder, DefaultType] fastapi.utils.get_value_or_default(Union[DefaultPlaceholder, DefaultType] first_item, *Union[DefaultPlaceholder, DefaultType] extra_items)
Pass items or `DefaultPlaceholder`s by descending priority. The first one to _not_ be a `DefaultPlaceholder` will be returned. Otherwise, the first item (a `DefaultPlaceholder`) will be returned.