pip::_internal::commands::install
pip::_internal::commands::install.logger
list[str] pip._internal.commands.install.get_lib_location_guesses(bool user=False, str|None home=None, str|None root=None, bool isolated=False, str|None prefix=None)
Referenced by pip._internal.commands.install.InstallCommand.run, pip._internal.commands.install.InstallCommand.run, pip._internal.commands.install.site_packages_writable, pip._internal.commands.install.site_packages_writable.
bool pip._internal.commands.install.site_packages_writable(str|None root, bool isolated)
References pip._internal.commands.install.get_lib_location_guesses.
Referenced by pip._internal.commands.install.decide_user_install, pip._internal.commands.install.decide_user_install.
bool pip._internal.commands.install.decide_user_install(bool|None use_user_site, str|None prefix_path=None, str|None target_dir=None, str|None root_path=None, bool isolated_mode=False)
Determine whether to do a user install based on the input options. If use_user_site is False, no additional checks are done. If use_user_site is True, it is checked for compatibility with other options. If use_user_site is None, the default behaviour depends on the environment, which is provided by the other arguments.
References pip._internal.commands.install.site_packages_writable.
Referenced by pip._internal.commands.install.InstallCommand.run, pip._internal.commands.install.InstallCommand.run.
str pip::_internal::commands::install::create_os_error_message(OSError error, bool show_traceback, bool using_user_site)
Format an error message for an OSError It may occur anytime during the execution of the install command.
Referenced by pip._internal.commands.install.InstallCommand.run, pip._internal.commands.install.InstallCommand.run.
List[str] pip._internal.commands.install.get_lib_location_guesses(bool user=False, Optional[str] home=None, Optional[str] root=None, bool isolated=False, Optional[str] prefix=None)
bool pip._internal.commands.install.site_packages_writable(Optional[str] root, bool isolated)
References pip._internal.commands.install.get_lib_location_guesses.
bool pip._internal.commands.install.decide_user_install(Optional[bool] use_user_site, Optional[str] prefix_path=None, Optional[str] target_dir=None, Optional[str] root_path=None, bool isolated_mode=False)
Determine whether to do a user install based on the input options. If use_user_site is False, no additional checks are done. If use_user_site is True, it is checked for compatibility with other options. If use_user_site is None, the default behaviour depends on the environment, which is provided by the other arguments.
References pip._internal.commands.install.site_packages_writable.