pkg_resources::_vendor::packaging::_musllinux
pkg_resources::_vendor::packaging::_musllinux.plat
pkg_resources::_vendor::packaging::_musllinux.end
pkg_resources::_vendor::packaging::_musllinux.t
Tuple[int, ...] pkg_resources._vendor.packaging._musllinux._read_unpacked(IO[bytes] f, str fmt)
Referenced by pkg_resources._vendor.packaging._musllinux._parse_ld_musl_from_elf.
Optional[str] pkg_resources._vendor.packaging._musllinux._parse_ld_musl_from_elf(IO[bytes] f)
Detect musl libc location by parsing the Python executable. Based on: https://gist.github.com/lyssdod/f51579ae8d93c8657a5564aefc2ffbca ELF header: https://refspecs.linuxfoundation.org/elf/gabi4+/ch4.eheader.html
References pkg_resources._vendor.packaging._musllinux._read_unpacked.
Referenced by pkg_resources._vendor.packaging._musllinux._get_musl_version.
Optional[_MuslVersion] pkg_resources._vendor.packaging._musllinux._parse_musl_version(str output)
Referenced by pkg_resources._vendor.packaging._musllinux._get_musl_version.
Optional[_MuslVersion] pkg_resources._vendor.packaging._musllinux._get_musl_version(str executable)
Detect currently-running musl runtime version. This is done by checking the specified executable's dynamic linking information, and invoking the loader to parse its output for a version string. If the loader is musl, the output would be something like:: musl libc (x86_64) Version 1.2.2 Dynamic Program Loader
References pkg_resources._vendor.packaging._musllinux._parse_ld_musl_from_elf, pkg_resources._vendor.packaging._musllinux._parse_musl_version.
Referenced by pkg_resources._vendor.packaging._musllinux.platform_tags.
Iterator[str] pkg_resources._vendor.packaging._musllinux.platform_tags(str arch)
Generate musllinux tags compatible to the current platform. :param arch: Should be the part of platform tag after the ``linux_`` prefix, e.g. ``x86_64``. The ``linux_`` prefix is assumed as a prerequisite for the current platform to be musllinux-compatible. :returns: An iterator of compatible musllinux tags.
References pkg_resources._vendor.packaging._musllinux._get_musl_version.