pip::_vendor::resolvelib::resolvers::resolution
float pip::_vendor::resolvelib::resolvers::resolution._OPTIMISTIC_BACKJUMPING_RATIO
Result[RT, CT, KT] pip._vendor.resolvelib.resolvers.resolution._build_result(State[RT, CT, KT] state)
References pip._vendor.resolvelib.resolvers.resolution._has_route_to_root.
Referenced by pip._vendor.resolvelib.resolvers.resolution.Resolver.resolve, pip._vendor.resolvelib.resolvers.Resolver.resolve.
bool pip._vendor.resolvelib.resolvers.resolution._has_route_to_root(Mapping[KT, Criterion[RT, CT]] criteria, KT|None key, dict[int, KT|None] all_keys, set[KT|None] connected)
References pip._vendor.resolvelib.resolvers.resolution._has_route_to_root.
Referenced by pip._vendor.resolvelib.resolvers.resolution._build_result, pip._vendor.resolvelib.resolvers.resolution._has_route_to_root.