pydantic::_internal::_typing_extra
pydantic::_internal::_typing_extra.NoneType
pydantic::_internal::_typing_extra.EllipsisType
pydantic::_internal::_typing_extra._t_annotated
pydantic::_internal::_typing_extra._te_annotated
pydantic::_internal::_typing_extra._classvar_re
pydantic::_internal::_typing_extra._t_final
pydantic::_internal::_typing_extra._te_final
tuple pydantic::_internal::_typing_extra._NONE_TYPES
pydantic::_internal::_typing_extra.origin_is_union
tuple pydantic::_internal::_typing_extra::WithArgsTypes
Any pydantic::_internal::_typing_extra.typing_base
pydantic::_internal::_typing_extra._make_forward_ref
Referenced by pydantic._internal._typing_extra._type_convert, pydantic._internal._typing_extra.get_function_type_hints, pydantic._internal._typing_extra.get_type_hints.
pydantic::_internal::_typing_extra.get_type_hints
bool pydantic._internal._typing_extra.is_annotated(Any tp)
Return whether the provided argument is a `Annotated` special form. ```python {test="skip" lint="skip"} is_annotated(Annotated[int, ...]) #> True ```
Any | None pydantic._internal._typing_extra.annotated_type(Any tp)
Return the type of the `Annotated` special form, or `None`.
Any | None pydantic._internal._typing_extra.unpack_type(Any tp)
Return the type wrapped by the `Unpack` special form, or `None`.
bool pydantic._internal._typing_extra.is_hashable(Any tp)
Return whether the provided argument is the `Hashable` class. ```python {test="skip" lint="skip"} is_hashable(Hashable) #> True ```
bool pydantic._internal._typing_extra.is_callable(Any tp)
Return whether the provided argument is a `Callable`, parametrized or not. ```python {test="skip" lint="skip"} is_callable(Callable[[int], str]) #> True is_callable(typing.Callable) #> True is_callable(collections.abc.Callable) #> True ```
bool pydantic._internal._typing_extra.is_classvar_annotation(Any tp)
Return whether the provided argument represents a class variable annotation. Although not explicitly stated by the typing specification, `ClassVar` can be used inside `Annotated` and as such, this function checks for this specific scenario. Because this function is used to detect class variables before evaluating forward references (or because evaluation failed), we also implement a naive regex match implementation. This is required because class variables are inspected before fields are collected, so we try to be as accurate as possible.
bool pydantic._internal._typing_extra.is_finalvar(Any tp)
Return whether the provided argument is a `Final` special form, parametrized or not. ```python {test="skip" lint="skip"} is_finalvar(Final[int]) #> True is_finalvar(Final) #> True
bool pydantic._internal._typing_extra.is_none_type(Any tp)
Return whether the argument represents the `None` type as part of an annotation. ```python {test="skip" lint="skip"} is_none_type(None) #> True is_none_type(NoneType) #> True is_none_type(Literal[None]) #> True is_none_type(type[None]) #> False
bool pydantic._internal._typing_extra.is_namedtuple(Any tp)
Return whether the provided argument is a named tuple class. The class can be created using `typing.NamedTuple` or `collections.namedtuple`. Parametrized generic classes are *not* assumed to be named tuples.
bool pydantic._internal._typing_extra.is_generic_alias(Any tp)
dict[str, Any] | None pydantic._internal._typing_extra.parent_frame_namespace(*, int parent_depth=2, bool force=False)
Annotation evaluations functions:
Fetch the local namespace of the parent frame where this function is called. Using this function is mostly useful to resolve forward annotations pointing to members defined in a local namespace, such as assignments inside a function. Using the standard library tools, it is currently not possible to resolve such annotations: ```python {lint="skip" test="skip"} from typing import get_type_hints def func() -> None: Alias = int class C: a: 'Alias' # Raises a `NameError: 'Alias' is not defined` get_type_hints(C) ``` Pydantic uses this function when a Pydantic model is being defined to fetch the parent frame locals. However, this only allows us to fetch the parent frame namespace and not other parents (e.g. a model defined in a function, itself defined in another function). Inspecting the next outer frames (using `f_back`) is not reliable enough (see https://discuss.python.org/t/20659). Because this function is mostly used to better resolve forward annotations, nothing is returned if the parent frame's code object is defined at the module level. In this case, the locals of the frame will be the same as the module globals where the class is defined (see `_namespace_utils.get_module_ns_of`). However, if you still want to fetch the module globals (e.g. when rebuilding a model, where the frame where the rebuild call is performed might contain members that you want to use for forward annotations evaluation), you can use the `force` parameter. Args: parent_depth: The depth at which to get the frame. Defaults to 2, meaning the parent frame where this function is called will be used. force: Whether to always return the frame locals, even if the frame's code object is defined at the module level. Returns: The locals of the namespace, or `None` if it was skipped as per the described logic.
Any pydantic._internal._typing_extra._type_convert(Any arg)
Convert `None` to `NoneType` and strings to `ForwardRef` instances. This is a backport of the private `typing._type_convert` function. When evaluating a type, `ForwardRef._evaluate` ends up being called, and is responsible for making this conversion. However, we still have to apply it for the first argument passed to our type evaluation functions, similarly to the `typing.get_type_hints` function.
References pydantic._internal._typing_extra._make_forward_ref.
Referenced by pydantic._internal._typing_extra.eval_type, pydantic._internal._typing_extra.try_eval_type.
dict[str, Any] pydantic._internal._typing_extra.safe_get_annotations(type[Any] cls)
Get the annotations for the provided class, accounting for potential deferred forward references. Starting with Python 3.14, accessing the `__annotations__` attribute might raise a `NameError` if a referenced symbol isn't defined yet. In this case, we return the annotation in the *forward ref* format.
Referenced by pydantic._internal._typing_extra.get_cls_type_hints, pydantic._internal._typing_extra.get_model_type_hints.
dict[str, tuple[Any, bool]] pydantic._internal._typing_extra.get_model_type_hints(type[BaseModel] obj, *, NsResolver|None ns_resolver=None)
Collect annotations from a Pydantic model class, including those from parent classes. Args: obj: The Pydantic model to inspect. ns_resolver: A namespace resolver instance to use. Defaults to an empty instance. Returns: A dictionary mapping annotation names to a two-tuple: the first element is the evaluated type or the original annotation if a `NameError` occurred, the second element is a boolean indicating if whether the evaluation succeeded.
References pydantic._internal._typing_extra.safe_get_annotations, pydantic._internal._typing_extra.try_eval_type.
dict[str, Any] pydantic._internal._typing_extra.get_cls_type_hints(type[Any] obj, *, NsResolver|None ns_resolver=None)
Collect annotations from a class, including those from parent classes. Args: obj: The class to inspect. ns_resolver: A namespace resolver instance to use. Defaults to an empty instance.
References pydantic._internal._typing_extra.eval_type, pydantic._internal._typing_extra.safe_get_annotations.
tuple[Any, bool] pydantic._internal._typing_extra.try_eval_type(Any value, GlobalsNamespace|None globalns=None, MappingNamespace|None localns=None)
Try evaluating the annotation using the provided namespaces. Args: value: The value to evaluate. If `None`, it will be replaced by `type[None]`. If an instance of `str`, it will be converted to a `ForwardRef`. localns: The global namespace to use during annotation evaluation. globalns: The local namespace to use during annotation evaluation. Returns: A two-tuple containing the possibly evaluated type and a boolean indicating whether the evaluation succeeded or not.
References pydantic._internal._typing_extra._type_convert, pydantic._internal._typing_extra.eval_type_backport.
Referenced by pydantic._internal._typing_extra.eval_type_lenient, pydantic._internal._typing_extra.get_model_type_hints.
Any pydantic._internal._typing_extra.eval_type(Any value, GlobalsNamespace|None globalns=None, MappingNamespace|None localns=None)
Evaluate the annotation using the provided namespaces. Args: value: The value to evaluate. If `None`, it will be replaced by `type[None]`. If an instance of `str`, it will be converted to a `ForwardRef`. localns: The global namespace to use during annotation evaluation. globalns: The local namespace to use during annotation evaluation.
References pydantic._internal._typing_extra._type_convert, pydantic._internal._typing_extra.eval_type_backport.
Referenced by pydantic._internal._typing_extra.get_cls_type_hints.
Any pydantic._internal._typing_extra.eval_type_lenient(Any value, GlobalsNamespace|None globalns=None, MappingNamespace|None localns=None)
References pydantic._internal._typing_extra.try_eval_type.
Any pydantic._internal._typing_extra.eval_type_backport(Any value, GlobalsNamespace|None globalns=None, MappingNamespace|None localns=None, tuple[Any,...]|None type_params=None)
An enhanced version of `typing._eval_type` which will fall back to using the `eval_type_backport` package if it's installed to let older Python versions use newer typing constructs. Specifically, this transforms `X | Y` into `typing.Union[X, Y]` and `list[X]` into `typing.List[X]` (as well as all the types made generic in PEP 585) if the original syntax is not supported in the current Python version. This function will also display a helpful error if the value passed fails to evaluate.
References pydantic._internal._typing_extra._eval_type_backport.
Referenced by pydantic._internal._typing_extra._eval_type_backport, pydantic._internal._typing_extra.eval_type, pydantic._internal._typing_extra.get_function_type_hints, pydantic._internal._typing_extra.get_type_hints, pydantic._internal._typing_extra.try_eval_type.
Any pydantic._internal._typing_extra._eval_type_backport(Any value, GlobalsNamespace|None globalns=None, MappingNamespace|None localns=None, tuple[Any,...]|None type_params=None)
References pydantic._internal._typing_extra._eval_type, pydantic._internal._typing_extra.eval_type_backport, pydantic._internal._typing_extra.is_backport_fixable_error.
Referenced by pydantic._internal._typing_extra.eval_type_backport.
Any pydantic._internal._typing_extra._eval_type(Any value, GlobalsNamespace|None globalns=None, MappingNamespace|None localns=None, tuple[Any,...]|None type_params=None)
Referenced by pydantic._internal._typing_extra._eval_type_backport.
bool pydantic._internal._typing_extra.is_backport_fixable_error(TypeError e)
Referenced by pydantic._internal._typing_extra._eval_type_backport.
dict[str, Any] pydantic._internal._typing_extra.get_function_type_hints(Callable[..., Any] function, *, set[str]|None include_keys=None, GlobalsNamespace|None globalns=None, MappingNamespace|None localns=None)
Return type hints for a function. This is similar to the `typing.get_type_hints` function, with a few differences: - Support `functools.partial` by using the underlying `func` attribute. - Do not wrap type annotation of a parameter with `Optional` if it has a default value of `None` (related bug: https://github.com/python/cpython/issues/90353, only fixed in 3.11+).
References pydantic._internal._typing_extra._make_forward_ref, pydantic._internal._typing_extra.eval_type_backport.
typing.ForwardRef pydantic._internal._typing_extra._make_forward_ref(Any arg, bool is_argument=True, *, bool is_class=False)
Wrapper for ForwardRef that accounts for the `is_class` argument missing in older versions. The `module` argument is omitted as it breaks <3.9.8, =3.10.0 and isn't used in the calls below. See https://github.com/python/cpython/pull/28560 for some background. The backport happened on 3.9.8, see: https://github.com/pydantic/pydantic/discussions/6244#discussioncomment-6275458, and on 3.10.1 for the 3.10 branch, see: https://github.com/pydantic/pydantic/issues/6912 Implemented as EAFP with memory.
dict[str, Any] pydantic._internal._typing_extra.get_type_hints(Any obj, dict[str, Any]|None globalns=None, dict[str, Any]|None localns=None, bool include_extras=False)
Taken verbatim from python 3.10.8 unchanged, except: * type annotations of the function definition above. * prefixing `typing.` where appropriate * Use `_make_forward_ref` instead of `typing.ForwardRef` to handle the `is_class` argument. https://github.com/python/cpython/blob/aaaf5174241496afca7ce4d4584570190ff972fe/Lib/typing.py#L1773-L1875 DO NOT CHANGE THIS METHOD UNLESS ABSOLUTELY NECESSARY. ====================================================== Return type hints for an object. This is often the same as obj.__annotations__, but it handles forward references encoded as string literals, adds Optional[t] if a default value equal to None is set and recursively replaces all 'Annotated[T, ...]' with 'T' (unless 'include_extras=True'). The argument may be a module, class, method, or function. The annotations are returned as a dictionary. For classes, annotations include also inherited members. TypeError is raised if the argument is not of a type that can contain annotations, and an empty dictionary is returned if no annotations are present. BEWARE -- the behavior of globalns and localns is counterintuitive (unless you are familiar with how eval() and exec() work). The search order is locals first, then globals. - If no dict arguments are passed, an attempt is made to use the globals from obj (or the respective module's globals for classes), and these are also used as the locals. If the object does not appear to have globals, an empty dictionary is used. For classes, the search order is globals first then locals. - If one dict argument is passed, it is used for both globals and locals. - If two dict arguments are passed, they specify globals and locals, respectively.
References pydantic._internal._typing_extra._make_forward_ref, pydantic._internal._typing_extra.eval_type_backport.