click::shell_completion
str click::shell_completion._SOURCE_BASH
str click::shell_completion._SOURCE_ZSH
str click::shell_completion._SOURCE_FISH
click::shell_completion.ShellCompleteType
dict click::shell_completion._available_shells
int click.shell_completion.shell_complete(Command cli, cabc.MutableMapping[str, t.Any] ctx_args, str prog_name, str complete_var, str instruction)
Perform shell completion for the given CLI program. :param cli: Command being called. :param ctx_args: Extra arguments to pass to ``cli.make_context``. :param prog_name: Name of the executable in the shell. :param complete_var: Name of the environment variable that holds the completion instruction. :param instruction: Value of ``complete_var`` with the completion instruction and shell, in the form ``instruction_shell``. :return: Status code to exit with.
References click.shell_completion.get_completion_class.
ShellCompleteType click.shell_completion.add_completion_class(ShellCompleteType cls, str|None name=None)
Register a :class:`ShellComplete` subclass under the given name. The name will be provided by the completion instruction environment variable during completion. :param cls: The completion class that will handle completion for the shell. :param name: Name to register the class under. Defaults to the class's ``name`` attribute.
type[ShellComplete] | None click.shell_completion.get_completion_class(str shell)
Look up a registered :class:`ShellComplete` subclass by the name provided by the completion instruction environment variable. If the name isn't registered, returns ``None``. :param shell: Name the class is registered under.
Referenced by click.shell_completion.shell_complete.
list[str] click.shell_completion.split_arg_string(str string)
Split an argument string as with :func:`shlex.split`, but don't fail if the string is incomplete. Ignores a missing closing quote or incomplete escape sequence and uses the partial token as-is. .. code-block:: python split_arg_string("example 'my file") ["example", "my file"] split_arg_string("example my\\") ["example", "my"] :param string: String to split. .. versionchanged:: 8.2 Moved to ``shell_completion`` from ``parser``.
Referenced by click.shell_completion.BashComplete.get_completion_args, click.shell_completion.FishComplete.get_completion_args, click.shell_completion.ZshComplete.get_completion_args.
bool click.shell_completion._is_incomplete_argument(Context ctx, Parameter param)
Determine if the given parameter is an argument that can still accept values. :param ctx: Invocation context for the command represented by the parsed complete args. :param param: Argument object being checked.
Referenced by click.shell_completion._resolve_incomplete.
bool click.shell_completion._start_of_option(Context ctx, str value)
Check if the value looks like the start of an option.
Referenced by click.shell_completion._is_incomplete_option, click.shell_completion._resolve_incomplete.
bool click.shell_completion._is_incomplete_option(Context ctx, list[str] args, Parameter param)
Determine if the given parameter is an option that needs a value. :param args: List of complete args before the incomplete value. :param param: Option object being checked.
References click.shell_completion._start_of_option.
Referenced by click.shell_completion._resolve_incomplete.
Context click.shell_completion._resolve_context(Command cli, cabc.MutableMapping[str, t.Any] ctx_args, str prog_name, list[str] args)
Produce the context hierarchy starting with the command and traversing the complete arguments. This only follows the commands, it doesn't trigger input prompts or callbacks. :param cli: Command being called. :param prog_name: Name of the executable in the shell. :param args: List of complete args before the incomplete value.
Referenced by click.shell_completion.ShellComplete.get_completions.
tuple[Command | Parameter, str] click.shell_completion._resolve_incomplete(Context ctx, list[str] args, str incomplete)
Find the Click object that will handle the completion of the incomplete value. Return the object and the incomplete value. :param ctx: Invocation context for the command represented by the parsed complete args. :param args: List of complete args before the incomplete value. :param incomplete: Value being completed. May be empty.
References click.shell_completion._is_incomplete_argument, click.shell_completion._is_incomplete_option, click.shell_completion._start_of_option.
Referenced by click.shell_completion.ShellComplete.get_completions.