pip::_vendor::rich::cells
list pip::_vendor::rich::cells._SINGLE_CELL_UNICODE_RANGES
pip::_vendor::rich::cells._SINGLE_CELLS
pip::_vendor::rich::cells._is_single_cell_widths
Referenced by pip._vendor.rich.cells._get_codepoint_cell_size, pip._vendor.rich.cells.cached_cell_len, pip._vendor.rich.cells.cell_len, pip._vendor.rich.cells.set_cell_size.
int pip::_vendor::rich::cells::cached_cell_len(str text)
Get the number of cells required to display text. This method always caches, which may use up a lot of memory. It is recommended to use `cell_len` over this method. Args: text (str): Text to display. Returns: int: Get the number of cells required to display text.
References pip._vendor.rich.cells._is_single_cell_widths.
int pip::_vendor::rich::cells::cell_len(str text, Callable[[str], int] _cell_len=cached_cell_len)
Get the number of cells required to display text. Args: text (str): Text to display. Returns: int: Get the number of cells required to display text.
References pip._vendor.rich.cells._is_single_cell_widths.
Referenced by pip._vendor.rich.cells._get_codepoint_cell_size, pip._vendor.rich.cells.set_cell_size.
int pip::_vendor::rich::cells::get_character_cell_size(str character)
Get the cell size of a character. Args: character (str): A single character. Returns: int: Number of cells (0, 1 or 2) occupied by that character.
Referenced by pip._vendor.rich.cells.chop_cells.
str pip::_vendor::rich::cells::set_cell_size(str text, int total)
Set the length of a string to fit within given number of cells.
References pip._vendor.rich.cells._is_single_cell_widths, pip._vendor.rich.cells.cell_len.
Referenced by pip._vendor.rich.cells.chop_cells.
list[str] pip._vendor.rich.cells.chop_cells(str text, int width)
Split text into lines such that each line fits within the available (cell) width. Args: text: The text to fold such that it fits in the given width. width: The width available (number of cells). Returns: A list of strings such that each string in the list has cell width less than or equal to the available width.
References pip._vendor.rich.cells.chop_cells, pip._vendor.rich.cells.get_character_cell_size, pip._vendor.rich.print, pip._vendor.rich.cells.set_cell_size.
Referenced by pip._vendor.rich.cells.chop_cells.
int pip._vendor.rich.cells._get_codepoint_cell_size(int codepoint)
Get the cell size of a character. Args: codepoint (int): Codepoint of a character. Returns: int: Number of cells (0, 1 or 2) occupied by that character.
References pip._vendor.rich.cells._is_single_cell_widths, pip._vendor.rich.cells.cell_len.
List[str] pip._vendor.rich.cells.chop_cells(str text, int max_size, int position=0)
Break text in to equal (cell) length strings, returning the characters in reverse order