anyio::pytest_plugin
TestRunner anyio::pytest_plugin._current_runner
ExitStack anyio::pytest_plugin._runner_stack
int anyio::pytest_plugin._runner_leases
tuple[str, dict[str, Any]] anyio.pytest_plugin.extract_backend_and_options(object backend)
Referenced by anyio.pytest_plugin.pytest_fixture_setup, anyio.pytest_plugin.pytest_pyfunc_call.
Iterator[TestRunner] anyio.pytest_plugin.get_runner(str backend_name, dict[str, Any] backend_options)
Referenced by anyio.pytest_plugin.pytest_fixture_setup, anyio.pytest_plugin.pytest_pyfunc_call.
None anyio.pytest_plugin.pytest_addoption(pytest.Parser parser)
None anyio.pytest_plugin.pytest_configure(pytest.Config config)
Generator[Any] anyio.pytest_plugin.pytest_fixture_setup(Any fixturedef, Any request)
References anyio.pytest_plugin.extract_backend_and_options, anyio.pytest_plugin.get_runner.
None anyio.pytest_plugin.pytest_pycollect_makeitem(pytest.Module|pytest.Class collector, str name, object obj)
bool | None anyio.pytest_plugin.pytest_pyfunc_call(Any pyfuncitem)
References anyio.pytest_plugin.extract_backend_and_options, anyio.pytest_plugin.get_runner.
Any anyio.pytest_plugin.anyio_backend(Any request)
str anyio.pytest_plugin.anyio_backend_name(Any anyio_backend)
dict[str, Any] anyio.pytest_plugin.anyio_backend_options(Any anyio_backend)
FreePortFactory anyio.pytest_plugin.free_tcp_port_factory()
Referenced by anyio.pytest_plugin.free_tcp_port.
FreePortFactory anyio.pytest_plugin.free_udp_port_factory()
Referenced by anyio.pytest_plugin.free_udp_port.
int anyio.pytest_plugin.free_tcp_port(Callable[[], int] free_tcp_port_factory)
References anyio.pytest_plugin.free_tcp_port_factory.
int anyio.pytest_plugin.free_udp_port(Callable[[], int] free_udp_port_factory)
References anyio.pytest_plugin.free_udp_port_factory.