pip::_internal::operations::prepare
pip::_internal::operations::prepare.logger
BaseDistribution pip._internal.operations.prepare._get_prepared_distribution(InstallRequirement req, BuildTracker build_tracker, BuildEnvironmentInstaller build_env_installer, bool build_isolation, bool check_build_deps)
Prepare a distribution for installation.
Referenced by pip._internal.operations.prepare.RequirementPreparer._prepare_linked_requirement, pip._internal.operations.prepare.RequirementPreparer.prepare_editable_requirement.
None pip::_internal::operations::prepare::unpack_vcs_link(Link link, str location, int verbosity)
Referenced by pip._internal.operations.prepare.unpack_url, pip._internal.operations.prepare.unpack_url.
File pip._internal.operations.prepare.get_http_url(Link link, Downloader download, str|None download_dir=None, Hashes|None hashes=None)
References pip._internal.operations.prepare._check_download_dir.
Referenced by pip._internal.operations.prepare.RequirementPreparer._fetch_metadata_using_link_data_attr, pip._internal.operations.prepare.unpack_url, pip._internal.operations.prepare.unpack_url.
File pip._internal.operations.prepare.get_file_url(Link link, str|None download_dir=None, Hashes|None hashes=None)
Get file and optionally check its hash.
References pip._internal.operations.prepare._check_download_dir.
Referenced by pip._internal.operations.prepare.unpack_url, pip._internal.operations.prepare.unpack_url.
File | None pip._internal.operations.prepare.unpack_url(Link link, str location, Downloader download, int verbosity, str|None download_dir=None, Hashes|None hashes=None)
Unpack link into location, downloading if required. :param hashes: A Hashes object, one of whose embedded hashes must match, or HashMismatch will be raised. If the Hashes is empty, no matches are required, and unhashable types of requirements (like VCS ones, which would ordinarily raise HashUnsupported) are allowed.
References pip._internal.operations.prepare.get_file_url, pip._internal.operations.prepare.get_http_url, pip._internal.operations.prepare.unpack_vcs_link.
Referenced by pip._internal.operations.prepare.RequirementPreparer._prepare_linked_requirement.
str | None pip._internal.operations.prepare._check_download_dir(Link link, str download_dir, Hashes|None hashes, bool warn_on_hash_mismatch=True)
Check download_dir for previously downloaded file with correct hash If a correct file is found return its path else None
Referenced by pip._internal.operations.prepare.get_file_url, pip._internal.operations.prepare.get_file_url, pip._internal.operations.prepare.get_http_url, pip._internal.operations.prepare.get_http_url, pip._internal.operations.prepare.RequirementPreparer.prepare_linked_requirement, pip._internal.operations.prepare.RequirementPreparer.prepare_linked_requirements_more.
BaseDistribution pip._internal.operations.prepare._get_prepared_distribution(InstallRequirement req, BuildTracker build_tracker, PackageFinder finder, bool build_isolation, bool check_build_deps)
Prepare a distribution for installation.
File pip._internal.operations.prepare.get_http_url(Link link, Downloader download, Optional[str] download_dir=None, Optional[Hashes] hashes=None)
References pip._internal.operations.prepare._check_download_dir.
File pip._internal.operations.prepare.get_file_url(Link link, Optional[str] download_dir=None, Optional[Hashes] hashes=None)
Get file and optionally check its hash.
References pip._internal.operations.prepare._check_download_dir.
Optional[File] pip._internal.operations.prepare.unpack_url(Link link, str location, Downloader download, int verbosity, Optional[str] download_dir=None, Optional[Hashes] hashes=None)
Unpack link into location, downloading if required. :param hashes: A Hashes object, one of whose embedded hashes must match, or HashMismatch will be raised. If the Hashes is empty, no matches are required, and unhashable types of requirements (like VCS ones, which would ordinarily raise HashUnsupported) are allowed.
References pip._internal.operations.prepare.get_file_url, pip._internal.operations.prepare.get_http_url, pip._internal.operations.prepare.unpack_vcs_link.
Optional[str] pip._internal.operations.prepare._check_download_dir(Link link, str download_dir, Optional[Hashes] hashes, bool warn_on_hash_mismatch=True)
Check download_dir for previously downloaded file with correct hash If a correct file is found return its path else None