anyio::from_thread
anyio::from_thread.T_Retval
anyio::from_thread.T_co
anyio::from_thread.PosArgsT
EventLoopToken anyio.from_thread._token_or_error(EventLoopToken|None token)
Referenced by anyio.from_thread.run, anyio.from_thread.run_sync.
T_Retval anyio.from_thread.run(Callable[[Unpack[PosArgsT]], Awaitable[T_Retval]] func, *Unpack[PosArgsT] args, EventLoopToken|None token=None)
Call a coroutine function from a worker thread. :param func: a coroutine function :param args: positional arguments for the callable :param token: an event loop token to use to get back to the event loop thread (required if calling this function from outside an AnyIO worker thread) :return: the return value of the coroutine function :raises MissingTokenError: if no token was provided and called from outside an AnyIO worker thread :raises RunFinishedError: if the event loop tied to ``token`` is no longer running .. versionchanged:: 4.11.0 Added the ``token`` parameter.
References anyio.from_thread._token_or_error.
Referenced by starlette.middleware.wsgi.WSGIResponder.start_response, starlette.middleware.wsgi.WSGIResponder.wsgi.
T_Retval anyio.from_thread.run_sync(Callable[[Unpack[PosArgsT]], T_Retval] func, *Unpack[PosArgsT] args, EventLoopToken|None token=None)
Call a function in the event loop thread from a worker thread. :param func: a callable :param args: positional arguments for the callable :param token: an event loop token to use to get back to the event loop thread (required if calling this function from outside an AnyIO worker thread) :return: the return value of the callable :raises MissingTokenError: if no token was provided and called from outside an AnyIO worker thread :raises RunFinishedError: if the event loop tied to ``token`` is no longer running .. versionchanged:: 4.11.0 Added the ``token`` parameter.
References anyio.from_thread._token_or_error.
Generator[BlockingPortal, Any, None] anyio.from_thread.start_blocking_portal(str backend="asyncio", dict[str, Any]|None backend_options=None, *, str|None name=None)
Start a new event loop in a new thread and run a blocking portal in its main task. The parameters are the same as for :func:`~anyio.run`. :param backend: name of the backend :param backend_options: backend options :param name: name of the thread :return: a context manager that yields a blocking portal .. versionchanged:: 3.0 Usage as a context manager is now required.
Referenced by starlette.testclient.TestClient._portal_factory, starlette.testclient.TestClient.websocket_connect.
None anyio.from_thread.check_cancelled()
Check if the cancel scope of the host task's running the current worker thread has been cancelled. If the host task's current cancel scope has indeed been cancelled, the backend-specific cancellation exception will be raised. :raises RuntimeError: if the current thread was not spawned by :func:`.to_thread.run_sync`