test_datastream_service_unit
test_datastream_service_unit._make_service_for_tests()
Crea un DatastreamService aislado de archivos y hardware.
Referenced by test_datastream_exists_true_and_false, test_get_datastream_info_returns_metadata, test_send_data_calls_executor_once, test_send_data_datastream_no_existe, test_send_data_default_format_string, test_send_data_ok, test_send_data_osid_incorrecto, test_send_data_respects_datastream_format, test_send_data_response_structure, test_send_data_tipo_no_implementado.
test_datastream_service_unit.test_send_data_ok()
Caso feliz: OSID correcto, tipo=1 y datastream existente.
References _make_service_for_tests.
test_datastream_service_unit.test_send_data_osid_incorrecto()
Debe devolver error cuando el OSID no coincide.
References _make_service_for_tests.
test_datastream_service_unit.test_send_data_tipo_no_implementado()
Debe devolver error cuando tipove != 1.
References _make_service_for_tests.
test_datastream_service_unit.test_send_data_datastream_no_existe()
Debe devolver error cuando el datastream no existe en metadata.
References _make_service_for_tests.
test_datastream_service_unit.test_datastream_exists_true_and_false()
Prueba unitaria de datastream_exists para casos verdadero y falso.
References _make_service_for_tests.
test_datastream_service_unit.test_get_datastream_info_returns_metadata()
Prueba unitaria de get_datastream_info.
References _make_service_for_tests.
test_datastream_service_unit.test_send_data_default_format_string()
Si en la metadata no viene 'datastream_format', el servicio asume 'string' por defecto (según implementación real).
References _make_service_for_tests.
test_datastream_service_unit.test_send_data_respects_datastream_format()
Si en la metadata el 'datastream_format' es 'float', debe propagarse en la respuesta.
References _make_service_for_tests.
test_datastream_service_unit.test_send_data_calls_executor_once()
Verifica que get_value se llama exactamente una vez por petición.
References _make_service_for_tests.
test_datastream_service_unit.test_send_data_response_structure()
Verifica que la respuesta tenga la estructura mínima esperada.
References _make_service_for_tests.