click::formatting
int click::formatting.FORCED_WIDTH
tuple[int, ...] click.formatting.measure_table(cabc.Iterable[tuple[str, str]] rows)
Referenced by click.formatting.HelpFormatter.write_dl.
cabc.Iterator[tuple[str, ...]] click.formatting.iter_rows(cabc.Iterable[tuple[str, str]] rows, int col_count)
Referenced by click.formatting.HelpFormatter.write_dl.
str click.formatting.wrap_text(str text, int width=78, str initial_indent="", str subsequent_indent="", bool preserve_paragraphs=False)
A helper function that intelligently wraps text. By default, it assumes that it operates on a single paragraph of text but if the `preserve_paragraphs` parameter is provided it will intelligently handle paragraphs (defined by two empty lines). If paragraphs are handled, a paragraph can be prefixed with an empty line containing the ``\\b`` character (``\\x08``) to indicate that no rewrapping should happen in that block. :param text: the text that should be rewrapped. :param width: the maximum width for the text. :param initial_indent: the initial indent that should be placed on the first line as a string. :param subsequent_indent: the indent string that should be placed on each consecutive line. :param preserve_paragraphs: if this flag is set then the wrapping will intelligently handle paragraphs.
Referenced by click.formatting.HelpFormatter.write_dl, click.formatting.HelpFormatter.write_text, click.formatting.HelpFormatter.write_usage.
tuple[str, bool] click.formatting.join_options(cabc.Sequence[str] options)
Given a list of option strings this joins them in the most appropriate way and returns them in the form ``(formatted_string, any_prefix_is_slash)`` where the second item in the tuple is a flag that indicates if any of the option prefixes was a slash.