pydantic::v1::generics
pydantic::v1::generics.GenericModelT
pydantic::v1::generics.TypeVarType
pydantic::v1::generics.CacheKey
pydantic::v1::generics.Parametrization
pydantic::v1::generics.GenericTypesCache
pydantic::v1::generics.AssignedParameters
pydantic::v1::generics._generic_types_cache
pydantic::v1::generics._assigned_parameters
dict pydantic::v1::generics.DictValues
Any pydantic.v1.generics.replace_types(Any type_, Mapping[Any, Any] type_map)
Return type with all occurrences of `type_map` keys recursively replaced with their values. :param type_: Any type, class or generic alias :param type_map: Mapping from `TypeVar` instance to concrete types. :return: New type representing the basic structure of `type_` with all `typevar_map` keys recursively replaced. >>> replace_types(Tuple[str, Union[List[str], float]], {str: int}) Tuple[int, Union[List[int], float]]
References pydantic.v1.generics.replace_types.
Referenced by pydantic.v1.generics._prepare_model_fields, pydantic.v1.generics.replace_types.
None pydantic.v1.generics.check_parameters_count(Type[GenericModel] cls, Tuple[Any,...] parameters)
Iterator[TypeVarType] pydantic.v1.generics.iter_contained_typevars(Any v)
Recursively iterate through all subtypes and type args of `v` and yield any typevars that are found.
References pydantic.v1.generics.iter_contained_typevars.
Referenced by pydantic.v1.generics.iter_contained_typevars.
Tuple[Optional[str], bool] pydantic.v1.generics.get_caller_frame_info()
Used inside a function to check whether it was called globally Will only work against non-compiled code, therefore used only in pydantic.generics :returns Tuple[module_name, called_globally]
None pydantic.v1.generics._prepare_model_fields(Type[GenericModel] created_model, Mapping[str, Any] fields, Mapping[str, type] instance_type_hints, Mapping[Any, type] typevars_map)
Replace DeferredType fields with concrete type hints and prepare them.
References pydantic.v1.generics.replace_types.