pydantic::v1::mypy
str pydantic::v1::mypy.CONFIGFILE_KEY
str pydantic::v1::mypy.METADATA_KEY
pydantic::v1::mypy._NAMESPACE
str pydantic::v1::mypy.BASEMODEL_FULLNAME
str pydantic::v1::mypy.BASESETTINGS_FULLNAME
str pydantic::v1::mypy.MODEL_METACLASS_FULLNAME
str pydantic::v1::mypy.FIELD_FULLNAME
str pydantic::v1::mypy.DATACLASS_FULLNAME
Tuple[int, ...] pydantic::v1::mypy.MYPY_VERSION_TUPLE
tuple pydantic::v1::mypy.BUILTINS_NAME
pydantic::v1::mypy.ERROR_ORM
pydantic::v1::mypy.ERROR_CONFIG
pydantic::v1::mypy.ERROR_ALIAS
pydantic::v1::mypy.ERROR_UNEXPECTED
pydantic::v1::mypy.ERROR_UNTYPED
pydantic::v1::mypy.ERROR_FIELD_DEFAULTS
Tuple[int, ...] pydantic.v1.mypy.parse_mypy_version(str version)
'TypingType[Plugin]' pydantic.v1.mypy.plugin(str version)
`version` is the mypy version string We might want to use this to print a warning if the mypy version being used is newer, or especially older, than we expect (or need).
Type pydantic.v1.mypy.from_orm_callback(MethodContext ctx)
Raise an error if orm_mode is not enabled
References pydantic.v1.mypy.error_from_orm, pydantic.v1.mypy.error_unexpected_behavior, pydantic.v1.mypy.get_name.
None pydantic.v1.mypy.error_from_orm(str model_name, CheckerPluginInterface api, Context context)
Referenced by pydantic.v1.mypy.from_orm_callback.
None pydantic.v1.mypy.error_invalid_config_value(str name, SemanticAnalyzerPluginInterface api, Context context)
Referenced by pydantic.v1.mypy.PydanticModelTransformer.get_config_update.
None pydantic.v1.mypy.error_required_dynamic_aliases(SemanticAnalyzerPluginInterface api, Context context)
Referenced by pydantic.v1.mypy.PydanticModelTransformer.collect_config, pydantic.v1.mypy.PydanticModelTransformer.collect_fields.
None pydantic.v1.mypy.error_unexpected_behavior(str detail, Union[CheckerPluginInterface, SemanticAnalyzerPluginInterface] api, Context context)
Referenced by pydantic.v1.mypy.from_orm_callback, pydantic.v1.mypy.PydanticModelTransformer.set_frozen.
None pydantic.v1.mypy.error_untyped_fields(SemanticAnalyzerPluginInterface api, Context context)
Referenced by pydantic.v1.mypy.PydanticModelTransformer.collect_fields.
None pydantic.v1.mypy.error_default_and_default_factory_specified(CheckerPluginInterface api, Context context)
Referenced by pydantic.v1.mypy.PydanticPlugin._pydantic_field_callback.
None pydantic.v1.mypy.add_method(ClassDefContext ctx, str name, List[Argument] args, Type return_type, Optional[Type] self_type=None, Optional[TypeVarDef] tvar_def=None, bool is_classmethod=False, bool is_new=False)
Adds a new method to a class. This can be dropped if/when https://github.com/python/mypy/issues/7301 is merged
References pydantic.v1.mypy.get_fullname, pydantic.v1.mypy.get_name.
Referenced by pydantic.v1.mypy.PydanticModelTransformer.add_construct_method, pydantic.v1.mypy.PydanticModelTransformer.add_initializer.
str pydantic.v1.mypy.get_fullname(Union[FuncBase, SymbolNode] x)
Used for compatibility with mypy 0.740; can be dropped once support for 0.740 is dropped.
Referenced by pydantic.v1.mypy.add_method, pydantic.v1.mypy.PydanticModelTransformer.collect_config, pydantic.v1.mypy.PydanticModelTransformer.collect_fields, pydantic.v1.mypy.PydanticPlugin.get_base_class_hook, pydantic.v1.mypy.PydanticModelTransformer.set_frozen, pydantic.v1.mypy.PydanticModelTransformer.transform.
str pydantic.v1.mypy.get_name(Union[FuncBase, SymbolNode] x)
Used for compatibility with mypy 0.740; can be dropped once support for 0.740 is dropped.
Referenced by pydantic.v1.mypy.add_method, pydantic.v1.mypy.from_orm_callback, pydantic.v1.mypy.PydanticModelTransformer.set_frozen.
Optional[Dict[str, Any]] pydantic.v1.mypy.parse_toml(str config_file)