pip::_internal::metadata
pip::_internal::metadata.Protocol
bool pip::_internal::metadata::_should_use_importlib_metadata()
Whether to use the ``importlib.metadata`` or ``pkg_resources`` backend. By default, pip uses ``importlib.metadata`` on Python 3.11+, and ``pkg_resources`` otherwise. Up to Python 3.13, This can be overridden by a couple of ways: * If environment variable ``_PIP_USE_IMPORTLIB_METADATA`` is set, it dictates whether ``importlib.metadata`` is used, for Python <3.14. * On Python 3.11, 3.12 and 3.13, Python distributors can patch ``importlib.metadata`` to add a global constant ``_PIP_USE_IMPORTLIB_METADATA = False``. This makes pip use ``pkg_resources`` (unless the user set the aforementioned environment variable to *True*). On Python 3.14+, the ``pkg_resources`` backend cannot be used. Whether to use the ``importlib.metadata`` or ``pkg_resources`` backend. By default, pip uses ``importlib.metadata`` on Python 3.11+, and ``pkg_resourcess`` otherwise. This can be overridden by a couple of ways: * If environment variable ``_PIP_USE_IMPORTLIB_METADATA`` is set, it dictates whether ``importlib.metadata`` is used, regardless of Python version. * On Python 3.11+, Python distributors can patch ``importlib.metadata`` to add a global constant ``_PIP_USE_IMPORTLIB_METADATA = False``. This makes pip use ``pkg_resources`` (unless the user set the aforementioned environment variable to *True*).
Referenced by pip._internal.metadata.select_backend.
None pip._internal.metadata._emit_pkg_resources_deprecation_if_needed()
Referenced by pip._internal.metadata.select_backend.
Backend pip::_internal::metadata::select_backend()
References pip._internal.metadata._emit_pkg_resources_deprecation_if_needed, pip._internal.metadata._should_use_importlib_metadata.
Referenced by pip._internal.metadata.get_default_environment, pip._internal.metadata.get_directory_distribution, pip._internal.metadata.get_environment, pip._internal.metadata.get_environment, pip._internal.metadata.get_metadata_distribution, pip._internal.metadata.get_wheel_distribution.
BaseEnvironment pip::_internal::metadata::get_default_environment()
Get the default representation for the current environment. This returns an Environment instance from the chosen backend. The default Environment instance should be built from ``sys.path`` and may use caching to share instance state across calls. Get the default representation for the current environment. This returns an Environment instance from the chosen backend. The default Environment instance should be built from ``sys.path`` and may use caching to share instance state accorss calls.
References pip._internal.metadata.select_backend.
BaseEnvironment pip._internal.metadata.get_environment(list[str]|None paths)
Get a representation of the environment specified by ``paths``. This returns an Environment instance from the chosen backend based on the given import paths. The backend must build a fresh instance representing the state of installed distributions when this function is called.
References pip._internal.metadata.select_backend.
BaseDistribution pip::_internal::metadata::get_directory_distribution(str directory)
Get the distribution metadata representation in the specified directory. This returns a Distribution instance from the chosen backend based on the given on-disk ``.dist-info`` directory.
References pip._internal.metadata.select_backend.
BaseDistribution pip::_internal::metadata::get_wheel_distribution(Wheel wheel, str canonical_name)
Get the representation of the specified wheel's distribution metadata. This returns a Distribution instance from the chosen backend based on the given wheel's ``.dist-info`` directory. :param canonical_name: Normalized project name of the given wheel.
References pip._internal.metadata.select_backend.
BaseDistribution pip::_internal::metadata::get_metadata_distribution(bytes metadata_contents, str filename, str canonical_name)
Get the dist representation of the specified METADATA file contents. This returns a Distribution instance from the chosen backend sourced from the data in `metadata_contents`. :param metadata_contents: Contents of a METADATA file within a dist, or one served via PEP 658. :param filename: Filename for the dist this metadata represents. :param canonical_name: Normalized project name of the given dist.
References pip._internal.metadata.select_backend.
BaseEnvironment pip._internal.metadata.get_environment(Optional[List[str]] paths)
Get a representation of the environment specified by ``paths``. This returns an Environment instance from the chosen backend based on the given import paths. The backend must build a fresh instance representing the state of installed distributions when this function is called.
References pip._internal.metadata.select_backend.