pydantic::color
pydantic::color.ColorTuple
pydantic::color.ColorType
pydantic::color.HslColorTuple
str pydantic::color._r_255
str pydantic::color._r_comma
str pydantic::color._r_alpha
str pydantic::color._r_h
str pydantic::color._r_sl
str pydantic::color.r_hex_short
str pydantic::color.r_hex_long
str pydantic::color.r_rgb
str pydantic::color.r_hsl
str pydantic::color.r_rgb_v4_style
str pydantic::color.r_hsl_v4_style
dict pydantic::color.repeat_colors
int pydantic::color.rads
dict pydantic::color.COLORS_BY_NAME
dict pydantic::color.COLORS_BY_VALUE
RGBA pydantic.color.parse_tuple(tuple[Any,...] value)
Parse a tuple or list to get RGBA values. Args: value: A tuple or list. Returns: An `RGBA` tuple parsed from the input tuple. Raises: PydanticCustomError: If tuple is not valid.
References pydantic.color.parse_color_value, pydantic.color.parse_float_alpha.
RGBA pydantic.color.parse_str(str value)
Parse a string representing a color to an RGBA tuple. Possible formats for the input string include: * named color, see `COLORS_BY_NAME` * hex short eg. `<prefix>fff` (prefix can be `#`, `0x` or nothing) * hex long eg. `<prefix>ffffff` (prefix can be `#`, `0x` or nothing) * `rgb(<r>, <g>, <b>)` * `rgba(<r>, <g>, <b>, <a>)` Args: value: A string representing a color. Returns: An `RGBA` tuple parsed from the input string. Raises: ValueError: If the input string cannot be parsed to an RGBA tuple.
References pydantic.color.ints_to_rgba, pydantic.color.parse_hsl.
RGBA pydantic.color.ints_to_rgba(Union[int, str] r, Union[int, str] g, Union[int, str] b, Optional[float] alpha=None)
Converts integer or string values for RGB color and an optional alpha value to an `RGBA` object. Args: r: An integer or string representing the red color value. g: An integer or string representing the green color value. b: An integer or string representing the blue color value. alpha: A float representing the alpha value. Defaults to None. Returns: An instance of the `RGBA` class with the corresponding color and alpha values.
References pydantic.color.parse_color_value, pydantic.color.parse_float_alpha.
Referenced by pydantic.color.parse_str.
float pydantic.color.parse_color_value(Union[int, str] value, int max_val=255)
Parse the color value provided and return a number between 0 and 1. Args: value: An integer or string color value. max_val: Maximum range value. Defaults to 255. Raises: PydanticCustomError: If the value is not a valid color. Returns: A number between 0 and 1.
Referenced by pydantic.color.ints_to_rgba, pydantic.color.parse_hsl, pydantic.color.parse_tuple.
Optional[float] pydantic.color.parse_float_alpha(Union[None, str, float, int] value)
Parse an alpha value checking it's a valid float in the range 0 to 1. Args: value: The input value to parse. Returns: The parsed value as a float, or `None` if the value was None or equal 1. Raises: PydanticCustomError: If the input value cannot be successfully parsed as a float in the expected range.
Referenced by pydantic.color.ints_to_rgba, pydantic.color.parse_hsl, pydantic.color.parse_tuple.
RGBA pydantic.color.parse_hsl(str h, str h_units, str sat, str light, Optional[float] alpha=None)
Parse raw hue, saturation, lightness, and alpha values and convert to RGBA. Args: h: The hue value. h_units: The unit for hue value. sat: The saturation value. light: The lightness value. alpha: Alpha value. Returns: An instance of `RGBA`.
References pydantic.color.parse_color_value, pydantic.color.parse_float_alpha.
Referenced by pydantic.color.parse_str.
int pydantic.color.float_to_255(float c)
Converts a float value between 0 and 1 (inclusive) to an integer between 0 and 255 (inclusive). Args: c: The float value to be converted. Must be between 0 and 1 (inclusive). Returns: The integer equivalent of the given float value rounded to the nearest whole number. Raises: ValueError: If the given float value is outside the acceptable range of 0 to 1 (inclusive).
Referenced by pydantic.color.Color.as_hex, pydantic.color.Color.as_rgb_tuple.