pip::_vendor::platformdirs::android
str None pip::_vendor::platformdirs::android::_android_folder()
:return: base folder for the Android OS or None if it cannot be found
Referenced by pip._vendor.platformdirs.android.Android.user_cache_dir, pip._vendor.platformdirs.android.Android.user_config_dir, pip._vendor.platformdirs.android.Android.user_data_dir.
str pip::_vendor::platformdirs::android::_android_documents_folder()
:return: documents folder for the Android OS
Referenced by pip._vendor.platformdirs.android.Android.user_documents_dir.
str pip::_vendor::platformdirs::android::_android_downloads_folder()
:return: downloads folder for the Android OS
Referenced by pip._vendor.platformdirs.android.Android.user_downloads_dir.
str pip::_vendor::platformdirs::android::_android_pictures_folder()
:return: pictures folder for the Android OS
Referenced by pip._vendor.platformdirs.android.Android.user_pictures_dir.
str pip::_vendor::platformdirs::android::_android_videos_folder()
:return: videos folder for the Android OS
Referenced by pip._vendor.platformdirs.android.Android.user_videos_dir.
str pip::_vendor::platformdirs::android::_android_music_folder()
:return: music folder for the Android OS
Referenced by pip._vendor.platformdirs.android.Android.user_music_dir.