fastapi::routing
ASGIApp fastapi.routing.request_response(Callable[[Request], Union[Awaitable[Response], Response]] func)
Takes a function or coroutine `func(request) -> response`, and returns an ASGI application.
ASGIApp fastapi.routing.websocket_session(Callable[[WebSocket], Awaitable[None]] func)
Takes a coroutine `func(session)`, and returns an ASGI application.
Any fastapi.routing._prepare_response_content(Any res, *, bool exclude_unset, bool exclude_defaults=False, bool exclude_none=False)
References fastapi.routing._prepare_response_content.
Referenced by fastapi.routing._prepare_response_content, fastapi.routing.serialize_response.
Lifespan[Any] fastapi.routing._merge_lifespan_context(Lifespan[Any] original_context, Lifespan[Any] nested_context)
Any fastapi.routing.serialize_response(*, Optional[ModelField] field=None, Any response_content, Optional[IncEx] include=None, Optional[IncEx] exclude=None, bool by_alias=True, bool exclude_unset=False, bool exclude_defaults=False, bool exclude_none=False, bool is_coroutine=True)
References fastapi.routing._prepare_response_content.
Referenced by fastapi.routing.get_request_handler.
Any fastapi.routing.run_endpoint_function(*, Dependant dependant, Dict[str, Any] values, bool is_coroutine)
Referenced by fastapi.routing.get_request_handler.
Callable[[Request], Coroutine[Any, Any, Response]] fastapi.routing.get_request_handler(Dependant dependant, Optional[ModelField] body_field=None, Optional[int] status_code=None, Union[Type[Response], DefaultPlaceholder] response_class=Default(JSONResponse), Optional[ModelField] response_field=None, Optional[IncEx] response_model_include=None, Optional[IncEx] response_model_exclude=None, bool response_model_by_alias=True, bool response_model_exclude_unset=False, bool response_model_exclude_defaults=False, bool response_model_exclude_none=False, Optional[Any] dependency_overrides_provider=None, bool embed_body_fields=False)
References fastapi.routing.run_endpoint_function, fastapi.routing.serialize_response.
Referenced by fastapi.routing.APIRoute.get_route_handler.
Callable[[WebSocket], Coroutine[Any, Any, Any]] fastapi.routing.get_websocket_app(Dependant dependant, Optional[Any] dependency_overrides_provider=None, bool embed_body_fields=False)