pkg_resources::_vendor::importlib_resources::_legacy
pkg_resources::_vendor::importlib_resources::_legacy.Package
pkg_resources::_vendor::importlib_resources::_legacy.Resource
pkg_resources._vendor.importlib_resources._legacy.deprecated(func)
pkg_resources._vendor.importlib_resources._legacy.normalize_path(path)
Normalize a path by ensuring it is a string. If the resulting string contains path separators, an exception is raised.
Referenced by pkg_resources._vendor.importlib_resources._legacy.is_resource, pkg_resources._vendor.importlib_resources._legacy.open_binary, pkg_resources._vendor.importlib_resources._legacy.open_text, pkg_resources._vendor.importlib_resources._legacy.path, pkg_resources._vendor.importlib_resources._legacy.read_binary.
BinaryIO pkg_resources._vendor.importlib_resources._legacy.open_binary(Package package, Resource resource)
Return a file-like object opened for binary reading of the resource.
References pkg_resources._vendor.importlib_resources._legacy.normalize_path.
bytes pkg_resources._vendor.importlib_resources._legacy.read_binary(Package package, Resource resource)
Return the binary contents of the resource.
References pkg_resources._vendor.importlib_resources._legacy.normalize_path.
TextIO pkg_resources._vendor.importlib_resources._legacy.open_text(Package package, Resource resource, str encoding='utf-8', str errors='strict')
Return a file-like object opened for text reading of the resource.
References pkg_resources._vendor.importlib_resources._legacy.normalize_path.
Referenced by pkg_resources._vendor.importlib_resources._legacy.read_text.
str pkg_resources._vendor.importlib_resources._legacy.read_text(Package package, Resource resource, str encoding='utf-8', str errors='strict')
Return the decoded string of the resource. The decoding-related arguments have the same semantics as those of bytes.decode().
References pkg_resources._vendor.importlib_resources._legacy.open_text.
Iterable[str] pkg_resources._vendor.importlib_resources._legacy.contents(Package package)
Return an iterable of entries in `package`. Note that not all entries are resources. Specifically, directories are not considered resources. Use `is_resource()` on each entry returned here to check if it is a resource or not.
bool pkg_resources._vendor.importlib_resources._legacy.is_resource(Package package, str name)
True if `name` is a resource inside `package`. Directories are *not* resources.
References pkg_resources._vendor.importlib_resources._legacy.normalize_path.
ContextManager[pathlib.Path] pkg_resources._vendor.importlib_resources._legacy.path(Package package, Resource resource)
A context manager providing a file path object to the resource. If the resource does not already exist on its own on the file system, a temporary file will be created. If the file was created, the file will be deleted upon exiting the context manager (no exception is raised if the file was deleted prior to the context manager exiting).
References pkg_resources._vendor.importlib_resources._legacy.normalize_path.