fastapi::_compat::v1
fastapi::_compat::v1.PYDANTIC_VERSION_MINOR_TUPLE
int fastapi::_compat::v1.PYDANTIC_V2
Any fastapi::_compat::v1.RequiredParam
fastapi::_compat::v1.GetJsonSchemaHandler
fastapi::_compat::v1.JsonSchemaValue
fastapi::_compat::v1.CoreSchema
fastapi::_compat::v1.Url
dict fastapi::_compat::v1.sequence_shapes
dict fastapi::_compat::v1.sequence_shape_to_type
Any fastapi._compat.v1.with_info_plain_validator_function(Callable[..., Any] function, *, Union[str, None] ref=None, Any metadata=None, Any serialization=None)
Dict[str, Any] fastapi._compat.v1.get_model_definitions(*, Set[Union[Type[BaseModel], Type[Enum]]] flat_models, Dict[Union[Type[BaseModel], Type[Enum]], str] model_name_map)
Referenced by fastapi._compat.v1.get_definitions.
bool fastapi._compat.v1.is_pv1_scalar_field(ModelField field)
References fastapi._compat.v1.is_pv1_scalar_field.
Referenced by fastapi._compat.v1.is_pv1_scalar_field, fastapi._compat.v1.is_pv1_scalar_sequence_field, fastapi._compat.v1.is_scalar_field.
bool fastapi._compat.v1.is_pv1_scalar_sequence_field(ModelField field)
References fastapi._compat.v1.is_pv1_scalar_field.
Referenced by fastapi._compat.v1.is_scalar_sequence_field.
List[Dict[str, Any]] fastapi._compat.v1._normalize_errors(Sequence[Any] errors)
References fastapi._compat.v1._normalize_errors.
Referenced by fastapi._compat.v1._normalize_errors, fastapi._compat.v1._regenerate_error_with_loc.
List[Dict[str, Any]] fastapi._compat.v1._regenerate_error_with_loc(*, Sequence[Any] errors, Tuple[Union[str, int],...] loc_prefix)
References fastapi._compat.v1._normalize_errors.
None fastapi._compat.v1._model_rebuild(Type[BaseModel] model)
Any fastapi._compat.v1._model_dump(BaseModel model, Literal["json", "python"] mode="json", **Any kwargs)
Any fastapi._compat.v1._get_model_config(BaseModel model)
Dict[str, Any] fastapi._compat.v1.get_schema_from_model_field(*, ModelField field, ModelNameMap model_name_map, Dict[Tuple[ModelField, Literal["validation", "serialization"]], JsonSchemaValue] field_mapping, bool separate_input_output_schemas=True)
Tuple[ Dict[Tuple[ModelField, Literal["validation", "serialization"]], JsonSchemaValue], Dict[str, Dict[str, Any]], ] fastapi._compat.v1.get_definitions(*, List[ModelField] fields, ModelNameMap model_name_map, bool separate_input_output_schemas=True)
References fastapi._compat.v1.get_model_definitions.
bool fastapi._compat.v1.is_scalar_field(ModelField field)
References fastapi._compat.v1.is_pv1_scalar_field.
bool fastapi._compat.v1.is_sequence_field(ModelField field)
bool fastapi._compat.v1.is_scalar_sequence_field(ModelField field)
References fastapi._compat.v1.is_pv1_scalar_sequence_field.
bool fastapi._compat.v1.is_bytes_field(ModelField field)
bool fastapi._compat.v1.is_bytes_sequence_field(ModelField field)
FieldInfo fastapi._compat.v1.copy_field_info(*, FieldInfo field_info, Any annotation)
Sequence[Any] fastapi._compat.v1.serialize_sequence_value(*, ModelField field, Any value)
Dict[str, Any] fastapi._compat.v1.get_missing_field_error(Tuple[str,...] loc)
Type[BaseModel] fastapi._compat.v1.create_body_model(*, Sequence[ModelField] fields, str model_name)
List[ModelField] fastapi._compat.v1.get_model_fields(Type[BaseModel] model)