pip::_vendor::distlib::compat
pip::_vendor::distlib::compat.ssl
pip::_vendor::distlib::compat.string_types
pip::_vendor::distlib::compat.text_type
pip::_vendor::distlib::compat.raw_input
pip::_vendor::distlib::compat.filter
pip::_vendor::distlib::compat.ZipFile
pip::_vendor::distlib::compat::callable
Referenced by pip._vendor.distlib.compat.BaseConfigurator.configure_custom.
pip::_vendor::distlib::compat::fsencode
pip::_vendor::distlib::compat::fsdecode
str pip::_vendor::distlib::compat::_fsencoding
str pip::_vendor::distlib::compat::_fserrors
pip::_vendor::distlib::compat.cookie_re
pip::_vendor::distlib::compat.unescape
pip::_vendor::distlib::compat.IDENTIFIER
pip::_vendor::distlib::compat::quote(s)
pip::_vendor::distlib::compat::_dnsname_match(dn, hostname, max_wildcards=1)
Matching according to RFC 6125, section 6.4.3 http://tools.ietf.org/html/rfc6125#section-6.4.3
Referenced by pip._vendor.distlib.compat.match_hostname.
pip::_vendor::distlib::compat::match_hostname(cert, hostname)
Verify that *cert* (in decoded format as returned by SSLSocket.getpeercert()) matches the *hostname*. RFC 2818 and RFC 6125 rules are followed, but IP addresses are not accepted for *hostname*. CertificateError is raised on failure. On success, the function returns nothing.
References pip._vendor.distlib.compat._dnsname_match.
pip::_vendor::distlib::compat::which(cmd, mode=os.F_OK|os.X_OK, path=None)
Given a command, mode, and a PATH string, return the path which conforms to the given mode on the PATH, or None if there is no such file. `mode` defaults to os.F_OK | os.X_OK. `path` defaults to the result of os.environ.get("PATH"), or can be overridden with a custom search path.
pip::_vendor::distlib::compat::python_implementation()
Return a string identifying the Python implementation.
pip._vendor.distlib.compat.callable(obj)
pip._vendor.distlib.compat.fsencode(filename)
pip._vendor.distlib.compat.fsdecode(filename)
pip::_vendor::distlib::compat::_get_normal_name(orig_enc)
Imitates get_normal_name in tokenizer.c.
Referenced by pip._vendor.distlib.compat.detect_encoding, pip._vendor.distlib.compat.ZipFile.open.
pip::_vendor::distlib::compat::detect_encoding(readline)
The detect_encoding() function is used to detect the encoding that should be used to decode a Python source file. It requires one argument, readline, in the same way as the tokenize() generator. It will call readline a maximum of twice, and return the encoding used (as a string) and a list of any lines (left as bytes) it has read in. It detects the encoding from the presence of a utf-8 bom or an encoding cookie as specified in pep-0263. If both a bom and a cookie are present, but disagree, a SyntaxError will be raised. If the encoding cookie is an invalid charset, raise a SyntaxError. Note that if a utf-8 bom is found, 'utf-8-sig' is returned. If no encoding is specified, then the default of 'utf-8' will be returned.
References pip._vendor.distlib.compat._get_normal_name.
pip::_vendor::distlib::compat::_recursive_repr(fillvalue='...')
Decorator to make a repr function return fillvalue for a recursive call
pip::_vendor::distlib::compat::cache_from_source(path, debug_override=None)
pip::_vendor::distlib::compat::valid_ident(s)
Referenced by pip._vendor.distlib.compat.BaseConfigurator.configure_custom.
pip::_vendor::distlib::compat::pop(self, key, default=None)