pydantic::v1::tools
pydantic::v1::tools.NameFactory
pydantic::v1::tools.T
str pydantic.v1.tools._generate_parsing_type_name(Any type_)
Any pydantic.v1.tools._get_parsing_type(Any type_, *, Optional[NameFactory] type_name=None)
References pydantic.v1.main.create_model.
Referenced by pydantic.v1.tools.parse_obj_as, pydantic.v1.tools.schema_json_of, pydantic.v1.tools.schema_of.
T pydantic.v1.tools.parse_obj_as(Type[T] type_, Any obj, *, Optional[NameFactory] type_name=None)
References pydantic.v1.tools._get_parsing_type.
Referenced by pydantic.v1.tools.parse_file_as, pydantic.v1.tools.parse_raw_as.
T pydantic.v1.tools.parse_file_as(Type[T] type_, Union[str, Path] path, *, str content_type=None, str encoding='utf8', Protocol proto=None, bool allow_pickle=False, Callable[[str], Any] json_loads=json.loads, Optional[NameFactory] type_name=None)
References pydantic.v1.tools.parse_obj_as.
T pydantic.v1.tools.parse_raw_as(Type[T] type_, StrBytes b, *, str content_type=None, str encoding='utf8', Protocol proto=None, bool allow_pickle=False, Callable[[str], Any] json_loads=json.loads, Optional[NameFactory] type_name=None)
References pydantic.v1.tools.parse_obj_as.
'DictStrAny' pydantic.v1.tools.schema_of(Any type_, *, Optional[NameFactory] title=None, **Any schema_kwargs)
Generate a JSON schema (as dict) for the passed model or dynamically generated one
References pydantic.v1.tools._get_parsing_type.
str pydantic.v1.tools.schema_json_of(Any type_, *, Optional[NameFactory] title=None, **Any schema_json_kwargs)
Generate a JSON schema (as JSON) for the passed model or dynamically generated one
References pydantic.v1.tools._get_parsing_type.