pydantic::_internal::_schema_gather
TypeAlias pydantic::_internal::_schema_gather.AllSchemas
None pydantic._internal._schema_gather.traverse_metadata(AllSchemas schema, GatherContext ctx)
Referenced by pydantic._internal._schema_gather.traverse_definition_ref, pydantic._internal._schema_gather.traverse_schema.
None pydantic._internal._schema_gather.traverse_definition_ref(DefinitionReferenceSchema def_ref_schema, GatherContext ctx)
References pydantic._internal._schema_gather.traverse_metadata, pydantic._internal._schema_gather.traverse_schema.
Referenced by pydantic._internal._schema_gather.traverse_schema.
None pydantic._internal._schema_gather.traverse_schema(AllSchemas schema, GatherContext context)
References pydantic._internal._schema_gather.traverse_definition_ref, pydantic._internal._schema_gather.traverse_metadata, pydantic._internal._schema_gather.traverse_schema.
Referenced by pydantic._internal._schema_gather.gather_schemas_for_cleaning, pydantic._internal._schema_gather.traverse_definition_ref, pydantic._internal._schema_gather.traverse_schema.
GatherResult pydantic._internal._schema_gather.gather_schemas_for_cleaning(CoreSchema schema, dict[str, CoreSchema] definitions)
Traverse the core schema and definitions and return the necessary information for schema cleaning. During the core schema traversing, any `'definition-ref'` schema is: - Validated: the reference must point to an existing definition. If this is not the case, a `MissingDefinitionError` exception is raised. - Stored in the context: the actual reference is stored in the context. Depending on whether the `'definition-ref'` schema is encountered more that once, the schema itself is also saved in the context to be inlined (i.e. replaced by the definition it points to).
References pydantic._internal._schema_gather.traverse_schema.