_distutils_hack
str _distutils_hack.is_pypy
_distutils_hack.DISTUTILS_FINDER
_distutils_hack.warn_distutils_present()
Referenced by do_override.
_distutils_hack.clear_distutils()
Referenced by ensure_local_distutils, _distutils_hack.DistutilsMetaFinder.spec_for_pip, _distutils_hack.DistutilsMetaFinder.spec_for_sensitive_tests.
_distutils_hack.enabled()
Allow selection of distutils by environment variable.
Referenced by do_override.
_distutils_hack.ensure_local_distutils()
References clear_distutils.
Referenced by do_override.
_distutils_hack.do_override()
Ensure that the local copy of distutils is preferred over stdlib. See https://github.com/pypa/setuptools/issues/417#issuecomment-392298401 for more motivation.
References enabled, ensure_local_distutils, warn_distutils_present.
_distutils_hack.add_shim()
References insert_shim.
_distutils_hack.insert_shim()
Referenced by add_shim.
_distutils_hack.remove_shim()
Referenced by setuptools.sandbox.hide_setuptools.