pip::_vendor::pygments::plugin
str pip::_vendor::pygments::plugin::LEXER_ENTRY_POINT
str pip::_vendor::pygments::plugin::FORMATTER_ENTRY_POINT
str pip::_vendor::pygments::plugin::STYLE_ENTRY_POINT
str pip::_vendor::pygments::plugin::FILTER_ENTRY_POINT
pip::_vendor::pygments::plugin::iter_entry_points(group_name)
Referenced by pip._vendor.pygments.plugin.find_plugin_filters, pip._vendor.pygments.plugin.find_plugin_formatters, pip._vendor.pygments.plugin.find_plugin_lexers, pip._vendor.pygments.plugin.find_plugin_styles.
pip::_vendor::pygments::plugin::find_plugin_lexers()
References pip._vendor.pygments.plugin.iter_entry_points.
pip::_vendor::pygments::plugin::find_plugin_formatters()
References pip._vendor.pygments.plugin.iter_entry_points.
pip::_vendor::pygments::plugin::find_plugin_styles()
References pip._vendor.pygments.plugin.iter_entry_points.
pip::_vendor::pygments::plugin::find_plugin_filters()
References pip._vendor.pygments.plugin.iter_entry_points.