pydantic::v1::color
pydantic::v1::color.ColorTuple
pydantic::v1::color.ColorType
pydantic::v1::color.HslColorTuple
str pydantic::v1::color.r_hex_short
str pydantic::v1::color.r_hex_long
str pydantic::v1::color._r_255
str pydantic::v1::color._r_comma
str pydantic::v1::color.r_rgb
str pydantic::v1::color._r_alpha
str pydantic::v1::color.r_rgba
str pydantic::v1::color._r_h
str pydantic::v1::color._r_sl
str pydantic::v1::color.r_hsl
str pydantic::v1::color.r_hsla
dict pydantic::v1::color.repeat_colors
int pydantic::v1::color.rads
dict pydantic::v1::color.COLORS_BY_NAME
dict pydantic::v1::color.COLORS_BY_VALUE
RGBA pydantic.v1.color.parse_tuple(Tuple[Any,...] value)
Parse a tuple or list as a color.
References pydantic.v1.color.parse_color_value, pydantic.v1.color.parse_float_alpha.
RGBA pydantic.v1.color.parse_str(str value)
Parse a string to an RGBA tuple, trying the following formats (in this order): * named color, see COLORS_BY_NAME below * hex short eg. `<prefix>fff` (prefix can be `#`, `0x` or nothing) * hex long eg. `<prefix>ffffff` (prefix can be `#`, `0x` or nothing) * `rgb(<r>, <g>, <b>) ` * `rgba(<r>, <g>, <b>, <a>)`
References pydantic.v1.color.ints_to_rgba, pydantic.v1.color.parse_float_alpha, pydantic.v1.color.parse_hsl.
RGBA pydantic.v1.color.ints_to_rgba(Union[int, str] r, Union[int, str] g, Union[int, str] b, Optional[float] alpha)
References pydantic.v1.color.parse_color_value, pydantic.v1.color.parse_float_alpha.
Referenced by pydantic.v1.color.parse_str.
float pydantic.v1.color.parse_color_value(Union[int, str] value, int max_val=255)
Parse a value checking it's a valid int in the range 0 to max_val and divide by max_val to give a number in the range 0 to 1
Referenced by pydantic.v1.color.ints_to_rgba, pydantic.v1.color.parse_hsl, pydantic.v1.color.parse_tuple.
Optional[float] pydantic.v1.color.parse_float_alpha(Union[None, str, float, int] value)
Parse a value checking it's a valid float in the range 0 to 1
Referenced by pydantic.v1.color.ints_to_rgba, pydantic.v1.color.parse_str, pydantic.v1.color.parse_tuple.
RGBA pydantic.v1.color.parse_hsl(str h, str h_units, str sat, str light, Optional[float] alpha=None)
Parse raw hue, saturation, lightness and alpha values and convert to RGBA.
References pydantic.v1.color.parse_color_value.
Referenced by pydantic.v1.color.parse_str.
int pydantic.v1.color.float_to_255(float c)
Referenced by pydantic.v1.color.Color.as_hex, pydantic.v1.color.Color.as_rgb_tuple.