anyio::abc::_sockets
TypeAlias anyio::abc::_sockets.IPAddressType
TypeAlias anyio::abc::_sockets.IPSockAddrType
TypeAlias anyio::abc::_sockets.SockAddrType
TypeAlias anyio::abc::_sockets.UDPPacketType
TypeAlias anyio::abc::_sockets.UNIXDatagramPacketType
anyio::abc::_sockets.T_Retval
socket.socket anyio.abc._sockets._validate_socket(socket.socket|int sock_or_fd, socket.SocketKind sock_type, socket.AddressFamily addr_family=socket.AF_UNSPEC, *, bool require_connected=False, bool require_bound=False)
Referenced by anyio.abc._sockets.ConnectedUDPSocket.from_socket, anyio.abc._sockets.ConnectedUNIXDatagramSocket.from_socket, anyio.abc._sockets.SocketListener.from_socket, anyio.abc._sockets.SocketStream.from_socket, anyio.abc._sockets.UDPSocket.from_socket, anyio.abc._sockets.UNIXDatagramSocket.from_socket, anyio.abc._sockets.UNIXSocketStream.from_socket.