click::_compat
click::_compat.CYGWIN
click::_compat.WIN
t click::_compat.auto_wrap_for_ansi
click::_compat._ansi_re
cabc click::_compat._ansi_stream_wrappers
t.Callable[[], t.TextIO | None] click::_compat._default_text_stdin
t.Callable[[], t.TextIO | None] click::_compat._default_text_stdout
t.Callable[[], t.TextIO | None] click::_compat._default_text_stderr
dict click::_compat.binary_streams
dict click::_compat.text_streams
t.TextIO click._compat._make_text_stream(t.BinaryIO stream, str|None encoding, str|None errors, bool force_readable=False, bool force_writable=False)
References click._compat.get_best_encoding.
Referenced by click._compat._force_correct_text_stream.
bool click._compat.is_ascii_encoding(str encoding)
Checks if a given encoding is ascii.
Referenced by click._compat._stream_is_misconfigured, click._compat.get_best_encoding.
str click._compat.get_best_encoding(t.IO[t.Any] stream)
Returns the default stream encoding if not found.
References click._compat.is_ascii_encoding.
Referenced by click._compat._make_text_stream.
bool click._compat._is_binary_reader(t.IO[t.Any] stream, bool default=False)
Referenced by click._compat._find_binary_reader.
bool click._compat._is_binary_writer(t.IO[t.Any] stream, bool default=False)
Referenced by click._compat._find_binary_writer.
t.BinaryIO | None click._compat._find_binary_reader(t.IO[t.Any] stream)
References click._compat._is_binary_reader.
Referenced by click._compat.get_binary_stdin.
t.BinaryIO | None click._compat._find_binary_writer(t.IO[t.Any] stream)
References click._compat._is_binary_writer.
Referenced by click._compat.get_binary_stderr, click._compat.get_binary_stdout.
bool click._compat._stream_is_misconfigured(t.TextIO stream)
A stream is misconfigured if its encoding is ASCII.
References click._compat.is_ascii_encoding.
Referenced by click._compat._force_correct_text_stream.
bool click._compat._is_compat_stream_attr(t.TextIO stream, str attr, str|None value)
A stream attribute is compatible if it is equal to the desired value or the desired value is unset and the attribute has a value.
Referenced by click._compat._is_compatible_text_stream.
bool click._compat._is_compatible_text_stream(t.TextIO stream, str|None encoding, str|None errors)
Check if a stream's encoding and errors attributes are compatible with the desired values.
References click._compat._is_compat_stream_attr.
Referenced by click._compat._force_correct_text_stream.
t.TextIO click._compat._force_correct_text_stream(t.IO[t.Any] text_stream, str|None encoding, str|None errors, t.Callable[[t.IO[t.Any], bool], bool] is_binary, t.Callable[[t.IO[t.Any]], t.BinaryIO|None] find_binary, bool force_readable=False, bool force_writable=False)
References click._compat._is_compatible_text_stream, click._compat._make_text_stream, click._compat._stream_is_misconfigured.
Referenced by click._compat._force_correct_text_reader, click._compat._force_correct_text_writer.
t.TextIO click._compat._force_correct_text_reader(t.IO[t.Any] text_reader, str|None encoding, str|None errors, bool force_readable=False)
References click._compat._force_correct_text_stream.
Referenced by click._compat.get_text_stdin.
t.TextIO click._compat._force_correct_text_writer(t.IO[t.Any] text_writer, str|None encoding, str|None errors, bool force_writable=False)
References click._compat._force_correct_text_stream.
Referenced by click._compat.get_text_stderr, click._compat.get_text_stdout.
t.BinaryIO click._compat.get_binary_stdin()
References click._compat._find_binary_reader.
Referenced by click._compat.open_stream.
t.BinaryIO click._compat.get_binary_stdout()
References click._compat._find_binary_writer.
Referenced by click._compat.open_stream.
t.BinaryIO click._compat.get_binary_stderr()
References click._compat._find_binary_writer.
t.TextIO click._compat.get_text_stdin(str|None encoding=None, str|None errors=None)
References click._compat._force_correct_text_reader, click._compat._get_windows_console_stream.
Referenced by click._compat.open_stream.
t.TextIO click._compat.get_text_stdout(str|None encoding=None, str|None errors=None)
References click._compat._force_correct_text_writer, click._compat._get_windows_console_stream.
Referenced by click._compat.open_stream.
t.TextIO click._compat.get_text_stderr(str|None encoding=None, str|None errors=None)
References click._compat._force_correct_text_writer, click._compat._get_windows_console_stream.
t.IO[t.Any] click._compat._wrap_io_open(str|os.PathLike[str]|int file, str mode, str|None encoding, str|None errors)
Handles not passing ``encoding`` and ``errors`` in binary mode.
Referenced by click._compat.open_stream.
tuple[t.IO[t.Any], bool] click._compat.open_stream(str|os.PathLike[str] filename, str mode="r", str|None encoding=None, str|None errors="strict", bool atomic=False)
References click._compat._wrap_io_open, click._compat.get_binary_stdin, click._compat.get_binary_stdout, click._compat.get_text_stdin, click._compat.get_text_stdout.
str click._compat.strip_ansi(str value)
Referenced by click._compat.term_len.
bool click._compat._is_jupyter_kernel_output(t.IO[t.Any] stream)
Referenced by click._compat.should_strip_ansi.
bool click._compat.should_strip_ansi(t.IO[t.Any]|None stream=None, bool|None color=None)
References click._compat._is_jupyter_kernel_output, click._compat.isatty.
Referenced by click._compat.auto_wrap_for_ansi.
str click::_compat::_get_argv_encoding()
t.TextIO click._compat.auto_wrap_for_ansi(t.TextIO stream, bool|None color=None)
Support ANSI color and style codes on Windows by wrapping a stream with colorama.
References click._compat.should_strip_ansi.
t.TextIO | None click._compat._get_windows_console_stream(t.TextIO f, str|None encoding, str|None errors)
Referenced by click._compat.get_text_stderr, click._compat.get_text_stdin, click._compat.get_text_stdout.
int click._compat.term_len(str x)
References click._compat.strip_ansi.
bool click._compat.isatty(t.IO[t.Any] stream)
Referenced by click._compat.should_strip_ansi.
t.Callable[[], t.TextIO | None] click._compat._make_cached_stream_func(t.Callable[[], t.TextIO|None] src_func, t.Callable[[], t.TextIO] wrapper_func)