pip::_internal::utils::compatibility_tags
pip::_internal::utils::compatibility_tags._apple_arch_pat
pip::_internal::utils::compatibility_tags._osx_arch_pat
str pip._internal.utils.compatibility_tags.version_info_to_nodot(tuple[int,...] version_info)
list[str] pip._internal.utils.compatibility_tags._mac_platforms(str arch)
Referenced by pip._internal.utils.compatibility_tags._get_custom_platforms, pip._internal.utils.compatibility_tags.version_info_to_nodot.
list[str] pip._internal.utils.compatibility_tags._ios_platforms(str arch)
Referenced by pip._internal.utils.compatibility_tags._get_custom_platforms.
list[str] pip._internal.utils.compatibility_tags._android_platforms(str arch)
Referenced by pip._internal.utils.compatibility_tags._get_custom_platforms.
list[str] pip._internal.utils.compatibility_tags._custom_manylinux_platforms(str arch)
Referenced by pip._internal.utils.compatibility_tags._get_custom_platforms, pip._internal.utils.compatibility_tags.version_info_to_nodot.
list[str] pip._internal.utils.compatibility_tags._get_custom_platforms(str arch)
References pip._internal.utils.compatibility_tags._android_platforms, pip._internal.utils.compatibility_tags._custom_manylinux_platforms, pip._internal.utils.compatibility_tags._ios_platforms, pip._internal.utils.compatibility_tags._mac_platforms.
Referenced by pip._internal.utils.compatibility_tags._expand_allowed_platforms, pip._internal.utils.compatibility_tags._expand_allowed_platforms.
list[str] | None pip._internal.utils.compatibility_tags._expand_allowed_platforms(list[str]|None platforms)
References pip._internal.utils.compatibility_tags._get_custom_platforms.
Referenced by pip._internal.utils.compatibility_tags.get_supported, pip._internal.utils.compatibility_tags.get_supported.
PythonVersion pip::_internal::utils::compatibility_tags::_get_python_version(str version)
Referenced by pip._internal.utils.compatibility_tags.get_supported, pip._internal.utils.compatibility_tags.get_supported.
str pip._internal.utils.compatibility_tags._get_custom_interpreter(str|None implementation=None, str|None version=None)
Referenced by pip._internal.utils.compatibility_tags.get_supported, pip._internal.utils.compatibility_tags.get_supported.
list[Tag] pip._internal.utils.compatibility_tags.get_supported(str|None version=None, list[str]|None platforms=None, str|None impl=None, list[str]|None abis=None)
Return a list of supported tags for each version specified in `versions`. :param version: a string version, of the form "33" or "32", or None. The version will be assumed to support our ABI. :param platform: specify a list of platforms you want valid tags for, or None. If None, use the local system platform. :param impl: specify the exact implementation you want valid tags for, or None. If None, use the local interpreter impl. :param abis: specify a list of abis you want valid tags for, or None. If None, use the local interpreter abi.
References pip._internal.utils.compatibility_tags._expand_allowed_platforms, pip._internal.utils.compatibility_tags._get_custom_interpreter, pip._internal.utils.compatibility_tags._get_python_version.
str pip._internal.utils.compatibility_tags.version_info_to_nodot(Tuple[int,...] version_info)
References pip._internal.utils.compatibility_tags._custom_manylinux_platforms, pip._internal.utils.compatibility_tags._mac_platforms.
Optional[List[str]] pip._internal.utils.compatibility_tags._expand_allowed_platforms(Optional[List[str]] platforms)
References pip._internal.utils.compatibility_tags._get_custom_platforms.
str pip._internal.utils.compatibility_tags._get_custom_interpreter(Optional[str] implementation=None, Optional[str] version=None)
List[Tag] pip._internal.utils.compatibility_tags.get_supported(Optional[str] version=None, Optional[List[str]] platforms=None, Optional[str] impl=None, Optional[List[str]] abis=None)
Return a list of supported tags for each version specified in `versions`. :param version: a string version, of the form "33" or "32", or None. The version will be assumed to support our ABI. :param platform: specify a list of platforms you want valid tags for, or None. If None, use the local system platform. :param impl: specify the exact implementation you want valid tags for, or None. If None, use the local interpreter impl. :param abis: specify a list of abis you want valid tags for, or None. If None, use the local interpreter abi.
References pip._internal.utils.compatibility_tags._expand_allowed_platforms, pip._internal.utils.compatibility_tags._get_custom_interpreter, pip._internal.utils.compatibility_tags._get_python_version.