starlette::routing
starlette::routing.PARAM_REGEX
starlette::routing._T
bool starlette.routing.iscoroutinefunction_or_partial(Any obj)
Correctly determines if an object is a coroutine function, including those wrapped in functools.partial objects.
ASGIApp starlette.routing.request_response(Callable[[Request], Awaitable[Response]|Response] func)
Takes a function or coroutine `func(request) -> response`, and returns an ASGI application.
ASGIApp starlette.routing.websocket_session(Callable[[WebSocket], Awaitable[None]] func)
Takes a coroutine `func(session)`, and returns an ASGI application.
str starlette.routing.get_name(Callable[..., Any] endpoint)
tuple[str, dict[str, str]] starlette.routing.replace_params(str path, dict[str, Convertor[Any]] param_convertors, dict[str, str] path_params)
Referenced by starlette.routing.Host.url_path_for, starlette.routing.Mount.url_path_for, starlette.routing.Route.url_path_for, starlette.routing.WebSocketRoute.url_path_for.
tuple[Pattern[str], str, dict[str, Convertor[Any]]] starlette.routing.compile_path(str path)
Given a path string, like: "/{username:str}", or a host string, like: "{subdomain}.mydomain.org", return a three-tuple of (regex, format, {param_name:convertor}). regex: "/(?P<username>[^/]+)" format: "/{username}" convertors: {"username": StringConvertor()}
Callable[[Any], AbstractAsyncContextManager[Any]] starlette.routing._wrap_gen_lifespan_context(Callable[[Any], Generator[Any, Any, Any]] lifespan_context)