pip::_internal::req::req_dependency_group
list[str] pip._internal.req.req_dependency_group.parse_dependency_groups(list[tuple[str, str]] groups)
Parse dependency groups data as provided via the CLI, in a `[path:]group` syntax. Raises InstallationErrors if anything goes wrong.
References pip._internal.req.req_dependency_group._build_resolvers, pip._internal.req.req_dependency_group._resolve_all_groups.
Iterator[str] pip._internal.req.req_dependency_group._resolve_all_groups(dict[str, DependencyGroupResolver] resolvers, list[tuple[str, str]] groups)
Run all resolution, converting any error from `DependencyGroupResolver` into an InstallationError.
Referenced by pip._internal.req.req_dependency_group.parse_dependency_groups.
dict[str, Any] pip._internal.req.req_dependency_group._build_resolvers(Iterable[str] paths)
References pip._internal.req.req_dependency_group._load_pyproject.
Referenced by pip._internal.req.req_dependency_group.parse_dependency_groups.
dict[str, Any] pip._internal.req.req_dependency_group._load_pyproject(str path)
This helper loads a pyproject.toml as TOML. It raises an InstallationError if the operation fails.
Referenced by pip._internal.req.req_dependency_group._build_resolvers.