anyio::_backends::_asyncio
anyio::_backends::_asyncio.FileDescriptorLike
anyio::_backends::_asyncio.T_Retval
anyio::_backends::_asyncio.T_contra
anyio::_backends::_asyncio.PosArgsT
anyio::_backends::_asyncio.P
RunVar anyio::_backends::_asyncio._root_task
WeakKeyDictionary anyio::_backends::_asyncio._run_vars
anyio::_backends::_asyncio._eager_task_factory_code
anyio::_backends::_asyncio._Retval_Queue_Type
anyio::_backends::_asyncio.backend_class
None anyio._backends._asyncio._cancel_all_tasks(AbstractEventLoop loop)
Referenced by anyio._backends._asyncio.Runner.close.
None anyio._backends._asyncio._shutdown_default_executor(AbstractEventLoop loop)
Schedule the shutdown of the default executor.
Referenced by anyio._backends._asyncio.Runner.close.
asyncio.Task anyio._backends._asyncio.find_root_task()
Referenced by anyio._backends._asyncio.AsyncIOBackend.run_sync_in_worker_thread, anyio._backends._asyncio.AsyncIOBackend.setup_process_pool_exit_at_shutdown.
str anyio._backends._asyncio.get_callable_name(Callable func)
Referenced by anyio._backends._asyncio.TaskGroup._spawn, anyio._backends._asyncio.AsyncIOBackend.run.
bool anyio._backends._asyncio._task_started(asyncio.Task task)
Return ``True`` if the task has been started and has not finished.
Referenced by anyio._backends._asyncio.CancelScope._deliver_cancellation.
bool anyio._backends._asyncio.is_anyio_cancellation(CancelledError exc)
None anyio._backends._asyncio._forcibly_shutdown_process_pool_on_exit(set[Process] workers, object _task)
Forcibly shuts down worker processes belonging to this event loop.
None anyio._backends._asyncio._shutdown_process_pool_on_exit(set[abc.Process] workers)
Shuts down worker processes belonging to this event loop. NOTE: this only works when the event loop was started using asyncio.run() or anyio.run().
Referenced by anyio._backends._asyncio.AsyncIOBackend.setup_process_pool_exit_at_shutdown.