h11::_writers
h11::_writers.Writer
h11::_writers.WritersType
dict h11::_writers.WRITERS
None h11._writers.write_headers(Headers headers, Writer write)
Referenced by h11._writers.ChunkedWriter.send_eom, h11._writers.write_any_response, h11._writers.write_request.
None h11._writers.write_request(Request request, Writer write)
References h11._writers.write_headers.
None h11._writers.write_any_response(Union[InformationalResponse, Response] response, Writer write)
References h11._writers.write_headers.