pip::_vendor::truststore::_windows
pip::_vendor::truststore::_windows.HCERTCHAINENGINE
Referenced by pip._vendor.truststore._windows._verify_using_custom_ca_certs.
pip::_vendor::truststore::_windows.HCERTSTORE
pip::_vendor::truststore::_windows.HCRYPTPROV_LEGACY
pip::_vendor::truststore::_windows.PCERT_CONTEXT
pip::_vendor::truststore::_windows.PCCERT_CONTEXT
pip::_vendor::truststore::_windows.PCERT_ENHKEY_USAGE
pip::_vendor::truststore::_windows.PCERT_CHAIN_PARA
pip::_vendor::truststore::_windows.PCERT_CHAIN_ELEMENT
pip::_vendor::truststore::_windows.PCERT_SIMPLE_CHAIN
pip::_vendor::truststore::_windows.PCERT_CHAIN_CONTEXT
Referenced by pip._vendor.truststore._windows._get_and_verify_cert_chain.
pip::_vendor::truststore::_windows.PCCERT_CHAIN_CONTEXT
pip::_vendor::truststore::_windows.PCERT_CHAIN_POLICY_PARA
pip::_vendor::truststore::_windows.PCERT_CHAIN_POLICY_STATUS
pip::_vendor::truststore::_windows.PCERT_CHAIN_ENGINE_CONFIG
pip::_vendor::truststore::_windows.PHCERTCHAINENGINE
int pip::_vendor::truststore::_windows::X509_ASN_ENCODING
int pip::_vendor::truststore::_windows::PKCS_7_ASN_ENCODING
str pip::_vendor::truststore::_windows::CERT_STORE_PROV_MEMORY
int pip::_vendor::truststore::_windows::CERT_STORE_ADD_USE_EXISTING
int pip::_vendor::truststore::_windows::USAGE_MATCH_TYPE_OR
pip::_vendor::truststore::_windows.OID_PKIX_KP_SERVER_AUTH
int pip::_vendor::truststore::_windows::CERT_CHAIN_REVOCATION_CHECK_END_CERT
int pip::_vendor::truststore::_windows::CERT_CHAIN_REVOCATION_CHECK_CHAIN
int pip::_vendor::truststore::_windows::CERT_CHAIN_POLICY_IGNORE_ALL_NOT_TIME_VALID_FLAGS
int pip::_vendor::truststore::_windows::CERT_CHAIN_POLICY_IGNORE_INVALID_BASIC_CONSTRAINTS_FLAG
int pip::_vendor::truststore::_windows::CERT_CHAIN_POLICY_ALLOW_UNKNOWN_CA_FLAG
int pip::_vendor::truststore::_windows::CERT_CHAIN_POLICY_IGNORE_INVALID_NAME_FLAG
int pip::_vendor::truststore::_windows::CERT_CHAIN_POLICY_IGNORE_WRONG_USAGE_FLAG
int pip::_vendor::truststore::_windows::CERT_CHAIN_POLICY_IGNORE_INVALID_POLICY_FLAG
int pip::_vendor::truststore::_windows::CERT_CHAIN_POLICY_IGNORE_ALL_REV_UNKNOWN_FLAGS
int pip::_vendor::truststore::_windows::CERT_CHAIN_POLICY_ALLOW_TESTROOT_FLAG
int pip::_vendor::truststore::_windows::CERT_CHAIN_POLICY_TRUST_TESTROOT_FLAG
int pip::_vendor::truststore::_windows.SECURITY_FLAG_IGNORE_CERT_CN_INVALID
int pip::_vendor::truststore::_windows::AUTHTYPE_SERVER
int pip::_vendor::truststore::_windows::CERT_CHAIN_POLICY_SSL
int pip::_vendor::truststore::_windows::FORMAT_MESSAGE_FROM_SYSTEM
int pip::_vendor::truststore::_windows::FORMAT_MESSAGE_IGNORE_INSERTS
tuple pip::_vendor::truststore::_windows::CERT_CHAIN_POLICY_VERIFY_MODE_NONE_FLAGS
pip::_vendor::truststore::_windows.wincrypt
pip::_vendor::truststore::_windows.kernel32
pip::_vendor::truststore::_windows.CertCreateCertificateChainEngine
Referenced by pip._vendor.truststore._windows._verify_using_custom_ca_certs.
pip::_vendor::truststore::_windows.argtypes
pip::_vendor::truststore::_windows.errcheck
pip::_vendor::truststore::_windows.CertOpenStore
Referenced by pip._vendor.truststore._windows._verify_peercerts_impl, pip._vendor.truststore._windows._verify_using_custom_ca_certs.
pip::_vendor::truststore::_windows.restype
pip::_vendor::truststore::_windows.CertAddEncodedCertificateToStore
Referenced by pip._vendor.truststore._windows._verify_peercerts_impl, pip._vendor.truststore._windows._verify_using_custom_ca_certs.
pip::_vendor::truststore::_windows.CertCreateCertificateContext
Referenced by pip._vendor.truststore._windows._verify_peercerts_impl.
pip::_vendor::truststore::_windows.CertGetCertificateChain
Referenced by pip._vendor.truststore._windows._get_and_verify_cert_chain.
pip::_vendor::truststore::_windows.CertVerifyCertificateChainPolicy
Referenced by pip._vendor.truststore._windows._get_and_verify_cert_chain.
pip::_vendor::truststore::_windows.CertCloseStore
Referenced by pip._vendor.truststore._windows._verify_peercerts_impl, pip._vendor.truststore._windows._verify_using_custom_ca_certs.
pip::_vendor::truststore::_windows.CertFreeCertificateChain
Referenced by pip._vendor.truststore._windows._get_and_verify_cert_chain.
pip::_vendor::truststore::_windows.CertFreeCertificateContext
Referenced by pip._vendor.truststore._windows._verify_peercerts_impl.
pip::_vendor::truststore::_windows.CertFreeCertificateChainEngine
Referenced by pip._vendor.truststore._windows._verify_using_custom_ca_certs.
pip::_vendor::truststore::_windows.FormatMessageW
Referenced by pip._vendor.truststore._windows._get_and_verify_cert_chain.
Any pip::_vendor::truststore::_windows::_handle_win_error(bool result, Any _, Any args)
None pip::_vendor::truststore::_windows::_verify_peercerts_impl(ssl.SSLContext ssl_context, list[bytes] cert_chain, str|None server_hostname=None)
Verify the cert_chain from the server using Windows APIs.
References pip._vendor.truststore._windows._get_and_verify_cert_chain, pip._vendor.truststore._windows._verify_using_custom_ca_certs, pip._vendor.truststore._windows.CertAddEncodedCertificateToStore, pip._vendor.truststore._windows.CertCloseStore, pip._vendor.truststore._windows.CertCreateCertificateContext, pip._vendor.truststore._windows.CertFreeCertificateContext, pip._vendor.truststore._windows.CertOpenStore.
None pip::_vendor::truststore::_windows::_get_and_verify_cert_chain(ssl.SSLContext ssl_context, HCERTCHAINENGINE|None hChainEngine, HCERTSTORE hIntermediateCertStore, c_void_p pPeerCertContext, PCERT_CHAIN_PARA pChainPara, str|None server_hostname, int chain_flags)
References pip._vendor.truststore._windows.CertFreeCertificateChain, pip._vendor.truststore._windows.CertGetCertificateChain, pip._vendor.truststore._windows.CertVerifyCertificateChainPolicy, pip._vendor.truststore._windows.FormatMessageW, pip._vendor.truststore._windows.PCERT_CHAIN_CONTEXT.
Referenced by pip._vendor.truststore._windows._verify_peercerts_impl, pip._vendor.truststore._windows._verify_using_custom_ca_certs.
None pip::_vendor::truststore::_windows::_verify_using_custom_ca_certs(ssl.SSLContext ssl_context, list[bytes] custom_ca_certs, HCERTSTORE hIntermediateCertStore, c_void_p pPeerCertContext, PCERT_CHAIN_PARA pChainPara, str|None server_hostname, int chain_flags)
References pip._vendor.truststore._windows._get_and_verify_cert_chain, pip._vendor.truststore._windows.CertAddEncodedCertificateToStore, pip._vendor.truststore._windows.CertCloseStore, pip._vendor.truststore._windows.CertCreateCertificateChainEngine, pip._vendor.truststore._windows.CertFreeCertificateChainEngine, pip._vendor.truststore._windows.CertOpenStore, pip._vendor.truststore._windows.HCERTCHAINENGINE.
Referenced by pip._vendor.truststore._windows._verify_peercerts_impl.
typing.Iterator[None] pip._vendor.truststore._windows._configure_context(ssl.SSLContext ctx)