pip::_internal::models::link
pip::_internal::models::link.logger
tuple pip::_internal::models::link::_SUPPORTED_HASHES
pip::_internal::models::link._reserved_chars_re
dict[str, str] | None pip._internal.models.link.supported_hashes(dict[str, str]|None hashes)
Referenced by pip._internal.models.link.Link.from_element, pip._internal.models.link.Link.from_element, pip._internal.models.link.Link.from_json, pip._internal.models.link.Link.from_json.
str pip::_internal::models::link::_clean_url_path_part(str part)
Clean a "part" of a URL path (i.e. after splitting on "@" characters).
str pip::_internal::models::link::_clean_file_url_path(str part)
Clean the first part of a URL path that corresponds to a local filesystem path (i.e. the first part after splitting on "@" characters).
str pip::_internal::models::link::_clean_url_path(str path, bool is_local_path)
Clean the path portion of a URL.
Referenced by pip._internal.models.link._ensure_quoted_url, pip._internal.models.link.supported_hashes.
str pip::_internal::models::link::_ensure_quoted_url(str url)
Make sure a link is fully quoted. For example, if ' ' occurs in the URL, it will be replaced with "%20", and without double-quoting other characters.
References pip._internal.models.link._clean_url_path.
Referenced by pip._internal.models.link.Link.from_element, pip._internal.models.link.Link.from_element, pip._internal.models.link.Link.from_json, pip._internal.models.link.Link.from_json.
str pip._internal.models.link._absolute_link_url(str base_url, str url)
A faster implementation of urllib.parse.urljoin with a shortcut for absolute http/https URLs.
Referenced by pip._internal.models.link.Link.from_element, pip._internal.models.link.Link.from_json.
_CleanResult pip::_internal::models::link::_clean_link(Link link)
Referenced by pip._internal.models.link.links_equivalent.
bool pip::_internal::models::link::links_equivalent(Link link1, Link link2)
References pip._internal.models.link._clean_link.
Optional[Dict[str, str]] pip._internal.models.link.supported_hashes(Optional[Dict[str, str]] hashes)
References pip._internal.models.link._clean_url_path.