pydantic::v1::datetime_parse
str pydantic::v1::datetime_parse.date_expr
tuple pydantic::v1::datetime_parse.time_expr
pydantic::v1::datetime_parse.date_re
pydantic::v1::datetime_parse.time_re
pydantic::v1::datetime_parse.datetime_re
pydantic::v1::datetime_parse.standard_duration_re
pydantic::v1::datetime_parse.iso8601_duration_re
pydantic::v1::datetime_parse.EPOCH
pydantic::v1::datetime_parse.MS_WATERSHED
pydantic::v1::datetime_parse.MAX_NUMBER
pydantic::v1::datetime_parse.StrBytesIntFloat
Union[None, int, float] pydantic.v1.datetime_parse.get_numeric(StrBytesIntFloat value, str native_expected_type)
Referenced by pydantic.v1.datetime_parse.parse_date, pydantic.v1.datetime_parse.parse_datetime, pydantic.v1.datetime_parse.parse_time.
datetime pydantic.v1.datetime_parse.from_unix_seconds(Union[int, float] seconds)
Referenced by pydantic.v1.datetime_parse.parse_date, pydantic.v1.datetime_parse.parse_datetime.
Union[None, int, timezone] pydantic.v1.datetime_parse._parse_timezone(Optional[str] value, Type[Exception] error)
Referenced by pydantic.v1.datetime_parse.parse_datetime, pydantic.v1.datetime_parse.parse_time.
date pydantic.v1.datetime_parse.parse_date(Union[date, StrBytesIntFloat] value)
Parse a date/int/float/string and return a datetime.date. Raise ValueError if the input is well formatted but not a valid date. Raise ValueError if the input isn't well formatted.
References pydantic.v1.datetime_parse.from_unix_seconds, pydantic.v1.datetime_parse.get_numeric.
time pydantic.v1.datetime_parse.parse_time(Union[time, StrBytesIntFloat] value)
Parse a time/string and return a datetime.time. Raise ValueError if the input is well formatted but not a valid time. Raise ValueError if the input isn't well formatted, in particular if it contains an offset.
References pydantic.v1.datetime_parse._parse_timezone, pydantic.v1.datetime_parse.get_numeric.
datetime pydantic.v1.datetime_parse.parse_datetime(Union[datetime, StrBytesIntFloat] value)
Parse a datetime/int/float/string and return a datetime.datetime. This function supports time zone offsets. When the input contains one, the output uses a timezone with a fixed offset from UTC. Raise ValueError if the input is well formatted but not a valid datetime. Raise ValueError if the input isn't well formatted.
References pydantic.v1.datetime_parse._parse_timezone, pydantic.v1.datetime_parse.from_unix_seconds, pydantic.v1.datetime_parse.get_numeric.
timedelta pydantic.v1.datetime_parse.parse_duration(StrBytesIntFloat value)
Parse a duration int/float/string and return a datetime.timedelta. The preferred format for durations in Django is '%d %H:%M:%S.%f'. Also supports ISO 8601 representation.