colorama::tests::isatty_test
colorama.tests.isatty_test.is_a_tty(stream)
Referenced by colorama.tests.isatty_test.IsattyTest.test_nonTTY, colorama.tests.isatty_test.IsattyTest.test_TTY, colorama.tests.isatty_test.IsattyTest.test_withPycharm, colorama.tests.isatty_test.IsattyTest.test_withPycharmNoneOverride, colorama.tests.isatty_test.IsattyTest.test_withPycharmNonTTYOverride, colorama.tests.isatty_test.IsattyTest.test_withPycharmTTYOverride.