pip::_internal::self_outdated_check
pip::_internal::self_outdated_check._WEEK
pip::_internal::self_outdated_check.logger
str pip::_internal::self_outdated_check::_get_statefile_name(str key)
datetime datetime pip::_internal::self_outdated_check::_convert_date(str isodate)
Convert an ISO format string to a date. Handles the format 2020-01-22T14:24:01Z (trailing Z) which is not supported by older versions of fromisoformat.
Referenced by pip._internal.self_outdated_check.SelfCheckState.get.
bool pip::_internal::self_outdated_check::was_installed_by_pip(str pkg)
Checks whether pkg was installed by pip This is used not to display the upgrade message when pip is in fact installed by system package manager, such as dnf on Fedora.
Referenced by pip._internal.self_outdated_check._self_version_check_logic, pip._internal.self_outdated_check._self_version_check_logic.
str | None pip._internal.self_outdated_check._get_current_remote_pip_version(PipSession session, optparse.Values options)
UpgradePrompt | None pip._internal.self_outdated_check._self_version_check_logic(*, SelfCheckState state, datetime.datetime current_time, Version local_version, Callable[[], str|None] get_remote_version)
References pip._internal.self_outdated_check.was_installed_by_pip.
Referenced by pip._internal.self_outdated_check._self_version_check_logic, pip._internal.self_outdated_check.pip_self_version_check.
None pip::_internal::self_outdated_check::pip_self_version_check(PipSession session, optparse.Values options)
Check for an update for pip. Limit the frequency of checks to once per week. State is stored either in the active virtualenv or in the user's USER_CACHE_DIR keyed off the prefix of the pip script path.
References pip._internal.self_outdated_check._self_version_check_logic.
Optional[UpgradePrompt] pip._internal.self_outdated_check._self_version_check_logic(*, SelfCheckState state, datetime.datetime current_time, DistributionVersion local_version, Callable[[], Optional[str]] get_remote_version)
References pip._internal.self_outdated_check._self_version_check_logic, pip._internal.self_outdated_check.was_installed_by_pip.