pydantic::v1::utils
pydantic::v1::utils.RichReprResult
str pydantic::v1::utils.ROOT_KEY
dict pydantic::v1::utils.IMMUTABLE_NON_COLLECTIONS_TYPES
dict pydantic::v1::utils.BUILTIN_COLLECTIONS
pydantic::v1::utils.KeyType
pydantic::v1::utils.T
dict pydantic::v1::utils.path_types
pydantic::v1::utils.Obj
dict pydantic::v1::utils.DUNDER_ATTRIBUTES
pydantic::v1::utils._EMPTY
Any pydantic.v1.utils.import_string(str dotted_path)
Stolen approximately from django. Import a dotted module path and return the attribute/class designated by the last name in the path. Raise ImportError if the import fails.
str pydantic.v1.utils.truncate(Union[str] v, *, int max_len=80)
Truncate a value and add a unicode ellipsis (three dots) to the end if it was too long
bool pydantic.v1.utils.sequence_like(Any v)
None pydantic.v1.utils.validate_field_name(Iterable[Type[Any]] bases, str field_name)
Ensure that the field's name does not shadow an existing attribute of the model.
bool pydantic.v1.utils.lenient_isinstance(Any o, Union[Type[Any], Tuple[Type[Any],...], None] class_or_tuple)
bool pydantic.v1.utils.lenient_issubclass(Any cls, Union[Type[Any], Tuple[Type[Any],...], None] class_or_tuple)
bool pydantic.v1.utils.in_ipython()
Check whether we're in an ipython environment, including jupyter notebooks.
bool pydantic.v1.utils.is_valid_identifier(str identifier)
Checks that a string is a valid identifier and not a Python keyword. :param identifier: The identifier to test. :return: True if the identifier is valid.
Referenced by pydantic.v1.utils.generate_model_signature.
Dict[KeyType, Any] pydantic.v1.utils.deep_update(Dict[KeyType, Any] mapping, *Dict[KeyType, Any] updating_mappings)
References pydantic.v1.utils.deep_update.
Referenced by pydantic.v1.utils.deep_update.
None pydantic.v1.utils.update_not_none(Dict[Any, Any] mapping, **Any update)
bool pydantic.v1.utils.almost_equal_floats(float value_1, float value_2, *, float delta=1e-8)
Return True if two floats are almost equal
'Signature' pydantic.v1.utils.generate_model_signature(Callable[..., None] init, Dict[str, 'ModelField'] fields, Type['BaseConfig'] config)
Generate signature for model based on its fields
References pydantic.v1.utils.is_valid_identifier.
Type['BaseModel'] pydantic.v1.utils.get_model(Union[Type['BaseModel'], Type['Dataclass']] obj)
str pydantic.v1.utils.to_camel(str string)
Referenced by pydantic.v1.utils.to_lower_camel.
str pydantic.v1.utils.to_lower_camel(str string)
References pydantic.v1.utils.to_camel.
List[T] pydantic.v1.utils.unique_list(Union[List[T], Tuple[T,...]] input_list, *, Callable[[T], str] name_factory=str)
Make a list unique while maintaining order. We update the list if another one with the same name is set (e.g. root validator overridden in subclass)
str pydantic.v1.utils.path_type('Path' p)
Find out what sort of thing a path is.
Obj pydantic.v1.utils.smart_deepcopy(Obj obj)
Return type as is for immutable built-in types Use obj.copy() for built-in empty collections Use copy.deepcopy() for non-empty collections and unknown objects
bool pydantic.v1.utils.is_valid_field(str name)
Referenced by pydantic.v1.utils.is_valid_private_name.
bool pydantic.v1.utils.is_valid_private_name(str name)
References pydantic.v1.utils.is_valid_field.
bool pydantic.v1.utils.all_identical(Iterable[Any] left, Iterable[Any] right)
Check that the items of `left` are the same objects as those in `right`. >>> a, b = object(), object() >>> all_identical([a, b, a], [a, b, a]) True >>> all_identical([a, b, [a]], [a, b, [a]]) # new list object, while "equal" is not "identical" False
NoReturn pydantic.v1.utils.assert_never(NoReturn obj, str msg)
Helper to make sure that we have covered all possible types. This is mostly useful for ``mypy``, docs: https://mypy.readthedocs.io/en/latest/literal_types.html#exhaustive-checks
Referenced by pydantic.v1.utils.ValueItems._coerce_items.
str pydantic.v1.utils.get_unique_discriminator_alias(Collection[str] all_aliases, str discriminator_key)
Validate that all aliases are the same and if that's the case return the alias
Referenced by pydantic.v1.utils._get_union_alias_and_all_values.
Tuple[str, Tuple[str, ...]] pydantic.v1.utils.get_discriminator_alias_and_values(Any tp, str discriminator_key)
Get alias and all valid values in the `Literal` type of the discriminator field `tp` can be a `BaseModel` class or directly an `Annotated` `Union` of many.
References pydantic.v1.utils._get_union_alias_and_all_values.
Referenced by pydantic.v1.utils._get_union_alias_and_all_values.
Tuple[str, Tuple[Tuple[str, ...], ...]] pydantic.v1.utils._get_union_alias_and_all_values(Type[Any] union_type, str discriminator_key)
References pydantic.v1.utils.get_discriminator_alias_and_values, pydantic.v1.utils.get_unique_discriminator_alias.
Referenced by pydantic.v1.utils.get_discriminator_alias_and_values.