ontology_service
dict ontology_service::headers
bool ontology_service::is_active()
Verifica si la ontología ha sido creada.
Referenced by objeto_service.ObjetoService.startObject.
str ontology_service::get_id()
Obtiene el ID del objeto inteligente desde la ontología.
str ontology_service::get_title()
Obtiene el título del objeto inteligente desde la ontología.
bool ontology_service.poblate_ontology(dict data)
Puebla la ontología con los datos proporcionados.
Referenced by objeto_service.ObjetoService.startObject.
bool ontology_service.poblate_eca(dict data)
Puebla una nueva regla ECA en la ontología.
Referenced by eca_service.EcaService.crear_eca.
bool ontology_service.edit_eca(dict data)
Edita una regla ECA en la ontología.
Referenced by eca_service.EcaService.editar_eca.
list ontology_service.get_ecas()
Obtiene todas las reglas ECA desde la ontología.
Referenced by eca_service.EcaService.listar_ecas.
list ontology_service.listarDinamicEstado(str estado)
Lista las ECAs por estado (on/off)
bool ontology_service.setEcaListState(list lista_ecas)
Actualiza el estado de una lista de ECAs.
Referenced by eca_service.EcaService.obtener_ecas_activos.
bool ontology_service.delete_eca(str eca_name)
Elimina una regla ECA de la ontología.
Referenced by eca_service.EcaService.eliminar_eca.
bool ontology_service.set_eca_state(str eca_name, str new_state)
Actualiza el estado de una regla ECA en la ontología.
Referenced by eca_service.EcaService.obtener_ecas_activos.
list ontology_service.verificar_contrato(str osid, str osidDestino)
Verifica si existe un contrato ECA entre dos objetos inteligentes. Args: osid (str): Id del objeto inteligente que envía la acción. osidDestino (str): Id del objeto inteligente que recibe la acción. Returns: list: Lista de contratos ECA entre los dos objetos inteligentes.
Referenced by eca_service.EcaService.send_command.