pip::_vendor::pkg_resources
bool pip::_vendor::pkg_resources::WRITE_SUPPORT
pip::_vendor::pkg_resources._T
pip::_vendor::pkg_resources._DistributionT
pip::_vendor::pkg_resources._NestedStr
pip::_vendor::pkg_resources._InstallerTypeT
pip::_vendor::pkg_resources._InstallerType
pip::_vendor::pkg_resources._PkgReqType
pip::_vendor::pkg_resources._EPDistType
pip::_vendor::pkg_resources._MetadataType
pip::_vendor::pkg_resources._ResolvedEntryPoint
pip::_vendor::pkg_resources._ResourceStream
pip::_vendor::pkg_resources._ModuleLike
pip::_vendor::pkg_resources._ProviderFactoryType
pip::_vendor::pkg_resources._DistFinderType
pip::_vendor::pkg_resources._NSHandlerType
pip::_vendor::pkg_resources._AdapterT
pip::_vendor::pkg_resources._PEP440_FALLBACK
pip::_vendor::pkg_resources.parse_version
dict pip::_vendor::pkg_resources::_state_vars
None pip::_vendor::pkg_resources::_sget_none
str pip::_vendor::pkg_resources::PY_MAJOR
int pip::_vendor::pkg_resources::EGG_DIST
int pip::_vendor::pkg_resources::BINARY_DIST
int pip::_vendor::pkg_resources::SOURCE_DIST
int pip::_vendor::pkg_resources::CHECKOUT_DIST
int pip::_vendor::pkg_resources::DEVELOP_DIST
pip::_vendor::pkg_resources.macosVersionString
pip::_vendor::pkg_resources.darwinVersionString
pip::_vendor::pkg_resources.get_platform
Referenced by pip._vendor.pkg_resources._macos_vers, pip._vendor.pkg_resources.get_build_platform.
pip::_vendor::pkg_resources.AvailableDistributions
pip::_vendor::pkg_resources.empty_provider
pip::_vendor::pkg_resources._namespace_handlers
pip::_vendor::pkg_resources._namespace_packages
pip::_vendor::pkg_resources.MODULE
pip::_vendor::pkg_resources.EGG_NAME
dict pip::_vendor::pkg_resources::_distributionImpl
pip::_vendor::pkg_resources.category
pip::_vendor::pkg_resources.PEP440Warning
pip::_vendor::pkg_resources.append
tuple pip::_vendor::pkg_resources._LOCALE_ENCODING
pip::_vendor::pkg_resources.resource_exists
pip::_vendor::pkg_resources.resource_isdir
pip::_vendor::pkg_resources.resource_filename
pip::_vendor::pkg_resources.resource_stream
pip::_vendor::pkg_resources.resource_string
pip::_vendor::pkg_resources.resource_listdir
pip::_vendor::pkg_resources.set_extraction_path
pip::_vendor::pkg_resources.cleanup_resources
pip::_vendor::pkg_resources.working_set
pip::_vendor::pkg_resources.require
Referenced by pip._vendor.pkg_resources.get_provider, pip._vendor.pkg_resources.get_provider, pip._vendor.pkg_resources.run_script.
pip::_vendor::pkg_resources.iter_entry_points
pip::_vendor::pkg_resources.add_activation_listener
pip::_vendor::pkg_resources.run_script
Referenced by pip._vendor.pkg_resources.run_script.
pip::_vendor::pkg_resources.run_main
pip::_vendor::pkg_resources.FileExistsError
pip::_vendor::pkg_resources.importlib_machinery
pip::_vendor::pkg_resources.resources_stream
pip::_vendor::pkg_resources.resource_dir
pip::_vendor::pkg_resources._distribution_finders
pip::_vendor::pkg_resources.stacklevel
dict pip::_vendor::pkg_resources._provider_factories
_T pip._vendor.pkg_resources._declare_state(str vartype, str varname, _T initial_value)
pip::_vendor::pkg_resources::_sget_dict(val)
pip::_vendor::pkg_resources::_sset_dict(key, ob, state)
pip::_vendor::pkg_resources::_sget_object(val)
pip::_vendor::pkg_resources::_sset_object(key, ob, state)
pip::_vendor::pkg_resources::get_supported_platform()
Return this platform's maximum compatible version. distutils.util.get_platform() normally reports the minimum version of macOS that would be required to *use* extensions produced by distutils. But what we want when checking compatibility is to know the version of macOS that we are *running*. To allow usage of packages that explicitly require a newer version of macOS, we must also know the current version of the OS. If this condition occurs for any other platform with a version in its platform strings, this function should be extended accordingly.
References pip._vendor.pkg_resources._macos_vers, pip._vendor.pkg_resources.get_build_platform.
pip._vendor.pkg_resources.register_loader_type(type[_ModuleLike] loader_type, _ProviderFactoryType provider_factory)
Register `provider_factory` to make providers for `loader_type` `loader_type` is the type or class of a PEP 302 ``module.__loader__``, and `provider_factory` is a function that, passed a *module* object, returns an ``IResourceProvider`` for that module.
IResourceProvider pip._vendor.pkg_resources.get_provider(str moduleOrReq)
Referenced by pip._vendor.pkg_resources.get_distribution, pip._vendor.pkg_resources.get_distribution.
Distribution pip._vendor.pkg_resources.get_provider(Requirement moduleOrReq)
IResourceProvider | Distribution pip._vendor.pkg_resources.get_provider(str|Requirement moduleOrReq)
Return an IResourceProvider for the named module or requirement
References pip._vendor.pkg_resources._find_adapter, pip._vendor.pkg_resources.require.
pip._vendor.pkg_resources._macos_vers()
Referenced by pip._vendor.pkg_resources._declare_state, pip._vendor.pkg_resources._macos_vers, pip._vendor.pkg_resources.get_build_platform, pip._vendor.pkg_resources.get_supported_platform.
pip::_vendor::pkg_resources::_macos_arch(machine)
Referenced by pip._vendor.pkg_resources._macos_vers, pip._vendor.pkg_resources.get_build_platform.
pip::_vendor::pkg_resources::get_build_platform()
Return this platform's string for platform-specific distributions XXX Currently this is the same as ``distutils.util.get_platform()``, but it needs some hacks for Linux and macOS.
References pip._vendor.pkg_resources._macos_arch, pip._vendor.pkg_resources._macos_vers, pip._vendor.pkg_resources.get_platform.
Referenced by pip._vendor.pkg_resources._declare_state, pip._vendor.pkg_resources.get_supported_platform.
pip._vendor.pkg_resources.compatible_platforms(str|None provided, str|None required)
Can code for the `provided` platform run on the `required` platform? Returns true if either platform is ``None``, or the platforms are equal. XXX Needs compatibility checks for Linux and other unixy OSes.
_DistributionT pip._vendor.pkg_resources.get_distribution(_DistributionT dist)
Distribution pip._vendor.pkg_resources.get_distribution(_PkgReqType dist)
Distribution pip._vendor.pkg_resources.get_distribution(Distribution|_PkgReqType dist)
Return a current distribution object for a Requirement or string
References pip._vendor.pkg_resources.get_provider.
_ResolvedEntryPoint pip._vendor.pkg_resources.load_entry_point(_EPDistType dist, str group, str name)
Return `name` entry point of `group` for `dist` or raise ImportError
dict[str, dict[str, EntryPoint]] pip._vendor.pkg_resources.get_entry_map(_EPDistType dist, None group=None)
dict[str, EntryPoint] pip._vendor.pkg_resources.get_entry_map(_EPDistType dist, str group)
pip._vendor.pkg_resources.get_entry_map(_EPDistType dist, str|None group=None)
Return the entry point map for `group`, or the full entry map
pip._vendor.pkg_resources.get_entry_info(_EPDistType dist, str group, str name)
Return the EntryPoint object for `group`+`name`, or ``None``
pip::_vendor::pkg_resources::get_default_cache()
Return the ``PYTHON_EGG_CACHE`` environment variable or a platform-relevant user cache dir for an app named "Python-Eggs".
pip._vendor.pkg_resources.safe_name(str name)
Convert an arbitrary string to a standard distribution name Any runs of non-alphanumeric/. characters are replaced with a single '-'.
pip._vendor.pkg_resources.safe_version(str version)
Convert an arbitrary string to a standard version string
pip::_vendor::pkg_resources::_forgiving_version(version)
Fallback when ``safe_version`` is not safe enough >>> parse_version(_forgiving_version('0.23ubuntu1')) <Version('0.23.dev0+sanitized.ubuntu1')> >>> parse_version(_forgiving_version('0.23-')) <Version('0.23.dev0+sanitized')> >>> parse_version(_forgiving_version('0.-_')) <Version('0.dev0+sanitized')> >>> parse_version(_forgiving_version('42.+?1')) <Version('42.dev0+sanitized.1')> >>> parse_version(_forgiving_version('hello world')) <Version('0.dev0+sanitized.hello.world')>
pip::_vendor::pkg_resources::_safe_segment(segment)
Convert an arbitrary string into a safe segment
pip._vendor.pkg_resources.safe_extra(str extra)
Convert an arbitrary string to a standard 'extra' name Any runs of non-alphanumeric characters are replaced with a single '_', and the result is always lowercased.
pip._vendor.pkg_resources.to_filename(str name)
Convert a project or version name to its filename-escaped form Any '-' characters are currently replaced with '_'.
pip._vendor.pkg_resources.invalid_marker(str text)
Validate text as a PEP 508 environment marker; return an exception if invalid or False otherwise.
bool pip._vendor.pkg_resources.evaluate_marker(str text, str|None extra=None)
Evaluate a PEP 508 environment marker. Return a boolean indicating the marker result in this environment. Raise SyntaxError if marker is invalid. This implementation uses the 'pyparsing' module.
pip::_vendor::pkg_resources::_parents(path)
yield all parents of path including path
pip._vendor.pkg_resources.register_finder(type[_T] importer_type, _DistFinderType[_T] distribution_finder)
Register `distribution_finder` to find distributions in sys.path items `importer_type` is the type or class of a PEP 302 "Importer" (sys.path item handler), and `distribution_finder` is a callable that, passed a path item and the importer instance, yields ``Distribution`` instances found on that path item. See ``pkg_resources.find_on_path`` for an example.
pip._vendor.pkg_resources.find_distributions(str path_item, bool only=False)
Yield distributions accessible via `path_item`
Iterator[Distribution] pip._vendor.pkg_resources.find_eggs_in_zip(zipimport.zipimporter importer, str path_item, bool only=False)
Find eggs in zip files; possibly multiple nested eggs.
pip._vendor.pkg_resources.find_nothing(object|None importer, str|None path_item, bool|None only=False)
pip._vendor.pkg_resources.find_on_path(object|None importer, path_item, only=False)
Yield distributions accessible on a sys.path directory
pip::_vendor::pkg_resources::dist_factory(path_item, entry, only)
Return a dist_factory for the given entry.
pip._vendor.pkg_resources.safe_listdir(StrOrBytesPath path)
Attempt to list contents of path, but suppress some exceptions.
pip._vendor.pkg_resources.distributions_from_metadata(str path)
pip::_vendor::pkg_resources::non_empty_lines(path)
Yield non-empty lines from file at path
pip::_vendor::pkg_resources::resolve_egg_link(path)
Given a path to an .egg-link, resolve distributions present in the referenced path.
pip._vendor.pkg_resources.register_namespace_handler(type[_T] importer_type, _NSHandlerType[_T] namespace_handler)
Register `namespace_handler` to declare namespace packages `importer_type` is the type or class of a PEP 302 "Importer" (sys.path item handler), and `namespace_handler` is a callable like this:: def namespace_handler(importer, path_entry, moduleName, module): # return a path_entry to use for child packages Namespace handlers are only called if the importer object has already agreed that it can handle the relevant path item, and they should only return a subpath if the module __path__ does not already contain an equivalent subpath. For an example namespace handler, see ``pkg_resources.file_ns_handler``.
pip::_vendor::pkg_resources::_handle_ns(packageName, path_item)
Ensure that named package includes a subpath of path_item (if needed)
pip._vendor.pkg_resources._rebuild_mod_path(orig_path, package_name, types.ModuleType module)
Rebuild module.__path__ ensuring that all entries are ordered corresponding to their sys.path order
pip._vendor.pkg_resources.declare_namespace(str packageName)
Declare that package 'packageName' is a namespace package
pip._vendor.pkg_resources.fixup_namespace_packages(str path_item, str|None parent=None)
Ensure that previously-declared namespace packages include path_item
pip._vendor.pkg_resources.file_ns_handler(object importer, StrPath path_item, str packageName, types.ModuleType module)
Compute an ns-package subpath for a filesystem or zipfile importer
pip._vendor.pkg_resources.null_ns_handler(object importer, str|None path_item, str|None packageName, _ModuleLike|None module)
str pip._vendor.pkg_resources.normalize_path(StrPath filename)
bytes pip._vendor.pkg_resources.normalize_path(BytesPath filename)
pip._vendor.pkg_resources.normalize_path(StrOrBytesPath filename)
Normalize a file/dir name for comparison purposes
pip._vendor.pkg_resources._cygwin_patch(StrOrBytesPath filename)
Contrary to POSIX 2008, on Cygwin, getcwd (3) contains symlink components. Using os.path.abspath() works around this limitation. A fix in os.getcwd() would probably better, in Cygwin even more so, except that this seems to be by design...
str pip._vendor.pkg_resources._normalize_cached(StrPath filename)
bytes pip._vendor.pkg_resources._normalize_cached(BytesPath filename)
str | bytes pip._vendor.pkg_resources._normalize_cached(StrOrBytesPath filename)
pip._vendor.pkg_resources._normalize_cached(filename)
pip::_vendor::pkg_resources::_is_egg_path(path)
Determine if given path appears to be an egg.
pip::_vendor::pkg_resources::_is_zip_egg(path)
pip::_vendor::pkg_resources::_is_unpacked_egg(path)
Determine if given path appears to be an unpacked egg.
pip::_vendor::pkg_resources::_set_parent_ns(packageName)
pip::_vendor::pkg_resources::_version_from_file(lines)
Given an iterable of lines from a Metadata file, return the value of the Version field, if present, or None otherwise.
pip::_vendor::pkg_resources::issue_warning(*args, **kw)
pip._vendor.pkg_resources.parse_requirements(_NestedStr strs)
Yield ``Requirement`` objects for each specification in `strs`. `strs` must be a string, or a (possibly-nested) iterable thereof.
pip::_vendor::pkg_resources::_always_object(classes)
Ensure object appears in the mro even for old-style classes.
_AdapterT pip._vendor.pkg_resources._find_adapter(Mapping[type, _AdapterT] registry, object ob)
Return an adapter factory for `ob` from `registry`
Referenced by pip._vendor.pkg_resources.get_provider, pip._vendor.pkg_resources.get_provider.
pip._vendor.pkg_resources.ensure_directory(StrOrBytesPath path)
Ensure that the parent directory of `path` exists
pip::_vendor::pkg_resources::_bypass_ensure_directory(path)
Sandbox-bypassing version of ensure_directory()
Iterator[tuple[str | None, list[str]]] pip._vendor.pkg_resources.split_sections(_NestedStr s)
Split a string or iterable thereof into (section, content) pairs Each ``section`` is a stripped version of the section header ("[section]") and each ``content`` is a list of stripped lines excluding blank lines and comment-only lines. If there are any such lines before the first section header, they're returned in a first ``section`` of ``None``.
pip::_vendor::pkg_resources::_mkstemp(*args, **kw)
str pip._vendor.pkg_resources._read_utf8_with_fallback(str file, fallback_encoding=_LOCALE_ENCODING)
See setuptools.unicode_utils._read_utf8_with_fallback
pip::_vendor::pkg_resources::_call_aside(f, *args, **kwargs)
pip::_vendor::pkg_resources::_initialize(g=globals())
pip::_vendor::pkg_resources::_initialize_master_working_set()
Prepare the master working set and make the ``require()`` API available. This function has explicit effects on the global state of pkg_resources. It is intended to be invoked once at the initialization of this module. Invocation by other packages is unsupported and done at their own risk.
pip._vendor.pkg_resources._declare_state(vartype, **kw)
References pip._vendor.pkg_resources._macos_vers, pip._vendor.pkg_resources.get_build_platform.
pip._vendor.pkg_resources.register_loader_type(loader_type, provider_factory)
Register `provider_factory` to make providers for `loader_type` `loader_type` is the type or class of a PEP 302 ``module.__loader__``, and `provider_factory` is a function that, passed a *module* object, returns an ``IResourceProvider`` for that module.
pip._vendor.pkg_resources.get_provider(moduleOrReq)
Return an IResourceProvider for the named module or requirement
References pip._vendor.pkg_resources._find_adapter, pip._vendor.pkg_resources.require.
pip._vendor.pkg_resources._macos_vers(_cache=[])
References pip._vendor.pkg_resources._macos_arch, pip._vendor.pkg_resources._macos_vers, pip._vendor.pkg_resources.get_platform.
pip._vendor.pkg_resources.compatible_platforms(provided, required)
Can code for the `provided` platform run on the `required` platform? Returns true if either platform is ``None``, or the platforms are equal. XXX Needs compatibility checks for Linux and other unixy OSes.
pip._vendor.pkg_resources.run_script(dist_spec, script_name)
Locate distribution `dist_spec` and run its `script_name` script
References pip._vendor.pkg_resources.require, pip._vendor.pkg_resources.run_script.
pip._vendor.pkg_resources.get_distribution(dist)
Return a current distribution object for a Requirement or string
References pip._vendor.pkg_resources.get_provider.
pip._vendor.pkg_resources.load_entry_point(dist, group, name)
Return `name` entry point of `group` for `dist` or raise ImportError
pip._vendor.pkg_resources.get_entry_map(dist, group=None)
Return the entry point map for `group`, or the full entry map
pip._vendor.pkg_resources.get_entry_info(dist, group, name)
Return the EntryPoint object for `group`+`name`, or ``None``
pip._vendor.pkg_resources.safe_name(name)
Convert an arbitrary string to a standard distribution name Any runs of non-alphanumeric/. characters are replaced with a single '-'.
pip._vendor.pkg_resources.safe_version(version)
Convert an arbitrary string to a standard version string
pip._vendor.pkg_resources.safe_extra(extra)
Convert an arbitrary string to a standard 'extra' name Any runs of non-alphanumeric characters are replaced with a single '_', and the result is always lowercased.
pip._vendor.pkg_resources.to_filename(name)
Convert a project or version name to its filename-escaped form Any '-' characters are currently replaced with '_'.
pip._vendor.pkg_resources.invalid_marker(text)
Validate text as a PEP 508 environment marker; return an exception if invalid or False otherwise.
pip._vendor.pkg_resources.evaluate_marker(text, extra=None)
Evaluate a PEP 508 environment marker. Return a boolean indicating the marker result in this environment. Raise SyntaxError if marker is invalid. This implementation uses the 'pyparsing' module.
pip._vendor.pkg_resources.register_finder(importer_type, distribution_finder)
Register `distribution_finder` to find distributions in sys.path items `importer_type` is the type or class of a PEP 302 "Importer" (sys.path item handler), and `distribution_finder` is a callable that, passed a path item and the importer instance, yields ``Distribution`` instances found on that path item. See ``pkg_resources.find_on_path`` for an example.
pip._vendor.pkg_resources.find_distributions(path_item, only=False)
Yield distributions accessible via `path_item`
pip._vendor.pkg_resources.find_eggs_in_zip(importer, path_item, only=False)
Find eggs in zip files; possibly multiple nested eggs.
pip._vendor.pkg_resources.find_nothing(importer, path_item, only=False)
pip._vendor.pkg_resources.find_on_path(importer, path_item, only=False)
Yield distributions accessible on a sys.path directory
pip._vendor.pkg_resources.safe_listdir(path)
Attempt to list contents of path, but suppress some exceptions.
pip._vendor.pkg_resources.distributions_from_metadata(path)
pip._vendor.pkg_resources.register_namespace_handler(importer_type, namespace_handler)
Register `namespace_handler` to declare namespace packages `importer_type` is the type or class of a PEP 302 "Importer" (sys.path item handler), and `namespace_handler` is a callable like this:: def namespace_handler(importer, path_entry, moduleName, module): # return a path_entry to use for child packages Namespace handlers are only called if the importer object has already agreed that it can handle the relevant path item, and they should only return a subpath if the module __path__ does not already contain an equivalent subpath. For an example namespace handler, see ``pkg_resources.file_ns_handler``.
pip._vendor.pkg_resources._rebuild_mod_path(orig_path, package_name, module)
Rebuild module.__path__ ensuring that all entries are ordered corresponding to their sys.path order
pip._vendor.pkg_resources.declare_namespace(packageName)
Declare that package 'packageName' is a namespace package
pip._vendor.pkg_resources.fixup_namespace_packages(path_item, parent=None)
Ensure that previously-declared namespace packages include path_item
pip._vendor.pkg_resources.file_ns_handler(importer, path_item, packageName, module)
Compute an ns-package subpath for a filesystem or zipfile importer
pip._vendor.pkg_resources.null_ns_handler(importer, path_item, packageName, module)
pip._vendor.pkg_resources.normalize_path(filename)
Normalize a file/dir name for comparison purposes
pip._vendor.pkg_resources._cygwin_patch(filename)
Contrary to POSIX 2008, on Cygwin, getcwd (3) contains symlink components. Using os.path.abspath() works around this limitation. A fix in os.getcwd() would probably better, in Cygwin even more so, except that this seems to be by design...
pip._vendor.pkg_resources._normalize_cached(filename, _cache={})
pip._vendor.pkg_resources.parse_requirements(strs)
Yield ``Requirement`` objects for each specification in `strs`. `strs` must be a string, or a (possibly-nested) iterable thereof.
pip._vendor.pkg_resources._find_adapter(registry, ob)
Return an adapter factory for `ob` from `registry`
pip._vendor.pkg_resources.ensure_directory(path)
Ensure that the parent directory of `path` exists
pip._vendor.pkg_resources.split_sections(s)
Split a string or iterable thereof into (section, content) pairs Each ``section`` is a stripped version of the section header ("[section]") and each ``content`` is a list of stripped lines excluding blank lines and comment-only lines. If there are any such lines before the first section header, they're returned in a first ``section`` of ``None``.