pydantic::networks
TypeAlias pydantic::networks.NetworkType
pydantic::networks.email_validator
pydantic::networks.EmailStr
pydantic::networks.IPvAnyAddress
pydantic::networks.IPvAnyInterface
pydantic::networks.IPvAnyNetwork
re.Pattern[str] pydantic::networks.pretty_email_regex
int pydantic::networks.MAX_EMAIL_LENGTH
TypeAdapter pydantic.networks._build_type_adapter(type[_BaseUrl|_BaseMultiHostUrl] cls)
None pydantic.networks.import_email_validator()
Referenced by pydantic.networks.validate_email.
re.Pattern[str] pydantic.networks._build_pretty_email_regex()
tuple[str, str] pydantic.networks.validate_email(str value)
Email address validation using [email-validator](https://pypi.org/project/email-validator/). Returns: A tuple containing the local part of the email (or the name for "pretty" email addresses) and the normalized email. Raises: PydanticCustomError: If the email is invalid. Note: Note that: * Raw IP address (literal) domain parts are not allowed. * `"John Doe <local_part@domain.com>"` style "pretty" email addresses are processed. * Spaces are striped from the beginning and end of addresses, but no error is raised.
References pydantic.networks.import_email_validator.
Referenced by pydantic.networks.EmailStr._validate, pydantic.networks.NameEmail._validate.