pydantic::v1::typing
tuple pydantic::v1::typing.TypingGenericAlias
Referenced by pydantic.v1.typing.convert_generics.
tuple pydantic::v1::typing.TypesUnionType
pydantic::v1::typing.get_all_type_hints
pydantic::v1::typing._T
pydantic::v1::typing.AnyCallable
pydantic::v1::typing.NoArgAnyCallable
pydantic::v1::typing.AnyArgTCallable
dict pydantic::v1::typing.AnnotatedTypeNames
dict pydantic::v1::typing.LITERAL_TYPES
tuple pydantic::v1::typing::WithArgsTypes
pydantic::v1::typing.StrPath
pydantic::v1::typing.TupleGenerator
pydantic::v1::typing.DictStrAny
pydantic::v1::typing.DictAny
pydantic::v1::typing.SetStr
pydantic::v1::typing.ListStr
pydantic::v1::typing.IntStr
pydantic::v1::typing.AbstractSetIntStr
pydantic::v1::typing.DictIntStrAny
pydantic::v1::typing.MappingIntStrAny
pydantic::v1::typing.CallableGenerator
pydantic::v1::typing.ReprArgs
bool pydantic::v1::typing.MYPY
pydantic::v1::typing.AnyClassMethod
pydantic::v1::typing.NoneType
tuple pydantic::v1::typing.NONE_TYPES
pydantic::v1::typing.test_type
Any pydantic::v1::typing::evaluate_forwardref(ForwardRef type_, Any globalns, Any localns)
Referenced by pydantic.v1.typing.update_field_forward_refs, pydantic.v1.typing.update_model_forward_refs.
Any pydantic.v1.typing.get_all_type_hints(Any obj, Any globalns=None, Any localns=None)
Optional[Type[Any]] pydantic.v1.typing.get_origin(Type[Any] t)
We can't directly use `typing.get_origin` since we need a fallback to support custom generic classes like `ConstrainedList` It should be useless once https://github.com/cython/cython/issues/3537 is solved and https://github.com/pydantic/pydantic/pull/1753 is merged.
Referenced by pydantic.v1.typing.convert_generics, pydantic.v1.typing.display_as_type, pydantic.v1.typing.get_class, pydantic.v1.typing.get_sub_types, pydantic.v1.typing.is_callable_type, pydantic.v1.typing.is_classvar, pydantic.v1.typing.is_finalvar, pydantic.v1.typing.is_literal_type, pydantic.v1.typing.is_typeddict_special.
Tuple[Any, ...] pydantic.v1.typing.get_args(Type[Any] t)
Compatibility version of get_args for python 3.7. Mostly compatible with the python 3.8 `typing` module version and able to handle almost all use cases. Get type arguments with all substitutions performed. For unions, basic simplifications used by Union constructor are performed. Examples:: get_args(Dict[str, int]) == (str, int) get_args(int) == () get_args(Union[int, Union[T, int], str][int]) == (int, str) get_args(Union[int, Tuple[T, int]][str]) == (int, Tuple[str, int]) get_args(Callable[[], T][int]) == ([], int)
Referenced by pydantic.v1.typing.convert_generics, pydantic.v1.typing.get_class, pydantic.v1.typing.get_sub_types, pydantic.v1.typing.literal_values.
Tuple[Any, ...] pydantic.v1.typing._generic_get_args(Type[Any] tp)
In python 3.9, `typing.Dict`, `typing.List`, ... do have an empty `__args__` by default (instead of the generic ~T for example). In order to still support `Dict` for example and consider it as `Dict[Any, Any]`, we retrieve the `_nparams` value that tells us how many parameters it needs.
References pydantic.v1.typing._generic_get_args.
Referenced by pydantic.v1.typing._generic_get_args.
Type[Any] pydantic.v1.typing.convert_generics(Type[Any] tp)
Python 3.9 and older only supports generics from `typing` module. They convert strings to ForwardRef automatically. Examples:: typing.List['Hero'] == typing.List[ForwardRef('Hero')] Recursively searches for `str` type hints and replaces them with ForwardRef. Examples:: convert_generics(list['Hero']) == list[ForwardRef('Hero')] convert_generics(dict['Hero', 'Team']) == dict[ForwardRef('Hero'), ForwardRef('Team')] convert_generics(typing.Dict['Hero', 'Team']) == typing.Dict[ForwardRef('Hero'), ForwardRef('Team')] convert_generics(list[str | 'Hero'] | int) == list[str | ForwardRef('Hero')] | int
References pydantic.v1.typing.convert_generics, pydantic.v1.typing.get_args, pydantic.v1.typing.get_origin, pydantic.v1.typing.TypingGenericAlias.
Referenced by pydantic.v1.typing.convert_generics.
bool pydantic::v1::typing::is_union(Optional[Type[Any]] tp)
Referenced by pydantic.v1.typing.display_as_type, pydantic.v1.typing.get_sub_types.
bool pydantic::v1::typing::is_none_type(Any type_)
References pydantic.v1.typing.all_literal_values, pydantic.v1.typing.is_literal_type.
str pydantic.v1.typing.display_as_type(Type[Any] v)
References pydantic.v1.typing.get_origin, pydantic.v1.typing.is_union.
Dict[str, Type[Any]] pydantic.v1.typing.resolve_annotations(Dict[str, Type[Any]] raw_annotations, Optional[str] module_name)
Partially taken from typing.get_type_hints. Resolve string or ForwardRef annotations into type objects if possible.
bool pydantic.v1.typing.is_callable_type(Type[Any] type_)
References pydantic.v1.typing.get_origin.
bool pydantic.v1.typing.is_literal_type(Type[Any] type_)
References pydantic.v1.typing.get_origin.
Referenced by pydantic.v1.typing.all_literal_values, pydantic.v1.typing.is_none_type.
Tuple[Any, ...] pydantic.v1.typing.literal_values(Type[Any] type_)
References pydantic.v1.typing.get_args.
Referenced by pydantic.v1.typing.all_literal_values.
Tuple[Any, ...] pydantic.v1.typing.all_literal_values(Type[Any] type_)
This method is used to retrieve all Literal values as Literal can be used recursively (see https://www.python.org/dev/peps/pep-0586) e.g. `Literal[Literal[Literal[1, 2, 3], "foo"], 5, None]`
References pydantic.v1.typing.all_literal_values, pydantic.v1.typing.is_literal_type, pydantic.v1.typing.literal_values.
Referenced by pydantic.v1.typing.all_literal_values, pydantic.v1.typing.is_none_type.
bool pydantic.v1.typing.is_namedtuple(Type[Any] type_)
Check if a given class is a named tuple. It can be either a `typing.NamedTuple` or `collections.namedtuple`
bool pydantic.v1.typing.is_typeddict(Type[Any] type_)
Check if a given class is a typed dict (from `typing` or `typing_extensions`) In 3.10, there will be a public method (https://docs.python.org/3.10/library/typing.html#typing.is_typeddict)
bool pydantic.v1.typing._check_typeddict_special(Any type_)
Referenced by pydantic.v1.typing.is_typeddict_special.
bool pydantic.v1.typing.is_typeddict_special(Any type_)
Check if type is a TypedDict special form (Required or NotRequired).
References pydantic.v1.typing._check_typeddict_special, pydantic.v1.typing.get_origin.
bool pydantic.v1.typing.is_new_type(Type[Any] type_)
Check whether type_ was created using typing.NewType
Type[Any] pydantic.v1.typing.new_type_supertype(Type[Any] type_)
bool pydantic.v1.typing._check_classvar(Optional[Type[Any]] v)
Referenced by pydantic.v1.typing.is_classvar.
bool pydantic.v1.typing._check_finalvar(Optional[Type[Any]] v)
Check if a given type is a `typing.Final` type.
Referenced by pydantic.v1.typing.is_finalvar.
bool pydantic.v1.typing.is_classvar(Type[Any] ann_type)
References pydantic.v1.typing._check_classvar, pydantic.v1.typing.get_origin.
bool pydantic.v1.typing.is_finalvar(Type[Any] ann_type)
References pydantic.v1.typing._check_finalvar, pydantic.v1.typing.get_origin.
None pydantic.v1.typing.update_field_forward_refs('ModelField' field, Any globalns, Any localns)
Try to update ForwardRefs on fields based on this ModelField, globalns and localns.
References pydantic.v1.typing.evaluate_forwardref, pydantic.v1.typing.update_field_forward_refs.
Referenced by pydantic.v1.typing.update_field_forward_refs, pydantic.v1.typing.update_model_forward_refs.
None pydantic.v1.typing.update_model_forward_refs(Type[Any] model, Iterable['ModelField'] fields, Dict[Union[Type[Any], str, ForwardRef], AnyCallable] json_encoders, 'DictStrAny' localns, Tuple[Type[BaseException],...] exc_to_suppress=())
Try to update model fields ForwardRefs based on model and localns.
References pydantic.v1.typing.evaluate_forwardref, pydantic.v1.typing.update_field_forward_refs.
Union[None, bool, Type[Any]] pydantic.v1.typing.get_class(Type[Any] type_)
Tries to get the class of a Type[T] annotation. Returns True if Type is used without brackets. Otherwise returns None.
References pydantic.v1.typing.get_args, pydantic.v1.typing.get_origin.
List[Any] pydantic.v1.typing.get_sub_types(Any tp)
Return all the types that are allowed by type `tp` `tp` can be a `Union` of allowed types or an `Annotated` type
References pydantic.v1.typing.get_args, pydantic.v1.typing.get_origin, pydantic.v1.typing.get_sub_types, pydantic.v1.typing.is_union.
Referenced by pydantic.v1.typing.get_sub_types.