typing_extensions
bool typing_extensions.PEP_560
typing_extensions.GenericMeta
tuple typing_extensions._PEP_696_IMPLEMENTED
str typing_extensions._FORWARD_REF_HAS_CLASS
typing_extensions._marker
typing_extensions.NoReturn
typing_extensions.T
typing_extensions.KT
typing_extensions.VT
typing_extensions.T_co
typing_extensions.T_contra
typing_extensions.ClassVar
typing_extensions.Final
typing_extensions.final
typing_extensions.disjoint_base
typing_extensions.Literal
typing_extensions.doc
typing_extensions._overload_dummy
typing_extensions.overload
typing_extensions.get_overloads
typing_extensions::clear_overloads
Clear all overloads in the registry.
typing_extensions._overload_registry
typing_extensions.Type
typing_extensions.Awaitable
typing_extensions.Coroutine
typing_extensions.AsyncIterable
typing_extensions.AsyncIterator
typing_extensions.Deque
typing_extensions.DefaultDict
typing_extensions.OrderedDict
typing_extensions.Counter
typing_extensions.ChainMap
typing_extensions.Text
typing_extensions.TYPE_CHECKING
typing_extensions._NoneType
typing_extensions.Generator
typing_extensions.AsyncGenerator
typing_extensions.ContextManager
typing_extensions.AsyncContextManager
dict typing_extensions._PROTO_ALLOWLIST
typing_extensions._EXCLUDED_ATTRS
typing_extensions.Protocol
typing_extensions.runtime_checkable
typing_extensions.runtime
typing_extensions.SupportsInt
typing_extensions.SupportsFloat
typing_extensions.SupportsComplex
typing_extensions.SupportsBytes
typing_extensions.SupportsIndex
typing_extensions.SupportsAbs
typing_extensions.SupportsRound
typing_extensions.Reader
typing_extensions.Writer
tuple typing_extensions._NEEDS_SINGLETONMETA
typing_extensions.NoDefault
typing_extensions.NoExtraItems
bool typing_extensions._PEP_728_IMPLEMENTED
typing_extensions.TypedDict
typing_extensions._TypedDictMeta
typing_extensions.is_typeddict
str typing_extensions._TAKES_MODULE
typing_extensions._TypedDict
tuple typing_extensions._TYPEDDICT_TYPES
typing_extensions.assert_type
typing_extensions.get_type_hints
typing_extensions.get_origin
Referenced by _get_typeddict_qualifiers, _is_unpack, _is_unpacked_typevartuple, pydantic._internal._generics._union_orderings_key, pydantic._internal._repr.display_as_type, get_args, pydantic._internal._generics.get_origin.
typing_extensions.get_args
Referenced by _get_typeddict_qualifiers, _is_unpacked_typevartuple, pydantic._internal._repr.display_as_type, pydantic._internal._generics.get_args.
typing_extensions.TypeAlias
typing_extensions.ParamSpecArgs
typing_extensions.ParamSpecKwargs
typing_extensions._type_convert
Referenced by typing_extensions._ConcatenateGenericAlias.copy_with.
typing_extensions._ConcatenateGenericAlias
typing_extensions.Concatenate
typing_extensions.TypeGuard
typing_extensions.TypeIs
typing_extensions.TypeForm
typing_extensions.LiteralString
typing_extensions.Self
typing_extensions.Never
typing_extensions.Required
typing_extensions.NotRequired
typing_extensions.ReadOnly
str typing_extensions._UNPACK_DOC
typing_extensions.Unpack
typing_extensions.reveal_type
int typing_extensions::_ASSERT_NEVER_REPR_MAX_LENGTH
typing_extensions.assert_never
typing_extensions.dataclass_transform
typing_extensions.override
typing_extensions._F
typing_extensions.deprecated
typing_extensions._T
typing_extensions::_check_generic
Check correct count for parameters of a generic cls (internal helper). This gives a nice error message in case of count mismatch.
dict typing_extensions._TYPEVARTUPLE_TYPES
typing_extensions._collect_type_vars
Referenced by typing_extensions.TypeAliasType._check_parameters, _collect_type_vars.
typing_extensions._collect_parameters
Referenced by _collect_parameters.
typing_extensions.NamedTuple
typing_extensions._prohibited_namedtuple_fields
typing_extensions._special_namedtuple_fields
typing_extensions._NamedTuple
typing_extensions.Buffer
typing_extensions.get_original_bases
typing_extensions.NewType
typing_extensions.TypeAliasType
typing_extensions._ATTRIBUTE_DELEGATION_EXCLUSIONS
typing_extensions.is_protocol
Referenced by _proto_hook, get_protocol_members.
typing_extensions.get_protocol_members
typing_extensions.Doc
typing_extensions._CapsuleType
typing_extensions._CAPI
typing_extensions.CapsuleType
typing_extensions.evaluate_forward_ref
Referenced by evaluate_forward_ref.
typing_extensions.type_repr
list typing_extensions._typing_names
typing_extensions.Generic
typing_extensions.ForwardRef
Referenced by _clean_optional, _type_convert, evaluate_forward_ref.
typing_extensions.Annotated
bool typing_extensions._is_runtime_protocol
typing_extensions::_should_collect_from_parameters(t)
Referenced by _collect_type_vars.
typing_extensions.final(f)
This decorator can be used to indicate to type checkers that the decorated method cannot be overridden, and decorated class cannot be subclassed. For example: class Base: @final def done(self) -> None: ... class Sub(Base): def done(self) -> None: # Error reported by type checker ... @final class Leaf: ... class Other(Leaf): # Error reported by type checker ... There is no runtime checking of these properties. The decorator sets the ``__final__`` attribute to ``True`` on the decorated object to allow runtime introspection.
typing_extensions.disjoint_base(cls)
This decorator marks a class as a disjoint base. Child classes of a disjoint base cannot inherit from other disjoint bases that are not parent classes of the disjoint base. For example: @disjoint_base class Disjoint1: pass @disjoint_base class Disjoint2: pass class Disjoint3(Disjoint1, Disjoint2): pass # Type checker error Type checkers can use knowledge of disjoint bases to detect unreachable code and determine when two types can overlap. See PEP 800.
typing_extensions.IntVar(name)
typing_extensions._flatten_literal_params(parameters)
An internal helper for Literal creation: flatten Literals among parameters
typing_extensions._value_and_type_iter(params)
typing_extensions.overload(func)
Decorator for overloaded functions/methods. In a stub file, place two or more stub definitions for the same function in a row, each decorated with @overload. For example: @overload def utf8(value: None) -> None: ... @overload def utf8(value: bytes) -> bytes: ... @overload def utf8(value: str) -> bytes: ... In a non-stub file (i.e. a regular .py file), do the same but follow it with an implementation. The implementation should *not* be decorated with @overload. For example: @overload def utf8(value: None) -> None: ... @overload def utf8(value: bytes) -> bytes: ... @overload def utf8(value: str) -> bytes: ... def utf8(value): # implementation goes here The overloads for a function can be retrieved at runtime using the get_overloads() function.
typing_extensions.get_overloads(func)
Return all defined overloads for *func* as a sequence.
typing_extensions._is_dunder(attr)
typing_extensions._get_protocol_attrs(cls)
Referenced by get_protocol_members.
typing_extensions._caller(depth=1, default='__main__')
Referenced by _allow_reckless_class_checks, _create_typeddict, _set_module, typing_extensions.ParamSpec.kwargs, NamedTuple.
typing_extensions._allow_reckless_class_checks(depth=2)
Allow instance and class checks for special stdlib modules. The abc and functools modules indiscriminately call isinstance() and issubclass() on the whole MRO of a user class, which may contain protocols.
References _caller.
typing_extensions._no_init(self, *args, **kwargs)
typing_extensions._type_check_issubclass_arg_1(arg)
Raise TypeError if `arg` is not an instance of `type` in `issubclass(arg, <protocol>)`. In most cases, this is verified by type.__subclasscheck__. Checking it again unnecessarily would slow down issubclass() checks, so, we don't perform this check unless we absolutely have to. For various error paths, however, we want to ensure that *this* error message is shown to the user where relevant, rather than a typing.py-specific error message.
typing_extensions._proto_hook(cls, other)
References is_protocol.
typing_extensions.runtime_checkable(cls)
Mark a protocol class as a runtime protocol. Such protocol can be used with isinstance() and issubclass(). Raise TypeError if applied to a non-protocol class. This allows a simple-minded structural check very similar to one trick ponies in collections.abc such as Iterable. For example:: @runtime_checkable class Closable(Protocol): def close(self): ... assert isinstance(open('/some/file'), Closable) Warning: this will check only the presence of the required methods, not their type signatures!
typing_extensions._get_typeddict_qualifiers(annotation_type)
References get_args, get_origin.
typing_extensions._create_typeddict(typename, fields, *, typing_is_inline, total, closed, extra_items, **kwargs)
References _caller.
Referenced by TypedDict.
typing_extensions.TypedDict(self, args)
A simple typed namespace. At runtime it is equivalent to a plain dict. TypedDict creates a dictionary type such that a type checker will expect all instances to have a certain set of keys, where each key is associated with a value of a consistent type. This expectation is not checked at runtime. Usage:: class Point2D(TypedDict): x: int y: int label: str a: Point2D = {'x': 1, 'y': 2, 'label': 'good'} # OK b: Point2D = {'z': 3, 'label': 'bad'} # Fails type check assert Point2D(x=1, y=2, label='first') == dict(x=1, y=2, label='first') The type info can be accessed via the Point2D.__annotations__ dict, and the Point2D.__required_keys__ and Point2D.__optional_keys__ frozensets. TypedDict supports an additional equivalent form:: Point2D = TypedDict('Point2D', {'x': int, 'y': int, 'label': str}) By default, all keys must be present in a TypedDict. It is possible to override this by specifying totality:: class Point2D(TypedDict, total=False): x: int y: int This means that a Point2D TypedDict can have any of the keys omitted. A type checker is only expected to support a literal False or True as the value of the total argument. True is the default, and makes all items defined in the class body be required. The Required and NotRequired special forms can also be used to mark individual keys as being required or not required:: class Point2D(TypedDict): x: int # the "x" key must always be present (Required is the default) y: NotRequired[int] # the "y" key can be omitted See PEP 655 for more details on Required and NotRequired.
References _create_typeddict.
typing_extensions.is_typeddict(tp)
Check if an annotation is a TypedDict class For example:: class Film(TypedDict): title: str year: int is_typeddict(Film) # => True is_typeddict(Union[list, str]) # => False
typing_extensions.assert_type(val, typ)
Assert (to the type checker) that the value is of the given type. When the type checker encounters a call to assert_type(), it emits an error if the value is not of the specified type:: def greet(name: str) -> None: assert_type(name, str) # ok assert_type(name, int) # type checker error At runtime this returns the first argument unchanged and otherwise does nothing.
typing_extensions._strip_extras(t)
Strips Annotated, Required and NotRequired from a given type.
References _strip_extras.
Referenced by _strip_extras, get_type_hints.
typing_extensions.get_type_hints(obj, globalns=None, localns=None, include_extras=False)
Return type hints for an object. This is often the same as obj.__annotations__, but it handles forward references encoded as string literals, adds Optional[t] if a default value equal to None is set and recursively replaces all 'Annotated[T, ...]', 'Required[T]' or 'NotRequired[T]' with 'T' (unless 'include_extras=True'). The argument may be a module, class, method, or function. The annotations are returned as a dictionary. For classes, annotations include also inherited members. TypeError is raised if the argument is not of a type that can contain annotations, and an empty dictionary is returned if no annotations are present. BEWARE -- the behavior of globalns and localns is counterintuitive (unless you are familiar with how eval() and exec() work). The search order is locals first, then globals. - If no dict arguments are passed, an attempt is made to use the globals from obj (or the respective module's globals for classes), and these are also used as the locals. If the object does not appear to have globals, an empty dictionary is used. - If one dict argument is passed, it is used for both globals and locals. - If two dict arguments are passed, they specify globals and locals, respectively.
References _clean_optional, _strip_extras.
typing_extensions._could_be_inserted_optional(t)
detects Union[..., None] pattern
Referenced by _clean_optional.
typing_extensions._clean_optional(obj, hints, globalns=None, localns=None)
References _could_be_inserted_optional, ForwardRef.
Referenced by get_type_hints.
typing_extensions.get_origin(tp)
Get the unsubscripted version of a type. This supports generic types, Callable, Tuple, Union, Literal, Final, ClassVar and Annotated. Return None for unsupported types. Examples:: get_origin(Literal[42]) is Literal get_origin(int) is None get_origin(ClassVar[int]) is ClassVar get_origin(Generic) is Generic get_origin(Generic[T]) is Generic get_origin(Union[T, int]) is Union get_origin(List[Tuple[T, T]][int]) == list get_origin(P.args) is P
typing_extensions.get_args(tp)
Get type arguments with all substitutions performed. For unions, basic simplifications used by Union constructor are performed. Examples:: get_args(Dict[str, int]) == (str, int) get_args(int) == () get_args(Union[int, Union[T, int], str][int]) == (int, str) get_args(Union[int, Tuple[T, int]][str]) == (int, Tuple[str, int]) get_args(Callable[[], T][int]) == ([], int)
References get_origin.
typing_extensions.TypeAlias(self, parameters)
Special marker indicating that an assignment should be recognized as a proper type alias definition by type checkers. For example:: Predicate: TypeAlias = Callable[..., bool] It's invalid when used anywhere except as in the example above.
typing_extensions._set_default(type_param, default)
typing_extensions._set_module(typevarlike)
References _caller.
typing_extensions._type_convert(arg, module=None, *, allow_special_forms=False)
For converting None to type(None), and strings to ForwardRef.
References ForwardRef.
typing_extensions._create_concatenate_alias(origin, parameters)
Referenced by _concatenate_getitem.
typing_extensions._concatenate_getitem(self, parameters)
References _create_concatenate_alias.
Referenced by Concatenate.
typing_extensions.Concatenate(self, parameters)
Used in conjunction with ``ParamSpec`` and ``Callable`` to represent a higher order function which adds, removes or transforms parameters of a callable. For example:: Callable[Concatenate[int, P], int] See PEP 612 for detailed information.
References _concatenate_getitem.
typing_extensions.TypeGuard(self, parameters)
Special typing form used to annotate the return type of a user-defined type guard function. ``TypeGuard`` only accepts a single type argument. At runtime, functions marked this way should return a boolean. ``TypeGuard`` aims to benefit *type narrowing* -- a technique used by static type checkers to determine a more precise type of an expression within a program's code flow. Usually type narrowing is done by analyzing conditional code flow and applying the narrowing to a block of code. The conditional expression here is sometimes referred to as a "type guard". Sometimes it would be convenient to use a user-defined boolean function as a type guard. Such a function should use ``TypeGuard[...]`` as its return type to alert static type checkers to this intention. Using ``-> TypeGuard`` tells the static type checker that for a given function: 1. The return value is a boolean. 2. If the return value is ``True``, the type of its argument is the type inside ``TypeGuard``. For example:: def is_str(val: Union[str, float]): # "isinstance" type guard if isinstance(val, str): # Type of ``val`` is narrowed to ``str`` ... else: # Else, type of ``val`` is narrowed to ``float``. ... Strict type narrowing is not enforced -- ``TypeB`` need not be a narrower form of ``TypeA`` (it can even be a wider form) and this may lead to type-unsafe results. The main reason is to allow for things like narrowing ``List[object]`` to ``List[str]`` even though the latter is not a subtype of the former, since ``List`` is invariant. The responsibility of writing type-safe type guards is left to the user. ``TypeGuard`` also works with type variables. For more information, see PEP 647 (User-Defined Type Guards).
typing_extensions.TypeIs(self, parameters)
Special typing form used to annotate the return type of a user-defined type narrower function. ``TypeIs`` only accepts a single type argument. At runtime, functions marked this way should return a boolean. ``TypeIs`` aims to benefit *type narrowing* -- a technique used by static type checkers to determine a more precise type of an expression within a program's code flow. Usually type narrowing is done by analyzing conditional code flow and applying the narrowing to a block of code. The conditional expression here is sometimes referred to as a "type guard". Sometimes it would be convenient to use a user-defined boolean function as a type guard. Such a function should use ``TypeIs[...]`` as its return type to alert static type checkers to this intention. Using ``-> TypeIs`` tells the static type checker that for a given function: 1. The return value is a boolean. 2. If the return value is ``True``, the type of its argument is the intersection of the type inside ``TypeIs`` and the argument's previously known type. For example:: def is_awaitable(val: object) -> TypeIs[Awaitable[Any]]: return hasattr(val, '__await__') def f(val: Union[int, Awaitable[int]]) -> int: if is_awaitable(val): assert_type(val, Awaitable[int]) else: assert_type(val, int) ``TypeIs`` also works with type variables. For more information, see PEP 742 (Narrowing types with TypeIs).
typing_extensions.TypeForm(self, parameters)
A special form representing the value that results from the evaluation of a type expression. This value encodes the information supplied in the type expression, and it represents the type described by that type expression. When used in a type expression, TypeForm describes a set of type form objects. It accepts a single type argument, which must be a valid type expression. ``TypeForm[T]`` describes the set of all type form objects that represent the type T or types that are assignable to T. Usage: def cast[T](typ: TypeForm[T], value: Any) -> T: ... reveal_type(cast(int, "x")) # int See PEP 747 for more information.
typing_extensions.LiteralString(self, params)
Represents an arbitrary literal string. Example:: from typing_extensions import LiteralString def query(sql: LiteralString) -> ...: ... query("SELECT * FROM table") # ok query(f"SELECT * FROM {input()}") # not ok See PEP 675 for details.
typing_extensions.Self(self, params)
Used to spell the type of "self" in classes. Example:: from typing import Self class ReturnsSelf: def parse(self, data: bytes) -> Self: ... return self
typing_extensions.Never(self, params)
The bottom type, a type that has no members. This can be used to define a function that should never be called, or a function that never returns:: from typing_extensions import Never def never_call_me(arg: Never) -> None: pass def int_or_str(arg: int | str) -> None: never_call_me(arg) # type checker error match arg: case int(): print("It's an int") case str(): print("It's a str") case _: never_call_me(arg) # ok, arg is of type Never
typing_extensions.Required(self, parameters)
A special typing construct to mark a key of a total=False TypedDict as required. For example: class Movie(TypedDict, total=False): title: Required[str] year: int m = Movie( title='The Matrix', # typechecker error if key is omitted year=1999, ) There is no runtime checking that a required key is actually provided when instantiating a related TypedDict.
typing_extensions.NotRequired(self, parameters)
A special typing construct to mark a key of a TypedDict as potentially missing. For example: class Movie(TypedDict): title: str year: NotRequired[int] m = Movie( title='The Matrix', # typechecker error if key is omitted year=1999, )
typing_extensions.ReadOnly(self, parameters)
A special typing construct to mark an item of a TypedDict as read-only. For example: class Movie(TypedDict): title: ReadOnly[str] year: int def mutate_movie(m: Movie) -> None: m["year"] = 1992 # allowed m["title"] = "The Matrix" # typechecker error There is no runtime checking for this property.
typing_extensions::_is_unpack(obj)
References get_origin.
Referenced by _check_generic, typing_extensions._ConcatenateGenericAlias.copy_with.
typing_extensions.Unpack(self, parameters)
typing_extensions._unpack_args(*args)
Referenced by typing_extensions._ConcatenateGenericAlias.copy_with.
T typing_extensions.reveal_type(T obj)
Reveal the inferred type of a variable. When a static type checker encounters a call to ``reveal_type()``, it will emit the inferred type of the argument:: x: int = 1 reveal_type(x) Running a static type checker (e.g., ``mypy``) on this example will produce output similar to 'Revealed type is "builtins.int"'. At runtime, the function prints the runtime type of the argument and returns it unchanged.
Never typing_extensions.assert_never(Never arg)
Assert to the type checker that a line of code is unreachable. Example:: def int_or_str(arg: int | str) -> None: match arg: case int(): print("It's an int") case str(): print("It's a str") case _: assert_never(arg) If a type checker finds that a call to assert_never() is reachable, it will emit an error. At runtime, this throws an exception when called.
typing.Callable[[T], T] typing_extensions.dataclass_transform(*, bool eq_default=True, bool order_default=False, bool kw_only_default=False, bool frozen_default=False, typing.Tuple[typing.Union[typing.Type[typing.Any], typing.Callable[..., typing.Any]],...] field_specifiers=(), **typing.Any kwargs)
Decorator that marks a function, class, or metaclass as providing dataclass-like behavior. Example: from typing_extensions import dataclass_transform _T = TypeVar("_T") # Used on a decorator function @dataclass_transform() def create_model(cls: type[_T]) -> type[_T]: ... return cls @create_model class CustomerModel: id: int name: str # Used on a base class @dataclass_transform() class ModelBase: ... class CustomerModel(ModelBase): id: int name: str # Used on a metaclass @dataclass_transform() class ModelMeta(type): ... class ModelBase(metaclass=ModelMeta): ... class CustomerModel(ModelBase): id: int name: str Each of the ``CustomerModel`` classes defined in this example will now behave similarly to a dataclass created with the ``@dataclasses.dataclass`` decorator. For example, the type checker will synthesize an ``__init__`` method. The arguments to this decorator can be used to customize this behavior: - ``eq_default`` indicates whether the ``eq`` parameter is assumed to be True or False if it is omitted by the caller. - ``order_default`` indicates whether the ``order`` parameter is assumed to be True or False if it is omitted by the caller. - ``kw_only_default`` indicates whether the ``kw_only`` parameter is assumed to be True or False if it is omitted by the caller. - ``frozen_default`` indicates whether the ``frozen`` parameter is assumed to be True or False if it is omitted by the caller. - ``field_specifiers`` specifies a static list of supported classes or functions that describe fields, similar to ``dataclasses.field()``. At runtime, this decorator records its arguments in the ``__dataclass_transform__`` attribute on the decorated object. See PEP 681 for details.
_F typing_extensions.override(_F arg)
Indicate that a method is intended to override a method in a base class. Usage: class Base: def method(self) -> None: pass class Child(Base): @override def method(self) -> None: super().method() When this decorator is applied to a method, the type checker will validate that it overrides a method with the same name on a base class. This helps prevent bugs that may occur when a base class is changed without an equivalent change to a child class. There is no runtime checking of these properties. The decorator sets the ``__override__`` attribute to ``True`` on the decorated object to allow runtime introspection. See PEP 698 for details.
typing_extensions::_is_param_expr(arg)
Referenced by _check_generic, typing_extensions._ConcatenateGenericAlias.copy_with.
typing_extensions._check_generic(cls, parameters, elen=_marker)
Check correct count for parameters of a generic cls (internal helper). This gives a nice error message in case of count mismatch.
References _is_param_expr, _is_unpack.
bool typing_extensions._has_generic_or_protocol_as_origin()
Referenced by _collect_parameters, _collect_type_vars.
bool typing_extensions._is_unpacked_typevartuple(x)
References get_args, get_origin.
Referenced by _collect_parameters, _collect_type_vars.
typing_extensions._collect_type_vars(types, typevar_types=None)
Collect all type variable contained in types in order of first appearance (lexicographic order). For example:: _collect_type_vars((T, List[S, T])) == (T, S)
References _collect_type_vars, _has_generic_or_protocol_as_origin, _is_unpacked_typevartuple, _should_collect_from_parameters.
typing_extensions._collect_parameters(args)
Collect all type variables and parameter specifications in args in order of first appearance (lexicographic order). For example:: assert _collect_parameters((T, Callable[P, T])) == (T, P)
References _collect_parameters, _has_generic_or_protocol_as_origin, _is_unpacked_typevartuple.
typing_extensions._make_nmtuple(name, types, module, defaults=())
Referenced by NamedTuple.
typing_extensions._namedtuple_mro_entries(bases)
typing_extensions.NamedTuple(typename, fields=_marker, **kwargs)
Typed version of namedtuple. Usage:: class Employee(NamedTuple): name: str id: int This is equivalent to:: Employee = collections.namedtuple('Employee', ['name', 'id']) The resulting class has an extra __annotations__ attribute, giving a dict that maps field names to types. (The field names are also in the _fields attribute, which is part of the namedtuple API.) An alternative equivalent functional syntax is also accepted:: Employee = NamedTuple('Employee', [('name', str), ('id', int)])
References _caller, _make_nmtuple.
typing_extensions.get_original_bases(cls)
Return the class's "original" bases prior to modification by `__mro_entries__`. Examples:: from typing import TypeVar, Generic from typing_extensions import NamedTuple, TypedDict T = TypeVar("T") class Foo(Generic[T]): ... class Bar(Foo[int], float): ... class Baz(list[str]): ... Eggs = NamedTuple("Eggs", [("a", int), ("b", str)]) Spam = TypedDict("Spam", {"a": int, "b": str}) assert get_original_bases(Bar) == (Foo[int], float) assert get_original_bases(Baz) == (list[str],) assert get_original_bases(Eggs) == (NamedTuple,) assert get_original_bases(Spam) == (TypedDict,) assert get_original_bases(int) == (object,)
typing_extensions::_is_unionable(obj)
Corresponds to is_unionable() in unionobject.c in CPython.
Referenced by typing_extensions.TypeAliasType._check_parameters.
bool typing_extensions.is_protocol(type tp)
Return True if the given type is a Protocol. Example:: >>> from typing_extensions import Protocol, is_protocol >>> class P(Protocol): ... def a(self) -> str: ... ... b: int >>> is_protocol(P) True >>> is_protocol(int) False
typing.FrozenSet[str] typing_extensions.get_protocol_members(type tp)
Return the set of members defined in a Protocol. Example:: >>> from typing_extensions import Protocol, get_protocol_members >>> class P(Protocol): ... def a(self) -> str: ... ... b: int >>> get_protocol_members(P) frozenset({'a', 'b'}) Raise a TypeError for arguments that are not Protocols.
References _get_protocol_attrs, is_protocol.
typing_extensions.get_annotations(obj, *, globals=None, locals=None, eval_str=False, format=Format.VALUE)
Compute the annotations dict for an object. obj may be a callable, class, or module. Passing in an object of any other type raises TypeError. Returns a dict. get_annotations() returns a new dict every time it's called; calling it twice on the same object will return two different but equivalent dicts. This is a backport of `inspect.get_annotations`, which has been in the standard library since Python 3.10. See the standard library documentation for more: https://docs.python.org/3/library/inspect.html#inspect.get_annotations This backport adds the *format* argument introduced by PEP 649. The three formats supported are: * VALUE: the annotations are returned as-is. This is the default and it is compatible with the behavior on previous Python versions. * FORWARDREF: return annotations as-is if possible, but replace any undefined names with ForwardRef objects. The implementation proposed by PEP 649 relies on language changes that cannot be backported; the typing-extensions implementation simply returns the same result as VALUE. * STRING: return annotations as strings, in a format close to the original source. Again, this behavior cannot be replicated directly in a backport. As an approximation, typing-extensions retrieves the annotations under VALUE semantics and then stringifies them. The purpose of this backport is to allow users who would like to use FORWARDREF or STRING semantics once PEP 649 is implemented, but who also want to support earlier Python versions, to simply write: typing_extensions.get_annotations(obj, format=Format.FORWARDREF)
typing_extensions._eval_with_owner(forward_ref, *, owner=None, globals=None, locals=None, type_params=None)
Referenced by evaluate_forward_ref.
typing_extensions.evaluate_forward_ref(forward_ref, *, owner=None, globals=None, locals=None, type_params=None, format=None, _recursive_guard=frozenset())
Evaluate a forward reference as a type hint. This is similar to calling the ForwardRef.evaluate() method, but unlike that method, evaluate_forward_ref() also: * Recursively evaluates forward references nested within the type hint. * Rejects certain objects that are not valid type hints. * Replaces type hints that evaluate to None with types.NoneType. * Supports the *FORWARDREF* and *STRING* formats. *forward_ref* must be an instance of ForwardRef. *owner*, if given, should be the object that holds the annotations that the forward reference derived from, such as a module, class object, or function. It is used to infer the namespaces to use for looking up names. *globals* and *locals* can also be explicitly given to provide the global and local namespaces. *type_params* is a tuple of type parameters that are in scope when evaluating the forward reference. This parameter must be provided (though it may be an empty tuple) if *owner* is not given and the forward reference does not already have an owner set. *format* specifies the format of the annotation and is a member of the annotationlib.Format enum.
References _eval_with_owner, evaluate_forward_ref, ForwardRef.
typing_extensions.type_repr(value)
Convert a Python value to a format suitable for use with the STRING format. This is intended as a helper for tools that support the STRING format but do not have access to the code that originally produced the annotations. It uses repr() for most objects.