pydantic::_internal::_decorators
pydantic::_internal::_decorators.ReturnType
tuple pydantic::_internal::_decorators.DecoratedType
pydantic::_internal::_decorators.DecoratorInfoType
pydantic::_internal::_decorators._sentinel
tuple pydantic::_internal::_decorators.AnyDecoratorCallable
tuple pydantic::_internal::_decorators._function_like
tuple[type[Any], ...] pydantic._internal._decorators.get_bases(type[Any] tp)
Get the base classes of a class or typeddict. Args: tp: The type or class to get the bases. Returns: The base classes.
Referenced by pydantic._internal._decorators.mro.
tuple[type[Any], ...] pydantic._internal._decorators.mro(type[Any] tp)
Calculate the Method Resolution Order of bases using the C3 algorithm. See https://www.python.org/download/releases/2.3/mro/
References pydantic._internal._decorators.get_bases, pydantic._internal._decorators.mro_for_bases.
Referenced by pydantic._internal._decorators.DecoratorInfos.build, pydantic._internal._decorators.get_attribute_from_base_dicts, pydantic._internal._decorators.get_attribute_from_bases, pydantic._internal._decorators.mro_for_bases.
tuple[type[Any], ...] pydantic._internal._decorators.mro_for_bases(tuple[type[Any],...] bases)
References pydantic._internal._decorators.mro.
Referenced by pydantic._internal._decorators.get_attribute_from_bases, pydantic._internal._decorators.mro.
Any pydantic._internal._decorators.get_attribute_from_bases(type[Any]|tuple[type[Any],...] tp, str name)
Get the attribute from the next class in the MRO that has it, aiming to simulate calling the method on the actual class. The reason for iterating over the mro instead of just getting the attribute (which would do that for us) is to support TypedDict, which lacks a real __mro__, but can have a virtual one constructed from its bases (as done here). Args: tp: The type or class to search for the attribute. If a tuple, this is treated as a set of base classes. name: The name of the attribute to retrieve. Returns: Any: The attribute value, if found. Raises: AttributeError: If the attribute is not found in any class in the MRO.
References pydantic._internal._decorators.get_attribute_from_bases, pydantic._internal._decorators.mro, pydantic._internal._decorators.mro_for_bases.
Referenced by pydantic._internal._decorators.Decorator.build, pydantic._internal._decorators.get_attribute_from_bases.
Any pydantic._internal._decorators.get_attribute_from_base_dicts(type[Any] tp, str name)
Get an attribute out of the `__dict__` following the MRO. This prevents the call to `__get__` on the descriptor, and allows us to get the original function for classmethod properties. Args: tp: The type or class to search for the attribute. name: The name of the attribute to retrieve. Returns: Any: The attribute value, if found. Raises: KeyError: If the attribute is not found in any class's `__dict__` in the MRO.
References pydantic._internal._decorators.mro.
Referenced by pydantic._internal._decorators.Decorator.build.
bool pydantic._internal._decorators.inspect_validator(Callable[..., Any] validator, *, FieldValidatorModes mode, Literal['field', 'model'] type)
Look at a field or model validator function and determine whether it takes an info argument. An error is raised if the function has an invalid signature. Args: validator: The validator function to inspect. mode: The proposed validator mode. type: The type of validator, either 'field' or 'model'. Returns: Whether the validator takes an info argument.
References pydantic._internal._decorators._signature_no_eval, pydantic._internal._decorators.count_positional_required_params.
tuple[bool, bool] pydantic._internal._decorators.inspect_field_serializer(Callable[..., Any] serializer, Literal['plain', 'wrap'] mode)
Look at a field serializer function and determine if it is a field serializer, and whether it takes an info argument. An error is raised if the function has an invalid signature. Args: serializer: The serializer function to inspect. mode: The serializer mode, either 'plain' or 'wrap'. Returns: Tuple of (is_field_serializer, info_arg).
References pydantic._internal._decorators._serializer_info_arg, pydantic._internal._decorators._signature_no_eval, pydantic._internal._decorators.count_positional_required_params.
bool pydantic._internal._decorators.inspect_annotated_serializer(Callable[..., Any] serializer, Literal['plain', 'wrap'] mode)
Look at a serializer function used via `Annotated` and determine whether it takes an info argument. An error is raised if the function has an invalid signature. Args: serializer: The serializer function to check. mode: The serializer mode, either 'plain' or 'wrap'. Returns: info_arg
References pydantic._internal._decorators._serializer_info_arg, pydantic._internal._decorators._signature_no_eval, pydantic._internal._decorators.count_positional_required_params.
bool pydantic._internal._decorators.inspect_model_serializer(Callable[..., Any] serializer, Literal['plain', 'wrap'] mode)
Look at a model serializer function and determine whether it takes an info argument. An error is raised if the function has an invalid signature. Args: serializer: The serializer function to check. mode: The serializer mode, either 'plain' or 'wrap'. Returns: `info_arg` - whether the function expects an info argument.
References pydantic._internal._decorators._serializer_info_arg, pydantic._internal._decorators._signature_no_eval, pydantic._internal._decorators.count_positional_required_params, pydantic._internal._decorators.is_instance_method_from_sig.
bool | None pydantic._internal._decorators._serializer_info_arg(Literal['plain', 'wrap'] mode, int n_positional)
Referenced by pydantic._internal._decorators.inspect_annotated_serializer, pydantic._internal._decorators.inspect_field_serializer, pydantic._internal._decorators.inspect_model_serializer.
bool pydantic._internal._decorators.is_instance_method_from_sig(AnyDecoratorCallable function)
Whether the function is an instance method. It will consider a function as instance method if the first parameter of function is `self`. Args: function: The function to check. Returns: `True` if the function is an instance method, `False` otherwise.
References pydantic._internal._decorators._signature_no_eval, pydantic._internal._decorators.unwrap_wrapped_function.
Referenced by pydantic._internal._decorators.inspect_model_serializer.
Any pydantic._internal._decorators.ensure_classmethod_based_on_signature(AnyDecoratorCallable function)
Apply the `@classmethod` decorator on the function. Args: function: The function to apply the decorator on. Return: The `@classmethod` decorator applied function.
References pydantic._internal._decorators._is_classmethod_from_sig, pydantic._internal._decorators.unwrap_wrapped_function.
bool pydantic._internal._decorators._is_classmethod_from_sig(AnyDecoratorCallable function)
References pydantic._internal._decorators._signature_no_eval, pydantic._internal._decorators.unwrap_wrapped_function.
Referenced by pydantic._internal._decorators.ensure_classmethod_based_on_signature.
Any pydantic._internal._decorators.unwrap_wrapped_function(Any func, *, bool unwrap_partial=True, bool unwrap_class_static_method=True)
Recursively unwraps a wrapped function until the underlying function is reached. This handles property, functools.partial, functools.partialmethod, staticmethod, and classmethod. Args: func: The function to unwrap. unwrap_partial: If True (default), unwrap partial and partialmethod decorators. unwrap_class_static_method: If True (default), also unwrap classmethod and staticmethod decorators. If False, only unwrap partial and partialmethod decorators. Returns: The underlying function of the wrapped function.
Referenced by pydantic._internal._decorators._is_classmethod_from_sig, pydantic._internal._decorators.Decorator.build, pydantic._internal._decorators.ensure_classmethod_based_on_signature, pydantic._internal._decorators.get_callable_return_type, pydantic._internal._decorators.is_instance_method_from_sig.
Any | PydanticUndefinedType pydantic._internal._decorators.get_callable_return_type(Any callable_obj, GlobalsNamespace|None globalns=None, MappingNamespace|None localns=None)
Get the callable return type. Args: callable_obj: The callable to analyze. globalns: The globals namespace to use during type annotation evaluation. localns: The locals namespace to use during type annotation evaluation. Returns: The function return type.
References pydantic._internal._decorators.unwrap_wrapped_function.
int pydantic._internal._decorators.count_positional_required_params(Signature sig)
Get the number of positional (required) arguments of a signature. This function should only be used to inspect signatures of validation and serialization functions. The first argument (the value being serialized or validated) is counted as a required argument even if a default value exists. Returns: The number of positional arguments of a signature.
Referenced by pydantic._internal._decorators.inspect_annotated_serializer, pydantic._internal._decorators.inspect_field_serializer, pydantic._internal._decorators.inspect_model_serializer, pydantic._internal._decorators.inspect_validator.
Any pydantic._internal._decorators.ensure_property(Any f)
Ensure that a function is a `property` or `cached_property`, or is a valid descriptor. Args: f: The function to check. Returns: The function, or a `property` or `cached_property` instance wrapping the function.
Signature pydantic._internal._decorators._signature_no_eval(Callable[..., Any] f)
Get the signature of a callable without evaluating any annotations.
Referenced by pydantic._internal._decorators._is_classmethod_from_sig, pydantic._internal._decorators.inspect_annotated_serializer, pydantic._internal._decorators.inspect_field_serializer, pydantic._internal._decorators.inspect_model_serializer, pydantic._internal._decorators.inspect_validator, pydantic._internal._decorators.is_instance_method_from_sig.