pip::_vendor::dependency_groups::_implementation
str pip._vendor.dependency_groups._implementation._normalize_name(str name)
Referenced by pip._vendor.dependency_groups._implementation._normalize_group_names, pip._vendor.dependency_groups._implementation.DependencyGroupResolver._resolve, pip._vendor.dependency_groups._implementation.DependencyGroupResolver.lookup, pip._vendor.dependency_groups._implementation.DependencyGroupResolver.resolve.
Mapping[str, str | Mapping[str, str]] pip._vendor.dependency_groups._implementation._normalize_group_names(Mapping[str, str|Mapping[str, str]] dependency_groups)
References pip._vendor.dependency_groups._implementation._normalize_name.
tuple[str, ...] pip._vendor.dependency_groups._implementation.resolve(Mapping[str, str|Mapping[str, str]] dependency_groups, *str groups)
Resolve a dependency group to a tuple of requirements, as strings. :param dependency_groups: the parsed contents of the ``[dependency-groups]`` table from ``pyproject.toml`` :param groups: the name of the group(s) to resolve :raises TypeError: if the inputs appear to be the wrong types :raises ValueError: if the data does not appear to be valid dependency group data :raises LookupError: if group name is absent :raises packaging.requirements.InvalidRequirement: if a specifier is not valid