uvicorn::main
uvicorn::main.LEVEL_CHOICES
uvicorn::main.LIFESPAN_CHOICES
uvicorn::main.INTERFACE_CHOICES
int uvicorn::main.STARTUP_FAILURE
uvicorn::main.logger
str uvicorn.main._metavar_from_type(Any _type)
Referenced by uvicorn.main.print_version.
None uvicorn.main.print_version(click.Context ctx, click.Parameter param, bool value)
References uvicorn.main._metavar_from_type.
None uvicorn.main.main(str app, str host, int port, str uds, int fd, LoopFactoryType|str loop, HTTPProtocolType|str http, WSProtocolType|str ws, int ws_max_size, int ws_max_queue, float ws_ping_interval, float ws_ping_timeout, bool ws_per_message_deflate, LifespanType lifespan, InterfaceType interface, bool reload, list[str] reload_dirs, list[str] reload_includes, list[str] reload_excludes, float reload_delay, int workers, str env_file, str log_config, str log_level, bool access_log, bool proxy_headers, bool server_header, bool date_header, str forwarded_allow_ips, str root_path, int limit_concurrency, int backlog, int limit_max_requests, int timeout_keep_alive, int|None timeout_graceful_shutdown, int timeout_worker_healthcheck, str ssl_keyfile, str ssl_certfile, str ssl_keyfile_password, int ssl_version, int ssl_cert_reqs, str ssl_ca_certs, str ssl_ciphers, list[str] headers, bool use_colors, str app_dir, int|None h11_max_incomplete_event_size, bool factory)
References uvicorn.main.run.
None uvicorn.main.run(ASGIApplication|Callable[..., Any]|str app, *, str host="127.0.0.1", int port=8000, str|None uds=None, int|None fd=None, LoopFactoryType|str loop="auto", type[asyncio.Protocol]|HTTPProtocolType|str http="auto", type[asyncio.Protocol]|WSProtocolType|str ws="auto", int ws_max_size=16777216, int ws_max_queue=32, float|None ws_ping_interval=20.0, float|None ws_ping_timeout=20.0, bool ws_per_message_deflate=True, LifespanType lifespan="auto", InterfaceType interface="auto", bool reload=False, list[str]|str|None reload_dirs=None, list[str]|str|None reload_includes=None, list[str]|str|None reload_excludes=None, float reload_delay=0.25, int|None workers=None, str|os.PathLike[str]|None env_file=None, dict[str, Any]|str|RawConfigParser|IO[Any]|None log_config=LOGGING_CONFIG, str|int|None log_level=None, bool access_log=True, bool proxy_headers=True, bool server_header=True, bool date_header=True, list[str]|str|None forwarded_allow_ips=None, str root_path="", int|None limit_concurrency=None, int backlog=2048, int|None limit_max_requests=None, int timeout_keep_alive=5, int|None timeout_graceful_shutdown=None, int timeout_worker_healthcheck=5, str|os.PathLike[str]|None ssl_keyfile=None, str|os.PathLike[str]|None ssl_certfile=None, str|None ssl_keyfile_password=None, int ssl_version=SSL_PROTOCOL_VERSION, int ssl_cert_reqs=ssl.CERT_NONE, str|os.PathLike[str]|None ssl_ca_certs=None, str ssl_ciphers="TLSv1", list[tuple[str, str]]|None headers=None, bool|None use_colors=None, str|None app_dir=None, bool factory=False, int|None h11_max_incomplete_event_size=None)
References uvicorn.main.run.
Referenced by uvicorn.main.main, uvicorn.main.run.