pip::_vendor::pyproject_hooks::_in_process::_in_process
str pip::_vendor::pyproject_hooks::_in_process::_in_process::WHEEL_BUILT_MARKER
dict pip::_vendor::pyproject_hooks::_in_process::_in_process::HOOK_NAMES
pip::_vendor::pyproject_hooks::_in_process::_in_process::write_json(obj, path, **kwargs)
Referenced by pip._vendor.pyproject_hooks._in_process._in_process.main.
pip::_vendor::pyproject_hooks::_in_process::_in_process::read_json(path)
Referenced by pip._vendor.pyproject_hooks._in_process._in_process.main.
pip::_vendor::pyproject_hooks::_in_process::_in_process::_build_backend()
Find and load the build backend
Referenced by pip._vendor.pyproject_hooks._in_process._in_process._supported_features, pip._vendor.pyproject_hooks._in_process._in_process.build_editable, pip._vendor.pyproject_hooks._in_process._in_process.build_sdist, pip._vendor.pyproject_hooks._in_process._in_process.build_wheel, pip._vendor.pyproject_hooks._in_process._in_process.contained_in, pip._vendor.pyproject_hooks._in_process._in_process.get_requires_for_build_editable, pip._vendor.pyproject_hooks._in_process._in_process.get_requires_for_build_sdist, pip._vendor.pyproject_hooks._in_process._in_process.get_requires_for_build_wheel, pip._vendor.pyproject_hooks._in_process._in_process.prepare_metadata_for_build_editable, pip._vendor.pyproject_hooks._in_process._in_process.prepare_metadata_for_build_wheel.
pip::_vendor::pyproject_hooks::_in_process::_in_process::_supported_features()
Return the list of options features supported by the backend. Returns a list of strings. The only possible value is 'build_editable'.
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend.
pip::_vendor::pyproject_hooks::_in_process::_in_process::get_requires_for_build_wheel(config_settings)
Invoke the optional get_requires_for_build_wheel hook Returns [] if the hook is not defined.
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend.
pip::_vendor::pyproject_hooks::_in_process::_in_process::get_requires_for_build_editable(config_settings)
Invoke the optional get_requires_for_build_editable hook Returns [] if the hook is not defined.
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend.
pip::_vendor::pyproject_hooks::_in_process::_in_process::prepare_metadata_for_build_wheel(metadata_directory, config_settings, _allow_fallback)
Invoke optional prepare_metadata_for_build_wheel Implements a fallback by building a wheel if the hook isn't defined, unless _allow_fallback is False in which case HookMissing is raised.
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend, pip._vendor.pyproject_hooks._in_process._in_process._get_wheel_metadata_from_wheel.
pip::_vendor::pyproject_hooks::_in_process::_in_process::prepare_metadata_for_build_editable(metadata_directory, config_settings, _allow_fallback)
Invoke optional prepare_metadata_for_build_editable Implements a fallback by building an editable wheel if the hook isn't defined, unless _allow_fallback is False in which case HookMissing is raised.
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend, pip._vendor.pyproject_hooks._in_process._in_process._get_wheel_metadata_from_wheel.
pip::_vendor::pyproject_hooks::_in_process::_in_process::_dist_info_files(whl_zip)
Identify the .dist-info folder inside a wheel ZipFile.
Referenced by pip._vendor.pyproject_hooks._in_process._in_process._get_wheel_metadata_from_wheel, pip._vendor.pyproject_hooks._in_process._in_process.contained_in.
pip::_vendor::pyproject_hooks::_in_process::_in_process::_get_wheel_metadata_from_wheel(whl_basename, metadata_directory, config_settings)
Extract the metadata from a wheel. Fallback for when the build backend does not define the 'get_wheel_metadata' hook.
References pip._vendor.pyproject_hooks._in_process._in_process._dist_info_files.
Referenced by pip._vendor.pyproject_hooks._in_process._in_process.contained_in, pip._vendor.pyproject_hooks._in_process._in_process.prepare_metadata_for_build_editable, pip._vendor.pyproject_hooks._in_process._in_process.prepare_metadata_for_build_wheel.
pip::_vendor::pyproject_hooks::_in_process::_in_process::_find_already_built_wheel(metadata_directory)
Check for a wheel already built during the get_wheel_metadata hook. Check for a wheel already built during the get_wheel_metadata hook.
Referenced by pip._vendor.pyproject_hooks._in_process._in_process.build_editable, pip._vendor.pyproject_hooks._in_process._in_process.build_wheel, pip._vendor.pyproject_hooks._in_process._in_process.contained_in.
pip::_vendor::pyproject_hooks::_in_process::_in_process::build_wheel(wheel_directory, config_settings, metadata_directory=None)
Invoke the mandatory build_wheel hook. If a wheel was already built in the prepare_metadata_for_build_wheel fallback, this will copy it rather than rebuilding the wheel.
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend, pip._vendor.pyproject_hooks._in_process._in_process._find_already_built_wheel, pip._vendor.pyproject_hooks._in_process._in_process.build_wheel.
Referenced by pip._vendor.pyproject_hooks._in_process._in_process.build_wheel, pip._vendor.pyproject_hooks._in_process._in_process.contained_in.
pip::_vendor::pyproject_hooks::_in_process::_in_process::build_editable(wheel_directory, config_settings, metadata_directory=None)
Invoke the optional build_editable hook. If a wheel was already built in the prepare_metadata_for_build_editable fallback, this will copy it rather than rebuilding the wheel.
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend, pip._vendor.pyproject_hooks._in_process._in_process._find_already_built_wheel.
pip::_vendor::pyproject_hooks::_in_process::_in_process::get_requires_for_build_sdist(config_settings)
Invoke the optional get_requires_for_build_wheel hook Returns [] if the hook is not defined.
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend.
pip::_vendor::pyproject_hooks::_in_process::_in_process::build_sdist(sdist_directory, config_settings)
Invoke the mandatory build_sdist hook.
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend.
pip::_vendor::pyproject_hooks::_in_process::_in_process::main()
References pip._vendor.pyproject_hooks._in_process._in_process.read_json, pip._vendor.pyproject_hooks._in_process._in_process.write_json.
pip._vendor.pyproject_hooks._in_process._in_process.contained_in(filename, directory)
Test if a file is located within the given directory.
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend, pip._vendor.pyproject_hooks._in_process._in_process._dist_info_files, pip._vendor.pyproject_hooks._in_process._in_process._find_already_built_wheel, pip._vendor.pyproject_hooks._in_process._in_process._get_wheel_metadata_from_wheel, pip._vendor.pyproject_hooks._in_process._in_process.build_wheel, pip._vendor.pyproject_hooks._in_process._in_process.contained_in.
Referenced by pip._vendor.pyproject_hooks._in_process._in_process.contained_in.