pydantic::_internal::_known_annotated_metadata
dict pydantic::_internal::_known_annotated_metadata.STRICT
dict pydantic::_internal::_known_annotated_metadata.FAIL_FAST
dict pydantic::_internal::_known_annotated_metadata.LENGTH_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.INEQUALITY
dict pydantic::_internal::_known_annotated_metadata.NUMERIC_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.ALLOW_INF_NAN
dict pydantic::_internal::_known_annotated_metadata.STR_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.BYTES_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.LIST_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.TUPLE_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.SET_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.DICT_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.GENERATOR_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.SEQUENCE_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.FLOAT_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.DECIMAL_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.INT_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.BOOL_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.UUID_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.DATE_TIME_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.TIMEDELTA_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.TIME_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.LAX_OR_STRICT_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.ENUM_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.COMPLEX_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.UNION_CONSTRAINTS
dict pydantic::_internal::_known_annotated_metadata.URL_CONSTRAINTS
tuple pydantic::_internal::_known_annotated_metadata.TEXT_SCHEMA_TYPES
tuple pydantic::_internal::_known_annotated_metadata.SEQUENCE_SCHEMA_TYPES
tuple pydantic::_internal::_known_annotated_metadata.NUMERIC_SCHEMA_TYPES
dict pydantic::_internal::_known_annotated_metadata.CONSTRAINTS_TO_ALLOWED_SCHEMAS
list pydantic::_internal::_known_annotated_metadata.constraint_schema_pairings
Any pydantic._internal._known_annotated_metadata.as_jsonable_value(Any v)
Referenced by pydantic._internal._known_annotated_metadata.apply_known_metadata.
Iterable[Any] pydantic._internal._known_annotated_metadata.expand_grouped_metadata(Iterable[Any] annotations)
Expand the annotations. Args: annotations: An iterable of annotations. Returns: An iterable of expanded annotations. Example: ```python from annotated_types import Ge, Len from pydantic._internal._known_annotated_metadata import expand_grouped_metadata print(list(expand_grouped_metadata([Ge(4), Len(5)]))) #> [Ge(ge=4), MinLen(min_length=5)] ```
Referenced by pydantic._internal._known_annotated_metadata.collect_known_metadata.
dict[type, str] pydantic._internal._known_annotated_metadata._get_at_to_constraint_map()
Return a mapping of annotated types to constraints. Normally, we would define a mapping like this in the module scope, but we can't do that because we don't permit module level imports of `annotated_types`, in an attempt to speed up the import time of `pydantic`. We still only want to have this dictionary defined in one place, so we use this function to cache the result.
Referenced by pydantic._internal._known_annotated_metadata.apply_known_metadata, pydantic._internal._known_annotated_metadata.collect_known_metadata.
CoreSchema | None pydantic._internal._known_annotated_metadata.apply_known_metadata(Any annotation, CoreSchema schema)
Apply `annotation` to `schema` if it is an annotation we know about (Gt, Le, etc.). Otherwise return `None`. This does not handle all known annotations. If / when it does, it can always return a CoreSchema and return the unmodified schema if the annotation should be ignored. Assumes that GroupedMetadata has already been expanded via `expand_grouped_metadata`. Args: annotation: The annotation. schema: The schema. Returns: An updated schema with annotation if it is an annotation we know about, `None` otherwise. Raises: RuntimeError: If a constraint can't be applied to a specific schema type. ValueError: If an unknown constraint is encountered.
References pydantic._internal._known_annotated_metadata._get_at_to_constraint_map, pydantic._internal._known_annotated_metadata.apply_known_metadata, pydantic._internal._known_annotated_metadata.as_jsonable_value, pydantic._internal._known_annotated_metadata.collect_known_metadata.
Referenced by pydantic._internal._known_annotated_metadata.apply_known_metadata.
tuple[dict[str, Any], list[Any]] pydantic._internal._known_annotated_metadata.collect_known_metadata(Iterable[Any] annotations)
Split `annotations` into known metadata and unknown annotations. Args: annotations: An iterable of annotations. Returns: A tuple contains a dict of known metadata and a list of unknown annotations. Example: ```python from annotated_types import Gt, Len from pydantic._internal._known_annotated_metadata import collect_known_metadata print(collect_known_metadata([Gt(1), Len(42), ...])) #> ({'gt': 1, 'min_length': 42}, [Ellipsis]) ```
References pydantic._internal._known_annotated_metadata._get_at_to_constraint_map, pydantic._internal._known_annotated_metadata.expand_grouped_metadata.
Referenced by pydantic._internal._known_annotated_metadata.apply_known_metadata.
None pydantic._internal._known_annotated_metadata.check_metadata(dict[str, Any] metadata, Iterable[str] allowed, Any source_type)
A small utility function to validate that the given metadata can be applied to the target. More than saving lines of code, this gives us a consistent error message for all of our internal implementations. Args: metadata: A dict of metadata. allowed: An iterable of allowed metadata. source_type: The source type. Raises: TypeError: If there is metadatas that can't be applied on source type.