setuptools::_distutils::command::install_egg_info
setuptools._distutils.command.install_egg_info.safe_name(name)
Convert an arbitrary string to a standard distribution name Any runs of non-alphanumeric/. characters are replaced with a single '-'.
Referenced by setuptools._distutils.command.install_egg_info.install_egg_info.basename.
setuptools._distutils.command.install_egg_info.safe_version(version)
Convert an arbitrary string to a standard version string Spaces become dots, and all other non-alphanumeric characters become dashes, with runs of multiple dashes condensed to a single dash.
Referenced by setuptools._distutils.command.install_egg_info.install_egg_info.basename.
setuptools._distutils.command.install_egg_info.to_filename(name)
Convert a project or version name to its filename-escaped form Any '-' characters are currently replaced with '_'.
Referenced by setuptools._distutils.command.install_egg_info.install_egg_info.basename.