click::parser
click::parser.V
tuple[cabc.Sequence[str | cabc.Sequence[str | None] | None], list[str]] click.parser._unpack_args(cabc.Sequence[str] args, cabc.Sequence[int] nargs_spec)
Given an iterable of arguments and an iterable of nargs specifications, it returns a tuple with all the unpacked arguments at the first index and all remaining arguments as the second. The nargs specification is the number of arguments that should be consumed or `-1` to indicate that this position should eat up all the remainders. Missing items are filled with ``UNSET``.
Referenced by click.parser._OptionParser._process_args_for_args.
tuple[str, str] click.parser._split_opt(str opt)
Referenced by click.parser._normalize_opt.
str click.parser._normalize_opt(str opt, Context|None ctx)
References click.parser._split_opt.
Referenced by click.parser._OptionParser._match_short_opt, click.parser._OptionParser._process_opts, click.parser._OptionParser.add_option.