pydantic::types
pydantic::types.T
pydantic::types.StrictBool
pydantic::types.PositiveInt
pydantic::types.NegativeInt
pydantic::types.NonPositiveInt
pydantic::types.NonNegativeInt
pydantic::types.StrictInt
pydantic::types.PositiveFloat
pydantic::types.NegativeFloat
pydantic::types.NonPositiveFloat
pydantic::types.NonNegativeFloat
pydantic::types.StrictFloat
pydantic::types.FiniteFloat
pydantic::types.StrictBytes
pydantic::types.StrictStr
pydantic::types.HashableItemType
pydantic::types.AnyItemType
pydantic::types.AnyType
Referenced by pydantic.mypy.PydanticModelTransformer._infer_dataclass_attr_init_type, pydantic.v1.mypy.PydanticModelTransformer.add_construct_method, pydantic.mypy.PydanticModelTransformer.add_initializer, pydantic.v1.mypy.PydanticModelTransformer.add_initializer, pydantic.mypy.PydanticModelTransformer.add_model_construct_method, pydantic.mypy.PydanticModelTransformer.collect_field_or_class_var_from_stmt, pydantic.mypy.PydanticModelField.to_argument, pydantic.v1.mypy.PydanticModelField.to_argument.
pydantic::types.ImportString
pydantic::types.UUID1
pydantic::types.UUID3
pydantic::types.UUID4
pydantic::types.UUID5
pydantic::types.UUID6
pydantic::types.UUID7
pydantic::types.UUID8
pydantic::types.FilePath
pydantic::types.DirectoryPath
pydantic::types.NewPath
pydantic::types.SocketPath
pydantic::types.Json
pydantic::types.SecretType
pydantic::types.PastDate
pydantic::types.FutureDate
pydantic::types.AwareDatetime
pydantic::types.NaiveDatetime
pydantic::types.PastDatetime
pydantic::types.FutureDatetime
pydantic::types.Base64Bytes
pydantic::types.Base64Str
pydantic::types.Base64UrlBytes
pydantic::types.Base64UrlStr
dict pydantic::types._JSON_TYPES
pydantic::types.JsonValue
pydantic::types.OnErrorOmit
type[int] pydantic.types.conint(*, bool|None strict=None, int|None gt=None, int|None ge=None, int|None lt=None, int|None le=None, int|None multiple_of=None)
!!! warning "Discouraged" This function is **discouraged** in favor of using [`Annotated`](https://docs.python.org/3/library/typing.html#typing.Annotated) with [`Field`][pydantic.fields.Field] instead. This function will be **deprecated** in Pydantic 3.0. The reason is that `conint` returns a type, which doesn't play well with static analysis tools. === ":x: Don't do this" ```python from pydantic import BaseModel, conint class Foo(BaseModel): bar: conint(strict=True, gt=0) ``` === ":white_check_mark: Do this" ```python from typing import Annotated from pydantic import BaseModel, Field class Foo(BaseModel): bar: Annotated[int, Field(strict=True, gt=0)] ``` A wrapper around `int` that allows for additional constraints. Args: strict: Whether to validate the integer in strict mode. Defaults to `None`. gt: The value must be greater than this. ge: The value must be greater than or equal to this. lt: The value must be less than this. le: The value must be less than or equal to this. multiple_of: The value must be a multiple of this. Returns: The wrapped integer type. ```python from pydantic import BaseModel, ValidationError, conint class ConstrainedExample(BaseModel): constrained_int: conint(gt=1) m = ConstrainedExample(constrained_int=2) print(repr(m)) #> ConstrainedExample(constrained_int=2) try: ConstrainedExample(constrained_int=0) except ValidationError as e: print(e.errors()) ''' [ { 'type': 'greater_than', 'loc': ('constrained_int',), 'msg': 'Input should be greater than 1', 'input': 0, 'ctx': {'gt': 1}, 'url': 'https://errors.pydantic.dev/2/v/greater_than', } ] ''' ```
type[float] pydantic.types.confloat(*, bool|None strict=None, float|None gt=None, float|None ge=None, float|None lt=None, float|None le=None, float|None multiple_of=None, bool|None allow_inf_nan=None)
!!! warning "Discouraged" This function is **discouraged** in favor of using [`Annotated`](https://docs.python.org/3/library/typing.html#typing.Annotated) with [`Field`][pydantic.fields.Field] instead. This function will be **deprecated** in Pydantic 3.0. The reason is that `confloat` returns a type, which doesn't play well with static analysis tools. === ":x: Don't do this" ```python from pydantic import BaseModel, confloat class Foo(BaseModel): bar: confloat(strict=True, gt=0) ``` === ":white_check_mark: Do this" ```python from typing import Annotated from pydantic import BaseModel, Field class Foo(BaseModel): bar: Annotated[float, Field(strict=True, gt=0)] ``` A wrapper around `float` that allows for additional constraints. Args: strict: Whether to validate the float in strict mode. gt: The value must be greater than this. ge: The value must be greater than or equal to this. lt: The value must be less than this. le: The value must be less than or equal to this. multiple_of: The value must be a multiple of this. allow_inf_nan: Whether to allow `-inf`, `inf`, and `nan`. Returns: The wrapped float type. ```python from pydantic import BaseModel, ValidationError, confloat class ConstrainedExample(BaseModel): constrained_float: confloat(gt=1.0) m = ConstrainedExample(constrained_float=1.1) print(repr(m)) #> ConstrainedExample(constrained_float=1.1) try: ConstrainedExample(constrained_float=0.9) except ValidationError as e: print(e.errors()) ''' [ { 'type': 'greater_than', 'loc': ('constrained_float',), 'msg': 'Input should be greater than 1', 'input': 0.9, 'ctx': {'gt': 1.0}, 'url': 'https://errors.pydantic.dev/2/v/greater_than', } ] ''' ```
type[bytes] pydantic.types.conbytes(*, int|None min_length=None, int|None max_length=None, bool|None strict=None)
A wrapper around `bytes` that allows for additional constraints. Args: min_length: The minimum length of the bytes. max_length: The maximum length of the bytes. strict: Whether to validate the bytes in strict mode. Returns: The wrapped bytes type.
type[str] pydantic.types.constr(*, bool|None strip_whitespace=None, bool|None to_upper=None, bool|None to_lower=None, bool|None strict=None, int|None min_length=None, int|None max_length=None, str|Pattern[str]|None pattern=None)
!!! warning "Discouraged" This function is **discouraged** in favor of using [`Annotated`](https://docs.python.org/3/library/typing.html#typing.Annotated) with [`StringConstraints`][pydantic.types.StringConstraints] instead. This function will be **deprecated** in Pydantic 3.0. The reason is that `constr` returns a type, which doesn't play well with static analysis tools. === ":x: Don't do this" ```python from pydantic import BaseModel, constr class Foo(BaseModel): bar: constr(strip_whitespace=True, to_upper=True, pattern=r'^[A-Z]+$') ``` === ":white_check_mark: Do this" ```python from typing import Annotated from pydantic import BaseModel, StringConstraints class Foo(BaseModel): bar: Annotated[ str, StringConstraints( strip_whitespace=True, to_upper=True, pattern=r'^[A-Z]+$' ), ] ``` A wrapper around `str` that allows for additional constraints. ```python from pydantic import BaseModel, constr class Foo(BaseModel): bar: constr(strip_whitespace=True, to_upper=True) foo = Foo(bar=' hello ') print(foo) #> bar='HELLO' ``` Args: strip_whitespace: Whether to remove leading and trailing whitespace. to_upper: Whether to turn all characters to uppercase. to_lower: Whether to turn all characters to lowercase. strict: Whether to validate the string in strict mode. min_length: The minimum length of the string. max_length: The maximum length of the string. pattern: A regex pattern to validate the string against. Returns: The wrapped string type.
type[set[HashableItemType]] pydantic.types.conset(type[HashableItemType] item_type, *, int|None min_length=None, int|None max_length=None)
A wrapper around `typing.Set` that allows for additional constraints. Args: item_type: The type of the items in the set. min_length: The minimum length of the set. max_length: The maximum length of the set. Returns: The wrapped set type.
type[frozenset[HashableItemType]] pydantic.types.confrozenset(type[HashableItemType] item_type, *, int|None min_length=None, int|None max_length=None)
A wrapper around `typing.FrozenSet` that allows for additional constraints. Args: item_type: The type of the items in the frozenset. min_length: The minimum length of the frozenset. max_length: The maximum length of the frozenset. Returns: The wrapped frozenset type.
type[list[AnyItemType]] pydantic.types.conlist(type[AnyItemType] item_type, *, int|None min_length=None, int|None max_length=None, bool|None unique_items=None)
A wrapper around [`list`][] that adds validation. Args: item_type: The type of the items in the list. min_length: The minimum length of the list. Defaults to None. max_length: The maximum length of the list. Defaults to None. unique_items: Whether the items in the list must be unique. Defaults to None. !!! warning Deprecated The `unique_items` parameter is deprecated, use `Set` instead. See [this issue](https://github.com/pydantic/pydantic-core/issues/296) for more details. Returns: The wrapped list type.
type[Decimal] pydantic.types.condecimal(*, bool|None strict=None, int|Decimal|None gt=None, int|Decimal|None ge=None, int|Decimal|None lt=None, int|Decimal|None le=None, int|Decimal|None multiple_of=None, int|None max_digits=None, int|None decimal_places=None, bool|None allow_inf_nan=None)
!!! warning "Discouraged" This function is **discouraged** in favor of using [`Annotated`](https://docs.python.org/3/library/typing.html#typing.Annotated) with [`Field`][pydantic.fields.Field] instead. This function will be **deprecated** in Pydantic 3.0. The reason is that `condecimal` returns a type, which doesn't play well with static analysis tools. === ":x: Don't do this" ```python from pydantic import BaseModel, condecimal class Foo(BaseModel): bar: condecimal(strict=True, allow_inf_nan=True) ``` === ":white_check_mark: Do this" ```python from decimal import Decimal from typing import Annotated from pydantic import BaseModel, Field class Foo(BaseModel): bar: Annotated[Decimal, Field(strict=True, allow_inf_nan=True)] ``` A wrapper around Decimal that adds validation. Args: strict: Whether to validate the value in strict mode. Defaults to `None`. gt: The value must be greater than this. Defaults to `None`. ge: The value must be greater than or equal to this. Defaults to `None`. lt: The value must be less than this. Defaults to `None`. le: The value must be less than or equal to this. Defaults to `None`. multiple_of: The value must be a multiple of this. Defaults to `None`. max_digits: The maximum number of digits. Defaults to `None`. decimal_places: The number of decimal places. Defaults to `None`. allow_inf_nan: Whether to allow infinity and NaN. Defaults to `None`. ```python from decimal import Decimal from pydantic import BaseModel, ValidationError, condecimal class ConstrainedExample(BaseModel): constrained_decimal: condecimal(gt=Decimal('1.0')) m = ConstrainedExample(constrained_decimal=Decimal('1.1')) print(repr(m)) #> ConstrainedExample(constrained_decimal=Decimal('1.1')) try: ConstrainedExample(constrained_decimal=Decimal('0.9')) except ValidationError as e: print(e.errors()) ''' [ { 'type': 'greater_than', 'loc': ('constrained_decimal',), 'msg': 'Input should be greater than 1.0', 'input': Decimal('0.9'), 'ctx': {'gt': Decimal('1.0')}, 'url': 'https://errors.pydantic.dev/2/v/greater_than', } ] ''' ```
str | Secret[SecretType] pydantic.types._serialize_secret(Secret[SecretType] value, core_schema.SerializationInfo info)
str pydantic.types._secret_display(SecretType value)
Referenced by pydantic.types.SecretBytes._display, pydantic.types.SecretStr._display, pydantic.types._serialize_secret_field.
str | _SecretField[SecretType] pydantic.types._serialize_secret_field(_SecretField[SecretType] value, core_schema.SerializationInfo info)
References pydantic.types._secret_display.
None pydantic.types._check_annotated_type(str annotated_type, str expected_type, str annotation)
type[date] pydantic.types.condate(*, bool|None strict=None, date|None gt=None, date|None ge=None, date|None lt=None, date|None le=None)
A wrapper for date that adds constraints. Args: strict: Whether to validate the date value in strict mode. Defaults to `None`. gt: The value must be greater than this. Defaults to `None`. ge: The value must be greater than or equal to this. Defaults to `None`. lt: The value must be less than this. Defaults to `None`. le: The value must be less than or equal to this. Defaults to `None`. Returns: A date type with the specified constraints.
str pydantic.types._get_type_name(Any x)