pip::_internal::commands::list
pip::_internal::commands::list._ProcessedDists
pip::_internal::commands::list.logger
tuple[list[list[str]], list[str]] pip._internal.commands.list.format_for_columns(_ProcessedDists pkgs, Values options)
Convert the package data into something usable by output_package_listing_columns.
Referenced by pip._internal.commands.list.ListCommand.output_package_listing, pip._internal.commands.list.ListCommand.output_package_listing.
str pip._internal.commands.list.format_for_json(_ProcessedDists packages, Values options)
Referenced by pip._internal.commands.list.ListCommand.output_package_listing, pip._internal.commands.list.ListCommand.output_package_listing.
Tuple[List[List[str]], List[str]] pip._internal.commands.list.format_for_columns("_ProcessedDists" pkgs, Values options)
Convert the package data into something usable by output_package_listing_columns.
str pip._internal.commands.list.format_for_json("_ProcessedDists" packages, Values options)