pip::_internal::req::req_file
pip::_internal::req::req_file.ReqFileLines
pip::_internal::req::req_file.LineParser
pip::_internal::req::req_file.SCHEME_RE
pip::_internal::req::req_file.COMMENT_RE
pip::_internal::req::req_file.ENV_VAR_RE
list pip::_internal::req::req_file::SUPPORTED_OPTIONS
list pip::_internal::req::req_file::SUPPORTED_OPTIONS_REQ
list pip::_internal::req::req_file::SUPPORTED_OPTIONS_EDITABLE_REQ
list pip::_internal::req::req_file::SUPPORTED_OPTIONS_REQ_DEST
list pip::_internal::req::req_file::SUPPORTED_OPTIONS_EDITABLE_REQ_DEST
list pip::_internal::req::req_file.BOMS
pip::_internal::req::req_file.PEP263_ENCODING_RE
str pip::_internal::req::req_file.DEFAULT_ENCODING
pip::_internal::req::req_file.logger
Generator[ParsedRequirement, None, None] pip._internal.req.req_file.parse_requirements(str filename, PipSession session, PackageFinder|None finder=None, optparse.Values|None options=None, bool constraint=False)
Parse a requirements file and yield ParsedRequirement instances. :param filename: Path or url of requirements file. :param session: PipSession instance. :param finder: Instance of pip.index.PackageFinder. :param options: cli options. :param constraint: If true, parsing a constraint file rather than requirements file.
References pip._internal.req.req_file.get_line_parser, pip._internal.req.req_file.handle_line.
ReqFileLines pip::_internal::req::req_file::preprocess(str content)
Split, filter, and join lines, and return a line iterator :param content: the content of the requirements file
References pip._internal.req.req_file.expand_env_variables, pip._internal.req.req_file.ignore_comments, pip._internal.req.req_file.join_lines.
Referenced by pip._internal.req.req_file.RequirementsFileParser._parse_file.
ParsedRequirement pip._internal.req.req_file.handle_requirement_line(ParsedLine line, optparse.Values|None options=None)
Referenced by pip._internal.req.req_file.handle_line, pip._internal.req.req_file.handle_line.
None pip._internal.req.req_file.handle_option_line(Values opts, str filename, int lineno, PackageFinder|None finder=None, optparse.Values|None options=None, PipSession|None session=None)
Referenced by pip._internal.req.req_file.handle_line, pip._internal.req.req_file.handle_line.
ParsedRequirement | None pip._internal.req.req_file.handle_line(ParsedLine line, optparse.Values|None options=None, PackageFinder|None finder=None, PipSession|None session=None)
Handle a single parsed requirements line; This can result in creating/yielding requirements, or updating the finder. :param line: The parsed line to be processed. :param options: CLI options. :param finder: The finder - updated by non-requirement lines. :param session: The session - updated by non-requirement lines. Returns a ParsedRequirement object if the line is a requirement line, otherwise returns None. For lines that contain requirements, the only options that have an effect are from SUPPORTED_OPTIONS_REQ, and they are scoped to the requirement. Other options from SUPPORTED_OPTIONS may be present, but are ignored. For lines that do not contain requirements, the only options that have an effect are from SUPPORTED_OPTIONS. Options from SUPPORTED_OPTIONS_REQ may be present, but are ignored. These lines may contain multiple options (although our docs imply only one is supported), and all our parsed and affect the finder.
References pip._internal.req.req_file.handle_option_line, pip._internal.req.req_file.handle_requirement_line.
Referenced by pip._internal.req.req_file.parse_requirements, pip._internal.req.req_file.parse_requirements.
LineParser pip._internal.req.req_file.get_line_parser(PackageFinder|None finder)
References pip._internal.req.req_file.break_args_options, pip._internal.req.req_file.build_parser.
Referenced by pip._internal.req.req_file.parse_requirements, pip._internal.req.req_file.parse_requirements.
tuple[str, str] pip._internal.req.req_file.break_args_options(str line)
Break up the line into an args and options string. We only want to shlex (and then optparse) the options, not the args. args can contain markers which are corrupted by shlex.
Referenced by pip._internal.req.req_file.get_line_parser, pip._internal.req.req_file.get_line_parser.
optparse OptionParser pip::_internal::req::req_file::build_parser()
Return a parser for parsing requirement lines
Referenced by pip._internal.req.req_file.get_line_parser, pip._internal.req.req_file.get_line_parser.
ReqFileLines pip::_internal::req::req_file::join_lines(ReqFileLines lines_enum)
Joins a line ending in '\' with the previous line (except when following comments). The joined line takes on the index of the first line.
Referenced by pip._internal.req.req_file.parse_requirements, pip._internal.req.req_file.preprocess.
ReqFileLines pip::_internal::req::req_file::ignore_comments(ReqFileLines lines_enum)
Strips comments and filter empty lines.
Referenced by pip._internal.req.req_file.parse_requirements, pip._internal.req.req_file.preprocess.
ReqFileLines pip::_internal::req::req_file::expand_env_variables(ReqFileLines lines_enum)
Replace all environment variables that can be retrieved via `os.getenv`. The only allowed format for environment variables defined in the requirement file is `${MY_VARIABLE_1}` to ensure two things: 1. Strings that contain a `$` aren't accidentally (partially) expanded. 2. Ensure consistency across platforms for requirement files. These points are the result of a discussion on the `github pull request #3514 <https://github.com/pypa/pip/pull/3514>`_. Valid characters in variable names follow the `POSIX standard <http://pubs.opengroup.org/onlinepubs/9699919799/>`_ and are limited to uppercase letter, digits and the `_` (underscore).
Referenced by pip._internal.req.req_file.parse_requirements, pip._internal.req.req_file.preprocess.
tuple[str, str] pip._internal.req.req_file.get_file_content(str url, PipSession session)
Gets the content of a file; it may be a filename, file: URL, or http: URL. Returns (location, content). Content is unicode. Respects # -*- coding: declarations on the retrieved files. :param url: File path or url. :param session: PipSession instance.
References pip._internal.req.req_file._decode_req_file.
Referenced by pip._internal.req.req_file.RequirementsFileParser._parse_file.
str pip._internal.req.req_file._decode_req_file(bytes data, str url)
Referenced by pip._internal.req.req_file.get_file_content.
Generator[ParsedRequirement, None, None] pip._internal.req.req_file.parse_requirements(str filename, PipSession session, Optional["PackageFinder"] finder=None, Optional[optparse.Values] options=None, bool constraint=False)
Parse a requirements file and yield ParsedRequirement instances. :param filename: Path or url of requirements file. :param session: PipSession instance. :param finder: Instance of pip.index.PackageFinder. :param options: cli options. :param constraint: If true, parsing a constraint file rather than requirements file.
References pip._internal.req.req_file.expand_env_variables, pip._internal.req.req_file.get_line_parser, pip._internal.req.req_file.handle_line, pip._internal.req.req_file.ignore_comments, pip._internal.req.req_file.join_lines.
ParsedRequirement pip._internal.req.req_file.handle_requirement_line(ParsedLine line, Optional[optparse.Values] options=None)
None pip._internal.req.req_file.handle_option_line(Values opts, str filename, int lineno, Optional["PackageFinder"] finder=None, Optional[optparse.Values] options=None, Optional[PipSession] session=None)
Optional[ParsedRequirement] pip._internal.req.req_file.handle_line(ParsedLine line, Optional[optparse.Values] options=None, Optional["PackageFinder"] finder=None, Optional[PipSession] session=None)
Handle a single parsed requirements line; This can result in creating/yielding requirements, or updating the finder. :param line: The parsed line to be processed. :param options: CLI options. :param finder: The finder - updated by non-requirement lines. :param session: The session - updated by non-requirement lines. Returns a ParsedRequirement object if the line is a requirement line, otherwise returns None. For lines that contain requirements, the only options that have an effect are from SUPPORTED_OPTIONS_REQ, and they are scoped to the requirement. Other options from SUPPORTED_OPTIONS may be present, but are ignored. For lines that do not contain requirements, the only options that have an effect are from SUPPORTED_OPTIONS. Options from SUPPORTED_OPTIONS_REQ may be present, but are ignored. These lines may contain multiple options (although our docs imply only one is supported), and all our parsed and affect the finder.
References pip._internal.req.req_file.handle_option_line, pip._internal.req.req_file.handle_requirement_line.
LineParser pip._internal.req.req_file.get_line_parser(Optional["PackageFinder"] finder)
References pip._internal.req.req_file.break_args_options, pip._internal.req.req_file.build_parser.