pydantic::v1::schema
str pydantic::v1::schema.default_prefix
str pydantic::v1::schema.default_ref_template
pydantic::v1::schema.TypeModelOrEnum
pydantic::v1::schema.TypeModelSet
tuple pydantic::v1::schema.numeric_types
tuple pydantic::v1::schema._str_types_attrs
tuple pydantic::v1::schema._numeric_types_attrs
tuple pydantic::v1::schema.field_class_to_schema
dict pydantic::v1::schema.json_scheme
dict pydantic::v1::schema._map_types_constraint
None pydantic.v1.schema._apply_modify_schema(Callable[..., None] modify_schema, Optional[ModelField] field, Dict[str, Any] field_schema)
Referenced by pydantic.v1.schema.enum_process_schema, pydantic.v1.schema.field_singleton_schema, pydantic.v1.schema.field_type_schema, pydantic.v1.schema.get_field_schema_validations.
Dict[str, Any] pydantic.v1.schema.schema(Sequence[Union[Type['BaseModel'], Type['Dataclass']]] models, *, bool by_alias=True, Optional[str] title=None, Optional[str] description=None, Optional[str] ref_prefix=None, str ref_template=default_ref_template)
Process a list of models and generate a single JSON Schema with all of them defined in the ``definitions`` top-level JSON key, including their sub-models. :param models: a list of models to include in the generated JSON Schema :param by_alias: generate the schemas using the aliases defined, if any :param title: title for the generated schema that includes the definitions :param description: description for the generated schema :param ref_prefix: the JSON Pointer prefix for schema references with ``$ref``, if None, will be set to the default of ``#/definitions/``. Update it if you want the schemas to reference the definitions somewhere else, e.g. for OpenAPI use ``#/components/schemas/``. The resulting generated schemas will still be at the top-level key ``definitions``, so you can extract them from there. But all the references will have the set prefix. :param ref_template: Use a ``string.format()`` template for ``$ref`` instead of a prefix. This can be useful for references that cannot be represented by ``ref_prefix`` such as a definition stored in another file. For a sibling json file in a ``/schemas`` directory use ``"/schemas/${model}.json#"``. :return: dict with the JSON Schema with a ``definitions`` top-level key including the schema definitions for the models and sub-models passed in ``models``.
References pydantic.v1.schema.get_flat_models_from_models, pydantic.v1.schema.get_model_name_map, pydantic.v1.schema.model_process_schema.
Dict[str, Any] pydantic.v1.schema.model_schema(Union[Type['BaseModel'], Type['Dataclass']] model, bool by_alias=True, Optional[str] ref_prefix=None, str ref_template=default_ref_template)
Generate a JSON Schema for one model. With all the sub-models defined in the ``definitions`` top-level JSON key. :param model: a Pydantic model (a class that inherits from BaseModel) :param by_alias: generate the schemas using the aliases defined, if any :param ref_prefix: the JSON Pointer prefix for schema references with ``$ref``, if None, will be set to the default of ``#/definitions/``. Update it if you want the schemas to reference the definitions somewhere else, e.g. for OpenAPI use ``#/components/schemas/``. The resulting generated schemas will still be at the top-level key ``definitions``, so you can extract them from there. But all the references will have the set prefix. :param ref_template: Use a ``string.format()`` template for ``$ref`` instead of a prefix. This can be useful for references that cannot be represented by ``ref_prefix`` such as a definition stored in another file. For a sibling json file in a ``/schemas`` directory use ``"/schemas/${model}.json#"``. :return: dict with the JSON Schema for the passed ``model``
References pydantic.v1.schema.get_flat_models_from_model, pydantic.v1.schema.get_model_name_map, pydantic.v1.schema.get_schema_ref, pydantic.v1.schema.model_process_schema.
Tuple[Dict[str, Any], bool] pydantic.v1.schema.get_field_info_schema(ModelField field, bool schema_overrides=False)
References pydantic.v1.schema.encode_default.
Referenced by pydantic.v1.schema.field_schema, pydantic.v1.schema.field_singleton_schema.
Tuple[Dict[str, Any], Dict[str, Any], Set[str]] pydantic.v1.schema.field_schema(ModelField field, *, bool by_alias=True, Dict[TypeModelOrEnum, str] model_name_map, Optional[str] ref_prefix=None, str ref_template=default_ref_template, Optional[TypeModelSet] known_models=None)
Process a Pydantic field and return a tuple with a JSON Schema for it as the first item. Also return a dictionary of definitions with models as keys and their schemas as values. If the passed field is a model and has sub-models, and those sub-models don't have overrides (as ``title``, ``default``, etc), they will be included in the definitions and referenced in the schema instead of included recursively. :param field: a Pydantic ``ModelField`` :param by_alias: use the defined alias (if any) in the returned schema :param model_name_map: used to generate the JSON Schema references to other models included in the definitions :param ref_prefix: the JSON Pointer prefix to use for references to other schemas, if None, the default of #/definitions/ will be used :param ref_template: Use a ``string.format()`` template for ``$ref`` instead of a prefix. This can be useful for references that cannot be represented by ``ref_prefix`` such as a definition stored in another file. For a sibling json file in a ``/schemas`` directory use ``"/schemas/${model}.json#"``. :param known_models: used to solve circular references :return: tuple of the schema for this field and additional definitions
References pydantic.v1.schema.field_type_schema, pydantic.v1.schema.get_field_info_schema, pydantic.v1.schema.get_field_schema_validations.
Referenced by pydantic.v1.schema.field_singleton_schema, pydantic.v1.schema.model_type_schema.
Dict[str, Any] pydantic.v1.schema.get_field_schema_validations(ModelField field)
Get the JSON Schema validation keywords for a ``field`` with an annotation of a Pydantic ``FieldInfo`` with validation arguments.
References pydantic.v1.schema._apply_modify_schema.
Referenced by pydantic.v1.schema.field_schema.
Dict[TypeModelOrEnum, str] pydantic.v1.schema.get_model_name_map(TypeModelSet unique_models)
Process a set of models and generate unique names for them to be used as keys in the JSON Schema definitions. By default the names are the same as the class name. But if two models in different Python modules have the same name (e.g. "users.Model" and "items.Model"), the generated names will be based on the Python module path for those conflicting models to prevent name collisions. :param unique_models: a Python set of models :return: dict mapping models to names
References pydantic.v1.schema.get_long_model_name, pydantic.v1.schema.normalize_name.
Referenced by pydantic.v1.schema.model_schema, pydantic.v1.schema.schema.
TypeModelSet pydantic.v1.schema.get_flat_models_from_model(Type['BaseModel'] model, Optional[TypeModelSet] known_models=None)
Take a single ``model`` and generate a set with itself and all the sub-models in the tree. I.e. if you pass model ``Foo`` (subclass of Pydantic ``BaseModel``) as ``model``, and it has a field of type ``Bar`` (also subclass of ``BaseModel``) and that model ``Bar`` has a field of type ``Baz`` (also subclass of ``BaseModel``), the return value will be ``set([Foo, Bar, Baz])``. :param model: a Pydantic ``BaseModel`` subclass :param known_models: used to solve circular references :return: a set with the initial model and all its sub-models
References pydantic.v1.schema.get_flat_models_from_fields.
Referenced by pydantic.v1.schema.get_flat_models_from_field, pydantic.v1.schema.get_flat_models_from_models, pydantic.v1.schema.model_schema.
TypeModelSet pydantic.v1.schema.get_flat_models_from_field(ModelField field, TypeModelSet known_models)
Take a single Pydantic ``ModelField`` (from a model) that could have been declared as a subclass of BaseModel (so, it could be a submodel), and generate a set with its model and all the sub-models in the tree. I.e. if you pass a field that was declared to be of type ``Foo`` (subclass of BaseModel) as ``field``, and that model ``Foo`` has a field of type ``Bar`` (also subclass of ``BaseModel``) and that model ``Bar`` has a field of type ``Baz`` (also subclass of ``BaseModel``), the return value will be ``set([Foo, Bar, Baz])``. :param field: a Pydantic ``ModelField`` :param known_models: used to solve circular references :return: a set with the model used in the declaration for this field, if any, and all its sub-models
References pydantic.v1.schema.get_flat_models_from_fields, pydantic.v1.schema.get_flat_models_from_model.
Referenced by pydantic.v1.schema.get_flat_models_from_fields.
TypeModelSet pydantic.v1.schema.get_flat_models_from_fields(Sequence[ModelField] fields, TypeModelSet known_models)
Take a list of Pydantic ``ModelField``s (from a model) that could have been declared as subclasses of ``BaseModel`` (so, any of them could be a submodel), and generate a set with their models and all the sub-models in the tree. I.e. if you pass a the fields of a model ``Foo`` (subclass of ``BaseModel``) as ``fields``, and on of them has a field of type ``Bar`` (also subclass of ``BaseModel``) and that model ``Bar`` has a field of type ``Baz`` (also subclass of ``BaseModel``), the return value will be ``set([Foo, Bar, Baz])``. :param fields: a list of Pydantic ``ModelField``s :param known_models: used to solve circular references :return: a set with any model declared in the fields, and all their sub-models
References pydantic.v1.schema.get_flat_models_from_field.
Referenced by pydantic.v1.schema.get_flat_models_from_field, pydantic.v1.schema.get_flat_models_from_model.
TypeModelSet pydantic.v1.schema.get_flat_models_from_models(Sequence[Type['BaseModel']] models)
Take a list of ``models`` and generate a set with them and all their sub-models in their trees. I.e. if you pass a list of two models, ``Foo`` and ``Bar``, both subclasses of Pydantic ``BaseModel`` as models, and ``Bar`` has a field of type ``Baz`` (also subclass of ``BaseModel``), the return value will be ``set([Foo, Bar, Baz])``.
References pydantic.v1.schema.get_flat_models_from_model.
Referenced by pydantic.v1.schema.schema.
str pydantic.v1.schema.get_long_model_name(TypeModelOrEnum model)
Referenced by pydantic.v1.schema.get_model_name_map.
Tuple[Dict[str, Any], Dict[str, Any], Set[str]] pydantic.v1.schema.field_type_schema(ModelField field, *, bool by_alias, Dict[TypeModelOrEnum, str] model_name_map, str ref_template, bool schema_overrides=False, Optional[str] ref_prefix=None, TypeModelSet known_models)
Used by ``field_schema()``, you probably should be using that function. Take a single ``field`` and generate the schema for its type only, not including additional information as title, etc. Also return additional schema definitions, from sub-models.
References pydantic.v1.schema._apply_modify_schema, pydantic.v1.schema.field_singleton_schema, pydantic.v1.schema.field_type_schema.
Referenced by pydantic.v1.schema.field_schema, pydantic.v1.schema.field_singleton_sub_fields_schema, pydantic.v1.schema.field_type_schema.
Tuple[Dict[str, Any], Dict[str, Any], Set[str]] pydantic.v1.schema.model_process_schema(TypeModelOrEnum model, *, bool by_alias=True, Dict[TypeModelOrEnum, str] model_name_map, Optional[str] ref_prefix=None, str ref_template=default_ref_template, Optional[TypeModelSet] known_models=None, Optional[ModelField] field=None)
Used by ``model_schema()``, you probably should be using that function. Take a single ``model`` and generate its schema. Also return additional schema definitions, from sub-models. The sub-models of the returned schema will be referenced, but their definitions will not be included in the schema. All the definitions are returned as the second value.
References pydantic.v1.schema.enum_process_schema, pydantic.v1.schema.model_type_schema.
Referenced by pydantic.v1.schema.field_singleton_schema, pydantic.v1.schema.model_schema, pydantic.v1.schema.schema.
Tuple[Dict[str, Any], Dict[str, Any], Set[str]] pydantic.v1.schema.model_type_schema(Type['BaseModel'] model, *, bool by_alias, Dict[TypeModelOrEnum, str] model_name_map, str ref_template, Optional[str] ref_prefix=None, TypeModelSet known_models)
You probably should be using ``model_schema()``, this function is indirectly used by that function. Take a single ``model`` and generate the schema for its type only, not including additional information as title, etc. Also return additional schema definitions, from sub-models.
References pydantic.v1.schema.field_schema.
Referenced by pydantic.v1.schema.model_process_schema.
Dict[str, Any] pydantic.v1.schema.enum_process_schema(Type[Enum] enum, *, Optional[ModelField] field=None)
Take a single `enum` and generate its schema. This is similar to the `model_process_schema` function, but applies to ``Enum`` objects.
References pydantic.v1.schema._apply_modify_schema, pydantic.v1.schema.add_field_type_to_schema.
Referenced by pydantic.v1.schema.field_singleton_schema, pydantic.v1.schema.model_process_schema.
Tuple[Dict[str, Any], Dict[str, Any], Set[str]] pydantic.v1.schema.field_singleton_sub_fields_schema(ModelField field, *, bool by_alias, Dict[TypeModelOrEnum, str] model_name_map, str ref_template, bool schema_overrides=False, Optional[str] ref_prefix=None, TypeModelSet known_models)
This function is indirectly used by ``field_schema()``, you probably should be using that function. Take a list of Pydantic ``ModelField`` from the declaration of a type with parameters, and generate their schema. I.e., fields used as "type parameters", like ``str`` and ``int`` in ``Tuple[str, int]``.
References pydantic.v1.schema.field_type_schema, pydantic.v1.schema.get_schema_ref.
Referenced by pydantic.v1.schema.field_singleton_schema.
None pydantic.v1.schema.add_field_type_to_schema(Any field_type, Dict[str, Any] schema_)
Update the given `schema` with the type-specific metadata for the given `field_type`. This function looks through `field_class_to_schema` for a class that matches the given `field_type`, and then modifies the given `schema` with the information from that type.
Referenced by pydantic.v1.schema.enum_process_schema, pydantic.v1.schema.field_singleton_schema.
Dict[str, Any] pydantic.v1.schema.get_schema_ref(str name, Optional[str] ref_prefix, str ref_template, bool schema_overrides)
Referenced by pydantic.v1.schema.field_singleton_schema, pydantic.v1.schema.field_singleton_sub_fields_schema, pydantic.v1.schema.model_schema.
Tuple[Dict[str, Any], Dict[str, Any], Set[str]] pydantic.v1.schema.field_singleton_schema(ModelField field, *, bool by_alias, Dict[TypeModelOrEnum, str] model_name_map, str ref_template, bool schema_overrides=False, Optional[str] ref_prefix=None, TypeModelSet known_models)
This function is indirectly used by ``field_schema()``, you should probably be using that function. Take a single Pydantic ``ModelField``, and return its schema and any additional definitions from sub-models.
References pydantic.v1.schema._apply_modify_schema, pydantic.v1.schema.add_field_type_to_schema, pydantic.v1.schema.enum_process_schema, pydantic.v1.schema.field_schema, pydantic.v1.schema.field_singleton_sub_fields_schema, pydantic.v1.schema.get_field_info_schema, pydantic.v1.schema.get_schema_ref, pydantic.v1.schema.model_process_schema, pydantic.v1.schema.multitypes_literal_field_for_schema.
Referenced by pydantic.v1.schema.field_type_schema.
ModelField pydantic.v1.schema.multitypes_literal_field_for_schema(Tuple[Any,...] values, ModelField field)
To support `Literal` with values of different types, we split it into multiple `Literal` with same type e.g. `Literal['qwe', 'asd', 1, 2]` becomes `Union[Literal['qwe', 'asd'], Literal[1, 2]]`
Referenced by pydantic.v1.schema.field_singleton_schema.
Any pydantic.v1.schema.encode_default(Any dft)
References pydantic.v1.schema.encode_default.
Referenced by pydantic.v1.schema.encode_default, pydantic.v1.schema.get_field_info_schema.
Type[Any] pydantic.v1.schema.get_annotation_from_field_info(Any annotation, FieldInfo field_info, str field_name, bool validate_assignment=False)
Get an annotation with validation implemented for numbers and strings based on the field_info. :param annotation: an annotation from a field specification, as ``str``, ``ConstrainedStr`` :param field_info: an instance of FieldInfo, possibly with declarations for validations and JSON Schema :param field_name: name of the field for use in error messages :param validate_assignment: default False, flag for BaseModel Config value of validate_assignment :return: the same ``annotation`` if unmodified or a new annotation with validation in place
References pydantic.v1.schema.get_annotation_with_constraints.
Tuple[Type[Any], Set[str]] pydantic.v1.schema.get_annotation_with_constraints(Any annotation, FieldInfo field_info)
Get an annotation with used constraints implemented for numbers and strings based on the field_info. :param annotation: an annotation from a field specification, as ``str``, ``ConstrainedStr`` :param field_info: an instance of FieldInfo, possibly with declarations for validations and JSON Schema :return: the same ``annotation`` if unmodified or a new annotation along with the used constraints.
References pydantic.v1.types.confrozenset, pydantic.v1.types.conlist, pydantic.v1.types.conset.
Referenced by pydantic.v1.schema.get_annotation_from_field_info.
str pydantic.v1.schema.normalize_name(str name)
Normalizes the given name. This can be applied to either a model *or* enum.
Referenced by pydantic.v1.schema.get_model_name_map.