pip::_internal::commands
pip::_internal::commands.CommandInfo
dict pip::_internal::commands::commands_dict
Command pip::_internal::commands::create_command(str name, **Any kwargs)
Create an instance of the Command class with the given name.
Referenced by pip._internal.commands.help.HelpCommand.run, pip._internal.commands.help.HelpCommand.run.
str | None pip._internal.commands.get_similar_commands(str name)
Command name auto-correct.
Referenced by pip._internal.commands.help.HelpCommand.run, pip._internal.commands.help.HelpCommand.run.