pkg_resources::_vendor::pyparsing::util
pkg_resources::_vendor::pyparsing::util._bslash
int pkg_resources._vendor.pyparsing.util.col(int loc, str strg)
Returns current column within a string, counting newlines as line separators. The first column is number 1. Note: the default parsing behavior is to expand tabs in the input string before starting the parsing process. See :class:`ParserElement.parseString` for more information on parsing strings containing ``<TAB>`` s, and suggested methods to maintain a consistent view of the parsed string, the parse location, and line and column positions within the parsed string.
Referenced by pkg_resources._vendor.pyparsing.core._default_start_debug_action, pkg_resources._vendor.pyparsing.helpers.indentedBlock, pkg_resources._vendor.pyparsing.actions.match_only_at_col, pkg_resources._vendor.pyparsing.core.AtLineStart.parseImpl, pkg_resources._vendor.pyparsing.core.IndentedBlock.parseImpl, pkg_resources._vendor.pyparsing.core.LineStart.parseImpl, pkg_resources._vendor.pyparsing.core.And.streamline.
int pkg_resources._vendor.pyparsing.util.lineno(int loc, str strg)
Returns current line number within a string, counting newlines as line separators. The first line is number 1. Note - the default parsing behavior is to expand tabs in the input string before starting the parsing process. See :class:`ParserElement.parseString` for more information on parsing strings containing ``<TAB>`` s, and suggested methods to maintain a consistent view of the parsed string, the parse location, and line and column positions within the parsed string.
Referenced by pkg_resources._vendor.pyparsing.core._default_start_debug_action.
str pkg_resources._vendor.pyparsing.util.line(int loc, str strg)
Returns the line of text containing loc within a string, counting newlines as line separators.
Referenced by pkg_resources._vendor.pyparsing.core._default_start_debug_action, pkg_resources._vendor.pyparsing.core.trace_parse_action.
str pkg_resources._vendor.pyparsing.util._escape_regex_range_chars(str s)
Referenced by pkg_resources._vendor.pyparsing.helpers.one_of.
str pkg_resources._vendor.pyparsing.util._collapse_string_to_ranges(Union[str, Iterable[str]] s, bool re_escape=True)
Referenced by pkg_resources._vendor.pyparsing.core.CharsNotIn._generateDefaultName, pkg_resources._vendor.pyparsing.core.Word._generateDefaultName.
list pkg_resources._vendor.pyparsing.util._flatten(list ll)
References pkg_resources._vendor.pyparsing.util._flatten.
Referenced by pkg_resources._vendor.pyparsing.util._flatten, pkg_resources._vendor.pyparsing.helpers.match_previous_expr, pkg_resources._vendor.pyparsing.helpers.match_previous_literal, pkg_resources._vendor.pyparsing.core.ParserElement.transform_string.