anyio::to_thread
anyio::to_thread.T_Retval
anyio::to_thread.PosArgsT
T_Retval anyio.to_thread.run_sync(Callable[[Unpack[PosArgsT]], T_Retval] func, *Unpack[PosArgsT] args, bool abandon_on_cancel=False, bool|None cancellable=None, CapacityLimiter|None limiter=None)
Call the given function with the given arguments in a worker thread. If the ``cancellable`` option is enabled and the task waiting for its completion is cancelled, the thread will still run its course but its return value (or any raised exception) will be ignored. :param func: a callable :param args: positional arguments for the callable :param abandon_on_cancel: ``True`` to abandon the thread (leaving it to run unchecked on own) if the host task is cancelled, ``False`` to ignore cancellations in the host task until the operation has completed in the worker thread :param cancellable: deprecated alias of ``abandon_on_cancel``; will override ``abandon_on_cancel`` if both parameters are passed :param limiter: capacity limiter to use to limit the total amount of threads running (if omitted, the default limiter is used) :return: an awaitable that yields the return value of the function.
Referenced by starlette.staticfiles.StaticFiles.check_config, fastapi.concurrency.contextmanager_in_threadpool, starlette.staticfiles.StaticFiles.get_response, starlette.concurrency.iterate_in_threadpool, starlette.concurrency.run_in_threadpool, starlette.responses.FileResponse.set_stat_headers.
CapacityLimiter anyio.to_thread.current_default_thread_limiter()
Return the capacity limiter that is used by default to limit the number of concurrent threads. :return: a capacity limiter object
References anyio.to_thread.current_default_thread_limiter.
Referenced by anyio.to_thread.current_default_thread_limiter.