setuptools::command::dist_info
str setuptools.command.dist_info._safe(str component)
Escape a component used to form a wheel name according to PEP 491
Referenced by setuptools.command.dist_info._version.
str setuptools.command.dist_info._version(str version)
Convert an arbitrary string to a version string.
References setuptools.command.dist_info._safe.
setuptools.command.dist_info._rm(dir_name, **opts)
Referenced by setuptools.command.dist_info.dist_info._maybe_bkp_dir.
setuptools.command.dist_info._copy(src, dst, **opts)
Referenced by setuptools.command.dist_info.dist_info._maybe_bkp_dir.