pip::_vendor::cachecontrol::heuristics
str pip::_vendor::cachecontrol::heuristics::TIME_FMT
datetime pip::_vendor::cachecontrol::heuristics::expire_after(timedelta delta, datetime|None date=None)
Referenced by pip._vendor.cachecontrol.heuristics.ExpiresAfter.update_headers, pip._vendor.cachecontrol.heuristics.OneDayCache.update_headers.
str pip::_vendor::cachecontrol::heuristics::datetime_to_header(datetime dt)
Referenced by pip._vendor.cachecontrol.heuristics.ExpiresAfter.update_headers, pip._vendor.cachecontrol.heuristics.OneDayCache.update_headers.