pip::_internal::utils::glibc
str | None pip._internal.utils.glibc.glibc_version_string()
References pip._internal.utils.glibc.glibc_version_string_confstr, pip._internal.utils.glibc.glibc_version_string_ctypes.
Referenced by pip._internal.utils.glibc.libc_ver.
str | None pip._internal.utils.glibc.glibc_version_string_confstr()
Referenced by pip._internal.utils.glibc.glibc_version_string.
str | None pip._internal.utils.glibc.glibc_version_string_ctypes()
Referenced by pip._internal.utils.glibc.glibc_version_string.
tuple[str, str] pip._internal.utils.glibc.libc_ver()
Try to determine the glibc version Returns a tuple of strings (lib, version) which default to empty strings in case the lookup fails.
References pip._internal.utils.glibc.glibc_version_string.