setuptools::_imp
int setuptools::_imp.PY_SOURCE
int setuptools::_imp.PY_COMPILED
int setuptools::_imp.C_EXTENSION
int setuptools::_imp.C_BUILTIN
int setuptools::_imp.PY_FROZEN
setuptools._imp.find_spec(module, paths)
Referenced by setuptools._imp.find_module, setuptools._imp.get_frozen_object, setuptools._imp.get_module.
setuptools._imp.find_module(module, paths=None)
Just like 'imp.find_module()', but with package support
References setuptools._imp.find_spec.
setuptools._imp.get_frozen_object(module, paths=None)
References setuptools._imp.find_spec.
setuptools._imp.get_module(module, paths, info)
References setuptools._imp.find_spec.