pip::_internal::operations::check
pip::_internal::operations::check.logger
pip::_internal::operations::check.PackageSet
pip::_internal::operations::check.Missing
pip::_internal::operations::check.Conflicting
pip::_internal::operations::check.MissingDict
pip::_internal::operations::check.ConflictingDict
pip::_internal::operations::check.CheckResult
pip::_internal::operations::check.ConflictDetails
tuple[PackageSet, bool] pip._internal.operations.check.create_package_set_from_installed()
Converts a list of distributions into a PackageSet.
Referenced by pip._internal.operations.check.check_install_conflicts, pip._internal.operations.check.check_install_conflicts.
CheckResult pip._internal.operations.check.check_package_set(PackageSet package_set, Callable[[str], bool]|None should_ignore=None)
Check if a package set is consistent If should_ignore is passed, it should be a callable that takes a package name and returns a boolean.
Referenced by pip._internal.operations.check.check_install_conflicts, pip._internal.operations.check.check_install_conflicts.
ConflictDetails pip._internal.operations.check.check_install_conflicts(list[InstallRequirement] to_install)
For checking if the dependency graph would be consistent after \ installing given requirements
References pip._internal.operations.check._create_whitelist, pip._internal.operations.check._simulate_installation_of, pip._internal.operations.check.check_package_set, pip._internal.operations.check.create_package_set_from_installed.
Generator[BaseDistribution, None, None] pip._internal.operations.check.check_unsupported(Iterable[BaseDistribution] packages, Iterable[Tag] supported_tags)
set[NormalizedName] pip._internal.operations.check._simulate_installation_of(list[InstallRequirement] to_install, PackageSet package_set)
Computes the version of packages after installing to_install.
Referenced by pip._internal.operations.check.check_install_conflicts, pip._internal.operations.check.check_install_conflicts.
set[NormalizedName] pip._internal.operations.check._create_whitelist(set[NormalizedName] would_be_installed, PackageSet package_set)
Referenced by pip._internal.operations.check.check_install_conflicts, pip._internal.operations.check.check_install_conflicts.
CheckResult pip._internal.operations.check.check_package_set(PackageSet package_set, Optional[Callable[[str], bool]] should_ignore=None)
Check if a package set is consistent If should_ignore is passed, it should be a callable that takes a package name and returns a boolean.
References pip._internal.operations.check.warn_legacy_versions_and_specifiers.
ConflictDetails pip._internal.operations.check.check_install_conflicts(List[InstallRequirement] to_install)
For checking if the dependency graph would be consistent after \ installing given requirements
References pip._internal.operations.check._create_whitelist, pip._internal.operations.check._simulate_installation_of, pip._internal.operations.check.check_package_set, pip._internal.operations.check.create_package_set_from_installed.
Set[NormalizedName] pip._internal.operations.check._simulate_installation_of(List[InstallRequirement] to_install, PackageSet package_set)
Computes the version of packages after installing to_install.
Set[NormalizedName] pip._internal.operations.check._create_whitelist(Set[NormalizedName] would_be_installed, PackageSet package_set)
None pip._internal.operations.check.warn_legacy_versions_and_specifiers(PackageSet package_set)
Referenced by pip._internal.operations.check.check_package_set.