fastapi::_compat::shared
tuple fastapi::_compat::shared::WithArgsTypes
fastapi::_compat::shared.PYDANTIC_VERSION_MINOR_TUPLE
int fastapi::_compat::shared.PYDANTIC_V2
dict fastapi::_compat::shared.sequence_annotation_to_type
fastapi::_compat::shared.sequence_types
Type fastapi::_compat::shared.Url
bool fastapi._compat.shared.lenient_issubclass(Any cls, Union[Type[Any], Tuple[Type[Any],...], None] class_or_tuple)
Referenced by fastapi._compat.shared._annotation_is_complex, fastapi._compat.shared._annotation_is_sequence, fastapi._compat.shared.annotation_is_pydantic_v1, fastapi._compat.shared.is_bytes_or_nonable_bytes_annotation, fastapi._compat.shared.is_uploadfile_or_nonable_uploadfile_annotation.
bool fastapi._compat.shared._annotation_is_sequence(Union[Type[Any], None] annotation)
References fastapi._compat.shared.lenient_issubclass.
Referenced by fastapi._compat.shared._annotation_is_complex, fastapi._compat.shared.field_annotation_is_sequence.
bool fastapi._compat.shared.field_annotation_is_sequence(Union[Type[Any], None] annotation)
References fastapi._compat.shared._annotation_is_sequence, fastapi._compat.shared.field_annotation_is_sequence.
Referenced by fastapi._compat.shared.annotation_is_pydantic_v1, fastapi._compat.shared.field_annotation_is_scalar_sequence, fastapi._compat.shared.field_annotation_is_sequence, fastapi._compat.shared.is_bytes_sequence_annotation, fastapi._compat.shared.is_uploadfile_sequence_annotation.
bool fastapi._compat.shared.value_is_sequence(Any value)
bool fastapi._compat.shared._annotation_is_complex(Union[Type[Any], None] annotation)
References fastapi._compat.shared._annotation_is_sequence, fastapi._compat.shared.lenient_issubclass.
Referenced by fastapi._compat.shared.field_annotation_is_complex.
bool fastapi._compat.shared.field_annotation_is_complex(Union[Type[Any], None] annotation)
References fastapi._compat.shared._annotation_is_complex, fastapi._compat.shared.field_annotation_is_complex.
Referenced by fastapi._compat.shared.field_annotation_is_complex, fastapi._compat.shared.field_annotation_is_scalar.
bool fastapi._compat.shared.field_annotation_is_scalar(Any annotation)
References fastapi._compat.shared.field_annotation_is_complex.
Referenced by fastapi._compat.shared.field_annotation_is_scalar_sequence.
bool fastapi._compat.shared.field_annotation_is_scalar_sequence(Union[Type[Any], None] annotation)
References fastapi._compat.shared.field_annotation_is_scalar, fastapi._compat.shared.field_annotation_is_scalar_sequence, fastapi._compat.shared.field_annotation_is_sequence.
Referenced by fastapi._compat.shared.field_annotation_is_scalar_sequence.
bool fastapi._compat.shared.is_bytes_or_nonable_bytes_annotation(Any annotation)
References fastapi._compat.shared.lenient_issubclass.
Referenced by fastapi._compat.shared.is_bytes_sequence_annotation.
bool fastapi._compat.shared.is_uploadfile_or_nonable_uploadfile_annotation(Any annotation)
References fastapi._compat.shared.lenient_issubclass.
Referenced by fastapi._compat.shared.is_uploadfile_sequence_annotation.
bool fastapi._compat.shared.is_bytes_sequence_annotation(Any annotation)
References fastapi._compat.shared.field_annotation_is_sequence, fastapi._compat.shared.is_bytes_or_nonable_bytes_annotation, fastapi._compat.shared.is_bytes_sequence_annotation.
Referenced by fastapi._compat.shared.is_bytes_sequence_annotation.
bool fastapi._compat.shared.is_uploadfile_sequence_annotation(Any annotation)
References fastapi._compat.shared.field_annotation_is_sequence, fastapi._compat.shared.is_uploadfile_or_nonable_uploadfile_annotation, fastapi._compat.shared.is_uploadfile_sequence_annotation.
Referenced by fastapi._compat.shared.is_uploadfile_sequence_annotation.
bool fastapi._compat.shared.annotation_is_pydantic_v1(Any annotation)
References fastapi._compat.shared.annotation_is_pydantic_v1, fastapi._compat.shared.field_annotation_is_sequence, fastapi._compat.shared.lenient_issubclass.
Referenced by fastapi._compat.shared.annotation_is_pydantic_v1.