pip::_internal::utils::wheel
tuple pip::_internal::utils::wheel::VERSION_COMPATIBLE
pip::_internal::utils::wheel.logger
tuple[str, Message] pip._internal.utils.wheel.parse_wheel(ZipFile wheel_zip, str name)
Extract information from the provided wheel, ensuring it meets basic standards. Returns the name of the .dist-info directory and the parsed WHEEL metadata.
References pip._internal.utils.wheel.check_compatibility, pip._internal.utils.wheel.wheel_dist_info_dir, pip._internal.utils.wheel.wheel_metadata, pip._internal.utils.wheel.wheel_version.
str pip::_internal::utils::wheel::wheel_dist_info_dir(ZipFile source, str name)
Returns the name of the contained .dist-info directory. Raises AssertionError or UnsupportedWheel if not found, >1 found, or it doesn't match the provided name.
Referenced by pip._internal.utils.wheel.parse_wheel.
bytes pip::_internal::utils::wheel::read_wheel_metadata_file(ZipFile source, str path)
Referenced by pip._internal.utils.wheel.wheel_metadata.
Message pip::_internal::utils::wheel::wheel_metadata(ZipFile source, str dist_info_dir)
Return the WHEEL metadata of an extracted wheel, if possible. Otherwise, raise UnsupportedWheel.
References pip._internal.utils.wheel.read_wheel_metadata_file.
Referenced by pip._internal.utils.wheel.parse_wheel.
tuple[int, ...] pip._internal.utils.wheel.wheel_version(Message wheel_data)
Given WHEEL metadata, return the parsed Wheel-Version. Otherwise, raise UnsupportedWheel.
Referenced by pip._internal.utils.wheel.parse_wheel.
None pip._internal.utils.wheel.check_compatibility(tuple[int,...] version, str name)
Raises errors or warns if called with an incompatible Wheel-Version. pip should refuse to install a Wheel-Version that's a major series ahead of what it's compatible with (e.g 2.0 > 1.1); and warn when installing a version only minor version ahead (e.g 1.2 > 1.1). version: a 2-tuple representing a Wheel-Version (Major, Minor) name: name of wheel or package to raise exception about :raises UnsupportedWheel: when an incompatible Wheel-Version is given
Referenced by pip._internal.utils.wheel.parse_wheel.
None pip._internal.utils.wheel.check_compatibility(Tuple[int,...] version, str name)
Raises errors or warns if called with an incompatible Wheel-Version. pip should refuse to install a Wheel-Version that's a major series ahead of what it's compatible with (e.g 2.0 > 1.1); and warn when installing a version only minor version ahead (e.g 1.2 > 1.1). version: a 2-tuple representing a Wheel-Version (Major, Minor) name: name of wheel or package to raise exception about :raises UnsupportedWheel: when an incompatible Wheel-Version is given