pip::_internal::operations::build::wheel_legacy
pip::_internal::operations::build::wheel_legacy.logger
str pip._internal.operations.build.wheel_legacy.format_command_result(list[str] command_args, str command_output)
Format command information for logging.
Referenced by pip._internal.operations.build.wheel_legacy.get_legacy_build_wheel_path, pip._internal.operations.build.wheel_legacy.get_legacy_build_wheel_path.
str | None pip._internal.operations.build.wheel_legacy.get_legacy_build_wheel_path(list[str] names, str temp_dir, str name, list[str] command_args, str command_output)
Return the path to the wheel in the temporary build directory.
References pip._internal.operations.build.wheel_legacy.format_command_result.
Referenced by pip._internal.operations.build.wheel_legacy.build_wheel_legacy, pip._internal.operations.build.wheel_legacy.build_wheel_legacy.
str | None pip._internal.operations.build.wheel_legacy.build_wheel_legacy(str name, str setup_py_path, str source_dir, list[str] global_options, list[str] build_options, str tempd)
Build one unpacked package using the "legacy" build process. Returns path to wheel if successfully built. Otherwise, returns None.
References pip._internal.operations.build.wheel_legacy.get_legacy_build_wheel_path.
str pip._internal.operations.build.wheel_legacy.format_command_result(List[str] command_args, str command_output)
Format command information for logging.
Optional[str] pip._internal.operations.build.wheel_legacy.get_legacy_build_wheel_path(List[str] names, str temp_dir, str name, List[str] command_args, str command_output)
Return the path to the wheel in the temporary build directory.
References pip._internal.operations.build.wheel_legacy.format_command_result.
Optional[str] pip._internal.operations.build.wheel_legacy.build_wheel_legacy(str name, str setup_py_path, str source_dir, List[str] global_options, List[str] build_options, str tempd)
Build one unpacked package using the "legacy" build process. Returns path to wheel if successfully built. Otherwise, returns None.
References pip._internal.operations.build.wheel_legacy.get_legacy_build_wheel_path.