pip::_internal::locations
pip::_internal::locations.logger
str pip::_internal::locations::_PLATLIBDIR
tuple pip::_internal::locations::_USE_SYSCONFIG_DEFAULT
bool pip::_internal::locations::_USE_SYSCONFIG
pip::_internal::locations._MISMATCH_LEVEL
bool pip::_internal::locations::_should_use_sysconfig()
This function determines the value of _USE_SYSCONFIG. By default, pip uses sysconfig on Python 3.10+. But Python distributors can override this decision by setting: sysconfig._PIP_USE_SYSCONFIG = True / False Rationale in https://github.com/pypa/pip/issues/10647 This is a function for testability, but should be constant during any one run.
bool pip::_internal::locations::_looks_like_bpo_44860()
The resolution to bpo-44860 will change this incorrect platlib. See <https://bugs.python.org/issue44860>.
Referenced by pip._internal.locations.get_scheme, pip._internal.locations.get_scheme.
bool pip._internal.locations._looks_like_red_hat_patched_platlib_purelib(dict[str, str] scheme)
Referenced by pip._internal.locations._looks_like_red_hat_lib, pip._internal.locations._looks_like_red_hat_patched_platlib_purelib.
bool pip::_internal::locations::_looks_like_red_hat_lib()
Red Hat patches platlib in unix_prefix and unix_home, but not purelib. This is the only way I can see to tell a Red Hat-patched Python.
References pip._internal.locations._looks_like_red_hat_patched_platlib_purelib.
Referenced by pip._internal.locations.get_scheme, pip._internal.locations.get_scheme.
bool pip::_internal::locations::_looks_like_debian_scheme()
Debian adds two additional schemes.
Referenced by pip._internal.locations._looks_like_deb_system_dist_packages, pip._internal.locations.get_scheme, pip._internal.locations.get_scheme.
bool pip::_internal::locations::_looks_like_red_hat_scheme()
Red Hat patches ``sys.prefix`` and ``sys.exec_prefix``. Red Hat's ``00251-change-user-install-location.patch`` changes the install command's ``prefix`` and ``exec_prefix`` to append ``"/local"``. This is (fortunately?) done quite unconditionally, so we create a default command object without any configuration to detect this.
Referenced by pip._internal.locations.get_scheme, pip._internal.locations.get_scheme.
bool pip::_internal::locations::_looks_like_slackware_scheme()
Slackware patches sysconfig but fails to patch distutils and site. Slackware changes sysconfig's user scheme to use ``"lib64"`` for the lib path, but does not do the same to the site module.
Referenced by pip._internal.locations.get_scheme, pip._internal.locations.get_scheme.
bool pip::_internal::locations::_looks_like_msys2_mingw_scheme()
MSYS2 patches distutils and sysconfig to use a UNIX-like scheme. However, MSYS2 incorrectly patches sysconfig ``nt`` scheme. The fix is likely going to be included in their 3.10 release, so we ignore the warning. See msys2/MINGW-packages#9319. MSYS2 MINGW's patch uses lowercase ``"lib"`` instead of the usual uppercase, and is missing the final ``"site-packages"``.
Referenced by pip._internal.locations.get_scheme, pip._internal.locations.get_scheme.
None pip::_internal::locations::_warn_mismatched(pathlib.Path old, pathlib.Path new, *, str key)
Referenced by pip._internal.locations._fix_abiflags, pip._internal.locations._warn_if_mismatch, pip._internal.locations.get_scheme, pip._internal.locations.get_scheme.
bool pip::_internal::locations::_warn_if_mismatch(pathlib.Path old, pathlib.Path new, *, str key)
References pip._internal.locations._warn_mismatched.
Referenced by pip._internal.locations.get_bin_prefix, pip._internal.locations.get_platlib, pip._internal.locations.get_purelib, pip._internal.locations.get_scheme.
None pip._internal.locations._log_context(*, bool user=False, str|None home=None, str|None root=None, str|None prefix=None)
Referenced by pip._internal.locations.get_bin_prefix, pip._internal.locations.get_platlib, pip._internal.locations.get_purelib, pip._internal.locations.get_scheme, pip._internal.locations.get_scheme.
Scheme pip._internal.locations.get_scheme(str dist_name, bool user=False, str|None home=None, str|None root=None, bool isolated=False, str|None prefix=None)
References pip._internal.locations._log_context, pip._internal.locations._looks_like_bpo_44860, pip._internal.locations._looks_like_debian_scheme, pip._internal.locations._looks_like_msys2_mingw_scheme, pip._internal.locations._looks_like_red_hat_lib, pip._internal.locations._looks_like_red_hat_scheme, pip._internal.locations._looks_like_slackware_scheme, pip._internal.locations._warn_mismatched.
str pip::_internal::locations::get_bin_prefix()
References pip._internal.locations._log_context, pip._internal.locations._warn_if_mismatch.
str pip::_internal::locations::get_bin_user()
bool pip::_internal::locations::_looks_like_deb_system_dist_packages(str value)
Check if the value is Debian's APT-controlled dist-packages. Debian's ``distutils.sysconfig.get_python_lib()`` implementation returns the default package path controlled by APT, but does not patch ``sysconfig`` to do the same. This is similar to the bug worked around in ``get_scheme()``, but here the default is ``deb_system`` instead of ``unix_local``. Ultimately we can't do anything about this Debian bug, and this detection allows us to skip the warning when needed.
References pip._internal.locations._looks_like_debian_scheme.
Referenced by pip._internal.locations.get_platlib, pip._internal.locations.get_purelib, pip._internal.locations.get_scheme.
str pip::_internal::locations::get_purelib()
Return the default pure-Python lib location.
References pip._internal.locations._log_context, pip._internal.locations._looks_like_deb_system_dist_packages, pip._internal.locations._warn_if_mismatch.
str pip::_internal::locations::get_platlib()
Return the default platform-shared lib location.
References pip._internal.locations._log_context, pip._internal.locations._looks_like_deb_system_dist_packages, pip._internal.locations._warn_if_mismatch.
bool pip._internal.locations._looks_like_red_hat_patched_platlib_purelib(Dict[str, str] scheme)
References pip._internal.locations._looks_like_red_hat_patched_platlib_purelib.
Generator[str, None, None] pip._internal.locations._fix_abiflags(Tuple[str] parts)
References pip._internal.locations._warn_mismatched.
Referenced by pip._internal.locations.get_scheme.
None pip._internal.locations._log_context(*, bool user=False, Optional[str] home=None, Optional[str] root=None, Optional[str] prefix=None)
Scheme pip._internal.locations.get_scheme(str dist_name, bool user=False, Optional[str] home=None, Optional[str] root=None, bool isolated=False, Optional[str] prefix=None)
References pip._internal.locations._fix_abiflags, pip._internal.locations._log_context, pip._internal.locations._looks_like_bpo_44860, pip._internal.locations._looks_like_deb_system_dist_packages, pip._internal.locations._looks_like_debian_scheme, pip._internal.locations._looks_like_msys2_mingw_scheme, pip._internal.locations._looks_like_red_hat_lib, pip._internal.locations._looks_like_red_hat_scheme, pip._internal.locations._looks_like_slackware_scheme, pip._internal.locations._warn_if_mismatch, pip._internal.locations._warn_mismatched.