pip::_internal::utils::misc
pip::_internal::utils::misc.logger
pip::_internal::utils::misc.T
pip::_internal::utils::misc.ExcInfo
pip::_internal::utils::misc.VersionInfo
pip::_internal::utils::misc.NetlocTuple
pip::_internal::utils::misc.OnExc
pip::_internal::utils::misc.OnErr
int pip::_internal::utils::misc.FILE_CHUNK_SIZE
str pip::_internal::utils::misc::get_pip_version()
tuple[int, int, int] pip._internal.utils.misc.normalize_version_info(tuple[int,...] py_version_info)
Convert a tuple of ints representing a Python version to one of length three. :param py_version_info: a tuple of ints representing a Python version, or None to specify no version. The tuple can have any length. :return: a tuple of length three if `py_version_info` is non-None. Otherwise, return `py_version_info` unchanged (i.e. None).
None pip::_internal::utils::misc::ensure_dir(str path)
os.path.makedirs without EEXIST.
str pip::_internal::utils::misc::get_prog()
None pip._internal.utils.misc.rmtree(str dir, bool ignore_errors=False, OnExc|None onexc=None)
None pip::_internal::utils::misc::_onerror_ignore(*Any _args)
None pip::_internal::utils::misc::_onerror_reraise(*Any _args)
None pip._internal.utils.misc.rmtree_errorhandler(FunctionType func, Path path, ExcInfo|BaseException exc_info, *, OnExc onexc=_onerror_reraise)
`rmtree` error handler to 'force' a file remove (i.e. like `rm -f`). * If a file is readonly then it's write flag is set and operation is retried. * `onerror` is the original callback from `rmtree(... onerror=onerror)` that is chained at the end if the "rm -f" still fails.
str pip::_internal::utils::misc::display_path(str path)
Gives the display value for a given path, making it relative to cwd if possible.
str pip::_internal::utils::misc::backup_dir(str dir, str ext=".bak")
Figure out the name of a directory to back up the given dir to (adding .bak, .bak2, etc)
str pip::_internal::utils::misc::ask_path_exists(str message, Iterable[str] options)
References pip._internal.utils.misc.ask.
None pip::_internal::utils::misc::_check_no_input(str message)
Raise an error if no input is allowed.
Referenced by pip._internal.utils.misc.ask, pip._internal.utils.misc.ask_input, pip._internal.utils.misc.ask_password, pip._internal.utils.misc.rmtree_errorhandler.
str pip::_internal::utils::misc::ask(str message, Iterable[str] options)
Ask the message interactively, with the given possible responses
References pip._internal.utils.misc._check_no_input.
Referenced by pip._internal.utils.misc.ask_path_exists, pip._internal.utils.misc.rmtree_errorhandler.
str pip::_internal::utils::misc::ask_input(str message)
Ask for input interactively.
References pip._internal.utils.misc._check_no_input.
str pip::_internal::utils::misc::ask_password(str message)
Ask for a password interactively.
References pip._internal.utils.misc._check_no_input.
int pip::_internal::utils::misc::strtobool(str val)
Convert a string representation of truth to true (1) or false (0). True values are 'y', 'yes', 't', 'true', 'on', and '1'; false values are 'n', 'no', 'f', 'false', 'off', and '0'. Raises ValueError if 'val' is anything else.
str pip::_internal::utils::misc::format_size(float bytes)
tuple[list[str], list[int]] pip._internal.utils.misc.tabulate(Iterable[Iterable[Any]] rows)
Return a list of formatted rows and a list of column sizes. For example:: >>> tabulate([['foobar', 2000], [0xdeadbeef]]) (['foobar 2000', '3735928559'], [10, 4])
bool pip::_internal::utils::misc::is_installable_dir(str path)
Is path is a directory containing pyproject.toml or setup.py? If pyproject.toml exists, this is a PEP 517 project. Otherwise we look for a legacy setuptools layout by identifying setup.py. We don't check for the setup.cfg because using it without setup.py is only available for PEP 517 projects, which are already covered by the pyproject.toml check.
Generator[bytes, None, None] pip._internal.utils.misc.read_chunks(BinaryIO file, int size=FILE_CHUNK_SIZE)
Yield pieces of data from a file-like object until EOF.
Referenced by pip._internal.utils.misc.hash_file.
str pip::_internal::utils::misc::normalize_path(str path, bool resolve_symlinks=True)
Convert a path to its canonical, case-normalized, absolute version.
Referenced by pip._internal.utils.misc.is_local, pip._internal.utils.misc.rmtree_errorhandler.
tuple[str, str] pip._internal.utils.misc.splitext(str path)
Like os.path.splitext, but take off .tar too
None pip::_internal::utils::misc::renames(str old, str new)
Like os.renames(), but handles renaming across devices.
bool pip::_internal::utils::misc::is_local(str path)
Return True if path is within sys.prefix, if we're running in a virtualenv. If we're not in a virtualenv, all paths are considered "local." Caution: this function assumes the head of path has been normalized with normalize_path.
References pip._internal.utils.misc.normalize_path.
None pip::_internal::utils::misc::write_output(Any msg, *Any args)
type[Any] pip._internal.utils.misc.enum(*Any sequential, **Any named)
str pip._internal.utils.misc.build_netloc(str host, int|None port)
Build a netloc from a host-port pair
str pip::_internal::utils::misc::build_url_from_netloc(str netloc, str scheme="https")
Build a full URL from a netloc.
Referenced by pip._internal.utils.misc.build_netloc, pip._internal.utils.misc.parse_netloc.
tuple[str | None, int | None] pip._internal.utils.misc.parse_netloc(str netloc)
Return the host-port pair from a netloc.
References pip._internal.utils.misc.build_url_from_netloc.
NetlocTuple pip::_internal::utils::misc::split_auth_from_netloc(str netloc)
Parse out and remove the auth information from a netloc. Returns: (netloc, (username, password)).
Referenced by pip._internal.utils.misc._get_netloc, pip._internal.utils.misc._transform_url, pip._internal.utils.misc.build_netloc, pip._internal.utils.misc.redact_netloc.
str pip::_internal::utils::misc::redact_netloc(str netloc)
Replace the sensitive data in a netloc with "****", if it exists. For example: - "user:pass@example.com" returns "user:****@example.com" - "accesstoken@example.com" returns "****@example.com"
References pip._internal.utils.misc.split_auth_from_netloc.
Referenced by pip._internal.utils.misc._redact_netloc, pip._internal.utils.misc._transform_url.
tuple[str, NetlocTuple] pip._internal.utils.misc._transform_url(str url, Callable[[str], tuple[Any,...]] transform_netloc)
Transform and replace netloc in a url. transform_netloc is a function taking the netloc and returning a tuple. The first element of this tuple is the new netloc. The entire tuple is returned. Returns a tuple containing the transformed url as item 0 and the original tuple returned by transform_netloc as item 1.
Referenced by pip._internal.utils.misc._transform_url, pip._internal.utils.misc.redact_auth_from_url, pip._internal.utils.misc.remove_auth_from_url, pip._internal.utils.misc.split_auth_netloc_from_url.
NetlocTuple pip::_internal::utils::misc::_get_netloc(str netloc)
References pip._internal.utils.misc.split_auth_from_netloc.
tuple[str] pip._internal.utils.misc._redact_netloc(str netloc)
References pip._internal.utils.misc.redact_netloc.
tuple[str, str, tuple[str | None, str | None]] pip._internal.utils.misc.split_auth_netloc_from_url(str url)
Parse a url into separate netloc, auth, and url with no auth. Returns: (url_without_auth, netloc, (username, password))
References pip._internal.utils.misc._transform_url.
str pip::_internal::utils::misc::remove_auth_from_url(str url)
Return a copy of url with 'username:password@' removed.
References pip._internal.utils.misc._transform_url.
str pip::_internal::utils::misc::redact_auth_from_url(str url)
Replace the password in a given url with ****.
References pip._internal.utils.misc._transform_url.
Referenced by pip._internal.utils.misc._transform_url, pip._internal.utils.misc.hide_url, pip._internal.utils.misc.redact_auth_from_requirement.
str pip::_internal::utils::misc::redact_auth_from_requirement(Requirement req)
Replace the password in a given requirement url with ****.
References pip._internal.utils.misc.redact_auth_from_url.
HiddenText pip::_internal::utils::misc::hide_value(str value)
HiddenText pip::_internal::utils::misc::hide_url(str url)
References pip._internal.utils.misc.redact_auth_from_url.
None pip::_internal::utils::misc::protect_pip_from_modification_on_windows(bool modifying_pip)
Protection of pip.exe from modification on Windows On Windows, any operation modifying pip should be run as: python -m pip ...
None pip::_internal::utils::misc::check_externally_managed()
Check whether the current environment is externally managed. If the ``EXTERNALLY-MANAGED`` config file is found, the current environment is considered externally managed, and an ExternallyManagedEnvironment is raised.
bool pip::_internal::utils::misc::is_console_interactive()
Is this console interactive?
tuple[Any, int] pip._internal.utils.misc.hash_file(str path, int blocksize=1<< 20)
Return (hash, length) for path using hashlib.sha256()
References pip._internal.utils.misc.read_chunks.
Iterator[tuple[Any, Any]] pip._internal.utils.misc.pairwise(Iterable[Any] iterable)
Return paired elements. For example: s -> (s0, s1), (s2, s3), (s4, s5), ...
tuple[Iterable[T], Iterable[T]] pip._internal.utils.misc.partition(Callable[[T], bool] pred, Iterable[T] iterable)
Use a predicate to partition entries into false entries and true entries, like partition(is_odd, range(10)) --> 0 2 4 6 8 and 1 3 5 7 9
None pip._internal.utils.misc.warn_if_run_as_root()
Output a warning for sudo users on Unix. In a virtual environment, sudo pip still writes to virtualenv. On Windows, users may run pip as Administrator without issues. This warning only applies to Unix root users outside of virtualenv.
Tuple[int, int, int] pip._internal.utils.misc.normalize_version_info(Tuple[int,...] py_version_info)
Convert a tuple of ints representing a Python version to one of length three. :param py_version_info: a tuple of ints representing a Python version, or None to specify no version. The tuple can have any length. :return: a tuple of length three if `py_version_info` is non-None. Otherwise, return `py_version_info` unchanged (i.e. None).
None pip._internal.utils.misc.rmtree(str dir, bool ignore_errors=False, Optional[OnExc] onexc=None)
None pip._internal.utils.misc.rmtree_errorhandler(FunctionType func, Path path, Union[ExcInfo, BaseException] exc_info, *, OnExc onexc=_onerror_reraise)
`rmtree` error handler to 'force' a file remove (i.e. like `rm -f`). * If a file is readonly then it's write flag is set and operation is retried. * `onerror` is the original callback from `rmtree(... onerror=onerror)` that is chained at the end if the "rm -f" still fails.
References pip._internal.utils.misc._check_no_input, pip._internal.utils.misc.ask, pip._internal.utils.misc.normalize_path.
Generator[StreamWrapper, None, None] pip._internal.utils.misc.captured_output(str stream_name)
Return a context manager used by captured_stdout/stdin/stderr that temporarily replaces the sys stream *stream_name* with a StringIO. Taken from Lib/support/__init__.py in the CPython repo.
Referenced by pip._internal.utils.misc.captured_stderr, pip._internal.utils.misc.captured_stdout.
ContextManager[StreamWrapper] pip._internal.utils.misc.captured_stdout()
Capture the output of sys.stdout: with captured_stdout() as stdout: print('hello') self.assertEqual(stdout.getvalue(), 'hello\n') Taken from Lib/support/__init__.py in the CPython repo.
References pip._internal.utils.misc.captured_output.
ContextManager[StreamWrapper] pip._internal.utils.misc.captured_stderr()
See captured_stdout().
References pip._internal.utils.misc.captured_output.
str pip._internal.utils.misc.build_netloc(str host, Optional[int] port)
Build a netloc from a host-port pair
References pip._internal.utils.misc.build_url_from_netloc, pip._internal.utils.misc.split_auth_from_netloc.
Tuple[str, NetlocTuple] pip._internal.utils.misc._transform_url(str url, Callable[[str], Tuple[Any,...]] transform_netloc)
Transform and replace netloc in a url. transform_netloc is a function taking the netloc and returning a tuple. The first element of this tuple is the new netloc. The entire tuple is returned. Returns a tuple containing the transformed url as item 0 and the original tuple returned by transform_netloc as item 1.
References pip._internal.utils.misc._transform_url, pip._internal.utils.misc.redact_auth_from_url, pip._internal.utils.misc.redact_netloc, pip._internal.utils.misc.split_auth_from_netloc.