pip::_internal::index::collector
pip::_internal::index::collector.logger
pip::_internal::index::collector.ResponseHeaders
pip::_internal::index::collector.Protocol
str | None pip._internal.index.collector._match_vcs_scheme(str url)
Look for VCS schemes in the URL. Returns the matched VCS scheme, or None if there's no match.
Referenced by pip._internal.index.collector._get_index_content, pip._internal.index.collector._handle_get_simple_fail.
None pip::_internal::index::collector::_ensure_api_header(Response response)
Check the Content-Type header to ensure the response contains a Simple API Response. Raises `_NotAPIContent` if the content type is not a valid content-type.
Referenced by pip._internal.index.collector._get_simple_response.
None pip::_internal::index::collector::_ensure_api_response(str url, PipSession session)
Send a HEAD request to the URL, and ensure the response contains a simple API Response. Raises `_NotHTTP` if the URL is not available for a HEAD request, or `_NotAPIContent` if the content type is not a valid content type.
Referenced by pip._internal.index.collector._get_simple_response.
Response pip::_internal::index::collector::_get_simple_response(str url, PipSession session)
Access an Simple API response with GET, and return the response. This consists of three parts: 1. If the URL looks suspiciously like an archive, send a HEAD first to check the Content-Type is HTML or Simple API, to avoid downloading a large file. Raise `_NotHTTP` if the content type cannot be determined, or `_NotAPIContent` if it is not HTML or a Simple API. 2. Actually perform the request. Raise HTTP exceptions on network failures. 3. Check the Content-Type header to make sure we got a Simple API response, and raise `_NotAPIContent` otherwise.
References pip._internal.index.collector._ensure_api_header, pip._internal.index.collector._ensure_api_response.
Referenced by pip._internal.index.collector._get_index_content, pip._internal.index.collector._handle_get_simple_fail.
str | None pip._internal.index.collector._get_encoding_from_headers(ResponseHeaders headers)
Determine if we have any encoding information in our headers.
Referenced by pip._internal.index.collector._handle_get_simple_fail, pip._internal.index.collector._make_index_content.
ParseLinks pip::_internal::index::collector::with_cached_index_content(ParseLinks fn)
Given a function that parses an Iterable[Link] from an IndexContent, cache the function's result (keyed by CacheablePageContent), unless the IndexContent `page` has `page.cache_link_parsing == False`.
Iterable[Link] pip._internal.index.collector.parse_links(IndexContent page)
Parse a Simple API's Index Content, and yield its anchor elements as Link objects.
None pip._internal.index.collector._handle_get_simple_fail(Link link, str|Exception reason, Callable[..., None]|None meth=None)
Referenced by pip._internal.index.collector._get_index_content, pip._internal.index.collector._handle_get_simple_fail.
IndexContent pip::_internal::index::collector::_make_index_content(Response response, bool cache_link_parsing=True)
References pip._internal.index.collector._get_encoding_from_headers.
Referenced by pip._internal.index.collector._get_index_content, pip._internal.index.collector._handle_get_simple_fail.
IndexContent | None pip._internal.index.collector._get_index_content(Link link, *, PipSession session)
References pip._internal.index.collector._get_simple_response, pip._internal.index.collector._handle_get_simple_fail, pip._internal.index.collector._make_index_content, pip._internal.index.collector._match_vcs_scheme.
Referenced by pip._internal.index.collector.LinkCollector.fetch_response.
Iterable[Link] pip._internal.index.collector.parse_links("IndexContent" page)
Parse a Simple API's Index Content, and yield its anchor elements as Link objects.
None pip._internal.index.collector._handle_get_simple_fail(Link link, Union[str, Exception] reason, Optional[Callable[..., None]] meth=None)
References pip._internal.index.collector._get_encoding_from_headers, pip._internal.index.collector._get_simple_response, pip._internal.index.collector._handle_get_simple_fail, pip._internal.index.collector._make_index_content, pip._internal.index.collector._match_vcs_scheme.