pydantic::v1::class_validators
pydantic::v1::class_validators.ValidatorCallable
pydantic::v1::class_validators.ValidatorsList
pydantic::v1::class_validators.ValidatorListDict
Set pydantic::v1::class_validators._FUNCS
str pydantic::v1::class_validators.VALIDATOR_CONFIG_KEY
str pydantic::v1::class_validators.ROOT_VALIDATOR_CONFIG_KEY
dict pydantic::v1::class_validators.all_kwargs
Callable[[AnyCallable], 'AnyClassMethod'] pydantic.v1.class_validators.validator(*str fields, bool pre=False, bool each_item=False, bool always=False, bool check_fields=True, Optional[bool] whole=None, bool allow_reuse=False)
Decorate methods on the class indicating that they should be used to validate fields :param fields: which field(s) the method should be called on :param pre: whether or not this validator should be called before the standard validators (else after) :param each_item: for complex objects (sets, lists etc.) whether to validate individual elements rather than the whole object :param always: whether this method and other validators should be called even if the value is missing :param check_fields: whether to check that the fields actually exist on the model :param allow_reuse: whether to track and raise an error if another validator refers to the decorated function
References pydantic.v1.class_validators._prepare_validator.
Referenced by pydantic.v1.class_validators._generic_validator_basic, pydantic.v1.class_validators._generic_validator_cls.
'AnyClassMethod' pydantic.v1.class_validators.root_validator(AnyCallable _func)
Callable[[AnyCallable], 'AnyClassMethod'] pydantic.v1.class_validators.root_validator(*, bool pre=False, bool allow_reuse=False, bool skip_on_failure=False)
Union['AnyClassMethod', Callable[[AnyCallable], 'AnyClassMethod']] pydantic.v1.class_validators.root_validator(Optional[AnyCallable] _func=None, *, bool pre=False, bool allow_reuse=False, bool skip_on_failure=False)
Decorate methods on a model indicating that they should be used to validate (and perhaps modify) data either before or after standard model parsing/validation is performed.
References pydantic.v1.class_validators._prepare_validator.
'AnyClassMethod' pydantic.v1.class_validators._prepare_validator(AnyCallable function, bool allow_reuse)
Avoid validators with duplicated names since without this, validators can be overwritten silently which generally isn't the intended behaviour, don't run in ipython (see #312) or if allow_reuse is False.
Referenced by pydantic.v1.class_validators.root_validator, pydantic.v1.class_validators.validator.
Dict[str, List[Validator]] pydantic.v1.class_validators.extract_validators(Dict[str, Any] namespace)
Tuple[List[AnyCallable], List[Tuple[bool, AnyCallable]]] pydantic.v1.class_validators.extract_root_validators(Dict[str, Any] namespace)
'ValidatorListDict' pydantic.v1.class_validators.inherit_validators('ValidatorListDict' base_validators, 'ValidatorListDict' validators)
'ValidatorCallable' pydantic.v1.class_validators.make_generic_validator(AnyCallable validator)
Make a generic function which calls a validator with the right arguments. Unfortunately other approaches (eg. return a partial of a function that builds the arguments) is slow, hence this laborious way of doing things. It's done like this so validators don't all need **kwargs in their signature, eg. any combination of the arguments "values", "fields" and/or "config" are permitted.
References pydantic.v1.class_validators._generic_validator_basic, pydantic.v1.class_validators._generic_validator_cls.
Referenced by pydantic.v1.class_validators.prep_validators.
'ValidatorsList' pydantic.v1.class_validators.prep_validators(Iterable[AnyCallable] v_funcs)
References pydantic.v1.class_validators.make_generic_validator.
'ValidatorCallable' pydantic.v1.class_validators._generic_validator_cls(AnyCallable validator, 'Signature' sig, Set[str] args)
References pydantic.v1.class_validators.validator.
Referenced by pydantic.v1.class_validators.make_generic_validator.
'ValidatorCallable' pydantic.v1.class_validators._generic_validator_basic(AnyCallable validator, 'Signature' sig, Set[str] args)
References pydantic.v1.class_validators.validator.
Referenced by pydantic.v1.class_validators.make_generic_validator.
Dict[str, 'AnyClassMethod'] pydantic.v1.class_validators.gather_all_validators('ModelOrDc' type_)