pip::_vendor::distlib::util
pip::_vendor::distlib::util.ssl
pip::_vendor::distlib::util.logger
pip::_vendor::distlib::util.IDENTIFIER
pip::_vendor::distlib::util.VERSION_IDENTIFIER
pip::_vendor::distlib::util.COMPARE_OP
pip::_vendor::distlib::util.MARKER_OP
pip::_vendor::distlib::util.OR
pip::_vendor::distlib::util.AND
pip::_vendor::distlib::util.NON_SPACE
pip::_vendor::distlib::util.STRING_CHUNK
pip::_vendor::distlib::util.ENTRY_RE
pip::_vendor::distlib::util.PROJECT_NAME_AND_VERSION
pip::_vendor::distlib::util.PYTHON_VERSION
pip::_vendor::distlib::util.NAME_VERSION_RE
str pip::_vendor::distlib::util::_external_data_base_url
tuple pip::_vendor::distlib::util::ARCHIVE_EXTENSIONS
tuple pip::_vendor::distlib::util::UNITS
pip::_vendor::distlib::util.RICH_GLOB
pip::_vendor::distlib::util._CHECK_RECURSIVE_GLOB
pip::_vendor::distlib::util._CHECK_MISMATCH_SET
dict pip::_vendor::distlib::util::_TARGET_TO_PLAT
pip::_vendor::distlib::util::parse_marker(marker_string)
Parse a marker string and return a dictionary containing a marker expression. The dictionary will contain keys "op", "lhs" and "rhs" for non-terminals in the expression grammar, or strings. A string contained in quotes is to be interpreted as a literal string, and a string not contained in quotes is a variable (such as os_name).
Referenced by pip._vendor.distlib.util.parse_requirement.
pip::_vendor::distlib::util::parse_requirement(req)
Parse a requirement passed in as a string. Return a Container whose attributes contain the various parts of the requirement.
References pip._vendor.distlib.util.parse_marker.
pip::_vendor::distlib::util::get_resources_dests(resources_root, rules)
Find destinations for resources files
References pip._vendor.distlib.util.iglob.
pip::_vendor::distlib::util::in_venv()
pip::_vendor::distlib::util::get_executable()
pip::_vendor::distlib::util::proceed(prompt, allowed_chars, error_prompt=None, default=None)
pip::_vendor::distlib::util::extract_by_key(d, keys)
pip::_vendor::distlib::util::read_exports(stream)
References pip._vendor.distlib.util.get_export_entry.
pip::_vendor::distlib::util::write_exports(exports, stream)
pip::_vendor::distlib::util::tempdir()
pip::_vendor::distlib::util::chdir(d)
pip::_vendor::distlib::util::socket_timeout(seconds=15)
pip::_vendor::distlib::util::convert_path(pathname)
Return 'pathname' as a name that will work on the native filesystem. The path is split on '/' and put back together again using the current directory separator. Needed because filenames in the setup script are always supplied in Unix style, and have to be converted to the local convention before we can actually use them in the filesystem. Raises ValueError on non-Unix-ish systems if 'pathname' either starts or ends with a slash.
pip::_vendor::distlib::util::resolve(module_name, dotted_path)
Referenced by pip._vendor.distlib.util.ExportEntry.value.
pip::_vendor::distlib::util::get_export_entry(specification)
Referenced by pip._vendor.distlib.util.read_exports.
pip::_vendor::distlib::util::get_cache_base(suffix=None)
Return the default base location for distlib caches. If the directory does not exist, it is created. Use the suffix provided for the base directory, and default to '.distlib' if it isn't provided. On Windows, if LOCALAPPDATA is defined in the environment, then it is assumed to be a directory, and will be the parent directory of the result. On POSIX, and on Windows if LOCALAPPDATA is not defined, the user's home directory - using os.expanduser('~') - will be the parent directory of the result. The result is just the directory '.distlib' in the parent directory as determined above, or with the name specified with ``suffix``.
pip._vendor.distlib.util.path_to_cache_dir(path, use_abspath=True)
Convert an absolute path to a directory name for use in a cache. The algorithm used is: #. On Windows, any ``':'`` in the drive is replaced with ``'---'``. #. Any occurrence of ``os.sep`` is replaced with ``'--'``. #. ``'.cache'`` is appended.
Referenced by pip._vendor.distlib.util.Cache.prefix_to_dir, pip._vendor.distlib.util.Cache.prefix_to_dir.
pip::_vendor::distlib::util::ensure_slash(s)
pip::_vendor::distlib::util::parse_credentials(netloc)
pip::_vendor::distlib::util::get_process_umask()
pip::_vendor::distlib::util::is_string_sequence(seq)
pip::_vendor::distlib::util::split_filename(filename, project_name=None)
Extract name, version, python version from a filename (no extension) Return name, version, pyver or None
pip::_vendor::distlib::util::parse_name_and_version(p)
A utility method used to get name and version from a string. From e.g. a Provides-Dist value. :param p: A value in a form 'foo (1.0)' :return: The name and version as a tuple.
pip::_vendor::distlib::util::get_extras(requested, available)
pip::_vendor::distlib::util::_get_external_data(url)
Referenced by pip._vendor.distlib.util.get_package_data, pip._vendor.distlib.util.get_project_data, pip._vendor.distlib.util.path_to_cache_dir.
pip::_vendor::distlib::util::get_project_data(name)
References pip._vendor.distlib.util._get_external_data.
pip::_vendor::distlib::util::get_package_data(name, version)
References pip._vendor.distlib.util._get_external_data.
pip::_vendor::distlib::util::unarchive(archive_filename, dest_dir, format=None, check=True)
pip::_vendor::distlib::util::zip_dir(directory)
zip a directory tree into a BytesIO object
pip::_vendor::distlib::util::iglob(path_glob)
Extended globbing function that supports ** and {opt1,opt2,opt3}.
Referenced by pip._vendor.distlib.util.get_resources_dests.
pip::_vendor::distlib::util::_iglob(path_glob)
pip::_vendor::distlib::util::_csv_open(fn, mode, **kwargs)
pip::_vendor::distlib::util::normalize_name(name)
Normalize a python package name a la PEP 503
pip::_vendor::distlib::util::_load_pypirc(index)
Read the PyPI access configuration as supported by distutils.
pip::_vendor::distlib::util::_store_pypirc(index)
pip::_vendor::distlib::util::get_host_platform()
Return a string that identifies the current platform. This is used mainly to distinguish platform-specific build directories and platform-specific built distributions. Typically includes the OS name and version and the architecture (as supplied by 'os.uname()'), although the exact information included depends on the OS; eg. on Linux, the kernel version isn't particularly important. Examples of returned values: linux-i586 linux-alpha (?) solaris-2.6-sun4u Windows will return one of: win-amd64 (64bit Windows on AMD64 (aka x86_64, Intel64, EM64T, etc) win32 (all others - specifically, sys.platform is returned) For other non-POSIX platforms, currently just returns 'sys.platform'.
pip::_vendor::distlib::util::get_platform()
pip._vendor.distlib.util.path_to_cache_dir(path)
Convert an absolute path to a directory name for use in a cache. The algorithm used is: #. On Windows, any ``':'`` in the drive is replaced with ``'---'``. #. Any occurrence of ``os.sep`` is replaced with ``'--'``. #. ``'.cache'`` is appended.
References pip._vendor.distlib.util._get_external_data.