pydantic::_internal::_fields
dict pydantic::_internal::_fields._deprecated_method_names
dict pydantic::_internal::_fields._deprecated_classmethod_names
BaseMetadata pydantic._internal._fields.pydantic_general_metadata(**Any metadata)
Create a new `_PydanticGeneralMetadata` class with the given metadata. Args: **metadata: The metadata to add. Returns: The new `_PydanticGeneralMetadata` class.
References pydantic._internal._fields._general_metadata_cls.
type[BaseMetadata] pydantic._internal._fields._general_metadata_cls()
Do it this way to avoid importing `annotated_types` at import time.
Referenced by pydantic._internal._fields.pydantic_general_metadata.
None pydantic._internal._fields._check_protected_namespaces(tuple[str|Pattern[str],...] protected_namespaces, str ann_name, tuple[type[Any],...] bases, str cls_name)
Referenced by pydantic._internal._fields.collect_model_fields.
None pydantic._internal._fields._update_fields_from_docstrings(type[Any] cls, dict[str, FieldInfo] fields, bool use_inspect=False)
Referenced by pydantic._internal._fields.collect_dataclass_fields, pydantic._internal._fields.collect_model_fields.
pydantic._internal._fields._apply_field_title_generator_to_field_info(Callable[[str, FieldInfo], str] title_generator, str field_name, FieldInfo field_info)
Referenced by pydantic._internal._fields.update_field_from_config.
pydantic._internal._fields._apply_alias_generator_to_field_info(Callable[[str], str]|AliasGenerator alias_generator, str field_name, FieldInfo field_info)
Apply an alias generator to aliases on a `FieldInfo` instance if appropriate. Args: alias_generator: A callable that takes a string and returns a string, or an `AliasGenerator` instance. field_name: The name of the field from which to generate the alias. field_info: The `FieldInfo` instance to which the alias generator is (maybe) applied.
Referenced by pydantic._internal._fields.update_field_from_config.
None pydantic._internal._fields.update_field_from_config(ConfigWrapper config_wrapper, str field_name, FieldInfo field_info)
Update the `FieldInfo` instance from the configuration set on the model it belongs to. This will apply the title and alias generators from the configuration. Args: config_wrapper: The configuration from the model. field_name: The field name the `FieldInfo` instance is attached to. field_info: The `FieldInfo` instance to update.
References pydantic._internal._fields._apply_alias_generator_to_field_info, pydantic._internal._fields._apply_field_title_generator_to_field_info.
Referenced by pydantic._internal._fields.collect_dataclass_fields, pydantic._internal._fields.collect_model_fields, pydantic._internal._fields.rebuild_dataclass_fields, pydantic._internal._fields.rebuild_model_fields.
tuple[dict[str, FieldInfo], set[str]] pydantic._internal._fields.collect_model_fields(type[BaseModel] cls, ConfigWrapper config_wrapper, NsResolver|None ns_resolver, *, Mapping[TypeVar, Any]|None typevars_map=None)
Collect the fields and class variables names of a nascent Pydantic model. The fields collection process is *lenient*, meaning it won't error if string annotations fail to evaluate. If this happens, the original annotation (and assigned value, if any) is stored on the created `FieldInfo` instance. The `rebuild_model_fields()` should be called at a later point (e.g. when rebuilding the model), and will make use of these stored attributes. Args: cls: BaseModel or dataclass. config_wrapper: The config wrapper instance. ns_resolver: Namespace resolver to use when getting model annotations. typevars_map: A dictionary mapping type variables to their concrete types. Returns: A two-tuple containing model fields and class variables names. Raises: NameError: - If there is a conflict between a field name and protected namespaces. - If there is a field other than `root` in `RootModel`. - If a field shadows an attribute in the parent model.
References pydantic._internal._fields._check_protected_namespaces, pydantic._internal._fields._update_fields_from_docstrings, pydantic._internal._fields.is_valid_field_name, pydantic._internal._fields.update_field_from_config.
dict[str, FieldInfo] pydantic._internal._fields.rebuild_model_fields(type[BaseModel] cls, *, ConfigWrapper config_wrapper, NsResolver ns_resolver, Mapping[TypeVar, Any] typevars_map)
Rebuild the (already present) model fields by trying to reevaluate annotations. This function should be called whenever a model with incomplete fields is encountered. Raises: NameError: If one of the annotations failed to evaluate. Note: This function *doesn't* mutate the model fields in place, as it can be called during schema generation, where you don't want to mutate other model's fields.
References pydantic._internal._fields.update_field_from_config.
dict[str, FieldInfo] pydantic._internal._fields.collect_dataclass_fields(type[StandardDataclass] cls, *, ConfigWrapper config_wrapper, NsResolver|None ns_resolver=None, dict[Any, Any]|None typevars_map=None)
Collect the fields of a dataclass. Args: cls: dataclass. config_wrapper: The config wrapper instance. ns_resolver: Namespace resolver to use when getting dataclass annotations. Defaults to an empty instance. typevars_map: A dictionary mapping type variables to their concrete types. Returns: The dataclass fields.
References pydantic._internal._fields._update_fields_from_docstrings, pydantic._internal._fields.update_field_from_config.
dict[str, FieldInfo] pydantic._internal._fields.rebuild_dataclass_fields(type[PydanticDataclass] cls, *, ConfigWrapper config_wrapper, NsResolver ns_resolver, Mapping[TypeVar, Any] typevars_map)
Rebuild the (already present) dataclass fields by trying to reevaluate annotations. This function should be called whenever a dataclass with incomplete fields is encountered. Raises: NameError: If one of the annotations failed to evaluate. Note: This function *doesn't* mutate the dataclass fields in place, as it can be called during schema generation, where you don't want to mutate other dataclass's fields.
References pydantic._internal._fields.update_field_from_config.
bool pydantic._internal._fields.is_valid_field_name(str name)
Referenced by pydantic._internal._fields.collect_model_fields.
bool pydantic._internal._fields.is_valid_privateattr_name(str name)
TypeIs[Callable[[dict[str, Any]], Any]] pydantic._internal._fields.takes_validated_data_argument(Callable[[], Any]|Callable[[dict[str, Any]], Any] default_factory)
Whether the provided default factory callable has a validated data parameter.