pydantic::_internal::_generics
pydantic::_internal::_generics.GenericTypesCacheKey
pydantic::_internal::_generics.KT
pydantic::_internal::_generics.VT
int pydantic::_internal::_generics._LIMITED_DICT_SIZE
pydantic::_internal::_generics.GenericTypesCache
Referenced by pydantic._internal._generics.get_cached_generic_type_early, pydantic._internal._generics.get_cached_generic_type_late, pydantic._internal._generics.set_cached_generic_type.
dict pydantic::_internal::_generics.DictValues
ContextVar pydantic::_internal::_generics._generic_recursion_cache
type[BaseModel] pydantic._internal._generics.create_generic_submodel(str model_name, type[BaseModel] origin, tuple[Any,...] args, tuple[Any,...] params)
Dynamically create a submodel of a provided (generic) BaseModel. This is used when producing concrete parametrizations of generic models. This function only *creates* the new subclass; the schema/validators/serialization must be updated to reflect a concrete parametrization elsewhere. Args: model_name: The name of the newly created model. origin: The base class for the new model to inherit from. args: A tuple of generic metadata arguments. params: A tuple of generic metadata parameters. Returns: The created submodel.
References pydantic._internal._generics._get_caller_frame_info.
tuple[str | None, bool] pydantic._internal._generics._get_caller_frame_info(int depth=2)
Used inside a function to check whether it was called globally. Args: depth: The depth to get the frame. Returns: A tuple contains `module_name` and `called_globally`. Raises: RuntimeError: If the function is not called inside a function.
Referenced by pydantic._internal._generics.create_generic_submodel.
Iterator[TypeVar] pydantic._internal._generics.iter_contained_typevars(Any v)
Recursively iterate through all subtypes and type args of `v` and yield any typevars that are found. This is inspired as an alternative to directly accessing the `__parameters__` attribute of a GenericAlias, since __parameters__ of (nested) generic BaseModel subclasses won't show up in that list.
References pydantic._internal._generics.get_args, pydantic._internal._generics.iter_contained_typevars.
Referenced by pydantic._internal._generics.get_model_typevars_map, pydantic._internal._generics.iter_contained_typevars.
Any pydantic._internal._generics.get_args(Any v)
References typing_extensions.get_args.
Referenced by pydantic._internal._generics._union_orderings_key, pydantic._internal._generics.iter_contained_typevars, pydantic._internal._generics.replace_types.
Any pydantic._internal._generics.get_origin(Any v)
References typing_extensions.get_origin.
Referenced by pydantic._internal._generics.get_standard_typevars_map, pydantic._internal._generics.replace_types.
dict[TypeVar, Any] | None pydantic._internal._generics.get_standard_typevars_map(Any cls)
Package a generic type's typevars and parametrization (if present) into a dictionary compatible with the `replace_types` function. Specifically, this works with standard typing generics and typing._GenericAlias.
References pydantic._internal._generics.get_origin.
dict[TypeVar, Any] pydantic._internal._generics.get_model_typevars_map(type[BaseModel] cls)
Package a generic BaseModel's typevars and concrete parametrization (if present) into a dictionary compatible with the `replace_types` function. Since BaseModel.__class_getitem__ does not produce a typing._GenericAlias, and the BaseModel generic info is stored in the __pydantic_generic_metadata__ attribute, we need special handling here.
References pydantic._internal._generics.iter_contained_typevars.
Any pydantic._internal._generics.replace_types(Any type_, Mapping[TypeVar, Any]|None type_map)
Return type with all occurrences of `type_map` keys recursively replaced with their values. Args: type_: The class or generic alias. type_map: Mapping from `TypeVar` instance to concrete types. Returns: A new type representing the basic structure of `type_` with all `typevar_map` keys recursively replaced. Example: ```python from typing import Union from pydantic._internal._generics import replace_types replace_types(tuple[str, Union[list[str], float]], {str: int}) #> tuple[int, Union[list[int], float]] ```
References pydantic._internal._generics.get_args, pydantic._internal._generics.get_origin, pydantic._internal._generics.replace_types.
Referenced by pydantic._internal._generics.map_generic_model_arguments, pydantic._internal._generics.replace_types.
dict[TypeVar, Any] pydantic._internal._generics.map_generic_model_arguments(type[BaseModel] cls, tuple[Any,...] args)
Return a mapping between the parameters of a generic model and the provided arguments during parameterization. Raises: TypeError: If the number of arguments does not match the parameters (i.e. if providing too few or too many arguments). Example: ```python {test="skip" lint="skip"} class Model[T, U, V = int](BaseModel): ... map_generic_model_arguments(Model, (str, bytes)) #> {T: str, U: bytes, V: int} map_generic_model_arguments(Model, (str,)) #> TypeError: Too few arguments for <class '__main__.Model'>; actual 1, expected at least 2 map_generic_model_arguments(Model, (str, bytes, int, complex)) #> TypeError: Too many arguments for <class '__main__.Model'>; actual 4, expected 3 ``` Note: This function is analogous to the private `typing._check_generic_specialization` function.
References pydantic._internal._generics.replace_types.
Iterator[PydanticRecursiveRef | None] pydantic._internal._generics.generic_recursion_self_type(type[BaseModel] origin, tuple[Any,...] args)
This contextmanager should be placed around the recursive calls used to build a generic type, and accept as arguments the generic origin type and the type arguments being passed to it. If the same origin and arguments are observed twice, it implies that a self-reference placeholder can be used while building the core schema, and will produce a schema_ref that will be valid in the final parent schema.
set[str] pydantic._internal._generics.recursively_defined_type_refs()
type[BaseModel] | None pydantic._internal._generics.get_cached_generic_type_early(type[BaseModel] parent, Any typevar_values)
The use of a two-stage cache lookup approach was necessary to have the highest performance possible for repeated calls to `__class_getitem__` on generic types (which may happen in tighter loops during runtime), while still ensuring that certain alternative parametrizations ultimately resolve to the same type. As a concrete example, this approach was necessary to make Model[List[T]][int] equal to Model[List[int]]. The approach could be modified to not use two different cache keys at different points, but the _early_cache_key is optimized to be as quick to compute as possible (for repeated-access speed), and the _late_cache_key is optimized to be as "correct" as possible, so that two types that will ultimately be the same after resolving the type arguments will always produce cache hits. If we wanted to move to only using a single cache key per type, we would either need to always use the slower/more computationally intensive logic associated with _late_cache_key, or would need to accept that Model[List[T]][int] is a different type than Model[List[T]][int]. Because we rely on subclass relationships during validation, I think it is worthwhile to ensure that types that are functionally equivalent are actually equal.
References pydantic._internal._generics._early_cache_key, pydantic._internal._generics.GenericTypesCache.
type[BaseModel] | None pydantic._internal._generics.get_cached_generic_type_late(type[BaseModel] parent, Any typevar_values, type[BaseModel] origin, tuple[Any,...] args)
See the docstring of `get_cached_generic_type_early` for more information about the two-stage cache lookup.
References pydantic._internal._generics._late_cache_key, pydantic._internal._generics.GenericTypesCache, pydantic._internal._generics.set_cached_generic_type.
None pydantic._internal._generics.set_cached_generic_type(type[BaseModel] parent, tuple[Any,...] typevar_values, type[BaseModel] type_, type[BaseModel]|None origin=None, tuple[Any,...]|None args=None)
See the docstring of `get_cached_generic_type_early` for more information about why items are cached with two different keys.
References pydantic._internal._generics._early_cache_key, pydantic._internal._generics._late_cache_key, pydantic._internal._generics.GenericTypesCache.
Referenced by pydantic._internal._generics.get_cached_generic_type_late.
Any pydantic._internal._generics._union_orderings_key(Any typevar_values)
This is intended to help differentiate between Union types with the same arguments in different order. Thanks to caching internal to the `typing` module, it is not possible to distinguish between List[Union[int, float]] and List[Union[float, int]] (and similarly for other "parent" origins besides List) because `typing` considers Union[int, float] to be equal to Union[float, int]. However, you _can_ distinguish between (top-level) Union[int, float] vs. Union[float, int]. Because we parse items as the first Union type that is successful, we get slightly more consistent behavior if we make an effort to distinguish the ordering of items in a union. It would be best if we could _always_ get the exact-correct order of items in the union, but that would require a change to the `typing` module itself. (See https://github.com/python/cpython/issues/86483 for reference.)
References pydantic._internal._generics._union_orderings_key, pydantic._internal._generics.get_args, typing_extensions.get_origin.
Referenced by pydantic._internal._generics._early_cache_key, pydantic._internal._generics._late_cache_key, pydantic._internal._generics._union_orderings_key.
GenericTypesCacheKey pydantic._internal._generics._early_cache_key(type[BaseModel] cls, Any typevar_values)
This is intended for minimal computational overhead during lookups of cached types. Note that this is overly simplistic, and it's possible that two different cls/typevar_values inputs would ultimately result in the same type being created in BaseModel.__class_getitem__. To handle this, we have a fallback _late_cache_key that is checked later if the _early_cache_key lookup fails, and should result in a cache hit _precisely_ when the inputs to __class_getitem__ would result in the same type.
References pydantic._internal._generics._union_orderings_key.
Referenced by pydantic._internal._generics.get_cached_generic_type_early, pydantic._internal._generics.set_cached_generic_type.
GenericTypesCacheKey pydantic._internal._generics._late_cache_key(type[BaseModel] origin, tuple[Any,...] args, Any typevar_values)
This is intended for use later in the process of creating a new type, when we have more information about the exact args that will be passed. If it turns out that a different set of inputs to __class_getitem__ resulted in the same inputs to the generic type creation process, we can still return the cached type, and update the cache with the _early_cache_key as well.
References pydantic._internal._generics._union_orderings_key.
Referenced by pydantic._internal._generics.get_cached_generic_type_late, pydantic._internal._generics.set_cached_generic_type.