pip::_vendor::platformdirs::unix
int pip::_vendor::platformdirs::unix::getuid()
str pip::_vendor::platformdirs::unix::_get_user_media_dir(str env_var, str fallback_tilde_path)
References pip._vendor.platformdirs.unix._get_user_dirs_folder.
Referenced by pip._vendor.platformdirs.unix.Unix.user_desktop_dir, pip._vendor.platformdirs.unix.Unix.user_documents_dir, pip._vendor.platformdirs.unix.Unix.user_downloads_dir, pip._vendor.platformdirs.unix.Unix.user_music_dir, pip._vendor.platformdirs.unix.Unix.user_pictures_dir, pip._vendor.platformdirs.unix.Unix.user_videos_dir.
str None pip::_vendor::platformdirs::unix::_get_user_dirs_folder(str key)
Return directory from user-dirs.dirs config file. See https://freedesktop.org/wiki/Software/xdg-user-dirs/. Return directory from user-dirs.dirs config file. See https://freedesktop.org/wiki/Software/xdg-user-dirs/.
Referenced by pip._vendor.platformdirs.unix.Unix._first_item_as_path_if_multipath, pip._vendor.platformdirs.unix._get_user_media_dir.