setuptools::_distutils::dist
setuptools::_distutils::dist.warnings
setuptools::_distutils::dist.command_re
setuptools._distutils.dist._ensure_list(value, fieldname)
Referenced by setuptools._distutils.dist.DistributionMetadata.set_classifiers, setuptools._distutils.dist.DistributionMetadata.set_keywords, setuptools._distutils.dist.DistributionMetadata.set_platforms.
setuptools._distutils.dist.fix_help_options(options)
Convert a 4-tuple 'help_options' list as found in various command classes to the 3-tuple form required by FancyGetopt.
Referenced by setuptools._distutils.dist.Distribution._parse_command_opts, setuptools._distutils.dist.Distribution._show_help.