paho::mqtt::publish
paho::mqtt::publish.MessageTuple
paho::mqtt::publish.MessagesList
paho.mqtt.publish._do_publish(paho.Client client)
Internal function
Referenced by paho.mqtt.publish._on_connect, paho.mqtt.publish._on_publish.
paho.mqtt.publish._on_connect(paho.Client client, MessagesList userdata, flags, reason_code, properties)
Internal v5 callback
References paho.mqtt.publish._do_publish.
None paho.mqtt.publish._on_publish(paho.Client client, collections.deque[MessagesList] userdata, int mid, ReasonCode reason_codes, Properties properties)
Internal callback
References paho.mqtt.publish._do_publish.
None paho.mqtt.publish.multiple(MessagesList msgs, str hostname="localhost", int port=1883, str client_id="", int keepalive=60, MessageDict|None will=None, AuthParameter|None auth=None, TLSParameter|None tls=None, MQTTProtocolVersion protocol=paho.MQTTv311, Literal["tcp", "websockets"] transport="tcp", Any|None proxy_args=None)
Publish multiple messages to a broker, then disconnect cleanly. This function creates an MQTT client, connects to a broker and publishes a list of messages. Once the messages have been delivered, it disconnects cleanly from the broker. :param msgs: a list of messages to publish. Each message is either a dict or a tuple. If a dict, only the topic must be present. Default values will be used for any missing arguments. The dict must be of the form: msg = {'topic':"<topic>", 'payload':"<payload>", 'qos':<qos>, 'retain':<retain>} topic must be present and may not be empty. If payload is "", None or not present then a zero length payload will be published. If qos is not present, the default of 0 is used. If retain is not present, the default of False is used. If a tuple, then it must be of the form: ("<topic>", "<payload>", qos, retain) :param str hostname: the address of the broker to connect to. Defaults to localhost. :param int port: the port to connect to the broker on. Defaults to 1883. :param str client_id: the MQTT client id to use. If "" or None, the Paho library will generate a client id automatically. :param int keepalive: the keepalive timeout value for the client. Defaults to 60 seconds. :param will: a dict containing will parameters for the client: will = {'topic': "<topic>", 'payload':"<payload">, 'qos':<qos>, 'retain':<retain>}. Topic is required, all other parameters are optional and will default to None, 0 and False respectively. Defaults to None, which indicates no will should be used. :param auth: a dict containing authentication parameters for the client: auth = {'username':"<username>", 'password':"<password>"} Username is required, password is optional and will default to None if not provided. Defaults to None, which indicates no authentication is to be used. :param tls: a dict containing TLS configuration parameters for the client: dict = {'ca_certs':"<ca_certs>", 'certfile':"<certfile>", 'keyfile':"<keyfile>", 'tls_version':"<tls_version>", 'ciphers':"<ciphers">, 'insecure':"<bool>"} ca_certs is required, all other parameters are optional and will default to None if not provided, which results in the client using the default behaviour - see the paho.mqtt.client documentation. Alternatively, tls input can be an SSLContext object, which will be processed using the tls_set_context method. Defaults to None, which indicates that TLS should not be used. :param str transport: set to "tcp" to use the default setting of transport which is raw TCP. Set to "websockets" to use WebSockets as the transport. :param proxy_args: a dictionary that will be given to the client.
Referenced by paho.mqtt.publish.single.
None paho.mqtt.publish.single(str topic, paho.PayloadType payload=None, int qos=0, bool retain=False, str hostname="localhost", int port=1883, str client_id="", int keepalive=60, MessageDict|None will=None, AuthParameter|None auth=None, TLSParameter|None tls=None, MQTTProtocolVersion protocol=paho.MQTTv311, Literal["tcp", "websockets"] transport="tcp", Any|None proxy_args=None)
Publish a single message to a broker, then disconnect cleanly. This function creates an MQTT client, connects to a broker and publishes a single message. Once the message has been delivered, it disconnects cleanly from the broker. :param str topic: the only required argument must be the topic string to which the payload will be published. :param payload: the payload to be published. If "" or None, a zero length payload will be published. :param int qos: the qos to use when publishing, default to 0. :param bool retain: set the message to be retained (True) or not (False). :param str hostname: the address of the broker to connect to. Defaults to localhost. :param int port: the port to connect to the broker on. Defaults to 1883. :param str client_id: the MQTT client id to use. If "" or None, the Paho library will generate a client id automatically. :param int keepalive: the keepalive timeout value for the client. Defaults to 60 seconds. :param will: a dict containing will parameters for the client: will = {'topic': "<topic>", 'payload':"<payload">, 'qos':<qos>, 'retain':<retain>}. Topic is required, all other parameters are optional and will default to None, 0 and False respectively. Defaults to None, which indicates no will should be used. :param auth: a dict containing authentication parameters for the client: Username is required, password is optional and will default to None auth = {'username':"<username>", 'password':"<password>"} if not provided. Defaults to None, which indicates no authentication is to be used. :param tls: a dict containing TLS configuration parameters for the client: dict = {'ca_certs':"<ca_certs>", 'certfile':"<certfile>", 'keyfile':"<keyfile>", 'tls_version':"<tls_version>", 'ciphers':"<ciphers">, 'insecure':"<bool>"} ca_certs is required, all other parameters are optional and will default to None if not provided, which results in the client using the default behaviour - see the paho.mqtt.client documentation. Defaults to None, which indicates that TLS should not be used. Alternatively, tls input can be an SSLContext object, which will be processed using the tls_set_context method. :param transport: set to "tcp" to use the default setting of transport which is raw TCP. Set to "websockets" to use WebSockets as the transport. :param proxy_args: a dictionary that will be given to the client.
References paho.mqtt.publish.multiple.