anyio::lowlevel
anyio::lowlevel.T
anyio::lowlevel.D
WeakKeyDictionary anyio::lowlevel._run_vars
None anyio.lowlevel.checkpoint()
Check for cancellation and allow the scheduler to switch to another task. Equivalent to (but more efficient than):: await checkpoint_if_cancelled() await cancel_shielded_checkpoint() .. versionadded:: 3.0
References anyio.lowlevel.checkpoint.
Referenced by anyio.lowlevel.checkpoint.
None anyio.lowlevel.checkpoint_if_cancelled()
Enter a checkpoint if the enclosing cancel scope has been cancelled. This does not allow the scheduler to switch to a different task. .. versionadded:: 3.0
References anyio.lowlevel.checkpoint_if_cancelled.
Referenced by anyio.lowlevel.checkpoint_if_cancelled.
None anyio.lowlevel.cancel_shielded_checkpoint()
Allow the scheduler to switch to another task but without checking for cancellation. Equivalent to (but potentially more efficient than):: with CancelScope(shield=True): await checkpoint() .. versionadded:: 3.0
References anyio.lowlevel.cancel_shielded_checkpoint.
Referenced by anyio.lowlevel.cancel_shielded_checkpoint.
EventLoopToken anyio.lowlevel.current_token()
Return a token object that can be used to call code in the current event loop from another thread. .. versionadded:: 4.11.0
Referenced by anyio.lowlevel.RunVar._current_vars.