lib::microdot::microdot
list lib::microdot::microdot.MUTED_SOCKET_ERRORS
lib::microdot::microdot.abort
lib::microdot::microdot.redirect
lib::microdot::microdot.send_file
lib::microdot::microdot::invoke_handler(handler, *args, **kwargs)
Invoke a handler and return the result. This method runs sync handlers in a thread pool executor. Invoke a handler and return the result. This method runs sync handlers in the asyncio thread, which can potentially cause blocking and performance issues.
Referenced by lib.microdot.microdot.Microdot.dispatch_request, lib.microdot.microdot.Microdot.error_response.
lib.microdot.microdot.iscoroutine(coro)
References lib.microdot.microdot.iscoroutine.
Referenced by lib.microdot.microdot.iscoroutine.
lib.microdot.microdot.print_exception(exc)
Referenced by lib.microdot.microdot.Microdot.dispatch_request, lib.microdot.microdot.Microdot.handle_request.
lib.microdot.microdot.urldecode(s)
Referenced by lib.microdot.microdot.Request._parse_urlencoded.
lib.microdot.microdot.urlencode(s)
lib.microdot.microdot.mro(cls)
Return the method resolution order of a class. This is a helper function that returns the method resolution order of a class. It is used by Microdot to find the best error handler to invoke for the raised exception. In CPython, this function returns the ``__mro__`` attribute of the class. In MicroPython, this function implements a recursive depth-first scanning of the class hierarchy.
Referenced by lib.microdot.microdot.Microdot.dispatch_request.