pip::_vendor::tomli_w::_writer
bool pip::_vendor::tomli_w::_writer.TYPE_CHECKING
pip::_vendor::tomli_w::_writer.ASCII_CTRL
pip::_vendor::tomli_w::_writer.ILLEGAL_BASIC_STR_CHARS
pip::_vendor::tomli_w::_writer.BARE_KEY_CHARS
tuple pip::_vendor::tomli_w::_writer.ARRAY_TYPES
int pip::_vendor::tomli_w::_writer.MAX_LINE_LENGTH
pip::_vendor::tomli_w::_writer.COMPACT_ESCAPES
None pip._vendor.tomli_w._writer.dump(Mapping[str, Any] obj, IO[bytes] fp, *, bool multiline_strings=False, int indent=4)
References pip._vendor.tomli_w._writer.gen_table_chunks.
str pip._vendor.tomli_w._writer.dumps(Mapping[str, Any] obj, *, bool multiline_strings=False, int indent=4)
References pip._vendor.tomli_w._writer.gen_table_chunks.
Generator[str, None, None] pip._vendor.tomli_w._writer.gen_table_chunks(Mapping[str, Any] table, Context ctx, *, str name, bool inside_aot=False)
References pip._vendor.tomli_w._writer.format_key_part, pip._vendor.tomli_w._writer.gen_table_chunks, pip._vendor.tomli_w._writer.is_aot, pip._vendor.tomli_w._writer.is_suitable_inline_table.
Referenced by pip._vendor.tomli_w._writer.dump, pip._vendor.tomli_w._writer.dumps, pip._vendor.tomli_w._writer.gen_table_chunks.
str pip._vendor.tomli_w._writer.format_literal(object obj, Context ctx, *, int nest_level=0)
References pip._vendor.tomli_w._writer.format_decimal, pip._vendor.tomli_w._writer.format_inline_array, pip._vendor.tomli_w._writer.format_inline_table, pip._vendor.tomli_w._writer.format_string.
Referenced by pip._vendor.tomli_w._writer.format_inline_array.
str pip._vendor.tomli_w._writer.format_decimal(Decimal obj)
Referenced by pip._vendor.tomli_w._writer.format_literal.
str pip._vendor.tomli_w._writer.format_inline_table(Mapping obj, Context ctx)
Referenced by pip._vendor.tomli_w._writer.format_literal.
str pip._vendor.tomli_w._writer.format_inline_array(tuple|list obj, Context ctx, int nest_level)
References pip._vendor.tomli_w._writer.format_literal.
Referenced by pip._vendor.tomli_w._writer.format_literal.
str pip._vendor.tomli_w._writer.format_key_part(str part)
References pip._vendor.tomli_w._writer.format_string.
Referenced by pip._vendor.tomli_w._writer.gen_table_chunks.
str pip._vendor.tomli_w._writer.format_string(str s, *, bool allow_multiline)
Referenced by pip._vendor.tomli_w._writer.format_key_part, pip._vendor.tomli_w._writer.format_literal.
bool pip._vendor.tomli_w._writer.is_aot(Any obj)
Decides if an object behaves as an array of tables (i.e. a nonempty list of dicts).
Referenced by pip._vendor.tomli_w._writer.gen_table_chunks.
bool pip._vendor.tomli_w._writer.is_suitable_inline_table(Mapping obj, Context ctx)
Use heuristics to decide if the inline-style representation is a good choice for a given table.
Referenced by pip._vendor.tomli_w._writer.gen_table_chunks.