click::_termui_impl
click::_termui_impl.V
str click::_termui_impl::BEFORE_BAR
str click::_termui_impl::AFTER_BAR
None click._termui_impl.pager(cabc.Iterable[str] generator, bool|None color=None)
Decide what method to use for paging through text.
References click._termui_impl._nullpager, click._termui_impl._pipepager, click._termui_impl._tempfilepager.
bool click._termui_impl._pipepager(cabc.Iterable[str] generator, list[str] cmd_parts, bool|None color)
Page through text by feeding it to another program. Invoking a pager through this might support colors. Returns `True` if the command was found, `False` otherwise and thus another pager should be attempted.
Referenced by click._termui_impl.pager.
bool click._termui_impl._tempfilepager(cabc.Iterable[str] generator, list[str] cmd_parts, bool|None color)
Page through text by invoking a program on a temporary file. Returns `True` if the command was found, `False` otherwise and thus another pager should be attempted.
Referenced by click._termui_impl.pager.
None click._termui_impl._nullpager(t.TextIO stream, cabc.Iterable[str] generator, bool|None color)
Simply print unformatted text. This is the ultimate fallback.
Referenced by click._termui_impl.pager.
int click._termui_impl.open_url(str url, bool wait=False, bool locate=False)
None click._termui_impl._translate_ch_to_exc(str ch)
Referenced by click._termui_impl.getchar.
cabc.Iterator[int] click._termui_impl.raw_terminal()
Referenced by click._termui_impl.getchar.
str click::_termui_impl::getchar(bool echo)
References click._termui_impl._translate_ch_to_exc, click._termui_impl.raw_terminal.