pip::_vendor::colorama::tests::isatty_test
pip._vendor.colorama.tests.isatty_test.is_a_tty(stream)
Referenced by pip._vendor.colorama.tests.isatty_test.IsattyTest.test_nonTTY, pip._vendor.colorama.tests.isatty_test.IsattyTest.test_TTY, pip._vendor.colorama.tests.isatty_test.IsattyTest.test_withPycharm, pip._vendor.colorama.tests.isatty_test.IsattyTest.test_withPycharmNoneOverride, pip._vendor.colorama.tests.isatty_test.IsattyTest.test_withPycharmNonTTYOverride, pip._vendor.colorama.tests.isatty_test.IsattyTest.test_withPycharmTTYOverride.