pydantic_core::core_schema
pydantic_core::core_schema.PydanticUndefined
pydantic_core::core_schema.ExtraBehavior
pydantic_core::core_schema.ContextT
pydantic_core::core_schema.ExpectedSerializationTypes
pydantic_core::core_schema.GeneralPlainNoInfoSerializerFunction
pydantic_core::core_schema.GeneralPlainInfoSerializerFunction
pydantic_core::core_schema.FieldPlainNoInfoSerializerFunction
pydantic_core::core_schema.FieldPlainInfoSerializerFunction
pydantic_core::core_schema.SerializerFunction
pydantic_core::core_schema.WhenUsed
pydantic_core::core_schema.GeneralWrapNoInfoSerializerFunction
pydantic_core::core_schema.GeneralWrapInfoSerializerFunction
pydantic_core::core_schema.FieldWrapNoInfoSerializerFunction
pydantic_core::core_schema.FieldWrapInfoSerializerFunction
pydantic_core::core_schema.WrapSerializerFunction
pydantic_core::core_schema.SerSchema
pydantic_core::core_schema.JsonType
pydantic_core::core_schema.IncExSeqOrElseSerSchema
pydantic_core::core_schema.IncExDict
pydantic_core::core_schema.IncExDictOrElseSerSchema
pydantic_core::core_schema.NoInfoValidatorFunction
pydantic_core::core_schema.WithInfoValidatorFunction
pydantic_core::core_schema.ValidationFunction
pydantic_core::core_schema.NoInfoWrapValidatorFunction
pydantic_core::core_schema.WithInfoWrapValidatorFunction
pydantic_core::core_schema.WrapValidatorFunction
TypeAlias pydantic_core::core_schema.VarKwargsMode
bool pydantic_core::core_schema.MYPY
TypeAlias pydantic_core::core_schema::CoreSchema
pydantic_core::core_schema.CoreSchemaType
pydantic_core::core_schema.CoreSchemaFieldType
pydantic_core::core_schema.ErrorType
dict pydantic_core::core_schema._deprecated_import_lookup
pydantic_core::core_schema.FieldValidationInfo
SimpleSerSchema pydantic_core.core_schema.simple_ser_schema(ExpectedSerializationTypes type)
Returns a schema for serialization with a custom type. Args: type: The type to use for serialization
PlainSerializerFunctionSerSchema pydantic_core.core_schema.plain_serializer_function_ser_schema(SerializerFunction function, *, bool|None is_field_serializer=None, bool|None info_arg=None, CoreSchema|None return_schema=None, WhenUsed when_used='always')
Returns a schema for serialization with a function, can be either a "general" or "field" function. Args: function: The function to use for serialization is_field_serializer: Whether the serializer is for a field, e.g. takes `model` as the first argument, and `info` includes `field_name` info_arg: Whether the function takes an `info` argument return_schema: Schema to use for serializing return value when_used: When the function should be called
References pydantic_core.core_schema._dict_not_none.
WrapSerializerFunctionSerSchema pydantic_core.core_schema.wrap_serializer_function_ser_schema(WrapSerializerFunction function, *, bool|None is_field_serializer=None, bool|None info_arg=None, CoreSchema|None schema=None, CoreSchema|None return_schema=None, WhenUsed when_used='always')
Returns a schema for serialization with a wrap function, can be either a "general" or "field" function. Args: function: The function to use for serialization is_field_serializer: Whether the serializer is for a field, e.g. takes `model` as the first argument, and `info` includes `field_name` info_arg: Whether the function takes an `info` argument schema: The schema to use for the inner serialization return_schema: Schema to use for serializing return value when_used: When the function should be called
References pydantic_core.core_schema._dict_not_none.
FormatSerSchema pydantic_core.core_schema.format_ser_schema(str formatting_string, *, WhenUsed when_used='json-unless-none')
Returns a schema for serialization using python's `format` method. Args: formatting_string: String defining the format to use when_used: Same meaning as for [general_function_plain_ser_schema], but with a different default
References pydantic_core.core_schema._dict_not_none.
ToStringSerSchema pydantic_core.core_schema.to_string_ser_schema(*, WhenUsed when_used='json-unless-none')
Returns a schema for serialization using python's `str()` / `__str__` method. Args: when_used: Same meaning as for [general_function_plain_ser_schema], but with a different default
ModelSerSchema pydantic_core.core_schema.model_ser_schema(type[Any] cls, CoreSchema schema)
Returns a schema for serialization using a model. Args: cls: The expected class type, used to generate warnings if the wrong type is passed schema: Internal schema to use to serialize the model dict
InvalidSchema pydantic_core.core_schema.invalid_schema(str|None ref=None, dict[str, Any]|None metadata=None)
Returns an invalid schema, used to indicate that a schema is invalid. Returns a schema that matches any value, e.g.: Args: ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core
References pydantic_core.core_schema._dict_not_none.
ComputedField pydantic_core.core_schema.computed_field(str property_name, CoreSchema return_schema, *, str|None alias=None, dict[str, Any]|None metadata=None)
ComputedFields are properties of a model or dataclass that are included in serialization. Args: property_name: The name of the property on the model or dataclass return_schema: The schema used for the type returned by the computed field alias: The name to use in the serialized output metadata: Any other information you want to include with the schema, not used by pydantic-core
References pydantic_core.core_schema._dict_not_none.
AnySchema pydantic_core.core_schema.any_schema(*, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches any value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.any_schema() v = SchemaValidator(schema) assert v.validate_python(1) == 1 ``` Args: ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
Referenced by pydantic_core.core_schema.tuple_variable_schema.
NoneSchema pydantic_core.core_schema.none_schema(*, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a None value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.none_schema() v = SchemaValidator(schema) assert v.validate_python(None) is None ``` Args: ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
BoolSchema pydantic_core.core_schema.bool_schema(bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a bool value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.bool_schema() v = SchemaValidator(schema) assert v.validate_python('True') is True ``` Args: strict: Whether the value should be a bool or a value that can be converted to a bool ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
IntSchema pydantic_core.core_schema.int_schema(*, int|None multiple_of=None, int|None le=None, int|None ge=None, int|None lt=None, int|None gt=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a int value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.int_schema(multiple_of=2, le=6, ge=2) v = SchemaValidator(schema) assert v.validate_python('4') == 4 ``` Args: multiple_of: The value must be a multiple of this number le: The value must be less than or equal to this number ge: The value must be greater than or equal to this number lt: The value must be strictly less than this number gt: The value must be strictly greater than this number strict: Whether the value should be a int or a value that can be converted to a int ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
FloatSchema pydantic_core.core_schema.float_schema(*, bool|None allow_inf_nan=None, float|None multiple_of=None, float|None le=None, float|None ge=None, float|None lt=None, float|None gt=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a float value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.float_schema(le=0.8, ge=0.2) v = SchemaValidator(schema) assert v.validate_python('0.5') == 0.5 ``` Args: allow_inf_nan: Whether to allow inf and nan values multiple_of: The value must be a multiple of this number le: The value must be less than or equal to this number ge: The value must be greater than or equal to this number lt: The value must be strictly less than this number gt: The value must be strictly greater than this number strict: Whether the value should be a float or a value that can be converted to a float ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
DecimalSchema pydantic_core.core_schema.decimal_schema(*, bool|None allow_inf_nan=None, Decimal|None multiple_of=None, Decimal|None le=None, Decimal|None ge=None, Decimal|None lt=None, Decimal|None gt=None, int|None max_digits=None, int|None decimal_places=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a decimal value, e.g.: ```py from decimal import Decimal from pydantic_core import SchemaValidator, core_schema schema = core_schema.decimal_schema(le=0.8, ge=0.2) v = SchemaValidator(schema) assert v.validate_python('0.5') == Decimal('0.5') ``` Args: allow_inf_nan: Whether to allow inf and nan values multiple_of: The value must be a multiple of this number le: The value must be less than or equal to this number ge: The value must be greater than or equal to this number lt: The value must be strictly less than this number gt: The value must be strictly greater than this number max_digits: The maximum number of decimal digits allowed decimal_places: The maximum number of decimal places allowed strict: Whether the value should be a float or a value that can be converted to a float ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
ComplexSchema pydantic_core.core_schema.complex_schema(*, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a complex value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.complex_schema() v = SchemaValidator(schema) assert v.validate_python('1+2j') == complex(1, 2) assert v.validate_python(complex(1, 2)) == complex(1, 2) ``` Args: strict: Whether the value should be a complex object instance or a value that can be converted to a complex object ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
StringSchema pydantic_core.core_schema.str_schema(*, str|Pattern[str]|None pattern=None, int|None max_length=None, int|None min_length=None, bool|None strip_whitespace=None, bool|None to_lower=None, bool|None to_upper=None, Literal['rust-regex', 'python-re']|None regex_engine=None, bool|None strict=None, bool|None coerce_numbers_to_str=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a string value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.str_schema(max_length=10, min_length=2) v = SchemaValidator(schema) assert v.validate_python('hello') == 'hello' ``` Args: pattern: A regex pattern that the value must match max_length: The value must be at most this length min_length: The value must be at least this length strip_whitespace: Whether to strip whitespace from the value to_lower: Whether to convert the value to lowercase to_upper: Whether to convert the value to uppercase regex_engine: The regex engine to use for pattern validation. Default is 'rust-regex'. - `rust-regex` uses the [`regex`](https://docs.rs/regex) Rust crate, which is non-backtracking and therefore more DDoS resistant, but does not support all regex features. - `python-re` use the [`re`](https://docs.python.org/3/library/re.html) module, which supports all regex features, but may be slower. strict: Whether the value should be a string or a value that can be converted to a string coerce_numbers_to_str: Whether to enable coercion of any `Number` type to `str` (not applicable in `strict` mode). ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
BytesSchema pydantic_core.core_schema.bytes_schema(*, int|None max_length=None, int|None min_length=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a bytes value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.bytes_schema(max_length=10, min_length=2) v = SchemaValidator(schema) assert v.validate_python(b'hello') == b'hello' ``` Args: max_length: The value must be at most this length min_length: The value must be at least this length strict: Whether the value should be a bytes or a value that can be converted to a bytes ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
DateSchema pydantic_core.core_schema.date_schema(*, bool|None strict=None, date|None le=None, date|None ge=None, date|None lt=None, date|None gt=None, Literal['past', 'future']|None now_op=None, int|None now_utc_offset=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a date value, e.g.: ```py from datetime import date from pydantic_core import SchemaValidator, core_schema schema = core_schema.date_schema(le=date(2020, 1, 1), ge=date(2019, 1, 1)) v = SchemaValidator(schema) assert v.validate_python(date(2019, 6, 1)) == date(2019, 6, 1) ``` Args: strict: Whether the value should be a date or a value that can be converted to a date le: The value must be less than or equal to this date ge: The value must be greater than or equal to this date lt: The value must be strictly less than this date gt: The value must be strictly greater than this date now_op: The value must be in the past or future relative to the current date now_utc_offset: The value must be in the past or future relative to the current date with this utc offset ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
TimeSchema pydantic_core.core_schema.time_schema(*, bool|None strict=None, time|None le=None, time|None ge=None, time|None lt=None, time|None gt=None, Literal['aware', 'naive']|int|None tz_constraint=None, Literal['truncate', 'error'] microseconds_precision='truncate', str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a time value, e.g.: ```py from datetime import time from pydantic_core import SchemaValidator, core_schema schema = core_schema.time_schema(le=time(12, 0, 0), ge=time(6, 0, 0)) v = SchemaValidator(schema) assert v.validate_python(time(9, 0, 0)) == time(9, 0, 0) ``` Args: strict: Whether the value should be a time or a value that can be converted to a time le: The value must be less than or equal to this time ge: The value must be greater than or equal to this time lt: The value must be strictly less than this time gt: The value must be strictly greater than this time tz_constraint: The value must be timezone aware or naive, or an int to indicate required tz offset microseconds_precision: The behavior when seconds have more than 6 digits or microseconds is too large ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
DatetimeSchema pydantic_core.core_schema.datetime_schema(*, bool|None strict=None, datetime|None le=None, datetime|None ge=None, datetime|None lt=None, datetime|None gt=None, Literal['past', 'future']|None now_op=None, Literal['aware', 'naive']|int|None tz_constraint=None, int|None now_utc_offset=None, Literal['truncate', 'error'] microseconds_precision='truncate', str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a datetime value, e.g.: ```py from datetime import datetime from pydantic_core import SchemaValidator, core_schema schema = core_schema.datetime_schema() v = SchemaValidator(schema) now = datetime.now() assert v.validate_python(str(now)) == now ``` Args: strict: Whether the value should be a datetime or a value that can be converted to a datetime le: The value must be less than or equal to this datetime ge: The value must be greater than or equal to this datetime lt: The value must be strictly less than this datetime gt: The value must be strictly greater than this datetime now_op: The value must be in the past or future relative to the current datetime tz_constraint: The value must be timezone aware or naive, or an int to indicate required tz offset TODO: use of a tzinfo where offset changes based on the datetime is not yet supported now_utc_offset: The value must be in the past or future relative to the current datetime with this utc offset microseconds_precision: The behavior when seconds have more than 6 digits or microseconds is too large ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
TimedeltaSchema pydantic_core.core_schema.timedelta_schema(*, bool|None strict=None, timedelta|None le=None, timedelta|None ge=None, timedelta|None lt=None, timedelta|None gt=None, Literal['truncate', 'error'] microseconds_precision='truncate', str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a timedelta value, e.g.: ```py from datetime import timedelta from pydantic_core import SchemaValidator, core_schema schema = core_schema.timedelta_schema(le=timedelta(days=1), ge=timedelta(days=0)) v = SchemaValidator(schema) assert v.validate_python(timedelta(hours=12)) == timedelta(hours=12) ``` Args: strict: Whether the value should be a timedelta or a value that can be converted to a timedelta le: The value must be less than or equal to this timedelta ge: The value must be greater than or equal to this timedelta lt: The value must be strictly less than this timedelta gt: The value must be strictly greater than this timedelta microseconds_precision: The behavior when seconds have more than 6 digits or microseconds is too large ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
LiteralSchema pydantic_core.core_schema.literal_schema(list[Any] expected, *, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a literal value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.literal_schema(['hello', 'world']) v = SchemaValidator(schema) assert v.validate_python('hello') == 'hello' ``` Args: expected: The value must be one of these values ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
EnumSchema pydantic_core.core_schema.enum_schema(Any cls, list[Any] members, *, Literal['str', 'int', 'float']|None sub_type=None, Callable[[Any], Any]|None missing=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches an enum value, e.g.: ```py from enum import Enum from pydantic_core import SchemaValidator, core_schema class Color(Enum): RED = 1 GREEN = 2 BLUE = 3 schema = core_schema.enum_schema(Color, list(Color.__members__.values())) v = SchemaValidator(schema) assert v.validate_python(2) is Color.GREEN ``` Args: cls: The enum class members: The members of the enum, generally `list(MyEnum.__members__.values())` sub_type: The type of the enum, either 'str' or 'int' or None for plain enums missing: A function to use when the value is not found in the enum, from `_missing_` strict: Whether to use strict mode, defaults to False ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
MissingSentinelSchema pydantic_core.core_schema.missing_sentinel_schema(dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema for the `MISSING` sentinel.
References pydantic_core.core_schema._dict_not_none.
IsInstanceSchema pydantic_core.core_schema.is_instance_schema(Any cls, *, str|None cls_repr=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that checks if a value is an instance of a class, equivalent to python's `isinstance` method, e.g.: ```py from pydantic_core import SchemaValidator, core_schema class A: pass schema = core_schema.is_instance_schema(cls=A) v = SchemaValidator(schema) v.validate_python(A()) ``` Args: cls: The value must be an instance of this class cls_repr: If provided this string is used in the validator name instead of `repr(cls)` ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
IsInstanceSchema pydantic_core.core_schema.is_subclass_schema(type[Any] cls, *, str|None cls_repr=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that checks if a value is a subtype of a class, equivalent to python's `issubclass` method, e.g.: ```py from pydantic_core import SchemaValidator, core_schema class A: pass class B(A): pass schema = core_schema.is_subclass_schema(cls=A) v = SchemaValidator(schema) v.validate_python(B) ``` Args: cls: The value must be a subclass of this class cls_repr: If provided this string is used in the validator name instead of `repr(cls)` ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
CallableSchema pydantic_core.core_schema.callable_schema(*, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that checks if a value is callable, equivalent to python's `callable` method, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.callable_schema() v = SchemaValidator(schema) v.validate_python(min) ``` Args: ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
UuidSchema pydantic_core.core_schema.uuid_schema(*, Literal[1, 3, 4, 5, 6, 7, 8]|None version=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
References pydantic_core.core_schema._dict_not_none.
IncExSeqSerSchema pydantic_core.core_schema.filter_seq_schema(*, set[int]|None include=None, set[int]|None exclude=None)
References pydantic_core.core_schema._dict_not_none.
ListSchema pydantic_core.core_schema.list_schema(CoreSchema|None items_schema=None, *, int|None min_length=None, int|None max_length=None, bool|None fail_fast=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, IncExSeqOrElseSerSchema|None serialization=None)
Returns a schema that matches a list value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.list_schema(core_schema.int_schema(), min_length=0, max_length=10) v = SchemaValidator(schema) assert v.validate_python(['4']) == [4] ``` Args: items_schema: The value must be a list of items that match this schema min_length: The value must be a list with at least this many items max_length: The value must be a list with at most this many items fail_fast: Stop validation on the first error strict: The value must be a list with exactly this many items ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
TupleSchema pydantic_core.core_schema.tuple_positional_schema(list[CoreSchema] items_schema, *, CoreSchema|None extras_schema=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, IncExSeqOrElseSerSchema|None serialization=None)
Returns a schema that matches a tuple of schemas, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.tuple_positional_schema( [core_schema.int_schema(), core_schema.str_schema()] ) v = SchemaValidator(schema) assert v.validate_python((1, 'hello')) == (1, 'hello') ``` Args: items_schema: The value must be a tuple with items that match these schemas extras_schema: The value must be a tuple with items that match this schema This was inspired by JSON schema's `prefixItems` and `items` fields. In python's `typing.Tuple`, you can't specify a type for "extra" items -- they must all be the same type if the length is variable. So this field won't be set from a `typing.Tuple` annotation on a pydantic model. strict: The value must be a tuple with exactly this many items ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema.tuple_schema.
TupleSchema pydantic_core.core_schema.tuple_variable_schema(CoreSchema|None items_schema=None, *, int|None min_length=None, int|None max_length=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, IncExSeqOrElseSerSchema|None serialization=None)
Returns a schema that matches a tuple of a given schema, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.tuple_variable_schema( items_schema=core_schema.int_schema(), min_length=0, max_length=10 ) v = SchemaValidator(schema) assert v.validate_python(('1', 2, 3)) == (1, 2, 3) ``` Args: items_schema: The value must be a tuple with items that match this schema min_length: The value must be a tuple with at least this many items max_length: The value must be a tuple with at most this many items strict: The value must be a tuple with exactly this many items ref: Optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema.any_schema, pydantic_core.core_schema.tuple_schema.
TupleSchema pydantic_core.core_schema.tuple_schema(list[CoreSchema] items_schema, *, int|None variadic_item_index=None, int|None min_length=None, int|None max_length=None, bool|None fail_fast=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, IncExSeqOrElseSerSchema|None serialization=None)
Returns a schema that matches a tuple of schemas, with an optional variadic item, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.tuple_schema( [core_schema.int_schema(), core_schema.str_schema(), core_schema.float_schema()], variadic_item_index=1, ) v = SchemaValidator(schema) assert v.validate_python((1, 'hello', 'world', 1.5)) == (1, 'hello', 'world', 1.5) ``` Args: items_schema: The value must be a tuple with items that match these schemas variadic_item_index: The index of the schema in `items_schema` to be treated as variadic (following PEP 646) min_length: The value must be a tuple with at least this many items max_length: The value must be a tuple with at most this many items fail_fast: Stop validation on the first error strict: The value must be a tuple with exactly this many items ref: Optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
Referenced by pydantic_core.core_schema.tuple_positional_schema, pydantic_core.core_schema.tuple_variable_schema.
SetSchema pydantic_core.core_schema.set_schema(CoreSchema|None items_schema=None, *, int|None min_length=None, int|None max_length=None, bool|None fail_fast=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a set of a given schema, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.set_schema( items_schema=core_schema.int_schema(), min_length=0, max_length=10 ) v = SchemaValidator(schema) assert v.validate_python({1, '2', 3}) == {1, 2, 3} ``` Args: items_schema: The value must be a set with items that match this schema min_length: The value must be a set with at least this many items max_length: The value must be a set with at most this many items fail_fast: Stop validation on the first error strict: The value must be a set with exactly this many items ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
FrozenSetSchema pydantic_core.core_schema.frozenset_schema(CoreSchema|None items_schema=None, *, int|None min_length=None, int|None max_length=None, bool|None fail_fast=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a frozenset of a given schema, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.frozenset_schema( items_schema=core_schema.int_schema(), min_length=0, max_length=10 ) v = SchemaValidator(schema) assert v.validate_python(frozenset(range(3))) == frozenset({0, 1, 2}) ``` Args: items_schema: The value must be a frozenset with items that match this schema min_length: The value must be a frozenset with at least this many items max_length: The value must be a frozenset with at most this many items fail_fast: Stop validation on the first error strict: The value must be a frozenset with exactly this many items ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
GeneratorSchema pydantic_core.core_schema.generator_schema(CoreSchema|None items_schema=None, *, int|None min_length=None, int|None max_length=None, str|None ref=None, dict[str, Any]|None metadata=None, IncExSeqOrElseSerSchema|None serialization=None)
Returns a schema that matches a generator value, e.g.: ```py from typing import Iterator from pydantic_core import SchemaValidator, core_schema def gen() -> Iterator[int]: yield 1 schema = core_schema.generator_schema(items_schema=core_schema.int_schema()) v = SchemaValidator(schema) v.validate_python(gen()) ``` Unlike other types, validated generators do not raise ValidationErrors eagerly, but instead will raise a ValidationError when a violating value is actually read from the generator. This is to ensure that "validated" generators retain the benefit of lazy evaluation. Args: items_schema: The value must be a generator with items that match this schema min_length: The value must be a generator that yields at least this many items max_length: The value must be a generator that yields at most this many items ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
IncExDictSerSchema pydantic_core.core_schema.filter_dict_schema(*, IncExDict|None include=None, IncExDict|None exclude=None)
References pydantic_core.core_schema._dict_not_none.
DictSchema pydantic_core.core_schema.dict_schema(CoreSchema|None keys_schema=None, CoreSchema|None values_schema=None, *, int|None min_length=None, int|None max_length=None, bool|None fail_fast=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a dict value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.dict_schema( keys_schema=core_schema.str_schema(), values_schema=core_schema.int_schema() ) v = SchemaValidator(schema) assert v.validate_python({'a': '1', 'b': 2}) == {'a': 1, 'b': 2} ``` Args: keys_schema: The value must be a dict with keys that match this schema values_schema: The value must be a dict with values that match this schema min_length: The value must be a dict with at least this many items max_length: The value must be a dict with at most this many items fail_fast: Stop validation on the first error strict: Whether the keys and values should be validated with strict mode ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
BeforeValidatorFunctionSchema pydantic_core.core_schema.no_info_before_validator_function(NoInfoValidatorFunction function, CoreSchema schema, *, str|None ref=None, CoreSchema|None json_schema_input_schema=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that calls a validator function before validating, no `info` argument is provided, e.g.: ```py from pydantic_core import SchemaValidator, core_schema def fn(v: bytes) -> str: return v.decode() + 'world' func_schema = core_schema.no_info_before_validator_function( function=fn, schema=core_schema.str_schema() ) schema = core_schema.typed_dict_schema({'a': core_schema.typed_dict_field(func_schema)}) v = SchemaValidator(schema) assert v.validate_python({'a': b'hello '}) == {'a': 'hello world'} ``` Args: function: The validator function to call schema: The schema to validate the output of the validator function ref: optional unique identifier of the schema, used to reference the schema in other places json_schema_input_schema: The core schema to be used to generate the corresponding JSON Schema input type metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
BeforeValidatorFunctionSchema pydantic_core.core_schema.with_info_before_validator_function(WithInfoValidatorFunction function, CoreSchema schema, *, str|None field_name=None, str|None ref=None, CoreSchema|None json_schema_input_schema=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that calls a validator function before validation, the function is called with an `info` argument, e.g.: ```py from pydantic_core import SchemaValidator, core_schema def fn(v: bytes, info: core_schema.ValidationInfo) -> str: assert info.data is not None assert info.field_name is not None return v.decode() + 'world' func_schema = core_schema.with_info_before_validator_function( function=fn, schema=core_schema.str_schema() ) schema = core_schema.typed_dict_schema({'a': core_schema.typed_dict_field(func_schema)}) v = SchemaValidator(schema) assert v.validate_python({'a': b'hello '}) == {'a': 'hello world'} ``` Args: function: The validator function to call field_name: The name of the field this validator is applied to, if any (deprecated) schema: The schema to validate the output of the validator function ref: optional unique identifier of the schema, used to reference the schema in other places json_schema_input_schema: The core schema to be used to generate the corresponding JSON Schema input type metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
Referenced by pydantic_core.core_schema.field_before_validator_function, pydantic_core.core_schema.general_before_validator_function.
AfterValidatorFunctionSchema pydantic_core.core_schema.no_info_after_validator_function(NoInfoValidatorFunction function, CoreSchema schema, *, str|None ref=None, CoreSchema|None json_schema_input_schema=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that calls a validator function after validating, no `info` argument is provided, e.g.: ```py from pydantic_core import SchemaValidator, core_schema def fn(v: str) -> str: return v + 'world' func_schema = core_schema.no_info_after_validator_function(fn, core_schema.str_schema()) schema = core_schema.typed_dict_schema({'a': core_schema.typed_dict_field(func_schema)}) v = SchemaValidator(schema) assert v.validate_python({'a': b'hello '}) == {'a': 'hello world'} ``` Args: function: The validator function to call after the schema is validated schema: The schema to validate before the validator function ref: optional unique identifier of the schema, used to reference the schema in other places json_schema_input_schema: The core schema to be used to generate the corresponding JSON Schema input type metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
AfterValidatorFunctionSchema pydantic_core.core_schema.with_info_after_validator_function(WithInfoValidatorFunction function, CoreSchema schema, *, str|None field_name=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that calls a validator function after validation, the function is called with an `info` argument, e.g.: ```py from pydantic_core import SchemaValidator, core_schema def fn(v: str, info: core_schema.ValidationInfo) -> str: assert info.data is not None assert info.field_name is not None return v + 'world' func_schema = core_schema.with_info_after_validator_function( function=fn, schema=core_schema.str_schema() ) schema = core_schema.typed_dict_schema({'a': core_schema.typed_dict_field(func_schema)}) v = SchemaValidator(schema) assert v.validate_python({'a': b'hello '}) == {'a': 'hello world'} ``` Args: function: The validator function to call after the schema is validated schema: The schema to validate before the validator function field_name: The name of the field this validator is applied to, if any (deprecated) ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
Referenced by pydantic_core.core_schema.field_after_validator_function, pydantic_core.core_schema.general_after_validator_function.
WrapValidatorFunctionSchema pydantic_core.core_schema.no_info_wrap_validator_function(NoInfoWrapValidatorFunction function, CoreSchema schema, *, str|None ref=None, CoreSchema|None json_schema_input_schema=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema which calls a function with a `validator` callable argument which can optionally be used to call inner validation with the function logic, this is much like the "onion" implementation of middleware in many popular web frameworks, no `info` argument is passed, e.g.: ```py from pydantic_core import SchemaValidator, core_schema def fn( v: str, validator: core_schema.ValidatorFunctionWrapHandler, ) -> str: return validator(input_value=v) + 'world' schema = core_schema.no_info_wrap_validator_function( function=fn, schema=core_schema.str_schema() ) v = SchemaValidator(schema) assert v.validate_python('hello ') == 'hello world' ``` Args: function: The validator function to call schema: The schema to validate the output of the validator function ref: optional unique identifier of the schema, used to reference the schema in other places json_schema_input_schema: The core schema to be used to generate the corresponding JSON Schema input type metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
WrapValidatorFunctionSchema pydantic_core.core_schema.with_info_wrap_validator_function(WithInfoWrapValidatorFunction function, CoreSchema schema, *, str|None field_name=None, CoreSchema|None json_schema_input_schema=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema which calls a function with a `validator` callable argument which can optionally be used to call inner validation with the function logic, this is much like the "onion" implementation of middleware in many popular web frameworks, an `info` argument is also passed, e.g.: ```py from pydantic_core import SchemaValidator, core_schema def fn( v: str, validator: core_schema.ValidatorFunctionWrapHandler, info: core_schema.ValidationInfo, ) -> str: return validator(input_value=v) + 'world' schema = core_schema.with_info_wrap_validator_function( function=fn, schema=core_schema.str_schema() ) v = SchemaValidator(schema) assert v.validate_python('hello ') == 'hello world' ``` Args: function: The validator function to call schema: The schema to validate the output of the validator function field_name: The name of the field this validator is applied to, if any (deprecated) json_schema_input_schema: The core schema to be used to generate the corresponding JSON Schema input type ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
Referenced by pydantic_core.core_schema.field_wrap_validator_function, pydantic_core.core_schema.general_wrap_validator_function.
PlainValidatorFunctionSchema pydantic_core.core_schema.no_info_plain_validator_function(NoInfoValidatorFunction function, *, str|None ref=None, CoreSchema|None json_schema_input_schema=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that uses the provided function for validation, no `info` argument is passed, e.g.: ```py from pydantic_core import SchemaValidator, core_schema def fn(v: str) -> str: assert 'hello' in v return v + 'world' schema = core_schema.no_info_plain_validator_function(function=fn) v = SchemaValidator(schema) assert v.validate_python('hello ') == 'hello world' ``` Args: function: The validator function to call ref: optional unique identifier of the schema, used to reference the schema in other places json_schema_input_schema: The core schema to be used to generate the corresponding JSON Schema input type metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
PlainValidatorFunctionSchema pydantic_core.core_schema.with_info_plain_validator_function(WithInfoValidatorFunction function, *, str|None field_name=None, str|None ref=None, CoreSchema|None json_schema_input_schema=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that uses the provided function for validation, an `info` argument is passed, e.g.: ```py from pydantic_core import SchemaValidator, core_schema def fn(v: str, info: core_schema.ValidationInfo) -> str: assert 'hello' in v return v + 'world' schema = core_schema.with_info_plain_validator_function(function=fn) v = SchemaValidator(schema) assert v.validate_python('hello ') == 'hello world' ``` Args: function: The validator function to call field_name: The name of the field this validator is applied to, if any (deprecated) ref: optional unique identifier of the schema, used to reference the schema in other places json_schema_input_schema: The core schema to be used to generate the corresponding JSON Schema input type metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
Referenced by pydantic_core.core_schema.field_plain_validator_function, pydantic_core.core_schema.general_plain_validator_function.
WithDefaultSchema pydantic_core.core_schema.with_default_schema(CoreSchema schema, *, Any default=PydanticUndefined, Union[Callable[[], Any], Callable[[dict[str, Any]], Any], None] default_factory=None, bool|None default_factory_takes_data=None, Literal['raise', 'omit', 'default']|None on_error=None, bool|None validate_default=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that adds a default value to the given schema, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.with_default_schema(core_schema.str_schema(), default='hello') wrapper_schema = core_schema.typed_dict_schema( {'a': core_schema.typed_dict_field(schema)} ) v = SchemaValidator(wrapper_schema) assert v.validate_python({}) == v.validate_python({'a': 'hello'}) ``` Args: schema: The schema to add a default value to default: The default value to use default_factory: A callable that returns the default value to use default_factory_takes_data: Whether the default factory takes a validated data argument on_error: What to do if the schema validation fails. One of 'raise', 'omit', 'default' validate_default: Whether the default value should be validated strict: Whether the underlying schema should be validated with strict mode ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
NullableSchema pydantic_core.core_schema.nullable_schema(CoreSchema schema, *, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a nullable value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.nullable_schema(core_schema.str_schema()) v = SchemaValidator(schema) assert v.validate_python(None) is None ``` Args: schema: The schema to wrap strict: Whether the underlying schema should be validated with strict mode ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
UnionSchema pydantic_core.core_schema.union_schema(list[CoreSchema|tuple[CoreSchema, str]] choices, *, bool|None auto_collapse=None, str|None custom_error_type=None, str|None custom_error_message=None, dict[str, str|int]|None custom_error_context=None, Literal['smart', 'left_to_right']|None mode=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a union value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.union_schema([core_schema.str_schema(), core_schema.int_schema()]) v = SchemaValidator(schema) assert v.validate_python('hello') == 'hello' assert v.validate_python(1) == 1 ``` Args: choices: The schemas to match. If a tuple, the second item is used as the label for the case. auto_collapse: whether to automatically collapse unions with one element to the inner validator, default true custom_error_type: The custom error type to use if the validation fails custom_error_message: The custom error message to use if the validation fails custom_error_context: The custom error context to use if the validation fails mode: How to select which choice to return * `smart` (default) will try to return the choice which is the closest match to the input value * `left_to_right` will return the first choice in `choices` which succeeds validation ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
TaggedUnionSchema pydantic_core.core_schema.tagged_union_schema(dict[Any, CoreSchema] choices, str|list[str|int]|list[list[str|int]]|Callable[[Any], Any] discriminator, *, str|None custom_error_type=None, str|None custom_error_message=None, dict[str, int|str|float]|None custom_error_context=None, bool|None strict=None, bool|None from_attributes=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a tagged union value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema apple_schema = core_schema.typed_dict_schema( { 'foo': core_schema.typed_dict_field(core_schema.str_schema()), 'bar': core_schema.typed_dict_field(core_schema.int_schema()), } ) banana_schema = core_schema.typed_dict_schema( { 'foo': core_schema.typed_dict_field(core_schema.str_schema()), 'spam': core_schema.typed_dict_field( core_schema.list_schema(items_schema=core_schema.int_schema()) ), } ) schema = core_schema.tagged_union_schema( choices={ 'apple': apple_schema, 'banana': banana_schema, }, discriminator='foo', ) v = SchemaValidator(schema) assert v.validate_python({'foo': 'apple', 'bar': '123'}) == {'foo': 'apple', 'bar': 123} assert v.validate_python({'foo': 'banana', 'spam': [1, 2, 3]}) == { 'foo': 'banana', 'spam': [1, 2, 3], } ``` Args: choices: The schemas to match When retrieving a schema from `choices` using the discriminator value, if the value is a str, it should be fed back into the `choices` map until a schema is obtained (This approach is to prevent multiple ownership of a single schema in Rust) discriminator: The discriminator to use to determine the schema to use * If `discriminator` is a str, it is the name of the attribute to use as the discriminator * If `discriminator` is a list of int/str, it should be used as a "path" to access the discriminator * If `discriminator` is a list of lists, each inner list is a path, and the first path that exists is used * If `discriminator` is a callable, it should return the discriminator when called on the value to validate; the callable can return `None` to indicate that there is no matching discriminator present on the input custom_error_type: The custom error type to use if the validation fails custom_error_message: The custom error message to use if the validation fails custom_error_context: The custom error context to use if the validation fails strict: Whether the underlying schemas should be validated with strict mode from_attributes: Whether to use the attributes of the object to retrieve the discriminator value ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
ChainSchema pydantic_core.core_schema.chain_schema(list[CoreSchema] steps, *, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that chains the provided validation schemas, e.g.: ```py from pydantic_core import SchemaValidator, core_schema def fn(v: str, info: core_schema.ValidationInfo) -> str: assert 'hello' in v return v + ' world' fn_schema = core_schema.with_info_plain_validator_function(function=fn) schema = core_schema.chain_schema( [fn_schema, fn_schema, fn_schema, core_schema.str_schema()] ) v = SchemaValidator(schema) assert v.validate_python('hello') == 'hello world world world' ``` Args: steps: The schemas to chain ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
LaxOrStrictSchema pydantic_core.core_schema.lax_or_strict_schema(CoreSchema lax_schema, CoreSchema strict_schema, *, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that uses the lax or strict schema, e.g.: ```py from pydantic_core import SchemaValidator, core_schema def fn(v: str, info: core_schema.ValidationInfo) -> str: assert 'hello' in v return v + ' world' lax_schema = core_schema.int_schema(strict=False) strict_schema = core_schema.int_schema(strict=True) schema = core_schema.lax_or_strict_schema( lax_schema=lax_schema, strict_schema=strict_schema, strict=True ) v = SchemaValidator(schema) assert v.validate_python(123) == 123 schema = core_schema.lax_or_strict_schema( lax_schema=lax_schema, strict_schema=strict_schema, strict=False ) v = SchemaValidator(schema) assert v.validate_python('123') == 123 ``` Args: lax_schema: The lax schema to use strict_schema: The strict schema to use strict: Whether the strict schema should be used ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
JsonOrPythonSchema pydantic_core.core_schema.json_or_python_schema(CoreSchema json_schema, CoreSchema python_schema, *, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that uses the Json or Python schema depending on the input: ```py from pydantic_core import SchemaValidator, ValidationError, core_schema v = SchemaValidator( core_schema.json_or_python_schema( json_schema=core_schema.int_schema(), python_schema=core_schema.int_schema(strict=True), ) ) assert v.validate_json('"123"') == 123 try: v.validate_python('123') except ValidationError: pass else: raise AssertionError('Validation should have failed') ``` Args: json_schema: The schema to use for Json inputs python_schema: The schema to use for Python inputs ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
TypedDictField pydantic_core.core_schema.typed_dict_field(CoreSchema schema, *, bool|None required=None, str|list[str|int]|list[list[str|int]]|None validation_alias=None, str|None serialization_alias=None, bool|None serialization_exclude=None, dict[str, Any]|None metadata=None, Callable[[Any], bool]|None serialization_exclude_if=None)
Returns a schema that matches a typed dict field, e.g.: ```py from pydantic_core import core_schema field = core_schema.typed_dict_field(schema=core_schema.int_schema(), required=True) ``` Args: schema: The schema to use for the field required: Whether the field is required, otherwise uses the value from `total` on the typed dict validation_alias: The alias(es) to use to find the field in the validation data serialization_alias: The alias to use as a key when serializing serialization_exclude: Whether to exclude the field when serializing serialization_exclude_if: A callable that determines whether to exclude the field when serializing based on its value. metadata: Any other information you want to include with the schema, not used by pydantic-core
References pydantic_core.core_schema._dict_not_none.
TypedDictSchema pydantic_core.core_schema.typed_dict_schema(dict[str, TypedDictField] fields, *, type[Any]|None cls=None, str|None cls_name=None, list[ComputedField]|None computed_fields=None, bool|None strict=None, CoreSchema|None extras_schema=None, ExtraBehavior|None extra_behavior=None, bool|None total=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None, CoreConfig|None config=None)
Returns a schema that matches a typed dict, e.g.: ```py from typing_extensions import TypedDict from pydantic_core import SchemaValidator, core_schema class MyTypedDict(TypedDict): a: str wrapper_schema = core_schema.typed_dict_schema( {'a': core_schema.typed_dict_field(core_schema.str_schema())}, cls=MyTypedDict ) v = SchemaValidator(wrapper_schema) assert v.validate_python({'a': 'hello'}) == {'a': 'hello'} ``` Args: fields: The fields to use for the typed dict cls: The class to use for the typed dict cls_name: The name to use in error locations. Falls back to `cls.__name__`, or the validator name if no class is provided. computed_fields: Computed fields to use when serializing the model, only applies when directly inside a model strict: Whether the typed dict is strict extras_schema: The extra validator to use for the typed dict ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core extra_behavior: The extra behavior to use for the typed dict total: Whether the typed dict is total, otherwise uses `typed_dict_total` from config serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
ModelField pydantic_core.core_schema.model_field(CoreSchema schema, *, str|list[str|int]|list[list[str|int]]|None validation_alias=None, str|None serialization_alias=None, bool|None serialization_exclude=None, Callable[[Any], bool]|None serialization_exclude_if=None, bool|None frozen=None, dict[str, Any]|None metadata=None)
Returns a schema for a model field, e.g.: ```py from pydantic_core import core_schema field = core_schema.model_field(schema=core_schema.int_schema()) ``` Args: schema: The schema to use for the field validation_alias: The alias(es) to use to find the field in the validation data serialization_alias: The alias to use as a key when serializing serialization_exclude: Whether to exclude the field when serializing serialization_exclude_if: A Callable that determines whether to exclude a field during serialization based on its value. frozen: Whether the field is frozen metadata: Any other information you want to include with the schema, not used by pydantic-core
References pydantic_core.core_schema._dict_not_none.
ModelFieldsSchema pydantic_core.core_schema.model_fields_schema(dict[str, ModelField] fields, *, str|None model_name=None, list[ComputedField]|None computed_fields=None, bool|None strict=None, CoreSchema|None extras_schema=None, CoreSchema|None extras_keys_schema=None, ExtraBehavior|None extra_behavior=None, bool|None from_attributes=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches the fields of a Pydantic model, e.g.: ```py from pydantic_core import SchemaValidator, core_schema wrapper_schema = core_schema.model_fields_schema( {'a': core_schema.model_field(core_schema.str_schema())} ) v = SchemaValidator(wrapper_schema) print(v.validate_python({'a': 'hello'})) #> ({'a': 'hello'}, None, {'a'}) ``` Args: fields: The fields of the model model_name: The name of the model, used for error messages, defaults to "Model" computed_fields: Computed fields to use when serializing the model, only applies when directly inside a model strict: Whether the model is strict extras_schema: The schema to use when validating extra input data extras_keys_schema: The schema to use when validating the keys of extra input data ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core extra_behavior: The extra behavior to use for the model fields from_attributes: Whether the model fields should be populated from attributes serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
ModelSchema pydantic_core.core_schema.model_schema(type[Any] cls, CoreSchema schema, *, type[Any]|None generic_origin=None, bool|None custom_init=None, bool|None root_model=None, str|None post_init=None, Literal['always', 'never', 'subclass-instances']|None revalidate_instances=None, bool|None strict=None, bool|None frozen=None, ExtraBehavior|None extra_behavior=None, CoreConfig|None config=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
A model schema generally contains a typed-dict schema. It will run the typed dict validator, then create a new class and set the dict and fields set returned from the typed dict validator to `__dict__` and `__pydantic_fields_set__` respectively. Example: ```py from pydantic_core import CoreConfig, SchemaValidator, core_schema class MyModel: __slots__ = ( '__dict__', '__pydantic_fields_set__', '__pydantic_extra__', '__pydantic_private__', ) schema = core_schema.model_schema( cls=MyModel, config=CoreConfig(str_max_length=5), schema=core_schema.model_fields_schema( fields={'a': core_schema.model_field(core_schema.str_schema())}, ), ) v = SchemaValidator(schema) assert v.isinstance_python({'a': 'hello'}) is True assert v.isinstance_python({'a': 'too long'}) is False ``` Args: cls: The class to use for the model schema: The schema to use for the model generic_origin: The origin type used for this model, if it's a parametrized generic. Ex, if this model schema represents `SomeModel[int]`, generic_origin is `SomeModel` custom_init: Whether the model has a custom init method root_model: Whether the model is a `RootModel` post_init: The call after init to use for the model revalidate_instances: whether instances of models and dataclasses (including subclass instances) should re-validate defaults to config.revalidate_instances, else 'never' strict: Whether the model is strict frozen: Whether the model is frozen extra_behavior: The extra behavior to use for the model, used in serialization config: The config to use for the model ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
DataclassField pydantic_core.core_schema.dataclass_field(str name, CoreSchema schema, *, bool|None kw_only=None, bool|None init=None, bool|None init_only=None, str|list[str|int]|list[list[str|int]]|None validation_alias=None, str|None serialization_alias=None, bool|None serialization_exclude=None, dict[str, Any]|None metadata=None, Callable[[Any], bool]|None serialization_exclude_if=None, bool|None frozen=None)
Returns a schema for a dataclass field, e.g.: ```py from pydantic_core import SchemaValidator, core_schema field = core_schema.dataclass_field( name='a', schema=core_schema.str_schema(), kw_only=False ) schema = core_schema.dataclass_args_schema('Foobar', [field]) v = SchemaValidator(schema) assert v.validate_python({'a': 'hello'}) == ({'a': 'hello'}, None) ``` Args: name: The name to use for the argument parameter schema: The schema to use for the argument parameter kw_only: Whether the field can be set with a positional argument as well as a keyword argument init: Whether the field should be validated during initialization init_only: Whether the field should be omitted from `__dict__` and passed to `__post_init__` validation_alias: The alias(es) to use to find the field in the validation data serialization_alias: The alias to use as a key when serializing serialization_exclude: Whether to exclude the field when serializing serialization_exclude_if: A callable that determines whether to exclude the field when serializing based on its value. metadata: Any other information you want to include with the schema, not used by pydantic-core frozen: Whether the field is frozen
References pydantic_core.core_schema._dict_not_none.
DataclassArgsSchema pydantic_core.core_schema.dataclass_args_schema(str dataclass_name, list[DataclassField] fields, *, list[ComputedField]|None computed_fields=None, bool|None collect_init_only=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None, ExtraBehavior|None extra_behavior=None)
Returns a schema for validating dataclass arguments, e.g.: ```py from pydantic_core import SchemaValidator, core_schema field_a = core_schema.dataclass_field( name='a', schema=core_schema.str_schema(), kw_only=False ) field_b = core_schema.dataclass_field( name='b', schema=core_schema.bool_schema(), kw_only=False ) schema = core_schema.dataclass_args_schema('Foobar', [field_a, field_b]) v = SchemaValidator(schema) assert v.validate_python({'a': 'hello', 'b': True}) == ({'a': 'hello', 'b': True}, None) ``` Args: dataclass_name: The name of the dataclass being validated fields: The fields to use for the dataclass computed_fields: Computed fields to use when serializing the dataclass collect_init_only: Whether to collect init only fields into a dict to pass to `__post_init__` ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema extra_behavior: How to handle extra fields
References pydantic_core.core_schema._dict_not_none.
DataclassSchema pydantic_core.core_schema.dataclass_schema(type[Any] cls, CoreSchema schema, list[str] fields, *, type[Any]|None generic_origin=None, str|None cls_name=None, bool|None post_init=None, Literal['always', 'never', 'subclass-instances']|None revalidate_instances=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None, bool|None frozen=None, bool|None slots=None, CoreConfig|None config=None)
Returns a schema for a dataclass. As with `ModelSchema`, this schema can only be used as a field within another schema, not as the root type. Args: cls: The dataclass type, used to perform subclass checks schema: The schema to use for the dataclass fields fields: Fields of the dataclass, this is used in serialization and in validation during re-validation and while validating assignment generic_origin: The origin type used for this dataclass, if it's a parametrized generic. Ex, if this model schema represents `SomeDataclass[int]`, generic_origin is `SomeDataclass` cls_name: The name to use in error locs, etc; this is useful for generics (default: `cls.__name__`) post_init: Whether to call `__post_init__` after validation revalidate_instances: whether instances of models and dataclasses (including subclass instances) should re-validate defaults to config.revalidate_instances, else 'never' strict: Whether to require an exact instance of `cls` ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema frozen: Whether the dataclass is frozen slots: Whether `slots=True` on the dataclass, means each field is assigned independently, rather than simply setting `__dict__`, default false
References pydantic_core.core_schema._dict_not_none.
ArgumentsParameter pydantic_core.core_schema.arguments_parameter(str name, CoreSchema schema, *, Literal['positional_only', 'positional_or_keyword', 'keyword_only']|None mode=None, str|list[str|int]|list[list[str|int]]|None alias=None)
Returns a schema that matches an argument parameter, e.g.: ```py from pydantic_core import SchemaValidator, core_schema param = core_schema.arguments_parameter( name='a', schema=core_schema.str_schema(), mode='positional_only' ) schema = core_schema.arguments_schema([param]) v = SchemaValidator(schema) assert v.validate_python(('hello',)) == (('hello',), {}) ``` Args: name: The name to use for the argument parameter schema: The schema to use for the argument parameter mode: The mode to use for the argument parameter alias: The alias to use for the argument parameter
References pydantic_core.core_schema._dict_not_none.
ArgumentsSchema pydantic_core.core_schema.arguments_schema(list[ArgumentsParameter] arguments, *, bool|None validate_by_name=None, bool|None validate_by_alias=None, CoreSchema|None var_args_schema=None, VarKwargsMode|None var_kwargs_mode=None, CoreSchema|None var_kwargs_schema=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches an arguments schema, e.g.: ```py from pydantic_core import SchemaValidator, core_schema param_a = core_schema.arguments_parameter( name='a', schema=core_schema.str_schema(), mode='positional_only' ) param_b = core_schema.arguments_parameter( name='b', schema=core_schema.bool_schema(), mode='positional_only' ) schema = core_schema.arguments_schema([param_a, param_b]) v = SchemaValidator(schema) assert v.validate_python(('hello', True)) == (('hello', True), {}) ``` Args: arguments: The arguments to use for the arguments schema validate_by_name: Whether to populate by the parameter names, defaults to `False`. validate_by_alias: Whether to populate by the parameter aliases, defaults to `True`. var_args_schema: The variable args schema to use for the arguments schema var_kwargs_mode: The validation mode to use for variadic keyword arguments. If `'uniform'`, every value of the keyword arguments will be validated against the `var_kwargs_schema` schema. If `'unpacked-typed-dict'`, the `var_kwargs_schema` argument must be a [`typed_dict_schema`][pydantic_core.core_schema.typed_dict_schema] var_kwargs_schema: The variable kwargs schema to use for the arguments schema ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
ArgumentsV3Parameter pydantic_core.core_schema.arguments_v3_parameter(str name, CoreSchema schema, *, Literal['positional_only', 'positional_or_keyword', 'keyword_only', 'var_args', 'var_kwargs_uniform', 'var_kwargs_unpacked_typed_dict',]|None mode=None, str|list[str|int]|list[list[str|int]]|None alias=None)
Returns a schema that matches an argument parameter, e.g.: ```py from pydantic_core import SchemaValidator, core_schema param = core_schema.arguments_v3_parameter( name='a', schema=core_schema.str_schema(), mode='positional_only' ) schema = core_schema.arguments_v3_schema([param]) v = SchemaValidator(schema) assert v.validate_python({'a': 'hello'}) == (('hello',), {}) ``` Args: name: The name to use for the argument parameter schema: The schema to use for the argument parameter mode: The mode to use for the argument parameter alias: The alias to use for the argument parameter
References pydantic_core.core_schema._dict_not_none.
ArgumentsV3Schema pydantic_core.core_schema.arguments_v3_schema(list[ArgumentsV3Parameter] arguments, *, bool|None validate_by_name=None, bool|None validate_by_alias=None, Literal['forbid', 'ignore']|None extra_behavior=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches an arguments schema, e.g.: ```py from pydantic_core import SchemaValidator, core_schema param_a = core_schema.arguments_v3_parameter( name='a', schema=core_schema.str_schema(), mode='positional_only' ) param_b = core_schema.arguments_v3_parameter( name='kwargs', schema=core_schema.bool_schema(), mode='var_kwargs_uniform' ) schema = core_schema.arguments_v3_schema([param_a, param_b]) v = SchemaValidator(schema) assert v.validate_python({'a': 'hi', 'kwargs': {'b': True}}) == (('hi',), {'b': True}) ``` This schema is currently not used by other Pydantic components. In V3, it will most likely become the default arguments schema for the `'call'` schema. Args: arguments: The arguments to use for the arguments schema. validate_by_name: Whether to populate by the parameter names, defaults to `False`. validate_by_alias: Whether to populate by the parameter aliases, defaults to `True`. extra_behavior: The extra behavior to use. ref: optional unique identifier of the schema, used to reference the schema in other places. metadata: Any other information you want to include with the schema, not used by pydantic-core. serialization: Custom serialization schema.
References pydantic_core.core_schema._dict_not_none.
CallSchema pydantic_core.core_schema.call_schema(CoreSchema arguments, Callable[..., Any] function, *, str|None function_name=None, CoreSchema|None return_schema=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches an arguments schema, then calls a function, e.g.: ```py from pydantic_core import SchemaValidator, core_schema param_a = core_schema.arguments_parameter( name='a', schema=core_schema.str_schema(), mode='positional_only' ) param_b = core_schema.arguments_parameter( name='b', schema=core_schema.bool_schema(), mode='positional_only' ) args_schema = core_schema.arguments_schema([param_a, param_b]) schema = core_schema.call_schema( arguments=args_schema, function=lambda a, b: a + str(not b), return_schema=core_schema.str_schema(), ) v = SchemaValidator(schema) assert v.validate_python((('hello', True))) == 'helloFalse' ``` Args: arguments: The arguments to use for the arguments schema function: The function to use for the call schema function_name: The function name to use for the call schema, if not provided `function.__name__` is used return_schema: The return schema to use for the call schema ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
CustomErrorSchema pydantic_core.core_schema.custom_error_schema(CoreSchema schema, str custom_error_type, *, str|None custom_error_message=None, dict[str, Any]|None custom_error_context=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a custom error value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.custom_error_schema( schema=core_schema.int_schema(), custom_error_type='MyError', custom_error_message='Error msg', ) v = SchemaValidator(schema) v.validate_python(1) ``` Args: schema: The schema to use for the custom error schema custom_error_type: The custom error type to use for the custom error schema custom_error_message: The custom error message to use for the custom error schema custom_error_context: The custom error context to use for the custom error schema ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
JsonSchema pydantic_core.core_schema.json_schema(CoreSchema|None schema=None, *, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a JSON value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema dict_schema = core_schema.model_fields_schema( { 'field_a': core_schema.model_field(core_schema.str_schema()), 'field_b': core_schema.model_field(core_schema.bool_schema()), }, ) class MyModel: __slots__ = ( '__dict__', '__pydantic_fields_set__', '__pydantic_extra__', '__pydantic_private__', ) field_a: str field_b: bool json_schema = core_schema.json_schema(schema=dict_schema) schema = core_schema.model_schema(cls=MyModel, schema=json_schema) v = SchemaValidator(schema) m = v.validate_python('{"field_a": "hello", "field_b": true}') assert isinstance(m, MyModel) ``` Args: schema: The schema to use for the JSON schema ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
UrlSchema pydantic_core.core_schema.url_schema(*, int|None max_length=None, list[str]|None allowed_schemes=None, bool|None host_required=None, str|None default_host=None, int|None default_port=None, str|None default_path=None, bool|None preserve_empty_path=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a URL value, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.url_schema() v = SchemaValidator(schema) print(v.validate_python('https://example.com')) #> https://example.com/ ``` Args: max_length: The maximum length of the URL allowed_schemes: The allowed URL schemes host_required: Whether the URL must have a host default_host: The default host to use if the URL does not have a host default_port: The default port to use if the URL does not have a port default_path: The default path to use if the URL does not have a path preserve_empty_path: Whether to preserve an empty path or convert it to '/', default False strict: Whether to use strict URL parsing ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
MultiHostUrlSchema pydantic_core.core_schema.multi_host_url_schema(*, int|None max_length=None, list[str]|None allowed_schemes=None, bool|None host_required=None, str|None default_host=None, int|None default_port=None, str|None default_path=None, bool|None preserve_empty_path=None, bool|None strict=None, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that matches a URL value with possibly multiple hosts, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.multi_host_url_schema() v = SchemaValidator(schema) print(v.validate_python('redis://localhost,0.0.0.0,127.0.0.1')) #> redis://localhost,0.0.0.0,127.0.0.1 ``` Args: max_length: The maximum length of the URL allowed_schemes: The allowed URL schemes host_required: Whether the URL must have a host default_host: The default host to use if the URL does not have a host default_port: The default port to use if the URL does not have a port default_path: The default path to use if the URL does not have a path preserve_empty_path: Whether to preserve an empty path or convert it to '/', default False strict: Whether to use strict URL parsing ref: optional unique identifier of the schema, used to reference the schema in other places metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
DefinitionsSchema pydantic_core.core_schema.definitions_schema(CoreSchema schema, list[CoreSchema] definitions)
Build a schema that contains both an inner schema and a list of definitions which can be used within the inner schema. ```py from pydantic_core import SchemaValidator, core_schema schema = core_schema.definitions_schema( core_schema.list_schema(core_schema.definition_reference_schema('foobar')), [core_schema.int_schema(ref='foobar')], ) v = SchemaValidator(schema) assert v.validate_python([1, 2, '3']) == [1, 2, 3] ``` Args: schema: The inner schema definitions: List of definitions which can be referenced within inner schema
DefinitionReferenceSchema pydantic_core.core_schema.definition_reference_schema(str schema_ref, str|None ref=None, dict[str, Any]|None metadata=None, SerSchema|None serialization=None)
Returns a schema that points to a schema stored in "definitions", this is useful for nested recursive models and also when you want to define validators separately from the main schema, e.g.: ```py from pydantic_core import SchemaValidator, core_schema schema_definition = core_schema.definition_reference_schema('list-schema') schema = core_schema.definitions_schema( schema=schema_definition, definitions=[ core_schema.list_schema(items_schema=schema_definition, ref='list-schema'), ], ) v = SchemaValidator(schema) assert v.validate_python([()]) == [[]] ``` Args: schema_ref: The schema ref to use for the definition reference schema metadata: Any other information you want to include with the schema, not used by pydantic-core serialization: Custom serialization schema
References pydantic_core.core_schema._dict_not_none.
Any pydantic_core.core_schema._dict_not_none(**Any kwargs)
Referenced by pydantic_core.core_schema.any_schema, pydantic_core.core_schema.arguments_parameter, pydantic_core.core_schema.arguments_schema, pydantic_core.core_schema.arguments_v3_parameter, pydantic_core.core_schema.arguments_v3_schema, pydantic_core.core_schema.bool_schema, pydantic_core.core_schema.bytes_schema, pydantic_core.core_schema.call_schema, pydantic_core.core_schema.callable_schema, pydantic_core.core_schema.chain_schema, pydantic_core.core_schema.complex_schema, pydantic_core.core_schema.computed_field, pydantic_core.core_schema.custom_error_schema, pydantic_core.core_schema.dataclass_args_schema, pydantic_core.core_schema.dataclass_field, pydantic_core.core_schema.dataclass_schema, pydantic_core.core_schema.date_schema, pydantic_core.core_schema.datetime_schema, pydantic_core.core_schema.decimal_schema, pydantic_core.core_schema.definition_reference_schema, pydantic_core.core_schema.dict_schema, pydantic_core.core_schema.enum_schema, pydantic_core.core_schema.filter_dict_schema, pydantic_core.core_schema.filter_seq_schema, pydantic_core.core_schema.float_schema, pydantic_core.core_schema.format_ser_schema, pydantic_core.core_schema.frozenset_schema, pydantic_core.core_schema.generator_schema, pydantic_core.core_schema.int_schema, pydantic_core.core_schema.invalid_schema, pydantic_core.core_schema.is_instance_schema, pydantic_core.core_schema.is_subclass_schema, pydantic_core.core_schema.json_or_python_schema, pydantic_core.core_schema.json_schema, pydantic_core.core_schema.lax_or_strict_schema, pydantic_core.core_schema.list_schema, pydantic_core.core_schema.literal_schema, pydantic_core.core_schema.missing_sentinel_schema, pydantic_core.core_schema.model_field, pydantic_core.core_schema.model_fields_schema, pydantic_core.core_schema.model_schema, pydantic_core.core_schema.multi_host_url_schema, pydantic_core.core_schema.no_info_after_validator_function, pydantic_core.core_schema.no_info_before_validator_function, pydantic_core.core_schema.no_info_plain_validator_function, pydantic_core.core_schema.no_info_wrap_validator_function, pydantic_core.core_schema.none_schema, pydantic_core.core_schema.nullable_schema, pydantic_core.core_schema.plain_serializer_function_ser_schema, pydantic_core.core_schema.set_schema, pydantic_core.core_schema.str_schema, pydantic_core.core_schema.tagged_union_schema, pydantic_core.core_schema.time_schema, pydantic_core.core_schema.timedelta_schema, pydantic_core.core_schema.tuple_schema, pydantic_core.core_schema.typed_dict_field, pydantic_core.core_schema.typed_dict_schema, pydantic_core.core_schema.union_schema, pydantic_core.core_schema.url_schema, pydantic_core.core_schema.uuid_schema, pydantic_core.core_schema.with_default_schema, pydantic_core.core_schema.with_info_after_validator_function, pydantic_core.core_schema.with_info_before_validator_function, pydantic_core.core_schema.with_info_plain_validator_function, pydantic_core.core_schema.with_info_wrap_validator_function, pydantic_core.core_schema.wrap_serializer_function_ser_schema.
pydantic_core.core_schema.field_before_validator_function(WithInfoValidatorFunction function, str field_name, CoreSchema schema, **kwargs)
All this stuff is deprecated by #980 and will be removed eventually They're kept because some code external code will be using them.
References pydantic_core.core_schema.with_info_before_validator_function.
pydantic_core.core_schema.general_before_validator_function(*args, **kwargs)
References pydantic_core.core_schema.with_info_before_validator_function.
pydantic_core.core_schema.field_after_validator_function(WithInfoValidatorFunction function, str field_name, CoreSchema schema, **kwargs)
References pydantic_core.core_schema.with_info_after_validator_function.
pydantic_core.core_schema.general_after_validator_function(*args, **kwargs)
References pydantic_core.core_schema.with_info_after_validator_function.
pydantic_core.core_schema.field_wrap_validator_function(WithInfoWrapValidatorFunction function, str field_name, CoreSchema schema, **kwargs)
References pydantic_core.core_schema.with_info_wrap_validator_function.
pydantic_core.core_schema.general_wrap_validator_function(*args, **kwargs)
References pydantic_core.core_schema.with_info_wrap_validator_function.
pydantic_core.core_schema.field_plain_validator_function(WithInfoValidatorFunction function, str field_name, **kwargs)
References pydantic_core.core_schema.with_info_plain_validator_function.
pydantic_core.core_schema.general_plain_validator_function(*args, **kwargs)
References pydantic_core.core_schema.with_info_plain_validator_function.