pydantic::_internal::_model_construction
pydantic::_internal::_model_construction.PydanticModelField
pydantic::_internal::_model_construction.PydanticModelPrivateAttr
pydantic::_internal::_model_construction.object_setattr
Referenced by pydantic._internal._model_construction.init_private_attributes.
pydantic::_internal::_model_construction._T
Any pydantic._internal._model_construction.NoInitField(*, Literal[False] init=False)
Only for typing purposes. Used as default value of `__pydantic_fields_set__`, `__pydantic_extra__`, `__pydantic_private__`, so they could be ignored when synthesizing the `__init__` signature.
None pydantic._internal._model_construction.init_private_attributes(BaseModel self, Any context)
This function is meant to behave like a BaseModel method to initialise private attributes. It takes context as an argument since that's what pydantic-core passes when calling it. Args: self: The BaseModel instance. context: The context.
References pydantic._internal._model_construction.object_setattr.
Callable[..., Any] | None pydantic._internal._model_construction.get_model_post_init(dict[str, Any] namespace, tuple[type[Any],...] bases)
Get the `model_post_init` method from the namespace or the class bases, or `None` if not defined.
dict[str, ModelPrivateAttr] pydantic._internal._model_construction.inspect_namespace(dict[str, Any] namespace, dict[str, Any] raw_annotations, tuple[type[Any],...] ignored_types, set[str] base_class_vars, set[str] base_class_fields)
Iterate over the namespace and: * gather private attributes * check for items which look like fields but are not (e.g. have no annotation) and warn. Args: namespace: The attribute dictionary of the class to be created. raw_annotations: The (non-evaluated) annotations of the model. ignored_types: A tuple of ignore types. base_class_vars: A set of base class class variables. base_class_fields: A set of base class fields. Returns: A dict contains private attributes info. Raises: TypeError: If there is a `__root__` field in model. NameError: If private attribute name is invalid. PydanticUserError: - If a field does not have a type annotation. - If a field on base class was overridden by a non-annotated attribute.
References pydantic._internal._model_construction.default_ignored_types.
None pydantic._internal._model_construction.set_default_hash_func(type[BaseModel] cls, tuple[type[Any],...] bases)
References pydantic._internal._model_construction.make_hash_func.
Any pydantic._internal._model_construction.make_hash_func(type[BaseModel] cls)
Referenced by pydantic._internal._model_construction.set_default_hash_func.
None pydantic._internal._model_construction.set_model_fields(type[BaseModel] cls, ConfigWrapper config_wrapper, NsResolver|None ns_resolver)
Collect and set `cls.__pydantic_fields__` and `cls.__class_vars__`. Args: cls: BaseModel or dataclass. config_wrapper: The config wrapper instance. ns_resolver: Namespace resolver to use when getting model annotations.
bool pydantic._internal._model_construction.complete_model_class(type[BaseModel] cls, ConfigWrapper config_wrapper, NsResolver ns_resolver, *, bool raise_errors=True, bool call_on_complete_hook=True, str|None create_model_module=None)
Finish building a model class. This logic must be called after class has been created since validation functions must be bound and `get_type_hints` requires a class object. Args: cls: BaseModel or dataclass. config_wrapper: The config wrapper instance. ns_resolver: The namespace resolver instance to use during schema building. raise_errors: Whether to raise errors. call_on_complete_hook: Whether to call the `__pydantic_on_complete__` hook. create_model_module: The module of the class to be created, if created by `create_model`. Returns: `True` if the model is successfully completed, else `False`. Raises: PydanticUndefinedAnnotation: If `PydanticUndefinedAnnotation` occurs in`__get_pydantic_core_schema__` and `raise_errors=True`.
References pydantic._internal._model_construction.set_deprecated_descriptors.
None pydantic._internal._model_construction.set_deprecated_descriptors(type[BaseModel] cls)
Set data descriptors on the class for deprecated fields.
Referenced by pydantic._internal._model_construction.complete_model_class.
dict[str, Any] | None pydantic._internal._model_construction.build_lenient_weakvaluedict(dict[str, Any]|None d)
Takes an input dictionary, and produces a new value that (invertibly) replaces the values with weakrefs. We can't just use a WeakValueDictionary because many types (including int, str, etc.) can't be stored as values in a WeakValueDictionary. The `unpack_lenient_weakvaluedict` function can be used to reverse this operation.
dict[str, Any] | None pydantic._internal._model_construction.unpack_lenient_weakvaluedict(dict[str, Any]|None d)
Inverts the transform performed by `build_lenient_weakvaluedict`.
tuple[type[Any], ...] pydantic._internal._model_construction.default_ignored_types()
Referenced by pydantic._internal._model_construction.inspect_namespace.