pydantic::_internal::_validators
pydantic::_internal::_validators.PatternType
dict pydantic::_internal::_validators.NUMERIC_VALIDATOR_LOOKUP
pydantic::_internal::_validators.IpType
dict pydantic::_internal::_validators.IP_VALIDATOR_LOOKUP
Sequence[Any] pydantic._internal._validators.sequence_validator(Sequence[Any] input_value, core_schema.ValidatorFunctionWrapHandler validator)
Validator for `Sequence` types, isinstance(v, Sequence) has already been called.
Any pydantic._internal._validators.import_string(Any value)
References pydantic._internal._validators._import_string_logic.
Any pydantic._internal._validators._import_string_logic(str dotted_path)
Inspired by uvicorn — dotted paths should include a colon before the final item if that item is not a module. (This is necessary to distinguish between a submodule and an attribute when there is a conflict.). If the dotted path does not include a colon and the final item is not a valid module, importing as an attribute rather than a submodule will be attempted automatically. So, for example, the following values of `dotted_path` result in the following returned values: * 'collections': <module 'collections'> * 'collections.abc': <module 'collections.abc'> * 'collections.abc:Mapping': <class 'collections.abc.Mapping'> * `collections.abc.Mapping`: <class 'collections.abc.Mapping'> (though this is a bit slower than the previous line) An error will be raised under any of the following scenarios: * `dotted_path` contains more than one colon (e.g., 'collections:abc:Mapping') * the substring of `dotted_path` before the colon is not a valid module in the environment (e.g., '123:Mapping') * the substring of `dotted_path` after the colon is not an attribute of the module (e.g., 'collections:abc123')
References pydantic._internal._validators._import_string_logic.
Referenced by pydantic._internal._validators._import_string_logic, pydantic._internal._validators.import_string.
re.Pattern[Any] pydantic._internal._validators.pattern_either_validator(Any input_value)
References pydantic._internal._validators.compile_pattern.
re.Pattern[str] pydantic._internal._validators.pattern_str_validator(Any input_value)
References pydantic._internal._validators.compile_pattern.
re.Pattern[bytes] pydantic._internal._validators.pattern_bytes_validator(Any input_value)
References pydantic._internal._validators.compile_pattern.
re.Pattern[PatternType] pydantic._internal._validators.compile_pattern(PatternType pattern)
Referenced by pydantic._internal._validators.pattern_bytes_validator, pydantic._internal._validators.pattern_either_validator, pydantic._internal._validators.pattern_str_validator.
IPv4Address pydantic._internal._validators.ip_v4_address_validator(Any input_value)
IPv6Address pydantic._internal._validators.ip_v6_address_validator(Any input_value)
IPv4Network pydantic._internal._validators.ip_v4_network_validator(Any input_value)
Assume IPv4Network initialised with a default `strict` argument. See more: https://docs.python.org/library/ipaddress.html#ipaddress.IPv4Network
IPv6Network pydantic._internal._validators.ip_v6_network_validator(Any input_value)
Assume IPv6Network initialised with a default `strict` argument. See more: https://docs.python.org/library/ipaddress.html#ipaddress.IPv6Network
IPv4Interface pydantic._internal._validators.ip_v4_interface_validator(Any input_value)
IPv6Interface pydantic._internal._validators.ip_v6_interface_validator(Any input_value)
Fraction pydantic._internal._validators.fraction_validator(Any input_value)
Any pydantic._internal._validators.forbid_inf_nan_check(Any x)
int | float | str pydantic._internal._validators._safe_repr(Any v)
The context argument for `PydanticKnownError` requires a number or str type, so we do a simple repr() coercion for types like timedelta. See tests/test_types.py::test_annotated_metadata_any_order for some context.
Referenced by pydantic._internal._validators.greater_than_or_equal_validator, pydantic._internal._validators.greater_than_validator, pydantic._internal._validators.less_than_or_equal_validator, pydantic._internal._validators.less_than_validator, pydantic._internal._validators.multiple_of_validator.
Any pydantic._internal._validators.greater_than_validator(Any x, Any gt)
References pydantic._internal._validators._safe_repr.
Any pydantic._internal._validators.greater_than_or_equal_validator(Any x, Any ge)
References pydantic._internal._validators._safe_repr.
Any pydantic._internal._validators.less_than_validator(Any x, Any lt)
References pydantic._internal._validators._safe_repr.
Any pydantic._internal._validators.less_than_or_equal_validator(Any x, Any le)
References pydantic._internal._validators._safe_repr.
Any pydantic._internal._validators.multiple_of_validator(Any x, Any multiple_of)
References pydantic._internal._validators._safe_repr.
Any pydantic._internal._validators.min_length_validator(Any x, Any min_length)
Any pydantic._internal._validators.max_length_validator(Any x, Any max_length)
tuple[int, int] pydantic._internal._validators._extract_decimal_digits_info(Decimal decimal)
Compute the total number of digits and decimal places for a given [`Decimal`][decimal.Decimal] instance. This function handles both normalized and non-normalized Decimal instances. Example: Decimal('1.230') -> 4 digits, 3 decimal places Args: decimal (Decimal): The decimal number to analyze. Returns: tuple[int, int]: A tuple containing the number of decimal places and total digits. Though this could be divided into two separate functions, the logic is easier to follow if we couple the computation of the number of decimals and digits together.
Referenced by pydantic._internal._validators.decimal_places_validator, pydantic._internal._validators.max_digits_validator.
Any pydantic._internal._validators.max_digits_validator(Any x, Any max_digits)
References pydantic._internal._validators._extract_decimal_digits_info.
Any pydantic._internal._validators.decimal_places_validator(Any x, Any decimal_places)
References pydantic._internal._validators._extract_decimal_digits_info.
collections.deque[Any] pydantic._internal._validators.deque_validator(Any input_value, core_schema.ValidatorFunctionWrapHandler handler)
collections.defaultdict[Any, Any] pydantic._internal._validators.defaultdict_validator(Any input_value, core_schema.ValidatorFunctionWrapHandler handler, Callable[[], Any] default_default_factory)
Callable[[], Any] pydantic._internal._validators.get_defaultdict_default_default_factory(Any values_source_type)
ZoneInfo pydantic._internal._validators.validate_str_is_valid_iana_tz(Any value)