pip::_vendor::idna::core
int pip::_vendor::idna::core::_virama_combining_class
str pip::_vendor::idna::core::_alabel_prefix
pip::_vendor::idna::core._unicode_dots_re
int pip::_vendor::idna::core::_combining_class(int cp)
Referenced by pip._vendor.idna.core.valid_contextj.
bool pip::_vendor::idna::core::_is_script(str cp, str script)
Referenced by pip._vendor.idna.core.valid_contexto.
bytes pip::_vendor::idna::core::_punycode(str s)
Referenced by pip._vendor.idna.core.alabel.
str pip::_vendor::idna::core::_unot(int s)
Referenced by pip._vendor.idna.core.check_label, pip._vendor.idna.core.uts46_remap.
bool pip::_vendor::idna::core::valid_label_length(Union[bytes, str] label)
Referenced by pip._vendor.idna.core.alabel.
bool pip::_vendor::idna::core::valid_string_length(Union[bytes, str] label, bool trailing_dot)
Referenced by pip._vendor.idna.core.encode.
bool pip::_vendor::idna::core::check_bidi(str label, bool check_ltr=False)
Referenced by pip._vendor.idna.core.check_label.
bool pip::_vendor::idna::core::check_initial_combiner(str label)
Referenced by pip._vendor.idna.core.check_label.
bool pip::_vendor::idna::core::check_hyphen_ok(str label)
Referenced by pip._vendor.idna.core.check_label.
None pip::_vendor::idna::core::check_nfc(str label)
Referenced by pip._vendor.idna.core.check_label.
bool pip::_vendor::idna::core::valid_contextj(str label, int pos)
References pip._vendor.idna.core._combining_class.
Referenced by pip._vendor.idna.core.check_label.
bool pip::_vendor::idna::core::valid_contexto(str label, int pos, bool exception=False)
References pip._vendor.idna.core._is_script.
Referenced by pip._vendor.idna.core.check_label.
None pip::_vendor::idna::core::check_label(Union[str, bytes, bytearray] label)
References pip._vendor.idna.core._unot, pip._vendor.idna.core.check_bidi, pip._vendor.idna.core.check_hyphen_ok, pip._vendor.idna.core.check_initial_combiner, pip._vendor.idna.core.check_nfc, pip._vendor.idna.core.valid_contextj, pip._vendor.idna.core.valid_contexto.
Referenced by pip._vendor.idna.core.alabel, pip._vendor.idna.core.ulabel.
bytes pip::_vendor::idna::core::alabel(str label)
References pip._vendor.idna.core._punycode, pip._vendor.idna.core.check_label, pip._vendor.idna.core.ulabel, pip._vendor.idna.core.valid_label_length.
Referenced by pip._vendor.idna.core.encode.
str pip::_vendor::idna::core::ulabel(Union[str, bytes, bytearray] label)
References pip._vendor.idna.core.check_label.
Referenced by pip._vendor.idna.core.alabel, pip._vendor.idna.core.decode.
str pip::_vendor::idna::core::uts46_remap(str domain, bool std3_rules=True, bool transitional=False)
Re-map the characters in the string according to UTS46 processing.
References pip._vendor.idna.core._unot.
Referenced by pip._vendor.idna.core.decode, pip._vendor.idna.core.encode.
bytes pip::_vendor::idna::core::encode(Union[str, bytes, bytearray] s, bool strict=False, bool uts46=False, bool std3_rules=False, bool transitional=False)
References pip._vendor.idna.core.alabel, pip._vendor.idna.core.uts46_remap, pip._vendor.idna.core.valid_string_length.
Referenced by pip._vendor.idna.compat.ToASCII.
str pip::_vendor::idna::core::decode(Union[str, bytes, bytearray] s, bool strict=False, bool uts46=False, bool std3_rules=False)
References pip._vendor.idna.core.ulabel, pip._vendor.idna.core.uts46_remap.
Referenced by pip._vendor.idna.compat.ToUnicode.