setuptools::_distutils::command::install
bool setuptools::_distutils::command::install.HAS_USER_SITE
dict setuptools::_distutils::command::install.WINDOWS_SCHEME
dict setuptools::_distutils::command::install.INSTALL_SCHEMES
tuple setuptools::_distutils::command::install.SCHEME_KEYS
setuptools._distutils.command.install._load_sysconfig_schemes()
Referenced by setuptools._distutils.command.install._load_schemes.
setuptools._distutils.command.install._load_schemes()
Extend default schemes with schemes from sysconfig.
References setuptools._distutils.command.install._load_sysconfig_schemes.
Referenced by setuptools._distutils.command.install._load_scheme.
setuptools._distutils.command.install._get_implementation()
Referenced by setuptools._distutils.command.install.install.finalize_options.
setuptools._distutils.command.install._select_scheme(ob, name)
References setuptools._distutils.command.install._inject_headers, setuptools._distutils.command.install._load_scheme, setuptools._distutils.command.install._remove_set, setuptools._distutils.command.install._resolve_scheme, setuptools._distutils.command.install._scheme_attrs.
Referenced by setuptools._distutils.command.install.install.select_scheme.
setuptools._distutils.command.install._remove_set(ob, attrs)
Include only attrs that are None in ob.
Referenced by setuptools._distutils.command.install._select_scheme.
setuptools._distutils.command.install._resolve_scheme(name)
References setuptools._distutils.command.install._pypy_hack.
Referenced by setuptools._distutils.command.install._select_scheme.
setuptools._distutils.command.install._load_scheme(name)
References setuptools._distutils.command.install._load_schemes.
Referenced by setuptools._distutils.command.install._inject_headers, setuptools._distutils.command.install._select_scheme.
setuptools._distutils.command.install._inject_headers(name, scheme)
Given a scheme name and the resolved scheme, if the scheme does not include headers, resolve the fallback scheme for the name and use headers from it. pypa/distutils#88
References setuptools._distutils.command.install._load_scheme, setuptools._distutils.command.install._pypy_hack.
Referenced by setuptools._distutils.command.install._select_scheme.
setuptools._distutils.command.install._scheme_attrs(scheme)
Resolve install directories by applying the install schemes.
Referenced by setuptools._distutils.command.install._select_scheme.
setuptools._distutils.command.install._pypy_hack(name)
Referenced by setuptools._distutils.command.install._inject_headers, setuptools._distutils.command.install._resolve_scheme.