h11::_connection
int h11::_connection.DEFAULT_MAX_INCOMPLETE_EVENT_SIZE
bool h11._connection._keep_alive(Union[Request, Response] event)
Referenced by h11._connection.Connection._process_event.
Tuple[str, Union[Tuple[()], Tuple[int]]] h11._connection._body_framing(bytes request_method, Union[Request, Response] event)
Referenced by h11._connection.Connection._clean_up_response_headers_for_sending, h11._connection.Connection._get_io_object.