pip::_internal::commands::show
pip::_internal::commands::show.logger
str pip._internal.commands.show.normalize_project_url_label(str label)
Referenced by pip._internal.commands.show.search_packages_info.
Generator[_PackageInfo, None, None] pip._internal.commands.show.search_packages_info(list[str] query)
Gather details from installed distributions. Print distribution name, version, location, and installed files. Installed files requires a pip generated 'installed-files.txt' in the distributions '.egg-info' directory.
References pip._internal.commands.show.normalize_project_url_label.
Referenced by pip._internal.commands.show.ShowCommand.run, pip._internal.commands.show.ShowCommand.run.
bool pip::_internal::commands::show::print_results(Iterable[_PackageInfo] distributions, bool list_files, bool verbose)
Print the information from installed distributions found.
Referenced by pip._internal.commands.show.ShowCommand.run, pip._internal.commands.show.ShowCommand.run.
Generator[_PackageInfo, None, None] pip._internal.commands.show.search_packages_info(List[str] query)
Gather details from installed distributions. Print distribution name, version, location, and installed files. Installed files requires a pip generated 'installed-files.txt' in the distributions '.egg-info' directory.