pydantic::v1::dataclasses
pydantic::v1::dataclasses.DataclassT
pydantic::v1::dataclasses.DataclassClassOrWrapper
pydantic::v1::dataclasses._T
Callable[[Type[_T]], 'DataclassClassOrWrapper'] pydantic.v1.dataclasses.dataclass(*, bool init=True, bool repr=True, bool eq=True, bool order=False, bool unsafe_hash=False, bool frozen=False, Union[ConfigDict, Type[object], None] config=None, Optional[bool] validate_on_init=None, Optional[bool] use_proxy=None, bool kw_only=...)
Referenced by pydantic.v1.dataclasses.make_dataclass_validator.
'DataclassClassOrWrapper' pydantic.v1.dataclasses.dataclass(Type[_T] _cls, *, bool init=True, bool repr=True, bool eq=True, bool order=False, bool unsafe_hash=False, bool frozen=False, Union[ConfigDict, Type[object], None] config=None, Optional[bool] validate_on_init=None, Optional[bool] use_proxy=None, bool kw_only=...)
Callable[[Type[_T]], 'DataclassClassOrWrapper'] pydantic.v1.dataclasses.dataclass(*, bool init=True, bool repr=True, bool eq=True, bool order=False, bool unsafe_hash=False, bool frozen=False, Union[ConfigDict, Type[object], None] config=None, Optional[bool] validate_on_init=None, Optional[bool] use_proxy=None)
'DataclassClassOrWrapper' pydantic.v1.dataclasses.dataclass(Type[_T] _cls, *, bool init=True, bool repr=True, bool eq=True, bool order=False, bool unsafe_hash=False, bool frozen=False, Union[ConfigDict, Type[object], None] config=None, Optional[bool] validate_on_init=None, Optional[bool] use_proxy=None)
Union[Callable[[Type[_T]], 'DataclassClassOrWrapper'], 'DataclassClassOrWrapper'] pydantic.v1.dataclasses.dataclass(Optional[Type[_T]] _cls=None, *, bool init=True, bool repr=True, bool eq=True, bool order=False, bool unsafe_hash=False, bool frozen=False, Union[ConfigDict, Type[object], None] config=None, Optional[bool] validate_on_init=None, Optional[bool] use_proxy=None, bool kw_only=False)
Like the python standard lib dataclasses but with type validation. The result is either a pydantic dataclass that will validate input data or a wrapper that will trigger validation around a stdlib dataclass to avoid modifying it directly
References pydantic.v1.dataclasses._add_pydantic_validation_attributes, pydantic.v1.dataclasses.is_builtin_dataclass.
Generator[Type['DataclassT'], None, None] pydantic.v1.dataclasses.set_validation(Type['DataclassT'] cls, bool value)
Referenced by pydantic.v1.dataclasses._validate_dataclass.
None pydantic.v1.dataclasses._add_pydantic_validation_attributes(Type['Dataclass'] dc_cls, Type[BaseConfig] config, bool validate_on_init, str dc_cls_doc)
We need to replace the right method. If no `__post_init__` has been set in the stdlib dataclass it won't even exist (code is generated on the fly by `dataclasses`) By default, we run validation after `__init__` or `__post_init__` if defined
References pydantic.v1.dataclasses.create_pydantic_model_from_dataclass.
Referenced by pydantic.v1.dataclasses.dataclass.
'CallableGenerator' pydantic.v1.dataclasses._get_validators('DataclassClassOrWrapper' cls)
Referenced by pydantic.v1.dataclasses.make_dataclass_validator.
'DataclassT' pydantic.v1.dataclasses._validate_dataclass(Type['DataclassT'] cls, Any v)
References pydantic.v1.dataclasses.set_validation.
Type['BaseModel'] pydantic.v1.dataclasses.create_pydantic_model_from_dataclass(Type['Dataclass'] dc_cls, Type[Any] config=BaseConfig, Optional[str] dc_cls_doc=None)
References pydantic.v1.main.create_model.
Referenced by pydantic.v1.dataclasses._add_pydantic_validation_attributes.
bool pydantic::v1::dataclasses::_is_field_cached_property('Dataclass' obj, str k)
Referenced by pydantic.v1.dataclasses._dataclass_validate_values.
None pydantic.v1.dataclasses._dataclass_validate_values('Dataclass' self)
References pydantic.v1.dataclasses._is_field_cached_property, pydantic.v1.main.validate_model.
None pydantic.v1.dataclasses._dataclass_validate_assignment_setattr('Dataclass' self, str name, Any value)
bool pydantic.v1.dataclasses.is_builtin_dataclass(Type[Any] _cls)
Whether a class is a stdlib dataclass (useful to discriminated a pydantic dataclass that is actually a wrapper around a stdlib dataclass) we check that - `_cls` is a dataclass - `_cls` is not a processed pydantic dataclass (with a basemodel attached) - `_cls` is not a pydantic dataclass inheriting directly from a stdlib dataclass e.g. ``` @dataclasses.dataclass class A: x: int @pydantic.dataclasses.dataclass class B(A): y: int ``` In this case, when we first check `B`, we make an extra check and look at the annotations ('y'), which won't be a superset of all the dataclass fields (only the stdlib fields i.e. 'x')
Referenced by pydantic.v1.dataclasses.dataclass.
'CallableGenerator' pydantic.v1.dataclasses.make_dataclass_validator(Type['Dataclass'] dc_cls, Type[BaseConfig] config)
Create a pydantic.dataclass from a builtin dataclass to add type validation and yield the validators It retrieves the parameters of the dataclass and forwards them to the newly created dataclass
References pydantic.v1.dataclasses._get_validators, pydantic.v1.dataclasses.dataclass.