pip::_vendor::pygments::util
pip::_vendor::pygments::util.split_path_re
pip::_vendor::pygments::util.doctype_lookup_re
pip::_vendor::pygments::util.tag_re
pip::_vendor::pygments::util.xml_decl_re
dict pip::_vendor::pygments::util::_looks_like_xml_cache
pip::_vendor::pygments::util::get_choice_opt(options, optname, allowed, default=None, normcase=False)
If the key `optname` from the dictionary is not in the sequence `allowed`, raise an error, otherwise return it.
pip::_vendor::pygments::util::get_bool_opt(options, optname, default=None)
Intuitively, this is `options.get(optname, default)`, but restricted to Boolean value. The Booleans can be represented as string, in order to accept Boolean value from the command line arguments. If the key `optname` is present in the dictionary `options` and is not associated with a Boolean, raise an `OptionError`. If it is absent, `default` is returned instead. The valid string values for ``True`` are ``1``, ``yes``, ``true`` and ``on``, the ones for ``False`` are ``0``, ``no``, ``false`` and ``off`` (matched case-insensitively).
pip::_vendor::pygments::util::get_int_opt(options, optname, default=None)
As :func:`get_bool_opt`, but interpret the value as an integer.
pip::_vendor::pygments::util::get_list_opt(options, optname, default=None)
If the key `optname` from the dictionary `options` is a string, split it at whitespace and return it. If it is already a list or a tuple, it is returned as a list.
pip::_vendor::pygments::util::docstring_headline(obj)
pip::_vendor::pygments::util::make_analysator(f)
Return a static text analyser function that returns float values.
pip::_vendor::pygments::util::shebang_matches(text, regex)
Check if the given regular expression matches the last part of the shebang if one exists. >>> from pygments.util import shebang_matches >>> shebang_matches('#!/usr/bin/env python', r'python(2\.\d)?') True >>> shebang_matches('#!/usr/bin/python2.4', r'python(2\.\d)?') True >>> shebang_matches('#!/usr/bin/python-ruby', r'python(2\.\d)?') False >>> shebang_matches('#!/usr/bin/python/ruby', r'python(2\.\d)?') False >>> shebang_matches('#!/usr/bin/startsomethingwith python', ... r'python(2\.\d)?') True It also checks for common windows executable file extensions:: >>> shebang_matches('#!C:\\Python2.4\\Python.exe', r'python(2\.\d)?') True Parameters (``'-f'`` or ``'--foo'`` are ignored so ``'perl'`` does the same as ``'perl -e'``) Note that this method automatically searches the whole string (eg: the regular expression is wrapped in ``'^$'``)
pip::_vendor::pygments::util::doctype_matches(text, regex)
Check if the doctype matches a regular expression (if present). Note that this method only checks the first part of a DOCTYPE. eg: 'html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"'
Referenced by pip._vendor.pygments.util.html_doctype_matches.
pip::_vendor::pygments::util::html_doctype_matches(text)
Check if the file looks like it has a html doctype.
References pip._vendor.pygments.util.doctype_matches.
pip::_vendor::pygments::util::looks_like_xml(text)
Check if a doctype exists or if we have some tags.
pip::_vendor::pygments::util::surrogatepair(c)
Given a unicode character code with length greater than 16 bits, return the two 16 bit surrogate pair.
pip::_vendor::pygments::util::format_lines(var_name, seq, raw=False, indent_level=0)
Formats a sequence of strings for output.
pip::_vendor::pygments::util::duplicates_removed(it, already_seen=())
Returns a list with duplicates removed from the iterable `it`. Order is preserved.
pip::_vendor::pygments::util::guess_decode(text)
Decode *text* with guessed encoding. First try UTF-8; this should fail for non-UTF-8 encodings. Then try the preferred locale encoding. Fall back to latin-1, which always works.
Referenced by pip._vendor.pygments.util.Future.get, pip._vendor.pygments.util.guess_decode_from_terminal.
pip::_vendor::pygments::util::guess_decode_from_terminal(text, term)
Decode *text* coming from terminal *term*. First try the terminal encoding, if given. Then try UTF-8. Then try the preferred locale encoding. Fall back to latin-1, which always works.
References pip._vendor.pygments.util.guess_decode.
pip::_vendor::pygments::util::terminal_encoding(term)
Return our best guess of encoding for the given *term*.