pip::_vendor::urllib3::util::ssl_match_hostname
pip::_vendor::urllib3::util::ssl_match_hostname.ipaddress
pip::_vendor::urllib3::util::ssl_match_hostname::_dnsname_match(dn, hostname, max_wildcards=1)
Matching according to RFC 6125, section 6.4.3 http://tools.ietf.org/html/rfc6125#section-6.4.3
Referenced by pip._vendor.urllib3.util.ssl_match_hostname.match_hostname.
pip::_vendor::urllib3::util::ssl_match_hostname::_to_unicode(obj)
Referenced by pip._vendor.urllib3.util.ssl_match_hostname._ipaddress_match, pip._vendor.urllib3.util.ssl_match_hostname.match_hostname.
pip::_vendor::urllib3::util::ssl_match_hostname::_ipaddress_match(ipname, host_ip)
Exact matching of IP addresses. RFC 6125 explicitly doesn't define an algorithm for this (section 1.7.2 - "Out of Scope").
References pip._vendor.urllib3.util.ssl_match_hostname._to_unicode.
Referenced by pip._vendor.urllib3.util.ssl_match_hostname.match_hostname.
pip::_vendor::urllib3::util::ssl_match_hostname::match_hostname(cert, hostname)
Verify that *cert* (in decoded format as returned by SSLSocket.getpeercert()) matches the *hostname*. RFC 2818 and RFC 6125 rules are followed, but IP addresses are not accepted for *hostname*. CertificateError is raised on failure. On success, the function returns nothing.
References pip._vendor.urllib3.util.ssl_match_hostname._dnsname_match, pip._vendor.urllib3.util.ssl_match_hostname._ipaddress_match, pip._vendor.urllib3.util.ssl_match_hostname._to_unicode.