pip::_vendor::packaging::version
pip::_vendor::packaging::version.LocalType
pip::_vendor::packaging::version.CmpPrePostDevType
pip::_vendor::packaging::version.CmpLocalType
pip::_vendor::packaging::version.CmpKey
pip::_vendor::packaging::version.VersionComparisonMethod
str pip::_vendor::packaging::version._VERSION_PATTERN
str pip::_vendor::packaging::version::VERSION_PATTERN
pip::_vendor::packaging::version._local_version_separators
pip::_vendor::packaging::version.InfiniteTypes
pip::_vendor::packaging::version.PrePostDevType
pip::_vendor::packaging::version.SubLocalType
pip::_vendor::packaging::version.LegacyCmpKey
pip::_vendor::packaging::version._Version
pip::_vendor::packaging::version._legacy_version_component_re
dict pip::_vendor::packaging::version._legacy_version_replacement_map
Version pip._vendor.packaging.version.parse(str version)
Parse the given version string. >>> parse('1.0.dev1') <Version('1.0.dev1')> :param version: The version string to parse. :raises InvalidVersion: When the version string is not a valid version. Parse the given version string and return either a :class:`Version` object or a :class:`LegacyVersion` object depending on if the given version is a valid PEP 440 version or a legacy version.
tuple[str, int] | None pip._vendor.packaging.version._parse_letter_version(str|None letter, str|bytes|SupportsInt|None number)
Referenced by pip._vendor.packaging.version._legacy_cmpkey.
LocalType | None pip._vendor.packaging.version._parse_local_version(str|None local)
Takes a string like abc.1.twelve and turns it into ("abc", 1, "twelve").
Referenced by pip._vendor.packaging.version._legacy_cmpkey.
CmpKey pip._vendor.packaging.version._cmpkey(int epoch, tuple[int,...] release, tuple[str, int]|None pre, tuple[str, int]|None post, tuple[str, int]|None dev, LocalType|None local)
Referenced by pip._vendor.packaging.version._legacy_cmpkey.
Iterator[str] pip._vendor.packaging.version._parse_version_parts(str s)
Referenced by pip._vendor.packaging.version._legacy_cmpkey.
LegacyCmpKey pip._vendor.packaging.version._legacy_cmpkey(str version)
References pip._vendor.packaging.version._cmpkey, pip._vendor.packaging.version._parse_letter_version, pip._vendor.packaging.version._parse_local_version, pip._vendor.packaging.version._parse_version_parts.
Optional[Tuple[str, int]] pip._vendor.packaging.version._parse_letter_version(str letter, Union[str, bytes, SupportsInt] number)
Optional[LocalType] pip._vendor.packaging.version._parse_local_version(str local)
Takes a string like abc.1.twelve and turns it into ("abc", 1, "twelve").
CmpKey pip._vendor.packaging.version._cmpkey(int epoch, Tuple[int,...] release, Optional[Tuple[str, int]] pre, Optional[Tuple[str, int]] post, Optional[Tuple[str, int]] dev, Optional[Tuple[SubLocalType]] local)