fastapi::dependencies::utils
tuple fastapi::dependencies::utils.multipart_not_installed_error
tuple fastapi::dependencies::utils.multipart_incorrect_install_error
fastapi::dependencies::utils.CacheKey
None fastapi.dependencies.utils.ensure_multipart_is_installed()
Referenced by fastapi.dependencies.utils.analyze_param.
Dependant fastapi.dependencies.utils.get_param_sub_dependant(*, str param_name, params.Depends depends, str path, Optional[List[str]] security_scopes=None)
References fastapi.dependencies.utils.get_sub_dependant.
Referenced by fastapi.dependencies.utils.get_dependant.
Dependant fastapi.dependencies.utils.get_parameterless_sub_dependant(*, params.Depends depends, str path)
References fastapi.dependencies.utils.get_sub_dependant.
Dependant fastapi.dependencies.utils.get_sub_dependant(*, params.Depends depends, Callable[..., Any] dependency, str path, Optional[str] name=None, Optional[List[str]] security_scopes=None)
References fastapi.dependencies.utils.get_dependant.
Referenced by fastapi.dependencies.utils.get_param_sub_dependant, fastapi.dependencies.utils.get_parameterless_sub_dependant.
Dependant fastapi.dependencies.utils.get_flat_dependant(Dependant dependant, *, bool skip_repeats=False, Optional[List[CacheKey]] visited=None)
References fastapi.dependencies.utils.get_flat_dependant.
Referenced by fastapi.dependencies.utils.get_flat_dependant, fastapi.dependencies.utils.get_flat_params.
List[ModelField] fastapi.dependencies.utils._get_flat_fields_from_params(List[ModelField] fields)
Referenced by fastapi.dependencies.utils.get_flat_params.
List[ModelField] fastapi.dependencies.utils.get_flat_params(Dependant dependant)
References fastapi.dependencies.utils._get_flat_fields_from_params, fastapi.dependencies.utils.get_flat_dependant.
inspect.Signature fastapi.dependencies.utils.get_typed_signature(Callable[..., Any] call)
References fastapi.dependencies.utils.get_typed_annotation.
Referenced by fastapi.dependencies.utils.get_dependant.
Any fastapi.dependencies.utils.get_typed_annotation(Any annotation, Dict[str, Any] globalns)
Referenced by fastapi.dependencies.utils.get_typed_return_annotation, fastapi.dependencies.utils.get_typed_signature.
Any fastapi.dependencies.utils.get_typed_return_annotation(Callable[..., Any] call)
References fastapi.dependencies.utils.get_typed_annotation.
Dependant fastapi.dependencies.utils.get_dependant(*, str path, Callable[..., Any] call, Optional[str] name=None, Optional[List[str]] security_scopes=None, bool use_cache=True)
References fastapi.dependencies.utils.add_non_field_param_to_dependency, fastapi.dependencies.utils.add_param_to_fields, fastapi.dependencies.utils.analyze_param, fastapi.dependencies.utils.get_param_sub_dependant, fastapi.dependencies.utils.get_typed_signature.
Referenced by fastapi.dependencies.utils.get_sub_dependant, fastapi.dependencies.utils.solve_dependencies.
Optional[bool] fastapi.dependencies.utils.add_non_field_param_to_dependency(*, str param_name, Any type_annotation, Dependant dependant)
Referenced by fastapi.dependencies.utils.get_dependant.
ParamDetails fastapi.dependencies.utils.analyze_param(*, str param_name, Any annotation, Any value, bool is_path_param)
References fastapi.dependencies.utils.ensure_multipart_is_installed.
Referenced by fastapi.dependencies.utils.get_dependant.
None fastapi.dependencies.utils.add_param_to_fields(*, ModelField field, Dependant dependant)
Referenced by fastapi.dependencies.utils.get_dependant.
bool fastapi.dependencies.utils.is_coroutine_callable(Callable[..., Any] call)
Referenced by fastapi.dependencies.utils.solve_dependencies.
bool fastapi.dependencies.utils.is_async_gen_callable(Callable[..., Any] call)
Referenced by fastapi.dependencies.utils.solve_dependencies, fastapi.dependencies.utils.solve_generator.
bool fastapi.dependencies.utils.is_gen_callable(Callable[..., Any] call)
Referenced by fastapi.dependencies.utils.solve_dependencies, fastapi.dependencies.utils.solve_generator.
Any fastapi.dependencies.utils.solve_generator(*, Callable[..., Any] call, AsyncExitStack stack, Dict[str, Any] sub_values)
References fastapi.dependencies.utils.is_async_gen_callable, fastapi.dependencies.utils.is_gen_callable.
Referenced by fastapi.dependencies.utils.solve_dependencies.
SolvedDependency fastapi.dependencies.utils.solve_dependencies(*, Union[Request, WebSocket] request, Dependant dependant, Optional[Union[Dict[str, Any], FormData]] body=None, Optional[StarletteBackgroundTasks] background_tasks=None, Optional[Response] response=None, Optional[Any] dependency_overrides_provider=None, Optional[Dict[Tuple[Callable[..., Any], Tuple[str]], Any]] dependency_cache=None, AsyncExitStack async_exit_stack, bool embed_body_fields)
References fastapi.dependencies.utils.get_dependant, fastapi.dependencies.utils.is_async_gen_callable, fastapi.dependencies.utils.is_coroutine_callable, fastapi.dependencies.utils.is_gen_callable, fastapi.dependencies.utils.request_body_to_args, fastapi.dependencies.utils.request_params_to_args, fastapi.dependencies.utils.solve_dependencies, fastapi.dependencies.utils.solve_generator.
Referenced by fastapi.dependencies.utils.solve_dependencies.
Tuple[Any, List[Any]] fastapi.dependencies.utils._validate_value_with_model_field(*, ModelField field, Any value, Dict[str, Any] values, Tuple[str,...] loc)
Referenced by fastapi.dependencies.utils.request_body_to_args, fastapi.dependencies.utils.request_params_to_args.
Any fastapi.dependencies.utils._get_multidict_value(ModelField field, Mapping[str, Any] values, Union[str, None] alias=None)
Referenced by fastapi.dependencies.utils._extract_form_body, fastapi.dependencies.utils.request_params_to_args.
Tuple[Dict[str, Any], List[Any]] fastapi.dependencies.utils.request_params_to_args(Sequence[ModelField] fields, Union[Mapping[str, Any], QueryParams, Headers] received_params)
References fastapi.dependencies.utils._get_multidict_value, fastapi.dependencies.utils._validate_value_with_model_field.
Referenced by fastapi.dependencies.utils.solve_dependencies.
bool fastapi.dependencies.utils.is_union_of_base_models(Any field_type)
Check if field type is a Union where all members are BaseModel subclasses.
Referenced by fastapi.dependencies.utils._should_embed_body_fields.
bool fastapi.dependencies.utils._should_embed_body_fields(List[ModelField] fields)
References fastapi.dependencies.utils.is_union_of_base_models.
Dict[str, Any] fastapi.dependencies.utils._extract_form_body(List[ModelField] body_fields, FormData received_body)
References fastapi.dependencies.utils._get_multidict_value.
Referenced by fastapi.dependencies.utils.request_body_to_args.
Tuple[Dict[str, Any], List[Dict[str, Any]]] fastapi.dependencies.utils.request_body_to_args(List[ModelField] body_fields, Optional[Union[Dict[str, Any], FormData]] received_body, bool embed_body_fields)
References fastapi.dependencies.utils._extract_form_body, fastapi.dependencies.utils._validate_value_with_model_field.
Referenced by fastapi.dependencies.utils.solve_dependencies.
Optional[ModelField] fastapi.dependencies.utils.get_body_field(*, Dependant flat_dependant, str name, bool embed_body_fields)
Get a ModelField representing the request body for a path operation, combining all body parameters into a single field if necessary. Used to check if it's form data (with `isinstance(body_field, params.Form)`) or JSON and to generate the JSON Schema for a request body. This is **not** used to validate/parse the request body, that's done with each individual body parameter.