pip::_internal::network::download
pip::_internal::network::download.logger
int | None pip._internal.network.download._get_http_response_size(Response resp)
Referenced by pip._internal.network.download.Downloader._attempt_resumes_or_redownloads, pip._internal.network.download._prepare_download, pip._internal.network.download.Downloader.batch.
str | None pip._internal.network.download._get_http_response_etag_or_last_modified(Response resp)
Return either the ETag or Last-Modified header (or None if neither exists). The return value can be used in an If-Range header.
Referenced by pip._internal.network.download.Downloader._http_get_resume.
Iterable[bytes] pip._internal.network.download._log_download(Response resp, Link link, BarType progress_bar, int|None total_length, int|None range_start=0)
Referenced by pip._internal.network.download.Downloader._process_response.
str pip::_internal::network::download::sanitize_content_filename(str filename)
Sanitize the "filename" value from a Content-Disposition header.
Referenced by pip._internal.network.download._prepare_download, pip._internal.network.download.parse_content_disposition.
str pip::_internal::network::download::parse_content_disposition(str content_disposition, str default_filename)
Parse the "filename" value from a Content-Disposition header, and return the default filename if the result is empty.
References pip._internal.network.download.sanitize_content_filename.
Referenced by pip._internal.network.download._get_http_response_filename, pip._internal.network.download._prepare_download.
str pip::_internal::network::download::_get_http_response_filename(Response resp, Link link)
Get an ideal filename from the given HTTP response, falling back to the link filename if not provided.
References pip._internal.network.download.parse_content_disposition.
Referenced by pip._internal.network.download._http_get_download, pip._internal.network.download.Downloader.batch.
Iterable[bytes] pip._internal.network.download._prepare_download(Response resp, Link link, str progress_bar)
References pip._internal.network.download._get_http_response_size, pip._internal.network.download.parse_content_disposition, pip._internal.network.download.sanitize_content_filename.
Referenced by pip._internal.network.download._http_get_download.
Response pip._internal.network.download._http_get_download(PipSession session, Link link)
References pip._internal.network.download._get_http_response_filename, pip._internal.network.download._http_get_download, pip._internal.network.download._prepare_download.
Referenced by pip._internal.network.download._http_get_download.