pip::_vendor::rich::traceback
str pip::_vendor::rich::traceback::WINDOWS
int pip::_vendor::rich::traceback::LOCALS_MAX_LENGTH
int pip::_vendor::rich::traceback::LOCALS_MAX_STRING
pip::_vendor::rich::traceback.show_locals
pip::_vendor::rich::traceback.console
Iterable[Tuple[int, int, int]] pip._vendor.rich.traceback._iter_syntax_lines(SyntaxPosition start, SyntaxPosition end)
Yield start and end positions per line. Args: start: Start position. end: End position. Returns: Iterable of (LINE, COLUMN1, COLUMN2).
Referenced by pip._vendor.rich.traceback.Traceback._render_stack.
Callable[[Type[BaseException], BaseException, Optional[TracebackType]], Any] pip._vendor.rich.traceback.install(*, Optional[Console] console=None, Optional[int] width=100, Optional[int] code_width=88, int extra_lines=3, Optional[str] theme=None, bool word_wrap=False, bool show_locals=False, int locals_max_length=LOCALS_MAX_LENGTH, int locals_max_string=LOCALS_MAX_STRING, bool locals_hide_dunder=True, Optional[bool] locals_hide_sunder=None, bool indent_guides=True, Iterable[Union[str, ModuleType]] suppress=(), int max_frames=100)
Install a rich traceback handler. Once installed, any tracebacks will be printed with syntax highlighting and rich formatting. Args: console (Optional[Console], optional): Console to write exception to. Default uses internal Console instance. width (Optional[int], optional): Width (in characters) of traceback. Defaults to 100. code_width (Optional[int], optional): Code width (in characters) of traceback. Defaults to 88. extra_lines (int, optional): Extra lines of code. Defaults to 3. theme (Optional[str], optional): Pygments theme to use in traceback. Defaults to ``None`` which will pick a theme appropriate for the platform. word_wrap (bool, optional): Enable word wrapping of long lines. Defaults to False. show_locals (bool, optional): Enable display of local variables. Defaults to False. locals_max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation. Defaults to 10. locals_max_string (int, optional): Maximum length of string before truncating, or None to disable. Defaults to 80. locals_hide_dunder (bool, optional): Hide locals prefixed with double underscore. Defaults to True. locals_hide_sunder (bool, optional): Hide locals prefixed with single underscore. Defaults to False. indent_guides (bool, optional): Enable indent guides in code and locals. Defaults to True. suppress (Sequence[Union[str, ModuleType]]): Optional sequence of modules or paths to exclude from traceback. Returns: Callable: The previous exception handler that was replaced.
None pip::_vendor::rich::traceback::bar(Any a)
References pip._vendor.rich.print.
None pip::_vendor::rich::traceback::foo(Any a)
Referenced by pip._vendor.rich.traceback.error.
None pip::_vendor::rich::traceback::error()
References pip._vendor.rich.traceback.error, pip._vendor.rich.traceback.foo.
Referenced by pip._vendor.rich.traceback.error.
Callable[[Type[BaseException], BaseException, Optional[TracebackType]], Any] pip._vendor.rich.traceback.install(*, Optional[Console] console=None, Optional[int] width=100, int extra_lines=3, Optional[str] theme=None, bool word_wrap=False, bool show_locals=False, int locals_max_length=LOCALS_MAX_LENGTH, int locals_max_string=LOCALS_MAX_STRING, bool locals_hide_dunder=True, Optional[bool] locals_hide_sunder=None, bool indent_guides=True, Iterable[Union[str, ModuleType]] suppress=(), int max_frames=100)
Install a rich traceback handler. Once installed, any tracebacks will be printed with syntax highlighting and rich formatting. Args: console (Optional[Console], optional): Console to write exception to. Default uses internal Console instance. width (Optional[int], optional): Width (in characters) of traceback. Defaults to 100. extra_lines (int, optional): Extra lines of code. Defaults to 3. theme (Optional[str], optional): Pygments theme to use in traceback. Defaults to ``None`` which will pick a theme appropriate for the platform. word_wrap (bool, optional): Enable word wrapping of long lines. Defaults to False. show_locals (bool, optional): Enable display of local variables. Defaults to False. locals_max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation. Defaults to 10. locals_max_string (int, optional): Maximum length of string before truncating, or None to disable. Defaults to 80. locals_hide_dunder (bool, optional): Hide locals prefixed with double underscore. Defaults to True. locals_hide_sunder (bool, optional): Hide locals prefixed with single underscore. Defaults to False. indent_guides (bool, optional): Enable indent guides in code and locals. Defaults to True. suppress (Sequence[Union[str, ModuleType]]): Optional sequence of modules or paths to exclude from traceback. Returns: Callable: The previous exception handler that was replaced.