pip::_internal::operations::freeze
pip::_internal::operations::freeze.logger
Generator[str, None, None] pip._internal.operations.freeze.freeze(list[str]|None requirement=None, bool local_only=False, bool user_only=False, list[str]|None paths=None, bool isolated=False, bool exclude_editable=False, Container[str] skip=())
str pip::_internal::operations::freeze::_format_as_name_version(BaseDistribution dist)
Referenced by pip._internal.operations.freeze._get_editable_info, pip._internal.operations.freeze.freeze, pip._internal.operations.freeze.FrozenRequirement.from_dist.
_EditableInfo pip::_internal::operations::freeze::_get_editable_info(BaseDistribution dist)
Compute and return values (req, comments) for use in FrozenRequirement.from_dist().
References pip._internal.operations.freeze._format_as_name_version.
Referenced by pip._internal.operations.freeze.FrozenRequirement.from_dist.
Generator[str, None, None] pip._internal.operations.freeze.freeze(Optional[List[str]] requirement=None, bool local_only=False, bool user_only=False, Optional[List[str]] paths=None, bool isolated=False, bool exclude_editable=False, Container[str] skip=())
References pip._internal.operations.freeze._format_as_name_version.