setuptools::depends
setuptools.depends.maybe_close(f)
Referenced by setuptools.depends.get_module_constant.
setuptools.depends.get_module_constant(module, symbol, default=-1, paths=None)
Find 'module' by searching 'paths', and extract 'symbol' Return 'None' if 'module' does not exist on 'paths', or it does not define 'symbol'. If the module defines 'symbol' as a constant, return the constant. Otherwise, return 'default'.
References setuptools.depends.extract_constant, setuptools.depends.maybe_close.
Referenced by setuptools.depends.Require.get_version.
setuptools.depends.extract_constant(code, symbol, default=-1)
Extract the constant value of 'symbol' from 'code' If the name 'symbol' is bound to a constant value by the Python code object 'code', return that value. If 'symbol' is bound to an expression, return 'default'. Otherwise, return 'None'. Return value is based on the first assignment to 'symbol'. 'symbol' must be a global, or at least a non-"fast" local in the code block. That is, only 'STORE_NAME' and 'STORE_GLOBAL' opcodes are checked, and 'symbol' must be present in 'code.co_names'.
Referenced by setuptools.depends.get_module_constant.
setuptools.depends._update_globals()
Patch the globals to remove the objects not available on some platforms. XXX it'd be better to test assertions about bytecode instead.
References setuptools.depends._update_globals.
Referenced by setuptools.depends._update_globals.