pip::_vendor::urllib3::util::wait
pip::_vendor::urllib3::util::wait::_retry_on_intr(fn, timeout)
Referenced by pip._vendor.urllib3.util.wait._have_working_poll, pip._vendor.urllib3.util.wait.poll_wait_for_socket, pip._vendor.urllib3.util.wait.select_wait_for_socket.
pip::_vendor::urllib3::util::wait::select_wait_for_socket(sock, read=False, write=False, timeout=None)
References pip._vendor.urllib3.util.wait._retry_on_intr.
pip::_vendor::urllib3::util::wait::poll_wait_for_socket(sock, read=False, write=False, timeout=None)
References pip._vendor.urllib3.util.wait._retry_on_intr.
pip::_vendor::urllib3::util::wait::null_wait_for_socket(*args, **kwargs)
pip::_vendor::urllib3::util::wait::_have_working_poll()
References pip._vendor.urllib3.util.wait._retry_on_intr.
Referenced by pip._vendor.urllib3.util.wait.wait_for_socket.
pip::_vendor::urllib3::util::wait::wait_for_socket(*args, **kwargs)
References pip._vendor.urllib3.util.wait._have_working_poll, pip._vendor.urllib3.util.wait.wait_for_socket.
Referenced by pip._vendor.urllib3.util.wait.wait_for_read, pip._vendor.urllib3.util.wait.wait_for_socket, pip._vendor.urllib3.util.wait.wait_for_write.
pip::_vendor::urllib3::util::wait::wait_for_read(sock, timeout=None)
Waits for reading to be available on a given socket. Returns True if the socket is readable, or False if the timeout expired.
References pip._vendor.urllib3.util.wait.wait_for_socket.
pip::_vendor::urllib3::util::wait::wait_for_write(sock, timeout=None)
Waits for writing to be available on a given socket. Returns True if the socket is readable, or False if the timeout expired.
References pip._vendor.urllib3.util.wait.wait_for_socket.