pydantic::v1::main
pydantic::v1::main.Model
pydantic::v1::main._T
tuple pydantic::v1::main.ANNOTATED_FIELD_UNTOUCHED_TYPES
tuple pydantic::v1::main.UNTOUCHED_TYPES
bool pydantic::v1::main::_is_base_model_class_defined
pydantic::v1::main.object_setattr
Referenced by pydantic.v1.main.BaseModel._copy_and_set_values, pydantic.v1.main.BaseModel._init_private_attributes, pydantic.v1.main.BaseModel.construct, pydantic.v1.main.BaseModel.from_orm.
pydantic::v1::main._missing
None pydantic.v1.main.validate_custom_root_type(Dict[str, ModelField] fields)
Optional[Callable[[Any], int]] pydantic.v1.main.generate_hash_function(bool frozen)
Type['BaseModel'] pydantic.v1.main.create_model(str __model_name, *, Optional[Type[BaseConfig]] __config__=None, None __base__=None, str __module__=__name__, Dict[str, 'AnyClassMethod'] __validators__=None, Dict[str, Any] __cls_kwargs__=None, **Any field_definitions)
Referenced by pydantic.v1.tools._get_parsing_type, pydantic.v1.annotated_types.create_model_from_namedtuple, pydantic.v1.annotated_types.create_model_from_typeddict, pydantic.v1.dataclasses.create_pydantic_model_from_dataclass.
Type['Model'] pydantic.v1.main.create_model(str __model_name, *, Optional[Type[BaseConfig]] __config__=None, Union[Type['Model'], Tuple[Type['Model'],...]] __base__, str __module__=__name__, Dict[str, 'AnyClassMethod'] __validators__=None, Dict[str, Any] __cls_kwargs__=None, **Any field_definitions)
Type['Model'] pydantic.v1.main.create_model(str __model_name, *, Optional[Type[BaseConfig]] __config__=None, Union[None, Type['Model'], Tuple[Type['Model'],...]] __base__=None, str __module__=__name__, Dict[str, 'AnyClassMethod'] __validators__=None, Dict[str, Any] __cls_kwargs__=None, Optional[Tuple[str,...]] __slots__=None, **Any field_definitions)
Dynamically create a model. :param __model_name: name of the created model :param __config__: config class to use for the new model :param __base__: base class for the new model to inherit from :param __module__: module of the created model :param __validators__: a dict of method names and @validator class methods :param __cls_kwargs__: a dict for class creation :param __slots__: Deprecated, `__slots__` should not be passed to `create_model` :param field_definitions: fields of the model (or extra fields if a base is supplied) in the format `<name>=(<type>, <default default>)` or `<name>=<default value>, e.g. `foobar=(str, ...)` or `foobar=123`, or, for complex use-cases, in the format `<name>=<Field>` or `<name>=(<type>, <FieldInfo>)`, e.g. `foo=Field(datetime, default_factory=datetime.utcnow, alias='bar')` or `foo=(str, FieldInfo(title='Foo'))`
Tuple['DictStrAny', 'SetStr', Optional[ValidationError]] pydantic.v1.main.validate_model(Type[BaseModel] model, 'DictStrAny' input_data, 'ModelOrDc' cls=None)
validate data against a model.
Referenced by pydantic.v1.dataclasses._dataclass_validate_values, pydantic.v1.main.BaseModel.from_orm.