click::decorators
click::decorators.P
click::decorators.R
click::decorators.T
click::decorators._AnyCallable
click::decorators.FC
click::decorators.CmdType
click::decorators.GrpType
t.Callable[P, R] click.decorators.pass_context(t.Callable[te.Concatenate[Context, P], R] f)
Marks a callback as wanting to receive the current context object as first argument.
t.Callable[P, R] click.decorators.pass_obj(t.Callable[te.Concatenate[T, P], R] f)
Similar to :func:`pass_context`, but only pass the object on the context onwards (:attr:`Context.obj`). This is useful if that object represents the state of a nested system.
t.Callable[[t.Callable[te.Concatenate[T, P], R]], t.Callable[P, R]] click.decorators.make_pass_decorator(type[T] object_type, bool ensure=False)
Given an object type this creates a decorator that will work similar to :func:`pass_obj` but instead of passing the object of the current context, it will find the innermost context of type :func:`object_type`. This generates a decorator that works roughly like this:: from functools import update_wrapper def decorator(f): @pass_context def new_func(ctx, *args, **kwargs): obj = ctx.find_object(object_type) return ctx.invoke(f, obj, *args, **kwargs) return update_wrapper(new_func, f) return decorator :param object_type: the type of the object to pass. :param ensure: if set to `True`, a new object will be created and remembered on the context if it's not there yet.
t.Callable[[t.Callable[te.Concatenate[T, P], R]], t.Callable[P, R]] click.decorators.pass_meta_key(str key, *, str|None doc_description=None)
Create a decorator that passes a key from :attr:`click.Context.meta` as the first argument to the decorated function. :param key: Key in ``Context.meta`` to pass. :param doc_description: Description of the object being passed, inserted into the decorator's docstring. Defaults to "the 'key' key from Context.meta". .. versionadded:: 8.0
Command click.decorators.command(_AnyCallable name)
Referenced by click.decorators.group.
t.Callable[[_AnyCallable], CmdType] click.decorators.command(str|None name, type[CmdType] cls, **t.Any attrs)
t.Callable[[_AnyCallable], CmdType] click.decorators.command(None name=None, *, type[CmdType] cls, **t.Any attrs)
t.Callable[[_AnyCallable], Command] click.decorators.command(str|None name=..., None cls=None, **t.Any attrs)
Command | t.Callable[[_AnyCallable], Command | CmdType] click.decorators.command(str|_AnyCallable|None name=None, type[CmdType]|None cls=None, **t.Any attrs)
Creates a new :class:`Command` and uses the decorated function as callback. This will also automatically attach all decorated :func:`option`\s and :func:`argument`\s as parameters to the command. The name of the command defaults to the name of the function, converted to lowercase, with underscores ``_`` replaced by dashes ``-``, and the suffixes ``_command``, ``_cmd``, ``_group``, and ``_grp`` are removed. For example, ``init_data_command`` becomes ``init-data``. All keyword arguments are forwarded to the underlying command class. For the ``params`` argument, any decorated params are appended to the end of the list. Once decorated the function turns into a :class:`Command` instance that can be invoked as a command line utility or be attached to a command :class:`Group`. :param name: The name of the command. Defaults to modifying the function's name as described above. :param cls: The command class to create. Defaults to :class:`Command`. .. versionchanged:: 8.2 The suffixes ``_command``, ``_cmd``, ``_group``, and ``_grp`` are removed when generating the name. .. versionchanged:: 8.1 This decorator can be applied without parentheses. .. versionchanged:: 8.1 The ``params`` argument can be used. Decorated params are appended to the end of the list.
Group click.decorators.group(_AnyCallable name)
t.Callable[[_AnyCallable], GrpType] click.decorators.group(str|None name, type[GrpType] cls, **t.Any attrs)
t.Callable[[_AnyCallable], GrpType] click.decorators.group(None name=None, *, type[GrpType] cls, **t.Any attrs)
t.Callable[[_AnyCallable], Group] click.decorators.group(str|None name=..., None cls=None, **t.Any attrs)
Group | t.Callable[[_AnyCallable], Group | GrpType] click.decorators.group(str|_AnyCallable|None name=None, type[GrpType]|None cls=None, **t.Any attrs)
Creates a new :class:`Group` with a function as callback. This works otherwise the same as :func:`command` just that the `cls` parameter is set to :class:`Group`. .. versionchanged:: 8.1 This decorator can be applied without parentheses.
References click.decorators.command.
None click.decorators._param_memo(t.Callable[..., t.Any] f, Parameter param)
Referenced by click.decorators.argument, click.decorators.option.
t.Callable[[FC], FC] click.decorators.argument(*str param_decls, type[Argument]|None cls=None, **t.Any attrs)
Attaches an argument to the command. All positional arguments are passed as parameter declarations to :class:`Argument`; all keyword arguments are forwarded unchanged (except ``cls``). This is equivalent to creating an :class:`Argument` instance manually and attaching it to the :attr:`Command.params` list. For the default argument class, refer to :class:`Argument` and :class:`Parameter` for descriptions of parameters. :param cls: the argument class to instantiate. This defaults to :class:`Argument`. :param param_decls: Passed as positional arguments to the constructor of ``cls``. :param attrs: Passed as keyword arguments to the constructor of ``cls``.
References click.decorators._param_memo.
t.Callable[[FC], FC] click.decorators.option(*str param_decls, type[Option]|None cls=None, **t.Any attrs)
Attaches an option to the command. All positional arguments are passed as parameter declarations to :class:`Option`; all keyword arguments are forwarded unchanged (except ``cls``). This is equivalent to creating an :class:`Option` instance manually and attaching it to the :attr:`Command.params` list. For the default option class, refer to :class:`Option` and :class:`Parameter` for descriptions of parameters. :param cls: the option class to instantiate. This defaults to :class:`Option`. :param param_decls: Passed as positional arguments to the constructor of ``cls``. :param attrs: Passed as keyword arguments to the constructor of ``cls``.
References click.decorators._param_memo.
Referenced by click.decorators.confirmation_option, click.decorators.help_option, click.decorators.password_option, click.decorators.version_option.
t.Callable[[FC], FC] click.decorators.confirmation_option(*str param_decls, **t.Any kwargs)
Add a ``--yes`` option which shows a prompt before continuing if not passed. If the prompt is declined, the program will exit. :param param_decls: One or more option names. Defaults to the single value ``"--yes"``. :param kwargs: Extra arguments are passed to :func:`option`.
References click.decorators.option.
t.Callable[[FC], FC] click.decorators.password_option(*str param_decls, **t.Any kwargs)
Add a ``--password`` option which prompts for a password, hiding input and asking to enter the value again for confirmation. :param param_decls: One or more option names. Defaults to the single value ``"--password"``. :param kwargs: Extra arguments are passed to :func:`option`.
References click.decorators.option.
t.Callable[[FC], FC] click.decorators.version_option(str|None version=None, *str param_decls, str|None package_name=None, str|None prog_name=None, str|None message=None, **t.Any kwargs)
Add a ``--version`` option which immediately prints the version number and exits the program. If ``version`` is not provided, Click will try to detect it using :func:`importlib.metadata.version` to get the version for the ``package_name``. If ``package_name`` is not provided, Click will try to detect it by inspecting the stack frames. This will be used to detect the version, so it must match the name of the installed package. :param version: The version number to show. If not provided, Click will try to detect it. :param param_decls: One or more option names. Defaults to the single value ``"--version"``. :param package_name: The package name to detect the version from. If not provided, Click will try to detect it. :param prog_name: The name of the CLI to show in the message. If not provided, it will be detected from the command. :param message: The message to show. The values ``%(prog)s``, ``%(package)s``, and ``%(version)s`` are available. Defaults to ``"%(prog)s, version %(version)s"``. :param kwargs: Extra arguments are passed to :func:`option`. :raise RuntimeError: ``version`` could not be detected. .. versionchanged:: 8.0 Add the ``package_name`` parameter, and the ``%(package)s`` value for messages. .. versionchanged:: 8.0 Use :mod:`importlib.metadata` instead of ``pkg_resources``. The version is detected based on the package name, not the entry point name. The Python package name must match the installed package name, or be passed with ``package_name=``.
References click.decorators.option.
t.Callable[[FC], FC] click.decorators.help_option(*str param_decls, **t.Any kwargs)
Pre-configured ``--help`` option which immediately prints the help page and exits the program. :param param_decls: One or more option names. Defaults to the single value ``"--help"``. :param kwargs: Extra arguments are passed to :func:`option`.
References click.decorators.option.