fastapi::openapi::utils
dict fastapi::openapi::utils.validation_error_definition
dict fastapi::openapi::utils.validation_error_response_definition
dict fastapi::openapi::utils.status_code_ranges
Tuple[Dict[str, Any], List[Dict[str, Any]]] fastapi.openapi.utils.get_openapi_security_definitions(Dependant flat_dependant)
Referenced by fastapi.openapi.utils.get_openapi_path.
List[Dict[str, Any]] fastapi.openapi.utils._get_openapi_operation_parameters(*, Dependant dependant, ModelNameMap model_name_map, Dict[Tuple[ModelField, Literal["validation", "serialization"]], JsonSchemaValue] field_mapping, bool separate_input_output_schemas=True)
Referenced by fastapi.openapi.utils.get_openapi_path.
Optional[Dict[str, Any]] fastapi.openapi.utils.get_openapi_operation_request_body(*, Optional[ModelField] body_field, ModelNameMap model_name_map, Dict[Tuple[ModelField, Literal["validation", "serialization"]], JsonSchemaValue] field_mapping, bool separate_input_output_schemas=True)
Referenced by fastapi.openapi.utils.get_openapi_path.
str fastapi.openapi.utils.generate_operation_id(*, routing.APIRoute route, str method)
str fastapi.openapi.utils.generate_operation_summary(*, routing.APIRoute route, str method)
Referenced by fastapi.openapi.utils.get_openapi_operation_metadata.
Dict[str, Any] fastapi.openapi.utils.get_openapi_operation_metadata(*, routing.APIRoute route, str method, Set[str] operation_ids)
References fastapi.openapi.utils.generate_operation_summary.
Referenced by fastapi.openapi.utils.get_openapi_path.
Tuple[Dict[str, Any], Dict[str, Any], Dict[str, Any]] fastapi.openapi.utils.get_openapi_path(*, routing.APIRoute route, Set[str] operation_ids, ModelNameMap model_name_map, Dict[Tuple[ModelField, Literal["validation", "serialization"]], JsonSchemaValue] field_mapping, bool separate_input_output_schemas=True)
References fastapi.openapi.utils._get_openapi_operation_parameters, fastapi.openapi.utils.get_openapi_operation_metadata, fastapi.openapi.utils.get_openapi_operation_request_body, fastapi.openapi.utils.get_openapi_path, fastapi.openapi.utils.get_openapi_security_definitions.
Referenced by fastapi.openapi.utils.get_openapi, fastapi.openapi.utils.get_openapi_path.
List[ModelField] fastapi.openapi.utils.get_fields_from_routes(Sequence[BaseRoute] routes)
References fastapi.openapi.utils.get_fields_from_routes.
Referenced by fastapi.openapi.utils.get_fields_from_routes, fastapi.openapi.utils.get_openapi.
Dict[str, Any] fastapi.openapi.utils.get_openapi(*, str title, str version, str openapi_version="3.1.0", Optional[str] summary=None, Optional[str] description=None, Sequence[BaseRoute] routes, Optional[Sequence[BaseRoute]] webhooks=None, Optional[List[Dict[str, Any]]] tags=None, Optional[List[Dict[str, Union[str, Any]]]] servers=None, Optional[str] terms_of_service=None, Optional[Dict[str, Union[str, Any]]] contact=None, Optional[Dict[str, Union[str, Any]]] license_info=None, bool separate_input_output_schemas=True, Optional[Dict[str, Any]] external_docs=None)
References fastapi.openapi.utils.get_fields_from_routes, fastapi.openapi.utils.get_openapi_path.