pip::_vendor::rich::pretty
bool pip::_vendor::rich::pretty::_has_attrs
pip::_vendor::rich::pretty._dummy_namedtuple
dict pip::_vendor::rich::pretty::_BRACES
pip::_vendor::rich::pretty._CONTAINERS
tuple pip::_vendor::rich::pretty::_MAPPING_CONTAINERS
pip::_vendor::rich::pretty.d
dict pip::_vendor::rich::pretty::data
None pip::_vendor::rich::pretty::pprint
A convenience function for pretty printing. Args: _object (Any): Object to pretty print. console (Console, optional): Console instance, or None to use default. Defaults to None. max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation. Defaults to None. max_string (int, optional): Maximum length of strings before truncating, or None to disable. Defaults to None. max_depth (int, optional): Maximum depth for nested data structures, or None for unlimited depth. Defaults to None. indent_guides (bool, optional): Enable indentation guides. Defaults to True. expand_all (bool, optional): Expand all containers. Defaults to False.
bool pip::_vendor::rich::pretty::_is_attr_object(Any obj)
Check if an object was created with attrs module.
Referenced by pip._vendor.rich.pretty._Line.expand, pip._vendor.rich.pretty.is_expandable, pip._vendor.rich.pretty.traverse.
Sequence["_attr_module.Attribute[Any]"] pip._vendor.rich.pretty._get_attr_fields(Any obj)
Get fields for an attrs object.
Referenced by pip._vendor.rich.pretty._Line.expand, pip._vendor.rich.pretty.traverse.
bool pip::_vendor::rich::pretty::_is_dataclass_repr(object obj)
Check if an instance of a dataclass contains the default repr. Args: obj (object): A dataclass instance. Returns: bool: True if the default repr is used, False if there is a custom repr.
Referenced by pip._vendor.rich.pretty._Line.expand, pip._vendor.rich.pretty.traverse.
bool pip::_vendor::rich::pretty::_has_default_namedtuple_repr(object obj)
Check if an instance of namedtuple contains the default repr Args: obj (object): A namedtuple Returns: bool: True if the default repr is used, False if there's a custom repr.
Referenced by pip._vendor.rich.pretty._Line.expand, pip._vendor.rich.pretty.traverse.
Union[str, None] pip._vendor.rich.pretty._ipy_display_hook(Any value, Optional["Console"] console=None, "OverflowMethod" overflow="ignore", bool crop=False, bool indent_guides=False, Optional[int] max_length=None, Optional[int] max_string=None, Optional[int] max_depth=None, bool expand_all=False)
References pip._vendor.rich.pretty._safe_isinstance, pip._vendor.rich.get_console.
bool pip::_vendor::rich::pretty::_safe_isinstance(object obj, Union[type, Tuple[type,...]] class_or_tuple)
isinstance can fail in rare cases, for example types with no __class__
Referenced by pip._vendor.rich.pretty._ipy_display_hook, pip._vendor.rich.pretty._Line.expand, pip._vendor.rich.pretty.install, pip._vendor.rich.pretty.is_expandable, pip._vendor.rich.pretty.pretty_repr, pip._vendor.rich.pretty.traverse.
None pip::_vendor::rich::pretty::install(Optional["Console"] console=None, "OverflowMethod" overflow="ignore", bool crop=False, bool indent_guides=False, Optional[int] max_length=None, Optional[int] max_string=None, Optional[int] max_depth=None, bool expand_all=False)
Install automatic pretty printing in the Python REPL. Args: console (Console, optional): Console instance or ``None`` to use global console. Defaults to None. overflow (Optional[OverflowMethod], optional): Overflow method. Defaults to "ignore". crop (Optional[bool], optional): Enable cropping of long lines. Defaults to False. indent_guides (bool, optional): Enable indentation guides. Defaults to False. max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation. Defaults to None. max_string (int, optional): Maximum length of string before truncating, or None to disable. Defaults to None. max_depth (int, optional): Maximum depth of nested data structures, or None for no maximum. Defaults to None. expand_all (bool, optional): Expand all containers. Defaults to False. max_frames (int): Maximum number of frames to show in a traceback, 0 for no maximum. Defaults to 100.
References pip._vendor.rich.pretty._safe_isinstance, pip._vendor.rich.get_console.
Tuple[str, str, str] pip._vendor.rich.pretty._get_braces_for_defaultdict(DefaultDict[Any, Any] _object)
Tuple[str, str, str] pip._vendor.rich.pretty._get_braces_for_deque(Deque[Any] _object)
Tuple[str, str, str] pip._vendor.rich.pretty._get_braces_for_array("array[Any]" _object)
bool pip::_vendor::rich::pretty::is_expandable(Any obj)
Check if an object may be expanded by pretty print.
References pip._vendor.rich.pretty._is_attr_object, pip._vendor.rich.pretty._safe_isinstance.
bool pip::_vendor::rich::pretty::_is_namedtuple(Any obj)
Checks if an object is most likely a namedtuple. It is possible to craft an object that passes this check and isn't a namedtuple, but there is only a minuscule chance of this happening unintentionally. Args: obj (Any): The object to test Returns: bool: True if the object is a namedtuple. False otherwise.
Referenced by pip._vendor.rich.pretty._Line.expand, pip._vendor.rich.pretty.traverse.
Node pip::_vendor::rich::pretty::traverse(Any _object, Optional[int] max_length=None, Optional[int] max_string=None, Optional[int] max_depth=None)
Traverse object and generate a tree. Args: _object (Any): Object to be traversed. max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation. Defaults to None. max_string (int, optional): Maximum length of string before truncating, or None to disable truncating. Defaults to None. max_depth (int, optional): Maximum depth of data structures, or None for no maximum. Defaults to None. Returns: Node: The root of a tree structure which can be used to render a pretty repr.
References pip._vendor.rich.pretty._get_attr_fields, pip._vendor.rich.pretty._has_default_namedtuple_repr, pip._vendor.rich.pretty._is_attr_object, pip._vendor.rich.pretty._is_dataclass_repr, pip._vendor.rich.pretty._is_namedtuple, pip._vendor.rich.pretty._safe_isinstance.
Referenced by pip._vendor.rich.pretty._Line.expand, pip._vendor.rich.pretty.pretty_repr.
str pip::_vendor::rich::pretty::pretty_repr(Any _object, *, int max_width=80, int indent_size=4, Optional[int] max_length=None, Optional[int] max_string=None, Optional[int] max_depth=None, bool expand_all=False)
Prettify repr string by expanding on to new lines to fit within a given width. Args: _object (Any): Object to repr. max_width (int, optional): Desired maximum width of repr string. Defaults to 80. indent_size (int, optional): Number of spaces to indent. Defaults to 4. max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation. Defaults to None. max_string (int, optional): Maximum length of string before truncating, or None to disable truncating. Defaults to None. max_depth (int, optional): Maximum depth of nested data structure, or None for no depth. Defaults to None. expand_all (bool, optional): Expand all containers regardless of available width. Defaults to False. Returns: str: A possibly multi-line representation of the object.
References pip._vendor.rich.pretty._safe_isinstance, pip._vendor.rich.pretty.traverse.
None pip._vendor.rich.pretty.pprint(Any _object, *, Optional["Console"] console=None, bool indent_guides=True, Optional[int] max_length=None, Optional[int] max_string=None, Optional[int] max_depth=None, bool expand_all=False)
A convenience function for pretty printing. Args: _object (Any): Object to pretty print. console (Console, optional): Console instance, or None to use default. Defaults to None. max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation. Defaults to None. max_string (int, optional): Maximum length of strings before truncating, or None to disable. Defaults to None. max_depth (int, optional): Maximum depth for nested data structures, or None for unlimited depth. Defaults to None. indent_guides (bool, optional): Enable indentation guides. Defaults to True. expand_all (bool, optional): Expand all containers. Defaults to False.
References pip._vendor.rich.get_console.