setuptools::_entry_points
setuptools._entry_points.ensure_valid(ep)
Exercise one of the dynamic properties to trigger the pattern match.
setuptools._entry_points.load_group(value, group)
Given a value of an entry point or series of entry points, return each as an EntryPoint.
Referenced by setuptools._entry_points.load.
setuptools._entry_points.by_group_and_name(ep)
setuptools._entry_points.validate(metadata.EntryPoints eps)
Ensure entry points are unique by group and name and validate each.
Referenced by setuptools._entry_points._, setuptools._entry_points.load.
setuptools._entry_points.load(eps)
Given a Distribution.entry_points, produce EntryPoints.
References setuptools._entry_points.load_group, setuptools._entry_points.validate.
setuptools._entry_points._(eps)
>>> ep, = load('[console_scripts]\nfoo=bar') >>> ep.group 'console_scripts' >>> ep.name 'foo' >>> ep.value 'bar'
References setuptools._entry_points.validate.
setuptools._entry_points.render(metadata.EntryPoints eps)
setuptools._entry_points.render_items(eps)