pip::_internal::resolution::resolvelib::candidates
pip::_internal::resolution::resolvelib::candidates.logger
pip::_internal::resolution::resolvelib::candidates.BaseCandidate
pip::_internal::resolution::resolvelib::candidates.REQUIRES_PYTHON_IDENTIFIER
BaseCandidate | None pip._internal.resolution.resolvelib.candidates.as_base_candidate(Candidate candidate)
The runtime version of BaseCandidate.
InstallRequirement pip::_internal::resolution::resolvelib::candidates::make_install_req_from_link(Link link, InstallRequirement template)
Referenced by pip._internal.resolution.resolvelib.candidates._InstallRequirementBackedCandidate.get_install_requirement.
InstallRequirement pip::_internal::resolution::resolvelib::candidates::make_install_req_from_editable(Link link, InstallRequirement template)
Referenced by pip._internal.resolution.resolvelib.candidates.LinkCandidate._prepare_distribution.
InstallRequirement pip::_internal::resolution::resolvelib::candidates::_make_install_req_from_dist(BaseDistribution dist, InstallRequirement template)
Referenced by pip._internal.resolution.resolvelib.candidates.EditableCandidate._prepare_distribution.