pip::_vendor::rich
Optional pip::_vendor::rich::_console
str pip::_vendor::rich::_IMPORT_CWD
Console pip::_vendor::rich::get_console()
Get a global :class:`~rich.console.Console` instance. This function is used when Rich requires a Console, and hasn't been explicitly given one. Returns: Console: A console instance.
Referenced by pip._vendor.rich.pretty._ipy_display_hook, pip._vendor.rich.jupyter.JupyterMixin._repr_mimebundle_, pip._vendor.rich.progress.Task._reset, pip._vendor.rich.pretty._Line.expand, pip._vendor.rich.inspect, pip._vendor.rich.pretty.install, pip._vendor.rich.pretty.pprint, pip._vendor.rich.jupyter.print, pip._vendor.rich.print, pip._vendor.rich.print_json, pip._vendor.rich.reconfigure, pip._vendor.rich.live._RefreshThread.run.
None pip::_vendor::rich::reconfigure(*Any args, **Any kwargs)
Reconfigures the global console by replacing it with another. Args: *args (Any): Positional arguments for the replacement :class:`~rich.console.Console`. **kwargs (Any): Keyword arguments for the replacement :class:`~rich.console.Console`.
References pip._vendor.rich.get_console.
None pip::_vendor::rich::print(*Any objects, str sep=" ", str end="\n", Optional[IO[str]] file=None, bool flush=False)
Print object(s) supplied via positional arguments. This function has an identical signature to the built-in print. For more advanced features, see the :class:`~rich.console.Console` class. Args: sep (str, optional): Separator between printed objects. Defaults to " ". end (str, optional): Character to write at end of output. Defaults to "\\n". file (IO[str], optional): File to write to, or None for stdout. Defaults to None. flush (bool, optional): Has no effect as Rich always flushes output. Defaults to False.
References pip._vendor.rich.get_console.
Referenced by pip._vendor.rich.traceback.bar, pip._vendor.rich.cells.chop_cells, pip._vendor.rich.ansi.AnsiDecoder.decode_line, pip._vendor.rich.logging.RichHandler.emit, pip._vendor.rich.pretty._Line.expand, pip._vendor.rich.file_proxy.FileProxy.flush, pip._vendor.rich.inspect, pip._vendor.rich.markup.Tag.markup, pip._vendor.rich.prompt.PromptBase.on_validate_error, pip._vendor.rich.theme.ThemeStack.pop_theme, pip._vendor.rich.prompt.Confirm.process_response, pip._vendor.rich.live.Live.refresh, pip._vendor.rich.scope.render_scope, pip._vendor.rich.scope.test, pip._vendor.rich._timer.timer, pip._vendor.rich.padding.Padding.unpack, pip._vendor.rich.console.ScreenContext.update.
None pip::_vendor::rich::print_json(Optional[str] json=None, *, Any data=None, Union[None, int, str] indent=2, bool highlight=True, bool skip_keys=False, bool ensure_ascii=False, bool check_circular=True, bool allow_nan=True, Optional[Callable[[Any], Any]] default=None, bool sort_keys=False)
Pretty prints JSON. Output will be valid JSON. Args: json (str): A string containing JSON. data (Any): If json is not supplied, then encode this data. indent (int, optional): Number of spaces to indent. Defaults to 2. highlight (bool, optional): Enable highlighting of output: Defaults to True. skip_keys (bool, optional): Skip keys not of a basic type. Defaults to False. ensure_ascii (bool, optional): Escape all non-ascii characters. Defaults to False. check_circular (bool, optional): Check for circular references. Defaults to True. allow_nan (bool, optional): Allow NaN and Infinity values. Defaults to True. default (Callable, optional): A callable that converts values that can not be encoded in to something that can be JSON encoded. Defaults to None. sort_keys (bool, optional): Sort dictionary keys. Defaults to False.
References pip._vendor.rich.get_console, pip._vendor.rich.print_json.
Referenced by pip._vendor.rich.print_json.
None pip::_vendor::rich::inspect(Any obj, *, Optional["Console"] console=None, Optional[str] title=None, bool help=False, bool methods=False, bool docs=True, bool private=False, bool dunder=False, bool sort=True, bool all=False, bool value=True)
Inspect any Python object. * inspect(<OBJECT>) to see summarized info. * inspect(<OBJECT>, methods=True) to see methods. * inspect(<OBJECT>, help=True) to see full (non-abbreviated) help. * inspect(<OBJECT>, private=True) to see private attributes (single underscore). * inspect(<OBJECT>, dunder=True) to see attributes beginning with double underscore. * inspect(<OBJECT>, all=True) to see all attributes. Args: obj (Any): An object to inspect. title (str, optional): Title to display over inspect result, or None use type. Defaults to None. help (bool, optional): Show full help text rather than just first paragraph. Defaults to False. methods (bool, optional): Enable inspection of callables. Defaults to False. docs (bool, optional): Also render doc strings. Defaults to True. private (bool, optional): Show private attributes (beginning with underscore). Defaults to False. dunder (bool, optional): Show attributes starting with double underscore. Defaults to False. sort (bool, optional): Sort attributes alphabetically. Defaults to True. all (bool, optional): Show all attributes. Defaults to False. value (bool, optional): Pretty print value. Defaults to True.
References pip._vendor.rich.get_console, pip._vendor.rich.print.
Referenced by pip._vendor.rich.diagnose.report.