pip::_vendor::urllib3::contrib::_securetransport::low_level
pip::_vendor::urllib3::contrib::_securetransport::low_level._PEM_CERTS_RE
dict pip::_vendor::urllib3::contrib::_securetransport::low_level::TLS_PROTOCOL_VERSIONS
pip::_vendor::urllib3::contrib::_securetransport::low_level::_cf_data_from_bytes(bytestring)
Given a bytestring, create a CFData object from it. This CFData object must be CFReleased by the caller.
Referenced by pip._vendor.urllib3.contrib._securetransport.low_level._cert_array_from_pem.
pip::_vendor::urllib3::contrib::_securetransport::low_level::_cf_dictionary_from_tuples(tuples)
Given a list of Python tuples, create an associated CFDictionary.
pip::_vendor::urllib3::contrib::_securetransport::low_level::_cfstr(py_bstr)
Given a Python binary data, create a CFString. The string must be CFReleased by the caller.
Referenced by pip._vendor.urllib3.contrib._securetransport.low_level._create_cfstring_array.
pip::_vendor::urllib3::contrib::_securetransport::low_level::_create_cfstring_array(lst)
Given a list of Python binary data, create an associated CFMutableArray. The array must be CFReleased by the caller. Raises an ssl.SSLError on failure.
References pip._vendor.urllib3.contrib._securetransport.low_level._cfstr.
pip::_vendor::urllib3::contrib::_securetransport::low_level::_cf_string_to_unicode(value)
Creates a Unicode string from a CFString object. Used entirely for error reporting. Yes, it annoys me quite a lot that this function is this complex.
Referenced by pip._vendor.urllib3.contrib._securetransport.low_level._assert_no_error.
pip::_vendor::urllib3::contrib::_securetransport::low_level::_assert_no_error(error, exception_class=None)
Checks the return code and throws an exception if there is an error to report
References pip._vendor.urllib3.contrib._securetransport.low_level._cf_string_to_unicode.
Referenced by pip._vendor.urllib3.contrib._securetransport.low_level._load_client_cert_chain, pip._vendor.urllib3.contrib._securetransport.low_level._load_items_from_file, pip._vendor.urllib3.contrib._securetransport.low_level._temporary_keychain.
pip::_vendor::urllib3::contrib::_securetransport::low_level::_cert_array_from_pem(pem_bundle)
Given a bundle of certs in PEM format, turns them into a CFArray of certs that can be used to validate a cert chain.
References pip._vendor.urllib3.contrib._securetransport.low_level._cf_data_from_bytes.
pip::_vendor::urllib3::contrib::_securetransport::low_level::_is_cert(item)
Returns True if a given CFTypeRef is a certificate.
Referenced by pip._vendor.urllib3.contrib._securetransport.low_level._load_items_from_file.
pip::_vendor::urllib3::contrib::_securetransport::low_level::_is_identity(item)
Returns True if a given CFTypeRef is an identity.
Referenced by pip._vendor.urllib3.contrib._securetransport.low_level._load_items_from_file.
pip::_vendor::urllib3::contrib::_securetransport::low_level::_temporary_keychain()
This function creates a temporary Mac keychain that we can use to work with credentials. This keychain uses a one-time password and a temporary file to store the data. We expect to have one keychain per socket. The returned SecKeychainRef must be freed by the caller, including calling SecKeychainDelete. Returns a tuple of the SecKeychainRef and the path to the temporary directory that contains it.
References pip._vendor.urllib3.contrib._securetransport.low_level._assert_no_error.
pip::_vendor::urllib3::contrib::_securetransport::low_level::_load_items_from_file(keychain, path)
Given a single file, loads all the trust objects from it into arrays and the keychain. Returns a tuple of lists: the first list is a list of identities, the second a list of certs.
References pip._vendor.urllib3.contrib._securetransport.low_level._assert_no_error, pip._vendor.urllib3.contrib._securetransport.low_level._is_cert, pip._vendor.urllib3.contrib._securetransport.low_level._is_identity.
Referenced by pip._vendor.urllib3.contrib._securetransport.low_level._load_client_cert_chain.
pip::_vendor::urllib3::contrib::_securetransport::low_level::_load_client_cert_chain(keychain, *paths)
Load certificates and maybe keys from a number of files. Has the end goal of returning a CFArray containing one SecIdentityRef, and then zero or more SecCertificateRef objects, suitable for use as a client certificate trust chain.
References pip._vendor.urllib3.contrib._securetransport.low_level._assert_no_error, pip._vendor.urllib3.contrib._securetransport.low_level._load_items_from_file.
pip::_vendor::urllib3::contrib::_securetransport::low_level::_build_tls_unknown_ca_alert(version)
Builds a TLS alert record for an unknown CA.