pip::_internal::cli::cmdoptions
pip::_internal::cli::cmdoptions.logger
Callable pip::_internal::cli::cmdoptions::cert
Callable pip::_internal::cli::cmdoptions::client_cert
Callable pip::_internal::cli::cmdoptions::index_url
Callable pip::_internal::cli::cmdoptions::no_index
Callable pip::_internal::cli::cmdoptions::src
Callable pip::_internal::cli::cmdoptions::platforms
Referenced by pip._internal.cli.cmdoptions.add_target_python_options, pip._internal.cli.cmdoptions.make_option_group.
Callable pip::_internal::cli::cmdoptions::python_version
Referenced by pip._internal.cli.cmdoptions.add_target_python_options, pip._internal.cli.cmdoptions.make_option_group.
Callable pip::_internal::cli::cmdoptions::implementation
Referenced by pip._internal.cli.cmdoptions.add_target_python_options, pip._internal.cli.cmdoptions.make_option_group.
Callable pip::_internal::cli::cmdoptions::abis
Referenced by pip._internal.cli.cmdoptions.add_target_python_options, pip._internal.cli.cmdoptions.make_option_group.
Callable pip::_internal::cli::cmdoptions::cache_dir
Callable pip::_internal::cli::cmdoptions::no_cache
Callable pip::_internal::cli::cmdoptions::no_deps
Callable pip::_internal::cli::cmdoptions.dependency_groups
Callable pip::_internal::cli::cmdoptions::ignore_requires_python
Callable pip::_internal::cli::cmdoptions::no_build_isolation
Callable pip::_internal::cli::cmdoptions::check_build_deps
Any pip::_internal::cli::cmdoptions::use_pep517
Any pip::_internal::cli::cmdoptions::no_use_pep517
Callable pip::_internal::cli::cmdoptions::config_settings
Callable pip::_internal::cli::cmdoptions::build_options
Callable pip::_internal::cli::cmdoptions::global_options
Callable pip::_internal::cli::cmdoptions::no_clean
Callable pip::_internal::cli::cmdoptions::pre
Callable pip::_internal::cli::cmdoptions.json
Callable pip::_internal::cli::cmdoptions::disable_pip_version_check
Callable pip::_internal::cli::cmdoptions::root_user_action
Callable pip::_internal::cli::cmdoptions::hash
Callable pip::_internal::cli::cmdoptions::require_hashes
Callable pip::_internal::cli::cmdoptions::list_path
Callable pip::_internal::cli::cmdoptions::list_exclude
Callable pip::_internal::cli::cmdoptions::no_python_version_warning
list pip::_internal::cli::cmdoptions::ALWAYS_ENABLED_FEATURES
Callable pip::_internal::cli::cmdoptions::use_new_feature
Callable pip::_internal::cli::cmdoptions::use_deprecated_feature
dict pip::_internal::cli::cmdoptions::general_group
groups #
dict pip::_internal::cli::cmdoptions::index_group
None pip::_internal::cli::cmdoptions::raise_option_error(OptionParser parser, Option option, str msg)
Raise an option parsing error using parser.error(). Args: parser: an OptionParser instance. option: an Option instance. msg: the error text.
Referenced by pip._internal.cli.cmdoptions._handle_dependency_group, pip._internal.cli.cmdoptions._handle_no_cache_dir, pip._internal.cli.cmdoptions._handle_no_use_pep517, pip._internal.cli.cmdoptions._handle_python_version, pip._internal.cli.cmdoptions.make_option_group.
OptionGroup pip._internal.cli.cmdoptions.make_option_group(dict[str, Any] group, ConfigOptionParser parser)
Return an OptionGroup object group -- assumed to be dict with 'name' and 'options' keys parser -- an optparse Parser
None pip::_internal::cli::cmdoptions::check_dist_restriction(Values options, bool check_target=False)
Function for determining if custom platform options are allowed. :param options: The OptionParser options. :param check_target: Whether or not to check if --target is being used.
str pip::_internal::cli::cmdoptions::_path_option_check(Option option, str opt, str value)
str pip::_internal::cli::cmdoptions::_package_name_option_check(Option option, str opt, str value)
Option pip::_internal::cli::cmdoptions::exists_action()
Option pip::_internal::cli::cmdoptions::extra_index_url()
Option pip::_internal::cli::cmdoptions::find_links()
Option pip::_internal::cli::cmdoptions::trusted_host()
Option pip::_internal::cli::cmdoptions::constraints()
Option pip::_internal::cli::cmdoptions::requirements()
Option pip::_internal::cli::cmdoptions::editable()
None pip::_internal::cli::cmdoptions::_handle_src(Option option, str opt_str, str value, OptionParser parser)
Any pip::_internal::cli::cmdoptions::_get_format_control(Values values, Option option)
Get a format_control object.
Referenced by pip._internal.cli.cmdoptions._handle_no_binary, pip._internal.cli.cmdoptions._handle_only_binary, pip._internal.cli.cmdoptions.make_option_group.
None pip::_internal::cli::cmdoptions::_handle_no_binary(Option option, str opt_str, str value, OptionParser parser)
References pip._internal.cli.cmdoptions._get_format_control.
None pip::_internal::cli::cmdoptions::_handle_only_binary(Option option, str opt_str, str value, OptionParser parser)
References pip._internal.cli.cmdoptions._get_format_control.
Option pip::_internal::cli::cmdoptions::no_binary()
Option pip::_internal::cli::cmdoptions::only_binary()
tuple[tuple[int, ...], str | None] pip._internal.cli.cmdoptions._convert_python_version(str value)
Convert a version string like "3", "37", or "3.7.3" into a tuple of ints. :return: A 2-tuple (version_info, error_msg), where `error_msg` is non-None if and only if there was a parsing error.
Referenced by pip._internal.cli.cmdoptions._handle_python_version, pip._internal.cli.cmdoptions.make_option_group.
None pip::_internal::cli::cmdoptions::_handle_python_version(Option option, str opt_str, str value, OptionParser parser)
Handle a provided --python-version value.
References pip._internal.cli.cmdoptions._convert_python_version, pip._internal.cli.cmdoptions.raise_option_error.
None pip::_internal::cli::cmdoptions::add_target_python_options(OptionGroup cmd_opts)
References pip._internal.cli.cmdoptions.abis, pip._internal.cli.cmdoptions.implementation, pip._internal.cli.cmdoptions.platforms, pip._internal.cli.cmdoptions.python_version.
TargetPython pip::_internal::cli::cmdoptions::make_target_python(Values options)
Option pip::_internal::cli::cmdoptions::prefer_binary()
None pip::_internal::cli::cmdoptions::_handle_no_cache_dir(Option option, str opt, str value, OptionParser parser)
Process a value provided for the --no-cache-dir option. This is an optparse.Option callback for the --no-cache-dir option.
References pip._internal.cli.cmdoptions.raise_option_error.
None pip._internal.cli.cmdoptions._handle_dependency_group(Option option, str opt, str value, OptionParser parser)
Process a value provided for the --group option. Splits on the rightmost ":", and validates that the path (if present) ends in `pyproject.toml`. Defaults the path to `pyproject.toml` when one is not given. `:` cannot appear in dependency group names, so this is a safe and simple parse. This is an optparse.Option callback for the dependency_groups option.
References pip._internal.cli.cmdoptions.raise_option_error.
None pip::_internal::cli::cmdoptions::_handle_no_use_pep517(Option option, str opt, str value, OptionParser parser)
Process a value provided for the --no-use-pep517 option. This is an optparse.Option callback for the no_use_pep517 option.
References pip._internal.cli.cmdoptions.raise_option_error.
None pip::_internal::cli::cmdoptions::_handle_config_settings(Option option, str opt_str, str value, OptionParser parser)
None pip::_internal::cli::cmdoptions::_handle_merge_hash(Option option, str opt_str, str value, OptionParser parser)
Given a value spelled "algo:digest", append the digest to a list pointed to in a dict by the algo name.
None pip::_internal::cli::cmdoptions::check_list_path_option(Values options)
OptionGroup pip._internal.cli.cmdoptions.make_option_group(Dict[str, Any] group, ConfigOptionParser parser)
Return an OptionGroup object group -- assumed to be dict with 'name' and 'options' keys parser -- an optparse Parser
References pip._internal.cli.cmdoptions._convert_python_version, pip._internal.cli.cmdoptions._get_format_control, pip._internal.cli.cmdoptions.abis, pip._internal.cli.cmdoptions.implementation, pip._internal.cli.cmdoptions.platforms, pip._internal.cli.cmdoptions.python_version, pip._internal.cli.cmdoptions.raise_option_error.