setuptools::config::_validate_pyproject::fastjsonschema_validations
str setuptools::config::_validate_pyproject::fastjsonschema_validations.VERSION
dict setuptools::config::_validate_pyproject::fastjsonschema_validations.REGEX_PATTERNS
setuptools::config::_validate_pyproject::fastjsonschema_validations.NoneType
setuptools.config._validate_pyproject.fastjsonschema_validations.validate(data, custom_formats={}, name_prefix=None)
References setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_build_dependencies.
setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_build_dependencies(data, custom_formats={}, name_prefix=None)
References setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___docs_python_org_3_install, setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_project_metadata, setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___setuptools_pypa_io_en_latest_references_keywords_html.
Referenced by setuptools.config._validate_pyproject.fastjsonschema_validations.validate.
setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___setuptools_pypa_io_en_latest_references_keywords_html(data, custom_formats={}, name_prefix=None)
References setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___setuptools_pypa_io_en_latest_references_keywords_html__definitions_attr_directive, setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___setuptools_pypa_io_en_latest_references_keywords_html__definitions_file_directive, setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___setuptools_pypa_io_en_latest_references_keywords_html__definitions_find_directive.
Referenced by setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_build_dependencies.
setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___setuptools_pypa_io_en_latest_references_keywords_html__definitions_file_directive(data, custom_formats={}, name_prefix=None)
Referenced by setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___setuptools_pypa_io_en_latest_references_keywords_html.
setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___setuptools_pypa_io_en_latest_references_keywords_html__definitions_attr_directive(data, custom_formats={}, name_prefix=None)
Referenced by setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___setuptools_pypa_io_en_latest_references_keywords_html.
setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___setuptools_pypa_io_en_latest_references_keywords_html__definitions_find_directive(data, custom_formats={}, name_prefix=None)
Referenced by setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___setuptools_pypa_io_en_latest_references_keywords_html.
setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___docs_python_org_3_install(data, custom_formats={}, name_prefix=None)
Referenced by setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_build_dependencies.
setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_project_metadata(data, custom_formats={}, name_prefix=None)
References setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_project_metadata___definitions_author, setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_project_metadata___definitions_dependency, setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_project_metadata___definitions_entry_point_group.
Referenced by setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_build_dependencies.
setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_project_metadata___definitions_dependency(data, custom_formats={}, name_prefix=None)
Referenced by setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_project_metadata.
setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_project_metadata___definitions_entry_point_group(data, custom_formats={}, name_prefix=None)
Referenced by setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_project_metadata.
setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_project_metadata___definitions_author(data, custom_formats={}, name_prefix=None)
Referenced by setuptools.config._validate_pyproject.fastjsonschema_validations.validate_https___packaging_python_org_en_latest_specifications_declaring_project_metadata.