pip::_vendor::requests::cookies
pip::_vendor::requests::cookies::extract_cookies_to_jar(jar, request, response)
Extract the cookies from the response into a CookieJar. :param jar: http.cookiejar.CookieJar (not necessarily a RequestsCookieJar) :param request: our own requests.Request object :param response: urllib3.HTTPResponse object Extract the cookies from the response into a CookieJar. :param jar: cookielib.CookieJar (not necessarily a RequestsCookieJar) :param request: our own requests.Request object :param response: urllib3.HTTPResponse object
pip::_vendor::requests::cookies::get_cookie_header(jar, request)
Produce an appropriate Cookie header string to be sent with `request`, or None. :rtype: str
pip::_vendor::requests::cookies::remove_cookie_by_name(cookiejar, name, domain=None, path=None)
Unsets a cookie by name, by default over all domains and paths. Wraps CookieJar.clear(), is O(n).
Referenced by pip._vendor.requests.cookies.RequestsCookieJar.get_dict, pip._vendor.requests.cookies.RequestsCookieJar.set.
pip::_vendor::requests::cookies::_copy_cookie_jar(jar)
pip::_vendor::requests::cookies::create_cookie(name, value, **kwargs)
Make a cookie from underspecified parameters. By default, the pair of `name` and `value` will be set for the domain '' and sent on every request (this is sometimes called a "supercookie").
Referenced by pip._vendor.requests.cookies.cookiejar_from_dict, pip._vendor.requests.cookies.RequestsCookieJar.get_policy, pip._vendor.requests.cookies.morsel_to_cookie, pip._vendor.requests.cookies.RequestsCookieJar.set.
pip::_vendor::requests::cookies::morsel_to_cookie(morsel)
Convert a Morsel object into a Cookie containing the one k/v pair.
References pip._vendor.requests.cookies.create_cookie.
Referenced by pip._vendor.requests.cookies.RequestsCookieJar.set.
pip::_vendor::requests::cookies::cookiejar_from_dict(cookie_dict, cookiejar=None, overwrite=True)
Returns a CookieJar from a key/value dictionary. :param cookie_dict: Dict of key/values to insert into CookieJar. :param cookiejar: (optional) A cookiejar to add the cookies to. :param overwrite: (optional) If False, will not replace cookies already in the jar with new ones. :rtype: CookieJar
References pip._vendor.requests.cookies.create_cookie.
Referenced by pip._vendor.requests.cookies.RequestsCookieJar.get_policy, pip._vendor.requests.cookies.merge_cookies.
pip::_vendor::requests::cookies::merge_cookies(cookiejar, cookies)
Add cookies to cookiejar and returns a merged CookieJar. :param cookiejar: CookieJar object to add the cookies to. :param cookies: Dictionary or CookieJar object to be added. :rtype: CookieJar
References pip._vendor.requests.cookies.cookiejar_from_dict.