fastapi::_compat::v2
fastapi::_compat::v2.RequiredParam
fastapi::_compat::v2.Undefined
fastapi::_compat::v2.UndefinedType
fastapi::_compat::v2.evaluate_forwardref
fastapi::_compat::v2.Validator
fastapi::_compat::v2.TypeModelOrEnum
fastapi::_compat::v2.TypeModelSet
Any fastapi._compat.v2.get_annotation_from_field_info(Any annotation, FieldInfo field_info, str field_name)
None fastapi._compat.v2._model_rebuild(Type[BaseModel] model)
Any fastapi._compat.v2._model_dump(BaseModel model, Literal["json", "python"] mode="json", **Any kwargs)
Any fastapi._compat.v2._get_model_config(BaseModel model)
Dict[str, Any] fastapi._compat.v2.get_schema_from_model_field(*, ModelField field, ModelNameMap model_name_map, Dict[Tuple[ModelField, Literal["validation", "serialization"]], JsonSchemaValue] field_mapping, bool separate_input_output_schemas=True)
Tuple[ Dict[Tuple[ModelField, Literal["validation", "serialization"]], JsonSchemaValue], Dict[str, Dict[str, Any]], ] fastapi._compat.v2.get_definitions(*, Sequence[ModelField] fields, ModelNameMap model_name_map, bool separate_input_output_schemas=True)
References fastapi._compat.v2._remap_definitions_and_field_mappings, fastapi._compat.v2.get_flat_models_from_fields.
Dict[str, Any] fastapi._compat.v2._replace_refs(*, Dict[str, Any] schema, Dict[str, str] old_name_to_new_name_map)
References fastapi._compat.v2._replace_refs.
Referenced by fastapi._compat.v2._remap_definitions_and_field_mappings, fastapi._compat.v2._replace_refs.
Tuple[ Dict[Tuple[ModelField, Literal["validation", "serialization"]], JsonSchemaValue], Dict[str, Any], ] fastapi._compat.v2._remap_definitions_and_field_mappings(*, ModelNameMap model_name_map, Dict[str, Any] definitions, Dict[Tuple[ModelField, Literal["validation", "serialization"]], JsonSchemaValue] field_mapping)
References fastapi._compat.v2._replace_refs.
Referenced by fastapi._compat.v2.get_definitions.
bool fastapi._compat.v2.is_scalar_field(ModelField field)
bool fastapi._compat.v2.is_sequence_field(ModelField field)
bool fastapi._compat.v2.is_scalar_sequence_field(ModelField field)
bool fastapi._compat.v2.is_bytes_field(ModelField field)
bool fastapi._compat.v2.is_bytes_sequence_field(ModelField field)
FieldInfo fastapi._compat.v2.copy_field_info(*, FieldInfo field_info, Any annotation)
Sequence[Any] fastapi._compat.v2.serialize_sequence_value(*, ModelField field, Any value)
Dict[str, Any] fastapi._compat.v2.get_missing_field_error(Tuple[str,...] loc)
Type[BaseModel] fastapi._compat.v2.create_body_model(*, Sequence[ModelField] fields, str model_name)
List[ModelField] fastapi._compat.v2.get_model_fields(Type[BaseModel] model)
Referenced by fastapi._compat.v2.get_flat_models_from_model.
str fastapi._compat.v2.normalize_name(str name)
Referenced by fastapi._compat.v2.get_model_name_map.
Dict[TypeModelOrEnum, str] fastapi._compat.v2.get_model_name_map(TypeModelSet unique_models)
References fastapi._compat.v2.get_long_model_name, fastapi._compat.v2.normalize_name.
TypeModelSet fastapi._compat.v2.get_flat_models_from_model(Type["BaseModel"] model, Union[TypeModelSet, None] known_models=None)
References fastapi._compat.v2.get_flat_models_from_fields, fastapi._compat.v2.get_model_fields.
Referenced by fastapi._compat.v2.get_flat_models_from_annotation, fastapi._compat.v2.get_flat_models_from_field.
TypeModelSet fastapi._compat.v2.get_flat_models_from_annotation(Any annotation, TypeModelSet known_models)
References fastapi._compat.v2.get_flat_models_from_annotation, fastapi._compat.v2.get_flat_models_from_model.
Referenced by fastapi._compat.v2.get_flat_models_from_annotation, fastapi._compat.v2.get_flat_models_from_field.
TypeModelSet fastapi._compat.v2.get_flat_models_from_field(ModelField field, TypeModelSet known_models)
References fastapi._compat.v2.get_flat_models_from_annotation, fastapi._compat.v2.get_flat_models_from_model.
Referenced by fastapi._compat.v2.get_flat_models_from_fields.
TypeModelSet fastapi._compat.v2.get_flat_models_from_fields(Sequence[ModelField] fields, TypeModelSet known_models)
References fastapi._compat.v2.get_flat_models_from_field.
Referenced by fastapi._compat.v2.get_definitions, fastapi._compat.v2.get_flat_models_from_model.
str fastapi._compat.v2.get_long_model_name(TypeModelOrEnum model)
Referenced by fastapi._compat.v2.get_model_name_map.