pip::_internal::utils::filesystem
pip::_internal::utils::filesystem.replace
pip::_internal::utils::filesystem._replace_retry
bool pip::_internal::utils::filesystem::check_path_owner(str path)
Generator[BinaryIO, None, None] pip._internal.utils.filesystem.adjacent_tmp_file(str path, **Any kwargs)
Return a file-like object pointing to a tmp file next to path. The file is created securely and is ensured to be written to disk after the context reaches its end. kwargs will be passed to tempfile.NamedTemporaryFile to control the way the temporary file will be opened.
bool pip::_internal::utils::filesystem::test_writable_dir(str path)
Check if a directory is writable. Uses os.access() on POSIX, tries creating files on Windows.
References pip._internal.utils.filesystem._test_writable_dir_win.
bool pip::_internal::utils::filesystem::_test_writable_dir_win(str path)
Referenced by pip._internal.utils.filesystem.test_writable_dir.
list[str] pip._internal.utils.filesystem.find_files(str path, str pattern)
Returns a list of absolute paths of files beneath path, recursively, with filenames which match the UNIX-style shell glob pattern.
int | float pip._internal.utils.filesystem.file_size(str path)
Referenced by pip._internal.utils.filesystem.directory_size, pip._internal.utils.filesystem.format_file_size.
str pip::_internal::utils::filesystem::format_file_size(str path)
References pip._internal.utils.filesystem.file_size.
int | float pip._internal.utils.filesystem.directory_size(str path)
References pip._internal.utils.filesystem.file_size.
Referenced by pip._internal.utils.filesystem.format_directory_size.
str pip::_internal::utils::filesystem::format_directory_size(str path)
References pip._internal.utils.filesystem.directory_size.