pip::_vendor::pygments
pip::_vendor::pygments::lex(code, lexer)
Lex `code` with the `lexer` (must be a `Lexer` instance) and return an iterable of tokens. Currently, this only calls `lexer.get_tokens()`.
Referenced by pip._vendor.pygments.highlight.
pip::_vendor::pygments::format(tokens, formatter, outfile=None)
Format ``tokens`` (an iterable of tokens) with the formatter ``formatter`` (a `Formatter` instance). If ``outfile`` is given and a valid file object (an object with a ``write`` method), the result will be written to it, otherwise it is returned as a string.
Referenced by pip._vendor.pygments.highlight.
pip::_vendor::pygments::highlight(code, lexer, formatter, outfile=None)
This is the most high-level highlighting function. It combines `lex` and `format` in one function.
References pip._vendor.pygments.format, pip._vendor.pygments.lex.
Referenced by pip._vendor.pygments.cmdline.main_inner.