pydantic::v1::networks
pydantic::v1::networks.CallableGenerator
pydantic::v1::networks.email_validator
pydantic::v1::networks.NetworkType
pydantic::v1::networks._url_regex_cache
pydantic::v1::networks._multi_host_url_regex_cache
pydantic::v1::networks._ascii_domain_regex_cache
pydantic::v1::networks._int_domain_regex_cache
pydantic::v1::networks._host_regex_cache
tuple pydantic::v1::networks._host_regex
str pydantic::v1::networks._scheme_regex
str pydantic::v1::networks._user_info_regex
str pydantic::v1::networks._path_regex
str pydantic::v1::networks._query_regex
str pydantic::v1::networks._fragment_regex
pydantic::v1::networks.pretty_email_regex
int pydantic::v1::networks.MAX_EMAIL_LENGTH
Pattern[str] pydantic.v1.networks.url_regex()
Referenced by pydantic.v1.networks.AnyUrl._match_url.
Pattern[str] pydantic.v1.networks.multi_host_url_regex()
Compiled multi host url regex. Additionally to `url_regex` it allows to match multiple hosts. E.g. host1.db.net,host2.db.net
Referenced by pydantic.v1.networks.MultiHostDsn._match_url.
Pattern[str] pydantic.v1.networks.ascii_domain_regex()
Referenced by pydantic.v1.networks.AnyUrl.validate_host.
Pattern[str] pydantic.v1.networks.int_domain_regex()
Referenced by pydantic.v1.networks.AnyUrl.validate_host.
Pattern[str] pydantic.v1.networks.host_regex()
Referenced by pydantic.v1.networks.MultiHostDsn._build_url.
Type[AnyUrl] pydantic.v1.networks.stricturl(*, bool strip_whitespace=True, int min_length=1, int max_length=2 **16, bool tld_required=True, bool host_required=True, Optional[Collection[str]] allowed_schemes=None)
None pydantic.v1.networks.import_email_validator()
Referenced by pydantic.v1.networks.validate_email.
Tuple[str, str] pydantic.v1.networks.validate_email(Union[str] value)
Email address validation using https://pypi.org/project/email-validator/ Notes: * raw ip address (literal) domain parts are not allowed. * "John Doe <local_part@domain.com>" style "pretty" email addresses are processed * spaces are striped from the beginning and end of addresses but no error is raised
References pydantic.v1.networks.import_email_validator.
Referenced by pydantic.v1.networks.EmailStr.validate, pydantic.v1.networks.NameEmail.validate.