pip::_vendor::packaging::_manylinux
int pip::_vendor::packaging::_manylinux.EF_ARM_ABIMASK
int pip::_vendor::packaging::_manylinux.EF_ARM_ABI_VER5
int pip::_vendor::packaging::_manylinux.EF_ARM_ABI_FLOAT_HARD
Dict pip::_vendor::packaging::_manylinux::_LAST_GLIBC_MINOR
dict pip::_vendor::packaging::_manylinux::_LEGACY_MANYLINUX_MAP
Generator[ELFFile | None, None, None] pip._vendor.packaging._manylinux._parse_elf(str path)
Referenced by pip._vendor.packaging._manylinux._is_linux_armhf, pip._vendor.packaging._manylinux._is_linux_i686.
bool pip._vendor.packaging._manylinux._is_linux_armhf(str executable)
References pip._vendor.packaging._manylinux._parse_elf.
bool pip._vendor.packaging._manylinux._is_linux_i686(str executable)
References pip._vendor.packaging._manylinux._parse_elf.
bool pip._vendor.packaging._manylinux._have_compatible_abi(str executable, Sequence[str] archs)
References pip._vendor.packaging._manylinux._is_linux_armhf, pip._vendor.packaging._manylinux._is_linux_i686.
Referenced by pip._vendor.packaging._manylinux.platform_tags, pip._vendor.packaging._manylinux.platform_tags.
str | None pip._vendor.packaging._manylinux._glibc_version_string_confstr()
Primary implementation of glibc_version_string using os.confstr.
Referenced by pip._vendor.packaging._manylinux._glibc_version_string, pip._vendor.packaging._manylinux._have_compatible_abi.
str | None pip._vendor.packaging._manylinux._glibc_version_string_ctypes()
Fallback implementation of glibc_version_string using ctypes.
Referenced by pip._vendor.packaging._manylinux._glibc_version_string, pip._vendor.packaging._manylinux._have_compatible_abi.
str | None pip._vendor.packaging._manylinux._glibc_version_string()
Returns glibc version string, or None if not using glibc.
References pip._vendor.packaging._manylinux._glibc_version_string_confstr, pip._vendor.packaging._manylinux._glibc_version_string_ctypes.
Referenced by pip._vendor.packaging._manylinux._get_glibc_version, pip._vendor.packaging._manylinux._have_compatible_abi.
tuple[int, int] pip._vendor.packaging._manylinux._parse_glibc_version(str version_str)
Parse glibc version. We use a regexp instead of str.split because we want to discard any random junk that might come after the minor version -- this might happen in patched/forked versions of glibc (e.g. Linaro's version of glibc uses version strings like "2.20-2014.11"). See gh-3588.
Referenced by pip._vendor.packaging._manylinux._get_glibc_version, pip._vendor.packaging._manylinux._have_compatible_abi.
tuple[int, int] pip._vendor.packaging._manylinux._get_glibc_version()
References pip._vendor.packaging._manylinux._glibc_version_string, pip._vendor.packaging._manylinux._parse_glibc_version.
Referenced by pip._vendor.packaging._manylinux._is_compatible, pip._vendor.packaging._manylinux._is_compatible, pip._vendor.packaging._manylinux.platform_tags, pip._vendor.packaging._manylinux.platform_tags.
bool pip._vendor.packaging._manylinux._is_compatible(str arch, _GLibCVersion version)
References pip._vendor.packaging._manylinux._get_glibc_version.
Referenced by pip._vendor.packaging._manylinux.platform_tags, pip._vendor.packaging._manylinux.platform_tags.
Iterator[str] pip._vendor.packaging._manylinux.platform_tags(Sequence[str] archs)
Generate manylinux tags compatible to the current platform. :param archs: Sequence of compatible architectures. The first one shall be the closest to the actual architecture and be the part of platform tag after the ``linux_`` prefix, e.g. ``x86_64``. The ``linux_`` prefix is assumed as a prerequisite for the current platform to be manylinux-compatible. :returns: An iterator of compatible manylinux tags.
References pip._vendor.packaging._manylinux._get_glibc_version, pip._vendor.packaging._manylinux._have_compatible_abi, pip._vendor.packaging._manylinux._is_compatible.
Optional[_ELFFileHeader] pip._vendor.packaging._manylinux._get_elf_header()
Referenced by pip._vendor.packaging._manylinux._is_linux_armhf, pip._vendor.packaging._manylinux._is_linux_i686.
bool pip._vendor.packaging._manylinux._is_linux_armhf()
References pip._vendor.packaging._manylinux._get_elf_header.
Referenced by pip._vendor.packaging._manylinux._have_compatible_abi, pip._vendor.packaging._manylinux._have_compatible_abi.
bool pip._vendor.packaging._manylinux._is_linux_i686()
References pip._vendor.packaging._manylinux._get_elf_header.
Referenced by pip._vendor.packaging._manylinux._have_compatible_abi, pip._vendor.packaging._manylinux._have_compatible_abi.
bool pip._vendor.packaging._manylinux._have_compatible_abi(str arch)
References pip._vendor.packaging._manylinux._glibc_version_string, pip._vendor.packaging._manylinux._glibc_version_string_confstr, pip._vendor.packaging._manylinux._glibc_version_string_ctypes, pip._vendor.packaging._manylinux._is_linux_armhf, pip._vendor.packaging._manylinux._is_linux_i686, pip._vendor.packaging._manylinux._parse_glibc_version.
bool pip._vendor.packaging._manylinux._is_compatible(str name, str arch, _GLibCVersion version)
References pip._vendor.packaging._manylinux._get_glibc_version.
Iterator[str] pip._vendor.packaging._manylinux.platform_tags(str linux, str arch)
References pip._vendor.packaging._manylinux._get_glibc_version, pip._vendor.packaging._manylinux._have_compatible_abi, pip._vendor.packaging._manylinux._is_compatible.