click::core
click::core.F
click::core.V
cabc.Iterator[tuple[str, Command]] click.core._complete_visible_commands(Context ctx, str incomplete)
List all the subcommands of a group that start with the incomplete value and aren't hidden. :param ctx: Invocation context for the group. :param incomplete: Value being completed. May be empty.
Referenced by click.core.Command.shell_complete, click.core.Group.shell_complete.
None click.core._check_nested_chain(Group base_command, str cmd_name, Command cmd, bool register=False)
Referenced by click.core.Group.add_command.
list[tuple[V, ...]] click.core.batch(cabc.Iterable[V] iterable, int batch_size)
Referenced by click.core.Option.value_from_envvar.
cabc.Iterator[None] click.core.augment_usage_errors(Context ctx, Parameter|None param=None)
Context manager that attaches extra information to exceptions.
Referenced by click.core.Parameter.handle_parse_result, click.core.Context.invoke.
list[Parameter] click.core.iter_params_for_processing(cabc.Sequence[Parameter] invocation_order, cabc.Sequence[Parameter] declaration_order)
Returns all declared parameters in the order they should be processed. The declared parameters are re-shuffled depending on the order in which they were invoked, as well as the eagerness of each parameters. The invocation order takes precedence over the declaration order. I.e. the order in which the user provided them to the CLI is respected. This behavior and its effect on callback evaluation is detailed at: https://click.palletsprojects.com/en/stable/advanced/#callback-evaluation-order
Referenced by click.core.Command.parse_args.
cabc.Iterator[t.Any] click.core._check_iter(t.Any value)
Check if the value is iterable but not a string. Raises a type error, or return an iterator over the value.
Referenced by click.core.Parameter.type_cast_value.