setuptools::_distutils::filelist
setuptools._distutils.filelist._find_all_simple(path)
Find all files under 'path'
Referenced by setuptools._distutils.filelist.findall.
setuptools._distutils.filelist.findall(dir=os.curdir)
Find all files under 'dir' and return the list of full filenames. Unless dir is '.', return full filenames with dir prepended.
References setuptools._distutils.filelist._find_all_simple.
setuptools._distutils.filelist.glob_to_re(pattern)
Translate a shell-like glob pattern to a regular expression; return a string containing the regex. Differs from 'fnmatch.translate()' in that '*' does not match "special characters" (which are platform-specific).
Referenced by setuptools._distutils.filelist.translate_pattern.
setuptools._distutils.filelist.translate_pattern(pattern, anchor=1, prefix=None, is_regex=0)
Translate a shell-like wildcard pattern to a compiled regular expression. Return the compiled regex. If 'is_regex' true, then 'pattern' is directly compiled to a regex (if it's a string) or just returned as-is (assumes it's a regex object).
References setuptools._distutils.filelist.glob_to_re.
Referenced by setuptools._distutils.filelist.FileList.exclude_pattern, setuptools._distutils.filelist.FileList.include_pattern.