pip::_vendor::rich::console
int pip::_vendor::rich::console::JUPYTER_DEFAULT_COLUMNS
int pip::_vendor::rich::console::JUPYTER_DEFAULT_LINES
str pip::_vendor::rich::console::WINDOWS
pip::_vendor::rich::console.HighlighterType
pip::_vendor::rich::console.JustifyMethod
pip::_vendor::rich::console.OverflowMethod
pip::_vendor::rich::console.NO_CHANGE
int pip::_vendor::rich::console::_STDIN_FILENO
int pip::_vendor::rich::console::_STDOUT_FILENO
int pip::_vendor::rich::console::_STDERR_FILENO
tuple pip::_vendor::rich::console::_STD_STREAMS
tuple pip::_vendor::rich::console::_STD_STREAMS_OUTPUT
dict pip::_vendor::rich::console::_TERM_COLORS
pip::_vendor::rich::console.RenderableType
pip::_vendor::rich::console.RenderResult
pip::_vendor::rich::console._null_highlighter
dict pip::_vendor::rich::console::COLOR_SYSTEMS
dict pip::_vendor::rich::console::_COLOR_SYSTEMS_NAMES
pip::_vendor::rich::console.console
Callable[..., Callable[..., Group]] pip._vendor.rich.console.group(bool fit=True)
A decorator that turns an iterable of renderables in to a group. Args: fit (bool, optional): Fit dimension of group to contents, or fill available space. Defaults to True.
bool pip::_vendor::rich::console::_is_jupyter()
Check if we're running in a Jupyter notebook.
Referenced by pip._vendor.rich.console.RenderHook.process_renderables.
WindowsConsoleFeatures pip::_vendor::rich::console::get_windows_console_features()
References pip._vendor.rich.console.get_windows_console_features.
Referenced by pip._vendor.rich.console.Console._detect_color_system, pip._vendor.rich.console.detect_legacy_windows, pip._vendor.rich.console.get_windows_console_features, pip._vendor.rich.console.RenderHook.process_renderables.
bool pip::_vendor::rich::console::detect_legacy_windows()
Detect legacy Windows.
References pip._vendor.rich.console.get_windows_console_features.
Referenced by pip._vendor.rich.console.RenderHook.process_renderables.
str pip::_vendor::rich::console::_svg_hash(str svg_main_code)
Returns a unique hash for the given SVG main code. Args: svg_main_code (str): The content we're going to inject in the SVG envelope. Returns: str: a hash of the given content