pip::_internal::cli::index_command
pip::_internal::cli::index_command.logger
SSLContext | None pip._internal.cli.index_command._create_truststore_ssl_context()
Referenced by pip._internal.cli.index_command.SessionCommandMixin._build_session, pip._internal.cli.req_command.SessionCommandMixin._build_session.
None pip._internal.cli.index_command._pip_self_version_check(PipSession session, Values options)
Referenced by pip._internal.cli.index_command.IndexGroupCommand.handle_pip_version_check.