pydantic::_internal::_docs_extraction
str pydantic._internal._docs_extraction._dedent_source_lines(list[str] source)
Referenced by pydantic._internal._docs_extraction._extract_source_from_frame, pydantic._internal._docs_extraction.extract_docstrings_from_cls.
list[str] | None pydantic._internal._docs_extraction._extract_source_from_frame(type[Any] cls)
References pydantic._internal._docs_extraction._dedent_source_lines.
Referenced by pydantic._internal._docs_extraction.extract_docstrings_from_cls.
dict[str, str] pydantic._internal._docs_extraction.extract_docstrings_from_cls(type[Any] cls, bool use_inspect=False)
Map model attributes and their corresponding docstring. Args: cls: The class of the Pydantic model to inspect. use_inspect: Whether to skip usage of frames to find the object and use the `inspect` module instead. Returns: A mapping containing attribute names and their corresponding docstring.
References pydantic._internal._docs_extraction._dedent_source_lines, pydantic._internal._docs_extraction._extract_source_from_frame.